// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: cmty/cmty_permission_pb.proto

// This CPP symbol can be defined to use imports that match up to the framework
// imports needed when using CocoaPods.
#if !defined(GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS)
 #define GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS 0
#endif

#if GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS
 #import <Protobuf/GPBProtocolBuffers_RuntimeSupport.h>
#else
 #import "GPBProtocolBuffers_RuntimeSupport.h"
#endif

#import <stdatomic.h>

#import "CmtyPermissionPb.pbobjc.h"
#import "SystemPb.pbobjc.h"
// @@protoc_insertion_point(imports)

#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wdeprecated-declarations"
#pragma clang diagnostic ignored "-Wdollar-in-identifier-extension"

#pragma mark - Objective C Class declarations
// Forward declarations of Objective C classes that we can use as
// static values in struct initializers.
// We don't use [Foo class] because it is not a static value.
GPBObjCClassDeclaration(CmtyMemberRole);
GPBObjCClassDeclaration(CmtyRole);
GPBObjCClassDeclaration(CmtyRoleResource);
GPBObjCClassDeclaration(Page);
GPBObjCClassDeclaration(PermissionItem);
GPBObjCClassDeclaration(PermissionTemplate);
GPBObjCClassDeclaration(Role);
GPBObjCClassDeclaration(RolePermissionConfig);

#pragma mark - CmtyPermissionPbRoot

@implementation CmtyPermissionPbRoot

// No extensions in the file and none of the imports (direct or indirect)
// defined extensions, so no need to generate +extensionRegistry.

@end

#pragma mark - CmtyPermissionPbRoot_FileDescriptor

static GPBFileDescriptor *CmtyPermissionPbRoot_FileDescriptor(void) {
  // This is called by +initialize so there is no need to worry
  // about thread safety of the singleton.
  static GPBFileDescriptor *descriptor = NULL;
  if (!descriptor) {
    GPB_DEBUG_CHECK_RUNTIME_VERSIONS();
    descriptor = [[GPBFileDescriptor alloc] initWithPackage:@"im.cmty"
                                                     syntax:GPBFileSyntaxProto3];
  }
  return descriptor;
}

#pragma mark - Enum CmtyRoleStatus

GPBEnumDescriptor *CmtyRoleStatus_EnumDescriptor(void) {
  static _Atomic(GPBEnumDescriptor*) descriptor = nil;
  if (!descriptor) {
    static const char *valueNames =
        "RoleEnabled\000RoleDisabled\000";
    static const int32_t values[] = {
        CmtyRoleStatus_RoleEnabled,
        CmtyRoleStatus_RoleDisabled,
    };
    GPBEnumDescriptor *worker =
        [GPBEnumDescriptor allocDescriptorForName:GPBNSStringifySymbol(CmtyRoleStatus)
                                       valueNames:valueNames
                                           values:values
                                            count:(uint32_t)(sizeof(values) / sizeof(int32_t))
                                     enumVerifier:CmtyRoleStatus_IsValidValue];
    GPBEnumDescriptor *expected = nil;
    if (!atomic_compare_exchange_strong(&descriptor, &expected, worker)) {
//      [worker release];
    }
  }
  return descriptor;
}

BOOL CmtyRoleStatus_IsValidValue(int32_t value__) {
  switch (value__) {
    case CmtyRoleStatus_RoleEnabled:
    case CmtyRoleStatus_RoleDisabled:
      return YES;
    default:
      return NO;
  }
}

#pragma mark - Enum CmtyMemberRoleStatus

GPBEnumDescriptor *CmtyMemberRoleStatus_EnumDescriptor(void) {
  static _Atomic(GPBEnumDescriptor*) descriptor = nil;
  if (!descriptor) {
    static const char *valueNames =
        "MemberRoleActive\000MemberRoleInactive\000";
    static const int32_t values[] = {
        CmtyMemberRoleStatus_MemberRoleActive,
        CmtyMemberRoleStatus_MemberRoleInactive,
    };
    GPBEnumDescriptor *worker =
        [GPBEnumDescriptor allocDescriptorForName:GPBNSStringifySymbol(CmtyMemberRoleStatus)
                                       valueNames:valueNames
                                           values:values
                                            count:(uint32_t)(sizeof(values) / sizeof(int32_t))
                                     enumVerifier:CmtyMemberRoleStatus_IsValidValue];
    GPBEnumDescriptor *expected = nil;
    if (!atomic_compare_exchange_strong(&descriptor, &expected, worker)) {
//      [worker release];
    }
  }
  return descriptor;
}

BOOL CmtyMemberRoleStatus_IsValidValue(int32_t value__) {
  switch (value__) {
    case CmtyMemberRoleStatus_MemberRoleActive:
    case CmtyMemberRoleStatus_MemberRoleInactive:
      return YES;
    default:
      return NO;
  }
}

#pragma mark - CmtyRole

@implementation CmtyRole

@dynamic roleCode;
@dynamic roleName;
@dynamic roleDescription;
@dynamic permissions;
@dynamic isSystem;
@dynamic priority;
@dynamic status;
@dynamic createTime;
@dynamic updateTime;

typedef struct CmtyRole__storage_ {
  uint32_t _has_storage_[1];
  int32_t priority;
  CmtyRoleStatus status;
  NSString *roleCode;
  NSString *roleName;
  NSString *roleDescription;
  NSString *permissions;
  int64_t createTime;
  int64_t updateTime;
} CmtyRole__storage_;

// This method is threadsafe because it is initially called
// in +initialize for each subclass.
+ (GPBDescriptor *)descriptor {
  static GPBDescriptor *descriptor = nil;
  if (!descriptor) {
    static GPBMessageFieldDescription fields[] = {
      {
        .name = "roleCode",
        .dataTypeSpecific.clazz = Nil,
        .number = CmtyRole_FieldNumber_RoleCode,
        .hasIndex = 0,
        .offset = (uint32_t)offsetof(CmtyRole__storage_, roleCode),
        .flags = (GPBFieldFlags)(GPBFieldOptional | GPBFieldClearHasIvarOnZero),
        .dataType = GPBDataTypeString,
      },
      {
        .name = "roleName",
        .dataTypeSpecific.clazz = Nil,
        .number = CmtyRole_FieldNumber_RoleName,
        .hasIndex = 1,
        .offset = (uint32_t)offsetof(CmtyRole__storage_, roleName),
        .flags = (GPBFieldFlags)(GPBFieldOptional | GPBFieldClearHasIvarOnZero),
        .dataType = GPBDataTypeString,
      },
      {
        .name = "roleDescription",
        .dataTypeSpecific.clazz = Nil,
        .number = CmtyRole_FieldNumber_RoleDescription,
        .hasIndex = 2,
        .offset = (uint32_t)offsetof(CmtyRole__storage_, roleDescription),
        .flags = (GPBFieldFlags)(GPBFieldOptional | GPBFieldClearHasIvarOnZero),
        .dataType = GPBDataTypeString,
      },
      {
        .name = "permissions",
        .dataTypeSpecific.clazz = Nil,
        .number = CmtyRole_FieldNumber_Permissions,
        .hasIndex = 3,
        .offset = (uint32_t)offsetof(CmtyRole__storage_, permissions),
        .flags = (GPBFieldFlags)(GPBFieldOptional | GPBFieldClearHasIvarOnZero),
        .dataType = GPBDataTypeString,
      },
      {
        .name = "isSystem",
        .dataTypeSpecific.clazz = Nil,
        .number = CmtyRole_FieldNumber_IsSystem,
        .hasIndex = 4,
        .offset = 5,  // Stored in _has_storage_ to save space.
        .flags = (GPBFieldFlags)(GPBFieldOptional | GPBFieldClearHasIvarOnZero),
        .dataType = GPBDataTypeBool,
      },
      {
        .name = "priority",
        .dataTypeSpecific.clazz = Nil,
        .number = CmtyRole_FieldNumber_Priority,
        .hasIndex = 6,
        .offset = (uint32_t)offsetof(CmtyRole__storage_, priority),
        .flags = (GPBFieldFlags)(GPBFieldOptional | GPBFieldClearHasIvarOnZero),
        .dataType = GPBDataTypeInt32,
      },
      {
        .name = "status",
        .dataTypeSpecific.enumDescFunc = CmtyRoleStatus_EnumDescriptor,
        .number = CmtyRole_FieldNumber_Status,
        .hasIndex = 7,
        .offset = (uint32_t)offsetof(CmtyRole__storage_, status),
        .flags = (GPBFieldFlags)(GPBFieldOptional | GPBFieldHasEnumDescriptor | GPBFieldClearHasIvarOnZero),
        .dataType = GPBDataTypeEnum,
      },
      {
        .name = "createTime",
        .dataTypeSpecific.clazz = Nil,
        .number = CmtyRole_FieldNumber_CreateTime,
        .hasIndex = 8,
        .offset = (uint32_t)offsetof(CmtyRole__storage_, createTime),
        .flags = (GPBFieldFlags)(GPBFieldOptional | GPBFieldClearHasIvarOnZero),
        .dataType = GPBDataTypeInt64,
      },
      {
        .name = "updateTime",
        .dataTypeSpecific.clazz = Nil,
        .number = CmtyRole_FieldNumber_UpdateTime,
        .hasIndex = 9,
        .offset = (uint32_t)offsetof(CmtyRole__storage_, updateTime),
        .flags = (GPBFieldFlags)(GPBFieldOptional | GPBFieldClearHasIvarOnZero),
        .dataType = GPBDataTypeInt64,
      },
    };
    GPBDescriptor *localDescriptor =
        [GPBDescriptor allocDescriptorForClass:[CmtyRole class]
                                     rootClass:[CmtyPermissionPbRoot class]
                                          file:CmtyPermissionPbRoot_FileDescriptor()
                                        fields:fields
                                    fieldCount:(uint32_t)(sizeof(fields) / sizeof(GPBMessageFieldDescription))
                                   storageSize:sizeof(CmtyRole__storage_)
                                         flags:(GPBDescriptorInitializationFlags)(GPBDescriptorInitializationFlag_UsesClassRefs | GPBDescriptorInitializationFlag_Proto3OptionalKnown)];
    #if defined(DEBUG) && DEBUG
      NSAssert(descriptor == nil, @"Startup recursed!");
    #endif  // DEBUG
    descriptor = localDescriptor;
  }
  return descriptor;
}

@end

int32_t CmtyRole_Status_RawValue(CmtyRole *message) {
  GPBDescriptor *descriptor = [CmtyRole descriptor];
  GPBFieldDescriptor *field = [descriptor fieldWithNumber:CmtyRole_FieldNumber_Status];
  return GPBGetMessageRawEnumField(message, field);
}

void SetCmtyRole_Status_RawValue(CmtyRole *message, int32_t value) {
  GPBDescriptor *descriptor = [CmtyRole descriptor];
  GPBFieldDescriptor *field = [descriptor fieldWithNumber:CmtyRole_FieldNumber_Status];
  GPBSetMessageRawEnumField(message, field, value);
}

#pragma mark - CmtyMemberRole

@implementation CmtyMemberRole

@dynamic userId;
@dynamic roleCode;
@dynamic hasRole, role;
@dynamic assignedBy;
@dynamic assignedTime;
@dynamic expireTime;
@dynamic status;

typedef struct CmtyMemberRole__storage_ {
  uint32_t _has_storage_[1];
  CmtyMemberRoleStatus status;
  NSString *userId;
  NSString *roleCode;
  CmtyRole *role;
  NSString *assignedBy;
  int64_t assignedTime;
  int64_t expireTime;
} CmtyMemberRole__storage_;

// This method is threadsafe because it is initially called
// in +initialize for each subclass.
+ (GPBDescriptor *)descriptor {
  static GPBDescriptor *descriptor = nil;
  if (!descriptor) {
    static GPBMessageFieldDescription fields[] = {
      {
        .name = "userId",
        .dataTypeSpecific.clazz = Nil,
        .number = CmtyMemberRole_FieldNumber_UserId,
        .hasIndex = 0,
        .offset = (uint32_t)offsetof(CmtyMemberRole__storage_, userId),
        .flags = (GPBFieldFlags)(GPBFieldOptional | GPBFieldClearHasIvarOnZero),
        .dataType = GPBDataTypeString,
      },
      {
        .name = "roleCode",
        .dataTypeSpecific.clazz = Nil,
        .number = CmtyMemberRole_FieldNumber_RoleCode,
        .hasIndex = 1,
        .offset = (uint32_t)offsetof(CmtyMemberRole__storage_, roleCode),
        .flags = (GPBFieldFlags)(GPBFieldOptional | GPBFieldClearHasIvarOnZero),
        .dataType = GPBDataTypeString,
      },
      {
        .name = "role",
        .dataTypeSpecific.clazz = GPBObjCClass(CmtyRole),
        .number = CmtyMemberRole_FieldNumber_Role,
        .hasIndex = 2,
        .offset = (uint32_t)offsetof(CmtyMemberRole__storage_, role),
        .flags = GPBFieldOptional,
        .dataType = GPBDataTypeMessage,
      },
      {
        .name = "assignedBy",
        .dataTypeSpecific.clazz = Nil,
        .number = CmtyMemberRole_FieldNumber_AssignedBy,
        .hasIndex = 3,
        .offset = (uint32_t)offsetof(CmtyMemberRole__storage_, assignedBy),
        .flags = (GPBFieldFlags)(GPBFieldOptional | GPBFieldClearHasIvarOnZero),
        .dataType = GPBDataTypeString,
      },
      {
        .name = "assignedTime",
        .dataTypeSpecific.clazz = Nil,
        .number = CmtyMemberRole_FieldNumber_AssignedTime,
        .hasIndex = 4,
        .offset = (uint32_t)offsetof(CmtyMemberRole__storage_, assignedTime),
        .flags = (GPBFieldFlags)(GPBFieldOptional | GPBFieldClearHasIvarOnZero),
        .dataType = GPBDataTypeInt64,
      },
      {
        .name = "expireTime",
        .dataTypeSpecific.clazz = Nil,
        .number = CmtyMemberRole_FieldNumber_ExpireTime,
        .hasIndex = 5,
        .offset = (uint32_t)offsetof(CmtyMemberRole__storage_, expireTime),
        .flags = (GPBFieldFlags)(GPBFieldOptional | GPBFieldClearHasIvarOnZero),
        .dataType = GPBDataTypeInt64,
      },
      {
        .name = "status",
        .dataTypeSpecific.enumDescFunc = CmtyMemberRoleStatus_EnumDescriptor,
        .number = CmtyMemberRole_FieldNumber_Status,
        .hasIndex = 6,
        .offset = (uint32_t)offsetof(CmtyMemberRole__storage_, status),
        .flags = (GPBFieldFlags)(GPBFieldOptional | GPBFieldHasEnumDescriptor | GPBFieldClearHasIvarOnZero),
        .dataType = GPBDataTypeEnum,
      },
    };
    GPBDescriptor *localDescriptor =
        [GPBDescriptor allocDescriptorForClass:[CmtyMemberRole class]
                                     rootClass:[CmtyPermissionPbRoot class]
                                          file:CmtyPermissionPbRoot_FileDescriptor()
                                        fields:fields
                                    fieldCount:(uint32_t)(sizeof(fields) / sizeof(GPBMessageFieldDescription))
                                   storageSize:sizeof(CmtyMemberRole__storage_)
                                         flags:(GPBDescriptorInitializationFlags)(GPBDescriptorInitializationFlag_UsesClassRefs | GPBDescriptorInitializationFlag_Proto3OptionalKnown)];
    #if defined(DEBUG) && DEBUG
      NSAssert(descriptor == nil, @"Startup recursed!");
    #endif  // DEBUG
    descriptor = localDescriptor;
  }
  return descriptor;
}

@end

int32_t CmtyMemberRole_Status_RawValue(CmtyMemberRole *message) {
  GPBDescriptor *descriptor = [CmtyMemberRole descriptor];
  GPBFieldDescriptor *field = [descriptor fieldWithNumber:CmtyMemberRole_FieldNumber_Status];
  return GPBGetMessageRawEnumField(message, field);
}

void SetCmtyMemberRole_Status_RawValue(CmtyMemberRole *message, int32_t value) {
  GPBDescriptor *descriptor = [CmtyMemberRole descriptor];
  GPBFieldDescriptor *field = [descriptor fieldWithNumber:CmtyMemberRole_FieldNumber_Status];
  GPBSetMessageRawEnumField(message, field, value);
}

#pragma mark - CmtyRoleResource

@implementation CmtyRoleResource

@dynamic roleCode;
@dynamic method;
@dynamic resourceId;
@dynamic isEnabled;
@dynamic createTime;
@dynamic updateTime;

typedef struct CmtyRoleResource__storage_ {
  uint32_t _has_storage_[1];
  NSString *roleCode;
  NSString *method;
  NSString *resourceId;
  int64_t createTime;
  int64_t updateTime;
} CmtyRoleResource__storage_;

// This method is threadsafe because it is initially called
// in +initialize for each subclass.
+ (GPBDescriptor *)descriptor {
  static GPBDescriptor *descriptor = nil;
  if (!descriptor) {
    static GPBMessageFieldDescription fields[] = {
      {
        .name = "roleCode",
        .dataTypeSpecific.clazz = Nil,
        .number = CmtyRoleResource_FieldNumber_RoleCode,
        .hasIndex = 0,
        .offset = (uint32_t)offsetof(CmtyRoleResource__storage_, roleCode),
        .flags = (GPBFieldFlags)(GPBFieldOptional | GPBFieldClearHasIvarOnZero),
        .dataType = GPBDataTypeString,
      },
      {
        .name = "method",
        .dataTypeSpecific.clazz = Nil,
        .number = CmtyRoleResource_FieldNumber_Method,
        .hasIndex = 1,
        .offset = (uint32_t)offsetof(CmtyRoleResource__storage_, method),
        .flags = (GPBFieldFlags)(GPBFieldOptional | GPBFieldClearHasIvarOnZero),
        .dataType = GPBDataTypeString,
      },
      {
        .name = "resourceId",
        .dataTypeSpecific.clazz = Nil,
        .number = CmtyRoleResource_FieldNumber_ResourceId,
        .hasIndex = 2,
        .offset = (uint32_t)offsetof(CmtyRoleResource__storage_, resourceId),
        .flags = (GPBFieldFlags)(GPBFieldOptional | GPBFieldClearHasIvarOnZero),
        .dataType = GPBDataTypeString,
      },
      {
        .name = "isEnabled",
        .dataTypeSpecific.clazz = Nil,
        .number = CmtyRoleResource_FieldNumber_IsEnabled,
        .hasIndex = 3,
        .offset = 4,  // Stored in _has_storage_ to save space.
        .flags = (GPBFieldFlags)(GPBFieldOptional | GPBFieldClearHasIvarOnZero),
        .dataType = GPBDataTypeBool,
      },
      {
        .name = "createTime",
        .dataTypeSpecific.clazz = Nil,
        .number = CmtyRoleResource_FieldNumber_CreateTime,
        .hasIndex = 5,
        .offset = (uint32_t)offsetof(CmtyRoleResource__storage_, createTime),
        .flags = (GPBFieldFlags)(GPBFieldOptional | GPBFieldClearHasIvarOnZero),
        .dataType = GPBDataTypeInt64,
      },
      {
        .name = "updateTime",
        .dataTypeSpecific.clazz = Nil,
        .number = CmtyRoleResource_FieldNumber_UpdateTime,
        .hasIndex = 6,
        .offset = (uint32_t)offsetof(CmtyRoleResource__storage_, updateTime),
        .flags = (GPBFieldFlags)(GPBFieldOptional | GPBFieldClearHasIvarOnZero),
        .dataType = GPBDataTypeInt64,
      },
    };
    GPBDescriptor *localDescriptor =
        [GPBDescriptor allocDescriptorForClass:[CmtyRoleResource class]
                                     rootClass:[CmtyPermissionPbRoot class]
                                          file:CmtyPermissionPbRoot_FileDescriptor()
                                        fields:fields
                                    fieldCount:(uint32_t)(sizeof(fields) / sizeof(GPBMessageFieldDescription))
                                   storageSize:sizeof(CmtyRoleResource__storage_)
                                         flags:(GPBDescriptorInitializationFlags)(GPBDescriptorInitializationFlag_UsesClassRefs | GPBDescriptorInitializationFlag_Proto3OptionalKnown)];
    #if defined(DEBUG) && DEBUG
      NSAssert(descriptor == nil, @"Startup recursed!");
    #endif  // DEBUG
    descriptor = localDescriptor;
  }
  return descriptor;
}

@end

#pragma mark - CmtyGetAllRoles

@implementation CmtyGetAllRoles

@dynamic hasPage, page;

typedef struct CmtyGetAllRoles__storage_ {
  uint32_t _has_storage_[1];
  Page *page;
} CmtyGetAllRoles__storage_;

// This method is threadsafe because it is initially called
// in +initialize for each subclass.
+ (GPBDescriptor *)descriptor {
  static GPBDescriptor *descriptor = nil;
  if (!descriptor) {
    static GPBMessageFieldDescription fields[] = {
      {
        .name = "page",
        .dataTypeSpecific.clazz = GPBObjCClass(Page),
        .number = CmtyGetAllRoles_FieldNumber_Page,
        .hasIndex = 0,
        .offset = (uint32_t)offsetof(CmtyGetAllRoles__storage_, page),
        .flags = GPBFieldOptional,
        .dataType = GPBDataTypeMessage,
      },
    };
    GPBDescriptor *localDescriptor =
        [GPBDescriptor allocDescriptorForClass:[CmtyGetAllRoles class]
                                     rootClass:[CmtyPermissionPbRoot class]
                                          file:CmtyPermissionPbRoot_FileDescriptor()
                                        fields:fields
                                    fieldCount:(uint32_t)(sizeof(fields) / sizeof(GPBMessageFieldDescription))
                                   storageSize:sizeof(CmtyGetAllRoles__storage_)
                                         flags:(GPBDescriptorInitializationFlags)(GPBDescriptorInitializationFlag_UsesClassRefs | GPBDescriptorInitializationFlag_Proto3OptionalKnown)];
    #if defined(DEBUG) && DEBUG
      NSAssert(descriptor == nil, @"Startup recursed!");
    #endif  // DEBUG
    descriptor = localDescriptor;
  }
  return descriptor;
}

@end

#pragma mark - CmtyGetRoleResources

@implementation CmtyGetRoleResources

@dynamic roleCodesArray, roleCodesArray_Count;

typedef struct CmtyGetRoleResources__storage_ {
  uint32_t _has_storage_[1];
  NSMutableArray *roleCodesArray;
} CmtyGetRoleResources__storage_;

// This method is threadsafe because it is initially called
// in +initialize for each subclass.
+ (GPBDescriptor *)descriptor {
  static GPBDescriptor *descriptor = nil;
  if (!descriptor) {
    static GPBMessageFieldDescription fields[] = {
      {
        .name = "roleCodesArray",
        .dataTypeSpecific.clazz = Nil,
        .number = CmtyGetRoleResources_FieldNumber_RoleCodesArray,
        .hasIndex = GPBNoHasBit,
        .offset = (uint32_t)offsetof(CmtyGetRoleResources__storage_, roleCodesArray),
        .flags = GPBFieldRepeated,
        .dataType = GPBDataTypeString,
      },
    };
    GPBDescriptor *localDescriptor =
        [GPBDescriptor allocDescriptorForClass:[CmtyGetRoleResources class]
                                     rootClass:[CmtyPermissionPbRoot class]
                                          file:CmtyPermissionPbRoot_FileDescriptor()
                                        fields:fields
                                    fieldCount:(uint32_t)(sizeof(fields) / sizeof(GPBMessageFieldDescription))
                                   storageSize:sizeof(CmtyGetRoleResources__storage_)
                                         flags:(GPBDescriptorInitializationFlags)(GPBDescriptorInitializationFlag_UsesClassRefs | GPBDescriptorInitializationFlag_Proto3OptionalKnown)];
    #if defined(DEBUG) && DEBUG
      NSAssert(descriptor == nil, @"Startup recursed!");
    #endif  // DEBUG
    descriptor = localDescriptor;
  }
  return descriptor;
}

@end

#pragma mark - CmtyRoleList

@implementation CmtyRoleList

@dynamic rolesArray, rolesArray_Count;
@dynamic hasPage, page;

typedef struct CmtyRoleList__storage_ {
  uint32_t _has_storage_[1];
  NSMutableArray *rolesArray;
  Page *page;
} CmtyRoleList__storage_;

// This method is threadsafe because it is initially called
// in +initialize for each subclass.
+ (GPBDescriptor *)descriptor {
  static GPBDescriptor *descriptor = nil;
  if (!descriptor) {
    static GPBMessageFieldDescription fields[] = {
      {
        .name = "rolesArray",
        .dataTypeSpecific.clazz = GPBObjCClass(CmtyRole),
        .number = CmtyRoleList_FieldNumber_RolesArray,
        .hasIndex = GPBNoHasBit,
        .offset = (uint32_t)offsetof(CmtyRoleList__storage_, rolesArray),
        .flags = GPBFieldRepeated,
        .dataType = GPBDataTypeMessage,
      },
      {
        .name = "page",
        .dataTypeSpecific.clazz = GPBObjCClass(Page),
        .number = CmtyRoleList_FieldNumber_Page,
        .hasIndex = 0,
        .offset = (uint32_t)offsetof(CmtyRoleList__storage_, page),
        .flags = GPBFieldOptional,
        .dataType = GPBDataTypeMessage,
      },
    };
    GPBDescriptor *localDescriptor =
        [GPBDescriptor allocDescriptorForClass:[CmtyRoleList class]
                                     rootClass:[CmtyPermissionPbRoot class]
                                          file:CmtyPermissionPbRoot_FileDescriptor()
                                        fields:fields
                                    fieldCount:(uint32_t)(sizeof(fields) / sizeof(GPBMessageFieldDescription))
                                   storageSize:sizeof(CmtyRoleList__storage_)
                                         flags:(GPBDescriptorInitializationFlags)(GPBDescriptorInitializationFlag_UsesClassRefs | GPBDescriptorInitializationFlag_Proto3OptionalKnown)];
    #if defined(DEBUG) && DEBUG
      NSAssert(descriptor == nil, @"Startup recursed!");
    #endif  // DEBUG
    descriptor = localDescriptor;
  }
  return descriptor;
}

@end

#pragma mark - CmtyMemberRoleList

@implementation CmtyMemberRoleList

@dynamic memberRolesArray, memberRolesArray_Count;

typedef struct CmtyMemberRoleList__storage_ {
  uint32_t _has_storage_[1];
  NSMutableArray *memberRolesArray;
} CmtyMemberRoleList__storage_;

// This method is threadsafe because it is initially called
// in +initialize for each subclass.
+ (GPBDescriptor *)descriptor {
  static GPBDescriptor *descriptor = nil;
  if (!descriptor) {
    static GPBMessageFieldDescription fields[] = {
      {
        .name = "memberRolesArray",
        .dataTypeSpecific.clazz = GPBObjCClass(CmtyMemberRole),
        .number = CmtyMemberRoleList_FieldNumber_MemberRolesArray,
        .hasIndex = GPBNoHasBit,
        .offset = (uint32_t)offsetof(CmtyMemberRoleList__storage_, memberRolesArray),
        .flags = GPBFieldRepeated,
        .dataType = GPBDataTypeMessage,
      },
    };
    GPBDescriptor *localDescriptor =
        [GPBDescriptor allocDescriptorForClass:[CmtyMemberRoleList class]
                                     rootClass:[CmtyPermissionPbRoot class]
                                          file:CmtyPermissionPbRoot_FileDescriptor()
                                        fields:fields
                                    fieldCount:(uint32_t)(sizeof(fields) / sizeof(GPBMessageFieldDescription))
                                   storageSize:sizeof(CmtyMemberRoleList__storage_)
                                         flags:(GPBDescriptorInitializationFlags)(GPBDescriptorInitializationFlag_UsesClassRefs | GPBDescriptorInitializationFlag_Proto3OptionalKnown)];
    #if defined(DEBUG) && DEBUG
      NSAssert(descriptor == nil, @"Startup recursed!");
    #endif  // DEBUG
    descriptor = localDescriptor;
  }
  return descriptor;
}

@end

#pragma mark - CmtyRoleResourceList

@implementation CmtyRoleResourceList

@dynamic resourcesArray, resourcesArray_Count;

typedef struct CmtyRoleResourceList__storage_ {
  uint32_t _has_storage_[1];
  NSMutableArray *resourcesArray;
} CmtyRoleResourceList__storage_;

// This method is threadsafe because it is initially called
// in +initialize for each subclass.
+ (GPBDescriptor *)descriptor {
  static GPBDescriptor *descriptor = nil;
  if (!descriptor) {
    static GPBMessageFieldDescription fields[] = {
      {
        .name = "resourcesArray",
        .dataTypeSpecific.clazz = GPBObjCClass(CmtyRoleResource),
        .number = CmtyRoleResourceList_FieldNumber_ResourcesArray,
        .hasIndex = GPBNoHasBit,
        .offset = (uint32_t)offsetof(CmtyRoleResourceList__storage_, resourcesArray),
        .flags = GPBFieldRepeated,
        .dataType = GPBDataTypeMessage,
      },
    };
    GPBDescriptor *localDescriptor =
        [GPBDescriptor allocDescriptorForClass:[CmtyRoleResourceList class]
                                     rootClass:[CmtyPermissionPbRoot class]
                                          file:CmtyPermissionPbRoot_FileDescriptor()
                                        fields:fields
                                    fieldCount:(uint32_t)(sizeof(fields) / sizeof(GPBMessageFieldDescription))
                                   storageSize:sizeof(CmtyRoleResourceList__storage_)
                                         flags:(GPBDescriptorInitializationFlags)(GPBDescriptorInitializationFlag_UsesClassRefs | GPBDescriptorInitializationFlag_Proto3OptionalKnown)];
    #if defined(DEBUG) && DEBUG
      NSAssert(descriptor == nil, @"Startup recursed!");
    #endif  // DEBUG
    descriptor = localDescriptor;
  }
  return descriptor;
}

@end

#pragma mark - PermissionItem

@implementation PermissionItem

@dynamic permissionKey;
@dynamic permissionName;
@dynamic defaultEnabled;
@dynamic description_p;
@dynamic messageTypes;

typedef struct PermissionItem__storage_ {
  uint32_t _has_storage_[1];
  NSString *permissionKey;
  NSString *permissionName;
  NSString *description_p;
  NSString *messageTypes;
} PermissionItem__storage_;

// This method is threadsafe because it is initially called
// in +initialize for each subclass.
+ (GPBDescriptor *)descriptor {
  static GPBDescriptor *descriptor = nil;
  if (!descriptor) {
    static GPBMessageFieldDescription fields[] = {
      {
        .name = "permissionKey",
        .dataTypeSpecific.clazz = Nil,
        .number = PermissionItem_FieldNumber_PermissionKey,
        .hasIndex = 0,
        .offset = (uint32_t)offsetof(PermissionItem__storage_, permissionKey),
        .flags = (GPBFieldFlags)(GPBFieldOptional | GPBFieldClearHasIvarOnZero),
        .dataType = GPBDataTypeString,
      },
      {
        .name = "permissionName",
        .dataTypeSpecific.clazz = Nil,
        .number = PermissionItem_FieldNumber_PermissionName,
        .hasIndex = 1,
        .offset = (uint32_t)offsetof(PermissionItem__storage_, permissionName),
        .flags = (GPBFieldFlags)(GPBFieldOptional | GPBFieldClearHasIvarOnZero),
        .dataType = GPBDataTypeString,
      },
      {
        .name = "defaultEnabled",
        .dataTypeSpecific.clazz = Nil,
        .number = PermissionItem_FieldNumber_DefaultEnabled,
        .hasIndex = 2,
        .offset = 3,  // Stored in _has_storage_ to save space.
        .flags = (GPBFieldFlags)(GPBFieldOptional | GPBFieldClearHasIvarOnZero),
        .dataType = GPBDataTypeBool,
      },
      {
        .name = "description_p",
        .dataTypeSpecific.clazz = Nil,
        .number = PermissionItem_FieldNumber_Description_p,
        .hasIndex = 4,
        .offset = (uint32_t)offsetof(PermissionItem__storage_, description_p),
        .flags = (GPBFieldFlags)(GPBFieldOptional | GPBFieldClearHasIvarOnZero),
        .dataType = GPBDataTypeString,
      },
      {
        .name = "messageTypes",
        .dataTypeSpecific.clazz = Nil,
        .number = PermissionItem_FieldNumber_MessageTypes,
        .hasIndex = 5,
        .offset = (uint32_t)offsetof(PermissionItem__storage_, messageTypes),
        .flags = (GPBFieldFlags)(GPBFieldOptional | GPBFieldClearHasIvarOnZero),
        .dataType = GPBDataTypeString,
      },
    };
    GPBDescriptor *localDescriptor =
        [GPBDescriptor allocDescriptorForClass:[PermissionItem class]
                                     rootClass:[CmtyPermissionPbRoot class]
                                          file:CmtyPermissionPbRoot_FileDescriptor()
                                        fields:fields
                                    fieldCount:(uint32_t)(sizeof(fields) / sizeof(GPBMessageFieldDescription))
                                   storageSize:sizeof(PermissionItem__storage_)
                                         flags:(GPBDescriptorInitializationFlags)(GPBDescriptorInitializationFlag_UsesClassRefs | GPBDescriptorInitializationFlag_Proto3OptionalKnown)];
    #if defined(DEBUG) && DEBUG
      NSAssert(descriptor == nil, @"Startup recursed!");
    #endif  // DEBUG
    descriptor = localDescriptor;
  }
  return descriptor;
}

@end

#pragma mark - PermissionTemplate

@implementation PermissionTemplate

@dynamic itemsArray, itemsArray_Count;

typedef struct PermissionTemplate__storage_ {
  uint32_t _has_storage_[1];
  NSMutableArray *itemsArray;
} PermissionTemplate__storage_;

// This method is threadsafe because it is initially called
// in +initialize for each subclass.
+ (GPBDescriptor *)descriptor {
  static GPBDescriptor *descriptor = nil;
  if (!descriptor) {
    static GPBMessageFieldDescription fields[] = {
      {
        .name = "itemsArray",
        .dataTypeSpecific.clazz = GPBObjCClass(PermissionItem),
        .number = PermissionTemplate_FieldNumber_ItemsArray,
        .hasIndex = GPBNoHasBit,
        .offset = (uint32_t)offsetof(PermissionTemplate__storage_, itemsArray),
        .flags = GPBFieldRepeated,
        .dataType = GPBDataTypeMessage,
      },
    };
    GPBDescriptor *localDescriptor =
        [GPBDescriptor allocDescriptorForClass:[PermissionTemplate class]
                                     rootClass:[CmtyPermissionPbRoot class]
                                          file:CmtyPermissionPbRoot_FileDescriptor()
                                        fields:fields
                                    fieldCount:(uint32_t)(sizeof(fields) / sizeof(GPBMessageFieldDescription))
                                   storageSize:sizeof(PermissionTemplate__storage_)
                                         flags:(GPBDescriptorInitializationFlags)(GPBDescriptorInitializationFlag_UsesClassRefs | GPBDescriptorInitializationFlag_Proto3OptionalKnown)];
    #if defined(DEBUG) && DEBUG
      NSAssert(descriptor == nil, @"Startup recursed!");
    #endif  // DEBUG
    descriptor = localDescriptor;
  }
  return descriptor;
}

@end

#pragma mark - RolePermissionConfig

@implementation RolePermissionConfig

@dynamic roleCode;
@dynamic permissionsArray, permissionsArray_Count;

typedef struct RolePermissionConfig__storage_ {
  uint32_t _has_storage_[1];
  NSString *roleCode;
  NSMutableArray *permissionsArray;
} RolePermissionConfig__storage_;

// This method is threadsafe because it is initially called
// in +initialize for each subclass.
+ (GPBDescriptor *)descriptor {
  static GPBDescriptor *descriptor = nil;
  if (!descriptor) {
    static GPBMessageFieldDescription fields[] = {
      {
        .name = "roleCode",
        .dataTypeSpecific.clazz = Nil,
        .number = RolePermissionConfig_FieldNumber_RoleCode,
        .hasIndex = 0,
        .offset = (uint32_t)offsetof(RolePermissionConfig__storage_, roleCode),
        .flags = (GPBFieldFlags)(GPBFieldOptional | GPBFieldClearHasIvarOnZero),
        .dataType = GPBDataTypeString,
      },
      {
        .name = "permissionsArray",
        .dataTypeSpecific.clazz = GPBObjCClass(PermissionItem),
        .number = RolePermissionConfig_FieldNumber_PermissionsArray,
        .hasIndex = GPBNoHasBit,
        .offset = (uint32_t)offsetof(RolePermissionConfig__storage_, permissionsArray),
        .flags = GPBFieldRepeated,
        .dataType = GPBDataTypeMessage,
      },
    };
    GPBDescriptor *localDescriptor =
        [GPBDescriptor allocDescriptorForClass:[RolePermissionConfig class]
                                     rootClass:[CmtyPermissionPbRoot class]
                                          file:CmtyPermissionPbRoot_FileDescriptor()
                                        fields:fields
                                    fieldCount:(uint32_t)(sizeof(fields) / sizeof(GPBMessageFieldDescription))
                                   storageSize:sizeof(RolePermissionConfig__storage_)
                                         flags:(GPBDescriptorInitializationFlags)(GPBDescriptorInitializationFlag_UsesClassRefs | GPBDescriptorInitializationFlag_Proto3OptionalKnown)];
    #if defined(DEBUG) && DEBUG
      NSAssert(descriptor == nil, @"Startup recursed!");
    #endif  // DEBUG
    descriptor = localDescriptor;
  }
  return descriptor;
}

@end

#pragma mark - ConfigurePermissions

@implementation ConfigurePermissions

@dynamic cmtyId;
@dynamic roleConfigsArray, roleConfigsArray_Count;

typedef struct ConfigurePermissions__storage_ {
  uint32_t _has_storage_[1];
  NSString *cmtyId;
  NSMutableArray *roleConfigsArray;
} ConfigurePermissions__storage_;

// This method is threadsafe because it is initially called
// in +initialize for each subclass.
+ (GPBDescriptor *)descriptor {
  static GPBDescriptor *descriptor = nil;
  if (!descriptor) {
    static GPBMessageFieldDescription fields[] = {
      {
        .name = "cmtyId",
        .dataTypeSpecific.clazz = Nil,
        .number = ConfigurePermissions_FieldNumber_CmtyId,
        .hasIndex = 0,
        .offset = (uint32_t)offsetof(ConfigurePermissions__storage_, cmtyId),
        .flags = (GPBFieldFlags)(GPBFieldOptional | GPBFieldClearHasIvarOnZero),
        .dataType = GPBDataTypeString,
      },
      {
        .name = "roleConfigsArray",
        .dataTypeSpecific.clazz = GPBObjCClass(RolePermissionConfig),
        .number = ConfigurePermissions_FieldNumber_RoleConfigsArray,
        .hasIndex = GPBNoHasBit,
        .offset = (uint32_t)offsetof(ConfigurePermissions__storage_, roleConfigsArray),
        .flags = GPBFieldRepeated,
        .dataType = GPBDataTypeMessage,
      },
    };
    GPBDescriptor *localDescriptor =
        [GPBDescriptor allocDescriptorForClass:[ConfigurePermissions class]
                                     rootClass:[CmtyPermissionPbRoot class]
                                          file:CmtyPermissionPbRoot_FileDescriptor()
                                        fields:fields
                                    fieldCount:(uint32_t)(sizeof(fields) / sizeof(GPBMessageFieldDescription))
                                   storageSize:sizeof(ConfigurePermissions__storage_)
                                         flags:(GPBDescriptorInitializationFlags)(GPBDescriptorInitializationFlag_UsesClassRefs | GPBDescriptorInitializationFlag_Proto3OptionalKnown)];
    #if defined(DEBUG) && DEBUG
      NSAssert(descriptor == nil, @"Startup recursed!");
    #endif  // DEBUG
    descriptor = localDescriptor;
  }
  return descriptor;
}

@end

#pragma mark - CmtyRolesAndTemplate

@implementation CmtyRolesAndTemplate

@dynamic rolesArray, rolesArray_Count;
@dynamic hasTemplate_p, template_p;

typedef struct CmtyRolesAndTemplate__storage_ {
  uint32_t _has_storage_[1];
  NSMutableArray *rolesArray;
  PermissionTemplate *template_p;
} CmtyRolesAndTemplate__storage_;

// This method is threadsafe because it is initially called
// in +initialize for each subclass.
+ (GPBDescriptor *)descriptor {
  static GPBDescriptor *descriptor = nil;
  if (!descriptor) {
    static GPBMessageFieldDescription fields[] = {
      {
        .name = "rolesArray",
        .dataTypeSpecific.clazz = GPBObjCClass(Role),
        .number = CmtyRolesAndTemplate_FieldNumber_RolesArray,
        .hasIndex = GPBNoHasBit,
        .offset = (uint32_t)offsetof(CmtyRolesAndTemplate__storage_, rolesArray),
        .flags = GPBFieldRepeated,
        .dataType = GPBDataTypeMessage,
      },
      {
        .name = "template_p",
        .dataTypeSpecific.clazz = GPBObjCClass(PermissionTemplate),
        .number = CmtyRolesAndTemplate_FieldNumber_Template_p,
        .hasIndex = 0,
        .offset = (uint32_t)offsetof(CmtyRolesAndTemplate__storage_, template_p),
        .flags = GPBFieldOptional,
        .dataType = GPBDataTypeMessage,
      },
    };
    GPBDescriptor *localDescriptor =
        [GPBDescriptor allocDescriptorForClass:[CmtyRolesAndTemplate class]
                                     rootClass:[CmtyPermissionPbRoot class]
                                          file:CmtyPermissionPbRoot_FileDescriptor()
                                        fields:fields
                                    fieldCount:(uint32_t)(sizeof(fields) / sizeof(GPBMessageFieldDescription))
                                   storageSize:sizeof(CmtyRolesAndTemplate__storage_)
                                         flags:(GPBDescriptorInitializationFlags)(GPBDescriptorInitializationFlag_UsesClassRefs | GPBDescriptorInitializationFlag_Proto3OptionalKnown)];
    #if defined(DEBUG) && DEBUG
      NSAssert(descriptor == nil, @"Startup recursed!");
    #endif  // DEBUG
    descriptor = localDescriptor;
  }
  return descriptor;
}

@end

#pragma mark - CmtyMemberRolePermissions

@implementation CmtyMemberRolePermissions

@dynamic hasRolePermissions, rolePermissions;

typedef struct CmtyMemberRolePermissions__storage_ {
  uint32_t _has_storage_[1];
  RolePermissionConfig *rolePermissions;
} CmtyMemberRolePermissions__storage_;

// This method is threadsafe because it is initially called
// in +initialize for each subclass.
+ (GPBDescriptor *)descriptor {
  static GPBDescriptor *descriptor = nil;
  if (!descriptor) {
    static GPBMessageFieldDescription fields[] = {
      {
        .name = "rolePermissions",
        .dataTypeSpecific.clazz = GPBObjCClass(RolePermissionConfig),
        .number = CmtyMemberRolePermissions_FieldNumber_RolePermissions,
        .hasIndex = 0,
        .offset = (uint32_t)offsetof(CmtyMemberRolePermissions__storage_, rolePermissions),
        .flags = GPBFieldOptional,
        .dataType = GPBDataTypeMessage,
      },
    };
    GPBDescriptor *localDescriptor =
        [GPBDescriptor allocDescriptorForClass:[CmtyMemberRolePermissions class]
                                     rootClass:[CmtyPermissionPbRoot class]
                                          file:CmtyPermissionPbRoot_FileDescriptor()
                                        fields:fields
                                    fieldCount:(uint32_t)(sizeof(fields) / sizeof(GPBMessageFieldDescription))
                                   storageSize:sizeof(CmtyMemberRolePermissions__storage_)
                                         flags:(GPBDescriptorInitializationFlags)(GPBDescriptorInitializationFlag_UsesClassRefs | GPBDescriptorInitializationFlag_Proto3OptionalKnown)];
    #if defined(DEBUG) && DEBUG
      NSAssert(descriptor == nil, @"Startup recursed!");
    #endif  // DEBUG
    descriptor = localDescriptor;
  }
  return descriptor;
}

@end


#pragma clang diagnostic pop

// @@protoc_insertion_point(global_scope)
