//// Generated by the protocol buffer compiler.  DO NOT EDIT!
//// source: cmty/cmty_pb.proto
//
//// This CPP symbol can be defined to use imports that match up to the framework
//// imports needed when using CocoaPods.
//#if !defined(GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS)
// #define GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS 0
//#endif
//
//#if GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS
// #import <Protobuf/GPBProtocolBuffers_RuntimeSupport.h>
//#else
// #import "GPBProtocolBuffers_RuntimeSupport.h"
//#endif
//
//#import <stdatomic.h>
//
//#import "CmtyPb.pbobjc.h"
//#import "SystemPb.pbobjc.h"
//// @@protoc_insertion_point(imports)
//
//#pragma clang diagnostic push
//#pragma clang diagnostic ignored "-Wdeprecated-declarations"
//#pragma clang diagnostic ignored "-Wdollar-in-identifier-extension"
//
//#pragma mark - Objective C Class declarations
//// Forward declarations of Objective C classes that we can use as
//// static values in struct initializers.
//// We don't use [Foo class] because it is not a static value.
//GPBObjCClassDeclaration(Cmty);
//GPBObjCClassDeclaration(Page);
//
//#pragma mark - CmtyPbRoot
//
//@implementation CmtyPbRoot
//
//// No extensions in the file and none of the imports (direct or indirect)
//// defined extensions, so no need to generate +extensionRegistry.
//
//@end
//
//#pragma mark - CmtyPbRoot_FileDescriptor
//
//static GPBFileDescriptor *CmtyPbRoot_FileDescriptor(void) {
//  // This is called by +initialize so there is no need to worry
//  // about thread safety of the singleton.
//  static GPBFileDescriptor *descriptor = NULL;
//  if (!descriptor) {
//    GPB_DEBUG_CHECK_RUNTIME_VERSIONS();
//    descriptor = [[GPBFileDescriptor alloc] initWithPackage:@"im.cmty"
//                                                     syntax:GPBFileSyntaxProto3];
//  }
//  return descriptor;
//}
//
//#pragma mark - Enum CmtyStatus
//
//GPBEnumDescriptor *CmtyStatus_EnumDescriptor(void) {
//  static _Atomic(GPBEnumDescriptor*) descriptor = nil;
//  if (!descriptor) {
//    static const char *valueNames =
//        "Active\000Disabled\000Suspended\000";
//    static const int32_t values[] = {
//        CmtyStatus_Active,
//        CmtyStatus_Disabled,
//        CmtyStatus_Suspended,
//    };
//    GPBEnumDescriptor *worker =
//        [GPBEnumDescriptor allocDescriptorForName:GPBNSStringifySymbol(CmtyStatus)
//                                       valueNames:valueNames
//                                           values:values
//                                            count:(uint32_t)(sizeof(values) / sizeof(int32_t))
//                                     enumVerifier:CmtyStatus_IsValidValue];
//    GPBEnumDescriptor *expected = nil;
////    if (!atomic_compare_exchange_strong(&descriptor, &expected, worker)) {
////      [worker release];
////    }
//  }
//  return descriptor;
//}
//
//BOOL CmtyStatus_IsValidValue(int32_t value__) {
//  switch (value__) {
//    case CmtyStatus_Active:
//    case CmtyStatus_Disabled:
//    case CmtyStatus_Suspended:
//      return YES;
//    default:
//      return NO;
//  }
//}
//
//#pragma mark - Enum MemberStatus
//
//GPBEnumDescriptor *MemberStatus_EnumDescriptor(void) {
//  static _Atomic(GPBEnumDescriptor*) descriptor = nil;
//  if (!descriptor) {
//    static const char *valueNames =
//        "Normal\000Muted\000Banned\000Kicked\000";
//    static const int32_t values[] = {
//        MemberStatus_Normal,
//        MemberStatus_Muted,
//        MemberStatus_Banned,
//        MemberStatus_Kicked,
//    };
//    GPBEnumDescriptor *worker =
//        [GPBEnumDescriptor allocDescriptorForName:GPBNSStringifySymbol(MemberStatus)
//                                       valueNames:valueNames
//                                           values:values
//                                            count:(uint32_t)(sizeof(values) / sizeof(int32_t))
//                                     enumVerifier:MemberStatus_IsValidValue];
//    GPBEnumDescriptor *expected = nil;
////    if (!atomic_compare_exchange_strong(&descriptor, &expected, worker)) {
////      [worker release];
////    }
//  }
//  return descriptor;
//}
//
//BOOL MemberStatus_IsValidValue(int32_t value__) {
//  switch (value__) {
//    case MemberStatus_Normal:
//    case MemberStatus_Muted:
//    case MemberStatus_Banned:
//    case MemberStatus_Kicked:
//      return YES;
//    default:
//      return NO;
//  }
//}
//
//#pragma mark - CmtyListQuery
//
//@implementation CmtyListQuery
//
//@dynamic hasPage, page;
//@dynamic keyword;
//
//typedef struct CmtyListQuery__storage_ {
//  uint32_t _has_storage_[1];
//  Page *page;
//  NSString *keyword;
//} CmtyListQuery__storage_;
//
//// This method is threadsafe because it is initially called
//// in +initialize for each subclass.
//+ (GPBDescriptor *)descriptor {
//  static GPBDescriptor *descriptor = nil;
//  if (!descriptor) {
//    static GPBMessageFieldDescription fields[] = {
//      {
//        .name = "page",
//        .dataTypeSpecific.clazz = GPBObjCClass(Page),
//        .number = CmtyListQuery_FieldNumber_Page,
//        .hasIndex = 0,
//        .offset = (uint32_t)offsetof(CmtyListQuery__storage_, page),
//        .flags = GPBFieldOptional,
//        .dataType = GPBDataTypeMessage,
//      },
//      {
//        .name = "keyword",
//        .dataTypeSpecific.clazz = Nil,
//        .number = CmtyListQuery_FieldNumber_Keyword,
//        .hasIndex = 1,
//        .offset = (uint32_t)offsetof(CmtyListQuery__storage_, keyword),
//        .flags = (GPBFieldFlags)(GPBFieldOptional | GPBFieldClearHasIvarOnZero),
//        .dataType = GPBDataTypeString,
//      },
//    };
//    GPBDescriptor *localDescriptor =
//        [GPBDescriptor allocDescriptorForClass:[CmtyListQuery class]
//                                     rootClass:[CmtyPbRoot class]
//                                          file:CmtyPbRoot_FileDescriptor()
//                                        fields:fields
//                                    fieldCount:(uint32_t)(sizeof(fields) / sizeof(GPBMessageFieldDescription))
//                                   storageSize:sizeof(CmtyListQuery__storage_)
//                                         flags:(GPBDescriptorInitializationFlags)(GPBDescriptorInitializationFlag_UsesClassRefs | GPBDescriptorInitializationFlag_Proto3OptionalKnown)];
//    #if defined(DEBUG) && DEBUG
//      NSAssert(descriptor == nil, @"Startup recursed!");
//    #endif  // DEBUG
//    descriptor = localDescriptor;
//  }
//  return descriptor;
//}
//
//@end
//
//#pragma mark - Cmty
//
//@implementation Cmty
//
//@dynamic communityId;
//@dynamic communityName;
//@dynamic communityAvatar;
//@dynamic description_p;
//@dynamic ownerId;
//@dynamic memberCount;
//@dynamic status;
//@dynamic needVerify;
//@dynamic allowPrivateChat;
//@dynamic allowAddFriend;
//@dynamic createdAt;
//@dynamic updatedAt;
//@dynamic extraInfo;
//@dynamic isMember;
//
//typedef struct Cmty__storage_ {
//  uint32_t _has_storage_[1];
//  int32_t memberCount;
//  CmtyStatus status;
//  NSString *communityId;
//  NSString *communityName;
//  NSString *communityAvatar;
//  NSString *description_p;
//  NSString *ownerId;
//  NSString *extraInfo;
//  int64_t createdAt;
//  int64_t updatedAt;
//} Cmty__storage_;
//
//// This method is threadsafe because it is initially called
//// in +initialize for each subclass.
//+ (GPBDescriptor *)descriptor {
//  static GPBDescriptor *descriptor = nil;
//  if (!descriptor) {
//    static GPBMessageFieldDescription fields[] = {
//      {
//        .name = "communityId",
//        .dataTypeSpecific.clazz = Nil,
//        .number = Cmty_FieldNumber_CommunityId,
//        .hasIndex = 0,
//        .offset = (uint32_t)offsetof(Cmty__storage_, communityId),
//        .flags = (GPBFieldFlags)(GPBFieldOptional | GPBFieldClearHasIvarOnZero),
//        .dataType = GPBDataTypeString,
//      },
//      {
//        .name = "communityName",
//        .dataTypeSpecific.clazz = Nil,
//        .number = Cmty_FieldNumber_CommunityName,
//        .hasIndex = 1,
//        .offset = (uint32_t)offsetof(Cmty__storage_, communityName),
//        .flags = (GPBFieldFlags)(GPBFieldOptional | GPBFieldClearHasIvarOnZero),
//        .dataType = GPBDataTypeString,
//      },
//      {
//        .name = "communityAvatar",
//        .dataTypeSpecific.clazz = Nil,
//        .number = Cmty_FieldNumber_CommunityAvatar,
//        .hasIndex = 2,
//        .offset = (uint32_t)offsetof(Cmty__storage_, communityAvatar),
//        .flags = (GPBFieldFlags)(GPBFieldOptional | GPBFieldClearHasIvarOnZero),
//        .dataType = GPBDataTypeString,
//      },
//      {
//        .name = "description_p",
//        .dataTypeSpecific.clazz = Nil,
//        .number = Cmty_FieldNumber_Description_p,
//        .hasIndex = 3,
//        .offset = (uint32_t)offsetof(Cmty__storage_, description_p),
//        .flags = (GPBFieldFlags)(GPBFieldOptional | GPBFieldClearHasIvarOnZero),
//        .dataType = GPBDataTypeString,
//      },
//      {
//        .name = "ownerId",
//        .dataTypeSpecific.clazz = Nil,
//        .number = Cmty_FieldNumber_OwnerId,
//        .hasIndex = 4,
//        .offset = (uint32_t)offsetof(Cmty__storage_, ownerId),
//        .flags = (GPBFieldFlags)(GPBFieldOptional | GPBFieldClearHasIvarOnZero),
//        .dataType = GPBDataTypeString,
//      },
//      {
//        .name = "memberCount",
//        .dataTypeSpecific.clazz = Nil,
//        .number = Cmty_FieldNumber_MemberCount,
//        .hasIndex = 5,
//        .offset = (uint32_t)offsetof(Cmty__storage_, memberCount),
//        .flags = (GPBFieldFlags)(GPBFieldOptional | GPBFieldClearHasIvarOnZero),
//        .dataType = GPBDataTypeInt32,
//      },
//      {
//        .name = "status",
//        .dataTypeSpecific.enumDescFunc = CmtyStatus_EnumDescriptor,
//        .number = Cmty_FieldNumber_Status,
//        .hasIndex = 6,
//        .offset = (uint32_t)offsetof(Cmty__storage_, status),
//        .flags = (GPBFieldFlags)(GPBFieldOptional | GPBFieldHasEnumDescriptor | GPBFieldClearHasIvarOnZero),
//        .dataType = GPBDataTypeEnum,
//      },
//      {
//        .name = "needVerify",
//        .dataTypeSpecific.clazz = Nil,
//        .number = Cmty_FieldNumber_NeedVerify,
//        .hasIndex = 7,
//        .offset = 8,  // Stored in _has_storage_ to save space.
//        .flags = (GPBFieldFlags)(GPBFieldOptional | GPBFieldClearHasIvarOnZero),
//        .dataType = GPBDataTypeBool,
//      },
//      {
//        .name = "allowPrivateChat",
//        .dataTypeSpecific.clazz = Nil,
//        .number = Cmty_FieldNumber_AllowPrivateChat,
//        .hasIndex = 9,
//        .offset = 10,  // Stored in _has_storage_ to save space.
//        .flags = (GPBFieldFlags)(GPBFieldOptional | GPBFieldClearHasIvarOnZero),
//        .dataType = GPBDataTypeBool,
//      },
//      {
//        .name = "allowAddFriend",
//        .dataTypeSpecific.clazz = Nil,
//        .number = Cmty_FieldNumber_AllowAddFriend,
//        .hasIndex = 11,
//        .offset = 12,  // Stored in _has_storage_ to save space.
//        .flags = (GPBFieldFlags)(GPBFieldOptional | GPBFieldClearHasIvarOnZero),
//        .dataType = GPBDataTypeBool,
//      },
//      {
//        .name = "createdAt",
//        .dataTypeSpecific.clazz = Nil,
//        .number = Cmty_FieldNumber_CreatedAt,
//        .hasIndex = 13,
//        .offset = (uint32_t)offsetof(Cmty__storage_, createdAt),
//        .flags = (GPBFieldFlags)(GPBFieldOptional | GPBFieldClearHasIvarOnZero),
//        .dataType = GPBDataTypeInt64,
//      },
//      {
//        .name = "updatedAt",
//        .dataTypeSpecific.clazz = Nil,
//        .number = Cmty_FieldNumber_UpdatedAt,
//        .hasIndex = 14,
//        .offset = (uint32_t)offsetof(Cmty__storage_, updatedAt),
//        .flags = (GPBFieldFlags)(GPBFieldOptional | GPBFieldClearHasIvarOnZero),
//        .dataType = GPBDataTypeInt64,
//      },
//      {
//        .name = "extraInfo",
//        .dataTypeSpecific.clazz = Nil,
//        .number = Cmty_FieldNumber_ExtraInfo,
//        .hasIndex = 15,
//        .offset = (uint32_t)offsetof(Cmty__storage_, extraInfo),
//        .flags = (GPBFieldFlags)(GPBFieldOptional | GPBFieldClearHasIvarOnZero),
//        .dataType = GPBDataTypeString,
//      },
//      {
//        .name = "isMember",
//        .dataTypeSpecific.clazz = Nil,
//        .number = Cmty_FieldNumber_IsMember,
//        .hasIndex = 16,
//        .offset = 17,  // Stored in _has_storage_ to save space.
//        .flags = (GPBFieldFlags)(GPBFieldOptional | GPBFieldClearHasIvarOnZero),
//        .dataType = GPBDataTypeBool,
//      },
//    };
//    GPBDescriptor *localDescriptor =
//        [GPBDescriptor allocDescriptorForClass:[Cmty class]
//                                     rootClass:[CmtyPbRoot class]
//                                          file:CmtyPbRoot_FileDescriptor()
//                                        fields:fields
//                                    fieldCount:(uint32_t)(sizeof(fields) / sizeof(GPBMessageFieldDescription))
//                                   storageSize:sizeof(Cmty__storage_)
//                                         flags:(GPBDescriptorInitializationFlags)(GPBDescriptorInitializationFlag_UsesClassRefs | GPBDescriptorInitializationFlag_Proto3OptionalKnown)];
//    #if defined(DEBUG) && DEBUG
//      NSAssert(descriptor == nil, @"Startup recursed!");
//    #endif  // DEBUG
//    descriptor = localDescriptor;
//  }
//  return descriptor;
//}
//
//@end
//
//int32_t Cmty_Status_RawValue(Cmty *message) {
//  GPBDescriptor *descriptor = [Cmty descriptor];
//  GPBFieldDescriptor *field = [descriptor fieldWithNumber:Cmty_FieldNumber_Status];
//  return GPBGetMessageRawEnumField(message, field);
//}
//
//void SetCmty_Status_RawValue(Cmty *message, int32_t value) {
//  GPBDescriptor *descriptor = [Cmty descriptor];
//  GPBFieldDescriptor *field = [descriptor fieldWithNumber:Cmty_FieldNumber_Status];
//  GPBSetMessageRawEnumField(message, field, value);
//}
//
//#pragma mark - CmtyList
//
//@implementation CmtyList
//
//@dynamic communitiesArray, communitiesArray_Count;
//@dynamic hasPage, page;
//
//typedef struct CmtyList__storage_ {
//  uint32_t _has_storage_[1];
//  NSMutableArray *communitiesArray;
//  Page *page;
//} CmtyList__storage_;
//
//// This method is threadsafe because it is initially called
//// in +initialize for each subclass.
//+ (GPBDescriptor *)descriptor {
//  static GPBDescriptor *descriptor = nil;
//  if (!descriptor) {
//    static GPBMessageFieldDescription fields[] = {
//      {
//        .name = "communitiesArray",
//        .dataTypeSpecific.clazz = GPBObjCClass(Cmty),
//        .number = CmtyList_FieldNumber_CommunitiesArray,
//        .hasIndex = GPBNoHasBit,
//        .offset = (uint32_t)offsetof(CmtyList__storage_, communitiesArray),
//        .flags = GPBFieldRepeated,
//        .dataType = GPBDataTypeMessage,
//      },
//      {
//        .name = "page",
//        .dataTypeSpecific.clazz = GPBObjCClass(Page),
//        .number = CmtyList_FieldNumber_Page,
//        .hasIndex = 0,
//        .offset = (uint32_t)offsetof(CmtyList__storage_, page),
//        .flags = GPBFieldOptional,
//        .dataType = GPBDataTypeMessage,
//      },
//    };
//    GPBDescriptor *localDescriptor =
//        [GPBDescriptor allocDescriptorForClass:[CmtyList class]
//                                     rootClass:[CmtyPbRoot class]
//                                          file:CmtyPbRoot_FileDescriptor()
//                                        fields:fields
//                                    fieldCount:(uint32_t)(sizeof(fields) / sizeof(GPBMessageFieldDescription))
//                                   storageSize:sizeof(CmtyList__storage_)
//                                         flags:(GPBDescriptorInitializationFlags)(GPBDescriptorInitializationFlag_UsesClassRefs | GPBDescriptorInitializationFlag_Proto3OptionalKnown)];
//    #if defined(DEBUG) && DEBUG
//      NSAssert(descriptor == nil, @"Startup recursed!");
//    #endif  // DEBUG
//    descriptor = localDescriptor;
//  }
//  return descriptor;
//}
//
//@end
//
//#pragma mark - CmtySettings
//
//@implementation CmtySettings
//
//@dynamic communityId;
//@dynamic needVerify;
//@dynamic allowPrivateChat;
//@dynamic allowAddFriend;
//@dynamic pauseInvite;
//@dynamic allowAccessOtherChannels;
//@dynamic newMemberSpeakTime;
//@dynamic speakFrequencyLimit;
//@dynamic speakTypeLimit;
//@dynamic speakCountLimit;
//
//typedef struct CmtySettings__storage_ {
//  uint32_t _has_storage_[1];
//  int32_t newMemberSpeakTime;
//  int32_t speakFrequencyLimit;
//  int32_t speakTypeLimit;
//  int32_t speakCountLimit;
//  NSString *communityId;
//} CmtySettings__storage_;
//
//// This method is threadsafe because it is initially called
//// in +initialize for each subclass.
//+ (GPBDescriptor *)descriptor {
//  static GPBDescriptor *descriptor = nil;
//  if (!descriptor) {
//    static GPBMessageFieldDescription fields[] = {
//      {
//        .name = "communityId",
//        .dataTypeSpecific.clazz = Nil,
//        .number = CmtySettings_FieldNumber_CommunityId,
//        .hasIndex = 0,
//        .offset = (uint32_t)offsetof(CmtySettings__storage_, communityId),
//        .flags = (GPBFieldFlags)(GPBFieldOptional | GPBFieldClearHasIvarOnZero),
//        .dataType = GPBDataTypeString,
//      },
//      {
//        .name = "needVerify",
//        .dataTypeSpecific.clazz = Nil,
//        .number = CmtySettings_FieldNumber_NeedVerify,
//        .hasIndex = 1,
//        .offset = 2,  // Stored in _has_storage_ to save space.
//        .flags = (GPBFieldFlags)(GPBFieldOptional | GPBFieldClearHasIvarOnZero),
//        .dataType = GPBDataTypeBool,
//      },
//      {
//        .name = "allowPrivateChat",
//        .dataTypeSpecific.clazz = Nil,
//        .number = CmtySettings_FieldNumber_AllowPrivateChat,
//        .hasIndex = 3,
//        .offset = 4,  // Stored in _has_storage_ to save space.
//        .flags = (GPBFieldFlags)(GPBFieldOptional | GPBFieldClearHasIvarOnZero),
//        .dataType = GPBDataTypeBool,
//      },
//      {
//        .name = "allowAddFriend",
//        .dataTypeSpecific.clazz = Nil,
//        .number = CmtySettings_FieldNumber_AllowAddFriend,
//        .hasIndex = 5,
//        .offset = 6,  // Stored in _has_storage_ to save space.
//        .flags = (GPBFieldFlags)(GPBFieldOptional | GPBFieldClearHasIvarOnZero),
//        .dataType = GPBDataTypeBool,
//      },
//      {
//        .name = "pauseInvite",
//        .dataTypeSpecific.clazz = Nil,
//        .number = CmtySettings_FieldNumber_PauseInvite,
//        .hasIndex = 7,
//        .offset = 8,  // Stored in _has_storage_ to save space.
//        .flags = (GPBFieldFlags)(GPBFieldOptional | GPBFieldClearHasIvarOnZero),
//        .dataType = GPBDataTypeBool,
//      },
//      {
//        .name = "allowAccessOtherChannels",
//        .dataTypeSpecific.clazz = Nil,
//        .number = CmtySettings_FieldNumber_AllowAccessOtherChannels,
//        .hasIndex = 9,
//        .offset = 10,  // Stored in _has_storage_ to save space.
//        .flags = (GPBFieldFlags)(GPBFieldOptional | GPBFieldClearHasIvarOnZero),
//        .dataType = GPBDataTypeBool,
//      },
//      {
//        .name = "newMemberSpeakTime",
//        .dataTypeSpecific.clazz = Nil,
//        .number = CmtySettings_FieldNumber_NewMemberSpeakTime,
//        .hasIndex = 11,
//        .offset = (uint32_t)offsetof(CmtySettings__storage_, newMemberSpeakTime),
//        .flags = (GPBFieldFlags)(GPBFieldOptional | GPBFieldClearHasIvarOnZero),
//        .dataType = GPBDataTypeInt32,
//      },
//      {
//        .name = "speakFrequencyLimit",
//        .dataTypeSpecific.clazz = Nil,
//        .number = CmtySettings_FieldNumber_SpeakFrequencyLimit,
//        .hasIndex = 12,
//        .offset = (uint32_t)offsetof(CmtySettings__storage_, speakFrequencyLimit),
//        .flags = (GPBFieldFlags)(GPBFieldOptional | GPBFieldClearHasIvarOnZero),
//        .dataType = GPBDataTypeInt32,
//      },
//      {
//        .name = "speakTypeLimit",
//        .dataTypeSpecific.clazz = Nil,
//        .number = CmtySettings_FieldNumber_SpeakTypeLimit,
//        .hasIndex = 13,
//        .offset = (uint32_t)offsetof(CmtySettings__storage_, speakTypeLimit),
//        .flags = (GPBFieldFlags)(GPBFieldOptional | GPBFieldClearHasIvarOnZero),
//        .dataType = GPBDataTypeInt32,
//      },
//      {
//        .name = "speakCountLimit",
//        .dataTypeSpecific.clazz = Nil,
//        .number = CmtySettings_FieldNumber_SpeakCountLimit,
//        .hasIndex = 14,
//        .offset = (uint32_t)offsetof(CmtySettings__storage_, speakCountLimit),
//        .flags = (GPBFieldFlags)(GPBFieldOptional | GPBFieldClearHasIvarOnZero),
//        .dataType = GPBDataTypeInt32,
//      },
//    };
//    GPBDescriptor *localDescriptor =
//        [GPBDescriptor allocDescriptorForClass:[CmtySettings class]
//                                     rootClass:[CmtyPbRoot class]
//                                          file:CmtyPbRoot_FileDescriptor()
//                                        fields:fields
//                                    fieldCount:(uint32_t)(sizeof(fields) / sizeof(GPBMessageFieldDescription))
//                                   storageSize:sizeof(CmtySettings__storage_)
//                                         flags:(GPBDescriptorInitializationFlags)(GPBDescriptorInitializationFlag_UsesClassRefs | GPBDescriptorInitializationFlag_Proto3OptionalKnown)];
//    #if defined(DEBUG) && DEBUG
//      NSAssert(descriptor == nil, @"Startup recursed!");
//    #endif  // DEBUG
//    descriptor = localDescriptor;
//  }
//  return descriptor;
//}
//
//@end
//
//#pragma mark - CmtyJoin
//
//@implementation CmtyJoin
//
//@dynamic inviteCode;
//@dynamic inviteLink;
//
//typedef struct CmtyJoin__storage_ {
//  uint32_t _has_storage_[1];
//  NSString *inviteCode;
//  NSString *inviteLink;
//} CmtyJoin__storage_;
//
//// This method is threadsafe because it is initially called
//// in +initialize for each subclass.
//+ (GPBDescriptor *)descriptor {
//  static GPBDescriptor *descriptor = nil;
//  if (!descriptor) {
//    static GPBMessageFieldDescription fields[] = {
//      {
//        .name = "inviteCode",
//        .dataTypeSpecific.clazz = Nil,
//        .number = CmtyJoin_FieldNumber_InviteCode,
//        .hasIndex = 0,
//        .offset = (uint32_t)offsetof(CmtyJoin__storage_, inviteCode),
//        .flags = (GPBFieldFlags)(GPBFieldOptional | GPBFieldClearHasIvarOnZero),
//        .dataType = GPBDataTypeString,
//      },
//      {
//        .name = "inviteLink",
//        .dataTypeSpecific.clazz = Nil,
//        .number = CmtyJoin_FieldNumber_InviteLink,
//        .hasIndex = 1,
//        .offset = (uint32_t)offsetof(CmtyJoin__storage_, inviteLink),
//        .flags = (GPBFieldFlags)(GPBFieldOptional | GPBFieldClearHasIvarOnZero),
//        .dataType = GPBDataTypeString,
//      },
//    };
//    GPBDescriptor *localDescriptor =
//        [GPBDescriptor allocDescriptorForClass:[CmtyJoin class]
//                                     rootClass:[CmtyPbRoot class]
//                                          file:CmtyPbRoot_FileDescriptor()
//                                        fields:fields
//                                    fieldCount:(uint32_t)(sizeof(fields) / sizeof(GPBMessageFieldDescription))
//                                   storageSize:sizeof(CmtyJoin__storage_)
//                                         flags:(GPBDescriptorInitializationFlags)(GPBDescriptorInitializationFlag_UsesClassRefs | GPBDescriptorInitializationFlag_Proto3OptionalKnown)];
//    #if defined(DEBUG) && DEBUG
//      NSAssert(descriptor == nil, @"Startup recursed!");
//    #endif  // DEBUG
//    descriptor = localDescriptor;
//  }
//  return descriptor;
//}
//
//@end
//
//#pragma mark - CmtyUpdateSettings
//
//@implementation CmtyUpdateSettings
//
//@dynamic needVerify;
//@dynamic allowPrivateChat;
//@dynamic allowAddFriend;
//@dynamic pauseInvite;
//@dynamic allowAccessOtherChannels;
//@dynamic newMemberSpeakTime;
//@dynamic speakFrequencyLimit;
//@dynamic speakTypeLimit;
//@dynamic speakCountLimit;
//
//typedef struct CmtyUpdateSettings__storage_ {
//  uint32_t _has_storage_[1];
//  int32_t newMemberSpeakTime;
//  int32_t speakFrequencyLimit;
//  int32_t speakTypeLimit;
//  int32_t speakCountLimit;
//} CmtyUpdateSettings__storage_;
//
//// This method is threadsafe because it is initially called
//// in +initialize for each subclass.
//+ (GPBDescriptor *)descriptor {
//  static GPBDescriptor *descriptor = nil;
//  if (!descriptor) {
//    static GPBMessageFieldDescription fields[] = {
//      {
//        .name = "needVerify",
//        .dataTypeSpecific.clazz = Nil,
//        .number = CmtyUpdateSettings_FieldNumber_NeedVerify,
//        .hasIndex = 0,
//        .offset = 1,  // Stored in _has_storage_ to save space.
//        .flags = (GPBFieldFlags)(GPBFieldOptional | GPBFieldClearHasIvarOnZero),
//        .dataType = GPBDataTypeBool,
//      },
//      {
//        .name = "allowPrivateChat",
//        .dataTypeSpecific.clazz = Nil,
//        .number = CmtyUpdateSettings_FieldNumber_AllowPrivateChat,
//        .hasIndex = 2,
//        .offset = 3,  // Stored in _has_storage_ to save space.
//        .flags = (GPBFieldFlags)(GPBFieldOptional | GPBFieldClearHasIvarOnZero),
//        .dataType = GPBDataTypeBool,
//      },
//      {
//        .name = "allowAddFriend",
//        .dataTypeSpecific.clazz = Nil,
//        .number = CmtyUpdateSettings_FieldNumber_AllowAddFriend,
//        .hasIndex = 4,
//        .offset = 5,  // Stored in _has_storage_ to save space.
//        .flags = (GPBFieldFlags)(GPBFieldOptional | GPBFieldClearHasIvarOnZero),
//        .dataType = GPBDataTypeBool,
//      },
//      {
//        .name = "pauseInvite",
//        .dataTypeSpecific.clazz = Nil,
//        .number = CmtyUpdateSettings_FieldNumber_PauseInvite,
//        .hasIndex = 6,
//        .offset = 7,  // Stored in _has_storage_ to save space.
//        .flags = (GPBFieldFlags)(GPBFieldOptional | GPBFieldClearHasIvarOnZero),
//        .dataType = GPBDataTypeBool,
//      },
//      {
//        .name = "allowAccessOtherChannels",
//        .dataTypeSpecific.clazz = Nil,
//        .number = CmtyUpdateSettings_FieldNumber_AllowAccessOtherChannels,
//        .hasIndex = 8,
//        .offset = 9,  // Stored in _has_storage_ to save space.
//        .flags = (GPBFieldFlags)(GPBFieldOptional | GPBFieldClearHasIvarOnZero),
//        .dataType = GPBDataTypeBool,
//      },
//      {
//        .name = "newMemberSpeakTime",
//        .dataTypeSpecific.clazz = Nil,
//        .number = CmtyUpdateSettings_FieldNumber_NewMemberSpeakTime,
//        .hasIndex = 10,
//        .offset = (uint32_t)offsetof(CmtyUpdateSettings__storage_, newMemberSpeakTime),
//        .flags = (GPBFieldFlags)(GPBFieldOptional | GPBFieldClearHasIvarOnZero),
//        .dataType = GPBDataTypeInt32,
//      },
//      {
//        .name = "speakFrequencyLimit",
//        .dataTypeSpecific.clazz = Nil,
//        .number = CmtyUpdateSettings_FieldNumber_SpeakFrequencyLimit,
//        .hasIndex = 11,
//        .offset = (uint32_t)offsetof(CmtyUpdateSettings__storage_, speakFrequencyLimit),
//        .flags = (GPBFieldFlags)(GPBFieldOptional | GPBFieldClearHasIvarOnZero),
//        .dataType = GPBDataTypeInt32,
//      },
//      {
//        .name = "speakTypeLimit",
//        .dataTypeSpecific.clazz = Nil,
//        .number = CmtyUpdateSettings_FieldNumber_SpeakTypeLimit,
//        .hasIndex = 12,
//        .offset = (uint32_t)offsetof(CmtyUpdateSettings__storage_, speakTypeLimit),
//        .flags = (GPBFieldFlags)(GPBFieldOptional | GPBFieldClearHasIvarOnZero),
//        .dataType = GPBDataTypeInt32,
//      },
//      {
//        .name = "speakCountLimit",
//        .dataTypeSpecific.clazz = Nil,
//        .number = CmtyUpdateSettings_FieldNumber_SpeakCountLimit,
//        .hasIndex = 13,
//        .offset = (uint32_t)offsetof(CmtyUpdateSettings__storage_, speakCountLimit),
//        .flags = (GPBFieldFlags)(GPBFieldOptional | GPBFieldClearHasIvarOnZero),
//        .dataType = GPBDataTypeInt32,
//      },
//    };
//    GPBDescriptor *localDescriptor =
//        [GPBDescriptor allocDescriptorForClass:[CmtyUpdateSettings class]
//                                     rootClass:[CmtyPbRoot class]
//                                          file:CmtyPbRoot_FileDescriptor()
//                                        fields:fields
//                                    fieldCount:(uint32_t)(sizeof(fields) / sizeof(GPBMessageFieldDescription))
//                                   storageSize:sizeof(CmtyUpdateSettings__storage_)
//                                         flags:(GPBDescriptorInitializationFlags)(GPBDescriptorInitializationFlag_UsesClassRefs | GPBDescriptorInitializationFlag_Proto3OptionalKnown)];
//    #if defined(DEBUG) && DEBUG
//      NSAssert(descriptor == nil, @"Startup recursed!");
//    #endif  // DEBUG
//    descriptor = localDescriptor;
//  }
//  return descriptor;
//}
//
//@end
//
//#pragma mark - CmtySearchQuery
//
//@implementation CmtySearchQuery
//
//@dynamic keyword;
//@dynamic hasPage, page;
//
//typedef struct CmtySearchQuery__storage_ {
//  uint32_t _has_storage_[1];
//  NSString *keyword;
//  Page *page;
//} CmtySearchQuery__storage_;
//
//// This method is threadsafe because it is initially called
//// in +initialize for each subclass.
//+ (GPBDescriptor *)descriptor {
//  static GPBDescriptor *descriptor = nil;
//  if (!descriptor) {
//    static GPBMessageFieldDescription fields[] = {
//      {
//        .name = "keyword",
//        .dataTypeSpecific.clazz = Nil,
//        .number = CmtySearchQuery_FieldNumber_Keyword,
//        .hasIndex = 0,
//        .offset = (uint32_t)offsetof(CmtySearchQuery__storage_, keyword),
//        .flags = (GPBFieldFlags)(GPBFieldOptional | GPBFieldClearHasIvarOnZero),
//        .dataType = GPBDataTypeString,
//      },
//      {
//        .name = "page",
//        .dataTypeSpecific.clazz = GPBObjCClass(Page),
//        .number = CmtySearchQuery_FieldNumber_Page,
//        .hasIndex = 1,
//        .offset = (uint32_t)offsetof(CmtySearchQuery__storage_, page),
//        .flags = GPBFieldOptional,
//        .dataType = GPBDataTypeMessage,
//      },
//    };
//    GPBDescriptor *localDescriptor =
//        [GPBDescriptor allocDescriptorForClass:[CmtySearchQuery class]
//                                     rootClass:[CmtyPbRoot class]
//                                          file:CmtyPbRoot_FileDescriptor()
//                                        fields:fields
//                                    fieldCount:(uint32_t)(sizeof(fields) / sizeof(GPBMessageFieldDescription))
//                                   storageSize:sizeof(CmtySearchQuery__storage_)
//                                         flags:(GPBDescriptorInitializationFlags)(GPBDescriptorInitializationFlag_UsesClassRefs | GPBDescriptorInitializationFlag_Proto3OptionalKnown)];
//    #if defined(DEBUG) && DEBUG
//      NSAssert(descriptor == nil, @"Startup recursed!");
//    #endif  // DEBUG
//    descriptor = localDescriptor;
//  }
//  return descriptor;
//}
//
//@end
//
//#pragma mark - CmtyOnlineCount
//
//@implementation CmtyOnlineCount
//
//@dynamic cmtyId;
//@dynamic onlineCount;
//@dynamic updatedAt;
//
//typedef struct CmtyOnlineCount__storage_ {
//  uint32_t _has_storage_[1];
//  int32_t onlineCount;
//  NSString *cmtyId;
//  int64_t updatedAt;
//} CmtyOnlineCount__storage_;
//
//// This method is threadsafe because it is initially called
//// in +initialize for each subclass.
//+ (GPBDescriptor *)descriptor {
//  static GPBDescriptor *descriptor = nil;
//  if (!descriptor) {
//    static GPBMessageFieldDescription fields[] = {
//      {
//        .name = "cmtyId",
//        .dataTypeSpecific.clazz = Nil,
//        .number = CmtyOnlineCount_FieldNumber_CmtyId,
//        .hasIndex = 0,
//        .offset = (uint32_t)offsetof(CmtyOnlineCount__storage_, cmtyId),
//        .flags = (GPBFieldFlags)(GPBFieldOptional | GPBFieldClearHasIvarOnZero),
//        .dataType = GPBDataTypeString,
//      },
//      {
//        .name = "onlineCount",
//        .dataTypeSpecific.clazz = Nil,
//        .number = CmtyOnlineCount_FieldNumber_OnlineCount,
//        .hasIndex = 1,
//        .offset = (uint32_t)offsetof(CmtyOnlineCount__storage_, onlineCount),
//        .flags = (GPBFieldFlags)(GPBFieldOptional | GPBFieldClearHasIvarOnZero),
//        .dataType = GPBDataTypeInt32,
//      },
//      {
//        .name = "updatedAt",
//        .dataTypeSpecific.clazz = Nil,
//        .number = CmtyOnlineCount_FieldNumber_UpdatedAt,
//        .hasIndex = 2,
//        .offset = (uint32_t)offsetof(CmtyOnlineCount__storage_, updatedAt),
//        .flags = (GPBFieldFlags)(GPBFieldOptional | GPBFieldClearHasIvarOnZero),
//        .dataType = GPBDataTypeInt64,
//      },
//    };
//    GPBDescriptor *localDescriptor =
//        [GPBDescriptor allocDescriptorForClass:[CmtyOnlineCount class]
//                                     rootClass:[CmtyPbRoot class]
//                                          file:CmtyPbRoot_FileDescriptor()
//                                        fields:fields
//                                    fieldCount:(uint32_t)(sizeof(fields) / sizeof(GPBMessageFieldDescription))
//                                   storageSize:sizeof(CmtyOnlineCount__storage_)
//                                         flags:(GPBDescriptorInitializationFlags)(GPBDescriptorInitializationFlag_UsesClassRefs | GPBDescriptorInitializationFlag_Proto3OptionalKnown)];
//    #if defined(DEBUG) && DEBUG
//      NSAssert(descriptor == nil, @"Startup recursed!");
//    #endif  // DEBUG
//    descriptor = localDescriptor;
//  }
//  return descriptor;
//}
//
//@end
//
//#pragma mark - CmtyLeaveRestriction
//
//@implementation CmtyLeaveRestriction
//
//@dynamic canLeave;
//@dynamic cooldownHours;
//@dynamic nextLeaveAt;
//@dynamic reason;
//
//typedef struct CmtyLeaveRestriction__storage_ {
//  uint32_t _has_storage_[1];
//  int32_t cooldownHours;
//  NSString *reason;
//  int64_t nextLeaveAt;
//} CmtyLeaveRestriction__storage_;
//
//// This method is threadsafe because it is initially called
//// in +initialize for each subclass.
//+ (GPBDescriptor *)descriptor {
//  static GPBDescriptor *descriptor = nil;
//  if (!descriptor) {
//    static GPBMessageFieldDescription fields[] = {
//      {
//        .name = "canLeave",
//        .dataTypeSpecific.clazz = Nil,
//        .number = CmtyLeaveRestriction_FieldNumber_CanLeave,
//        .hasIndex = 0,
//        .offset = 1,  // Stored in _has_storage_ to save space.
//        .flags = (GPBFieldFlags)(GPBFieldOptional | GPBFieldClearHasIvarOnZero),
//        .dataType = GPBDataTypeBool,
//      },
//      {
//        .name = "cooldownHours",
//        .dataTypeSpecific.clazz = Nil,
//        .number = CmtyLeaveRestriction_FieldNumber_CooldownHours,
//        .hasIndex = 2,
//        .offset = (uint32_t)offsetof(CmtyLeaveRestriction__storage_, cooldownHours),
//        .flags = (GPBFieldFlags)(GPBFieldOptional | GPBFieldClearHasIvarOnZero),
//        .dataType = GPBDataTypeInt32,
//      },
//      {
//        .name = "nextLeaveAt",
//        .dataTypeSpecific.clazz = Nil,
//        .number = CmtyLeaveRestriction_FieldNumber_NextLeaveAt,
//        .hasIndex = 3,
//        .offset = (uint32_t)offsetof(CmtyLeaveRestriction__storage_, nextLeaveAt),
//        .flags = (GPBFieldFlags)(GPBFieldOptional | GPBFieldClearHasIvarOnZero),
//        .dataType = GPBDataTypeInt64,
//      },
//      {
//        .name = "reason",
//        .dataTypeSpecific.clazz = Nil,
//        .number = CmtyLeaveRestriction_FieldNumber_Reason,
//        .hasIndex = 4,
//        .offset = (uint32_t)offsetof(CmtyLeaveRestriction__storage_, reason),
//        .flags = (GPBFieldFlags)(GPBFieldOptional | GPBFieldClearHasIvarOnZero),
//        .dataType = GPBDataTypeString,
//      },
//    };
//    GPBDescriptor *localDescriptor =
//        [GPBDescriptor allocDescriptorForClass:[CmtyLeaveRestriction class]
//                                     rootClass:[CmtyPbRoot class]
//                                          file:CmtyPbRoot_FileDescriptor()
//                                        fields:fields
//                                    fieldCount:(uint32_t)(sizeof(fields) / sizeof(GPBMessageFieldDescription))
//                                   storageSize:sizeof(CmtyLeaveRestriction__storage_)
//                                         flags:(GPBDescriptorInitializationFlags)(GPBDescriptorInitializationFlag_UsesClassRefs | GPBDescriptorInitializationFlag_Proto3OptionalKnown)];
//    #if defined(DEBUG) && DEBUG
//      NSAssert(descriptor == nil, @"Startup recursed!");
//    #endif  // DEBUG
//    descriptor = localDescriptor;
//  }
//  return descriptor;
//}
//
//@end
//
//#pragma mark - CmtyRejoinRestriction
//
//@implementation CmtyRejoinRestriction
//
//@dynamic canRejoin;
//@dynamic waitHours;
//@dynamic nextRejoinAt;
//@dynamic reason;
//
//typedef struct CmtyRejoinRestriction__storage_ {
//  uint32_t _has_storage_[1];
//  int32_t waitHours;
//  NSString *reason;
//  int64_t nextRejoinAt;
//} CmtyRejoinRestriction__storage_;
//
//// This method is threadsafe because it is initially called
//// in +initialize for each subclass.
//+ (GPBDescriptor *)descriptor {
//  static GPBDescriptor *descriptor = nil;
//  if (!descriptor) {
//    static GPBMessageFieldDescription fields[] = {
//      {
//        .name = "canRejoin",
//        .dataTypeSpecific.clazz = Nil,
//        .number = CmtyRejoinRestriction_FieldNumber_CanRejoin,
//        .hasIndex = 0,
//        .offset = 1,  // Stored in _has_storage_ to save space.
//        .flags = (GPBFieldFlags)(GPBFieldOptional | GPBFieldClearHasIvarOnZero),
//        .dataType = GPBDataTypeBool,
//      },
//      {
//        .name = "waitHours",
//        .dataTypeSpecific.clazz = Nil,
//        .number = CmtyRejoinRestriction_FieldNumber_WaitHours,
//        .hasIndex = 2,
//        .offset = (uint32_t)offsetof(CmtyRejoinRestriction__storage_, waitHours),
//        .flags = (GPBFieldFlags)(GPBFieldOptional | GPBFieldClearHasIvarOnZero),
//        .dataType = GPBDataTypeInt32,
//      },
//      {
//        .name = "nextRejoinAt",
//        .dataTypeSpecific.clazz = Nil,
//        .number = CmtyRejoinRestriction_FieldNumber_NextRejoinAt,
//        .hasIndex = 3,
//        .offset = (uint32_t)offsetof(CmtyRejoinRestriction__storage_, nextRejoinAt),
//        .flags = (GPBFieldFlags)(GPBFieldOptional | GPBFieldClearHasIvarOnZero),
//        .dataType = GPBDataTypeInt64,
//      },
//      {
//        .name = "reason",
//        .dataTypeSpecific.clazz = Nil,
//        .number = CmtyRejoinRestriction_FieldNumber_Reason,
//        .hasIndex = 4,
//        .offset = (uint32_t)offsetof(CmtyRejoinRestriction__storage_, reason),
//        .flags = (GPBFieldFlags)(GPBFieldOptional | GPBFieldClearHasIvarOnZero),
//        .dataType = GPBDataTypeString,
//      },
//    };
//    GPBDescriptor *localDescriptor =
//        [GPBDescriptor allocDescriptorForClass:[CmtyRejoinRestriction class]
//                                     rootClass:[CmtyPbRoot class]
//                                          file:CmtyPbRoot_FileDescriptor()
//                                        fields:fields
//                                    fieldCount:(uint32_t)(sizeof(fields) / sizeof(GPBMessageFieldDescription))
//                                   storageSize:sizeof(CmtyRejoinRestriction__storage_)
//                                         flags:(GPBDescriptorInitializationFlags)(GPBDescriptorInitializationFlag_UsesClassRefs | GPBDescriptorInitializationFlag_Proto3OptionalKnown)];
//    #if defined(DEBUG) && DEBUG
//      NSAssert(descriptor == nil, @"Startup recursed!");
//    #endif  // DEBUG
//    descriptor = localDescriptor;
//  }
//  return descriptor;
//}
//
//@end
//
//
//#pragma clang diagnostic pop
//
//// @@protoc_insertion_point(global_scope)
