// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: cmty/cmty_channel_group_pb.proto

// This CPP symbol can be defined to use imports that match up to the framework
// imports needed when using CocoaPods.
#if !defined(GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS)
 #define GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS 0
#endif

#if GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS
 #import <Protobuf/GPBProtocolBuffers_RuntimeSupport.h>
#else
 #import "GPBProtocolBuffers_RuntimeSupport.h"
#endif

#import "CmtyChannelGroupPb.pbobjc.h"
// @@protoc_insertion_point(imports)

#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wdeprecated-declarations"
#pragma clang diagnostic ignored "-Wdollar-in-identifier-extension"

#pragma mark - Objective C Class declarations
// Forward declarations of Objective C classes that we can use as
// static values in struct initializers.
// We don't use [Foo class] because it is not a static value.
GPBObjCClassDeclaration(CmtyChannelGroup);

#pragma mark - CmtyChannelGroupPbRoot

@implementation CmtyChannelGroupPbRoot

// No extensions in the file and no imports, so no need to generate
// +extensionRegistry.

@end

#pragma mark - CmtyChannelGroupPbRoot_FileDescriptor

static GPBFileDescriptor *CmtyChannelGroupPbRoot_FileDescriptor(void) {
  // This is called by +initialize so there is no need to worry
  // about thread safety of the singleton.
  static GPBFileDescriptor *descriptor = NULL;
  if (!descriptor) {
    GPB_DEBUG_CHECK_RUNTIME_VERSIONS();
    descriptor = [[GPBFileDescriptor alloc] initWithPackage:@"im.cmty.channel.group"
                                                     syntax:GPBFileSyntaxProto3];
  }
  return descriptor;
}

#pragma mark - CmtyChannelGroup

@implementation CmtyChannelGroup

@dynamic groupId;
@dynamic communityId;
@dynamic groupName;
@dynamic sortOrder;
@dynamic createdAt;
@dynamic updatedAt;

typedef struct CmtyChannelGroup__storage_ {
  uint32_t _has_storage_[1];
  int32_t sortOrder;
  NSString *groupId;
  NSString *communityId;
  NSString *groupName;
  int64_t createdAt;
  int64_t updatedAt;
} CmtyChannelGroup__storage_;

// This method is threadsafe because it is initially called
// in +initialize for each subclass.
+ (GPBDescriptor *)descriptor {
  static GPBDescriptor *descriptor = nil;
  if (!descriptor) {
    static GPBMessageFieldDescription fields[] = {
      {
        .name = "groupId",
        .dataTypeSpecific.clazz = Nil,
        .number = CmtyChannelGroup_FieldNumber_GroupId,
        .hasIndex = 0,
        .offset = (uint32_t)offsetof(CmtyChannelGroup__storage_, groupId),
        .flags = (GPBFieldFlags)(GPBFieldOptional | GPBFieldClearHasIvarOnZero),
        .dataType = GPBDataTypeString,
      },
      {
        .name = "communityId",
        .dataTypeSpecific.clazz = Nil,
        .number = CmtyChannelGroup_FieldNumber_CommunityId,
        .hasIndex = 1,
        .offset = (uint32_t)offsetof(CmtyChannelGroup__storage_, communityId),
        .flags = (GPBFieldFlags)(GPBFieldOptional | GPBFieldClearHasIvarOnZero),
        .dataType = GPBDataTypeString,
      },
      {
        .name = "groupName",
        .dataTypeSpecific.clazz = Nil,
        .number = CmtyChannelGroup_FieldNumber_GroupName,
        .hasIndex = 2,
        .offset = (uint32_t)offsetof(CmtyChannelGroup__storage_, groupName),
        .flags = (GPBFieldFlags)(GPBFieldOptional | GPBFieldClearHasIvarOnZero),
        .dataType = GPBDataTypeString,
      },
      {
        .name = "sortOrder",
        .dataTypeSpecific.clazz = Nil,
        .number = CmtyChannelGroup_FieldNumber_SortOrder,
        .hasIndex = 3,
        .offset = (uint32_t)offsetof(CmtyChannelGroup__storage_, sortOrder),
        .flags = (GPBFieldFlags)(GPBFieldOptional | GPBFieldClearHasIvarOnZero),
        .dataType = GPBDataTypeInt32,
      },
      {
        .name = "createdAt",
        .dataTypeSpecific.clazz = Nil,
        .number = CmtyChannelGroup_FieldNumber_CreatedAt,
        .hasIndex = 4,
        .offset = (uint32_t)offsetof(CmtyChannelGroup__storage_, createdAt),
        .flags = (GPBFieldFlags)(GPBFieldOptional | GPBFieldClearHasIvarOnZero),
        .dataType = GPBDataTypeInt64,
      },
      {
        .name = "updatedAt",
        .dataTypeSpecific.clazz = Nil,
        .number = CmtyChannelGroup_FieldNumber_UpdatedAt,
        .hasIndex = 5,
        .offset = (uint32_t)offsetof(CmtyChannelGroup__storage_, updatedAt),
        .flags = (GPBFieldFlags)(GPBFieldOptional | GPBFieldClearHasIvarOnZero),
        .dataType = GPBDataTypeInt64,
      },
    };
    GPBDescriptor *localDescriptor =
        [GPBDescriptor allocDescriptorForClass:[CmtyChannelGroup class]
                                     rootClass:[CmtyChannelGroupPbRoot class]
                                          file:CmtyChannelGroupPbRoot_FileDescriptor()
                                        fields:fields
                                    fieldCount:(uint32_t)(sizeof(fields) / sizeof(GPBMessageFieldDescription))
                                   storageSize:sizeof(CmtyChannelGroup__storage_)
                                         flags:(GPBDescriptorInitializationFlags)(GPBDescriptorInitializationFlag_UsesClassRefs | GPBDescriptorInitializationFlag_Proto3OptionalKnown)];
    #if defined(DEBUG) && DEBUG
      NSAssert(descriptor == nil, @"Startup recursed!");
    #endif  // DEBUG
    descriptor = localDescriptor;
  }
  return descriptor;
}

@end

#pragma mark - CmtyChannelGroupList

@implementation CmtyChannelGroupList

@dynamic groupsArray, groupsArray_Count;

typedef struct CmtyChannelGroupList__storage_ {
  uint32_t _has_storage_[1];
  NSMutableArray *groupsArray;
} CmtyChannelGroupList__storage_;

// This method is threadsafe because it is initially called
// in +initialize for each subclass.
+ (GPBDescriptor *)descriptor {
  static GPBDescriptor *descriptor = nil;
  if (!descriptor) {
    static GPBMessageFieldDescription fields[] = {
      {
        .name = "groupsArray",
        .dataTypeSpecific.clazz = GPBObjCClass(CmtyChannelGroup),
        .number = CmtyChannelGroupList_FieldNumber_GroupsArray,
        .hasIndex = GPBNoHasBit,
        .offset = (uint32_t)offsetof(CmtyChannelGroupList__storage_, groupsArray),
        .flags = GPBFieldRepeated,
        .dataType = GPBDataTypeMessage,
      },
    };
    GPBDescriptor *localDescriptor =
        [GPBDescriptor allocDescriptorForClass:[CmtyChannelGroupList class]
                                     rootClass:[CmtyChannelGroupPbRoot class]
                                          file:CmtyChannelGroupPbRoot_FileDescriptor()
                                        fields:fields
                                    fieldCount:(uint32_t)(sizeof(fields) / sizeof(GPBMessageFieldDescription))
                                   storageSize:sizeof(CmtyChannelGroupList__storage_)
                                         flags:(GPBDescriptorInitializationFlags)(GPBDescriptorInitializationFlag_UsesClassRefs | GPBDescriptorInitializationFlag_Proto3OptionalKnown)];
    #if defined(DEBUG) && DEBUG
      NSAssert(descriptor == nil, @"Startup recursed!");
    #endif  // DEBUG
    descriptor = localDescriptor;
  }
  return descriptor;
}

@end

#pragma mark - CmtyCreateChannelGroup

@implementation CmtyCreateChannelGroup

@dynamic communityId;
@dynamic groupName;

typedef struct CmtyCreateChannelGroup__storage_ {
  uint32_t _has_storage_[1];
  NSString *communityId;
  NSString *groupName;
} CmtyCreateChannelGroup__storage_;

// This method is threadsafe because it is initially called
// in +initialize for each subclass.
+ (GPBDescriptor *)descriptor {
  static GPBDescriptor *descriptor = nil;
  if (!descriptor) {
    static GPBMessageFieldDescription fields[] = {
      {
        .name = "communityId",
        .dataTypeSpecific.clazz = Nil,
        .number = CmtyCreateChannelGroup_FieldNumber_CommunityId,
        .hasIndex = 0,
        .offset = (uint32_t)offsetof(CmtyCreateChannelGroup__storage_, communityId),
        .flags = (GPBFieldFlags)(GPBFieldOptional | GPBFieldClearHasIvarOnZero),
        .dataType = GPBDataTypeString,
      },
      {
        .name = "groupName",
        .dataTypeSpecific.clazz = Nil,
        .number = CmtyCreateChannelGroup_FieldNumber_GroupName,
        .hasIndex = 1,
        .offset = (uint32_t)offsetof(CmtyCreateChannelGroup__storage_, groupName),
        .flags = (GPBFieldFlags)(GPBFieldOptional | GPBFieldClearHasIvarOnZero),
        .dataType = GPBDataTypeString,
      },
    };
    GPBDescriptor *localDescriptor =
        [GPBDescriptor allocDescriptorForClass:[CmtyCreateChannelGroup class]
                                     rootClass:[CmtyChannelGroupPbRoot class]
                                          file:CmtyChannelGroupPbRoot_FileDescriptor()
                                        fields:fields
                                    fieldCount:(uint32_t)(sizeof(fields) / sizeof(GPBMessageFieldDescription))
                                   storageSize:sizeof(CmtyCreateChannelGroup__storage_)
                                         flags:(GPBDescriptorInitializationFlags)(GPBDescriptorInitializationFlag_UsesClassRefs | GPBDescriptorInitializationFlag_Proto3OptionalKnown)];
    #if defined(DEBUG) && DEBUG
      NSAssert(descriptor == nil, @"Startup recursed!");
    #endif  // DEBUG
    descriptor = localDescriptor;
  }
  return descriptor;
}

@end

#pragma mark - CmtyUpdateChannelGroup

@implementation CmtyUpdateChannelGroup

@dynamic groupId;
@dynamic groupName;

typedef struct CmtyUpdateChannelGroup__storage_ {
  uint32_t _has_storage_[1];
  NSString *groupId;
  NSString *groupName;
} CmtyUpdateChannelGroup__storage_;

// This method is threadsafe because it is initially called
// in +initialize for each subclass.
+ (GPBDescriptor *)descriptor {
  static GPBDescriptor *descriptor = nil;
  if (!descriptor) {
    static GPBMessageFieldDescription fields[] = {
      {
        .name = "groupId",
        .dataTypeSpecific.clazz = Nil,
        .number = CmtyUpdateChannelGroup_FieldNumber_GroupId,
        .hasIndex = 0,
        .offset = (uint32_t)offsetof(CmtyUpdateChannelGroup__storage_, groupId),
        .flags = (GPBFieldFlags)(GPBFieldOptional | GPBFieldClearHasIvarOnZero),
        .dataType = GPBDataTypeString,
      },
      {
        .name = "groupName",
        .dataTypeSpecific.clazz = Nil,
        .number = CmtyUpdateChannelGroup_FieldNumber_GroupName,
        .hasIndex = 1,
        .offset = (uint32_t)offsetof(CmtyUpdateChannelGroup__storage_, groupName),
        .flags = (GPBFieldFlags)(GPBFieldOptional | GPBFieldClearHasIvarOnZero),
        .dataType = GPBDataTypeString,
      },
    };
    GPBDescriptor *localDescriptor =
        [GPBDescriptor allocDescriptorForClass:[CmtyUpdateChannelGroup class]
                                     rootClass:[CmtyChannelGroupPbRoot class]
                                          file:CmtyChannelGroupPbRoot_FileDescriptor()
                                        fields:fields
                                    fieldCount:(uint32_t)(sizeof(fields) / sizeof(GPBMessageFieldDescription))
                                   storageSize:sizeof(CmtyUpdateChannelGroup__storage_)
                                         flags:(GPBDescriptorInitializationFlags)(GPBDescriptorInitializationFlag_UsesClassRefs | GPBDescriptorInitializationFlag_Proto3OptionalKnown)];
    #if defined(DEBUG) && DEBUG
      NSAssert(descriptor == nil, @"Startup recursed!");
    #endif  // DEBUG
    descriptor = localDescriptor;
  }
  return descriptor;
}

@end

#pragma mark - CmtyDeleteChannelGroup

@implementation CmtyDeleteChannelGroup

@dynamic groupId;

typedef struct CmtyDeleteChannelGroup__storage_ {
  uint32_t _has_storage_[1];
  NSString *groupId;
} CmtyDeleteChannelGroup__storage_;

// This method is threadsafe because it is initially called
// in +initialize for each subclass.
+ (GPBDescriptor *)descriptor {
  static GPBDescriptor *descriptor = nil;
  if (!descriptor) {
    static GPBMessageFieldDescription fields[] = {
      {
        .name = "groupId",
        .dataTypeSpecific.clazz = Nil,
        .number = CmtyDeleteChannelGroup_FieldNumber_GroupId,
        .hasIndex = 0,
        .offset = (uint32_t)offsetof(CmtyDeleteChannelGroup__storage_, groupId),
        .flags = (GPBFieldFlags)(GPBFieldOptional | GPBFieldClearHasIvarOnZero),
        .dataType = GPBDataTypeString,
      },
    };
    GPBDescriptor *localDescriptor =
        [GPBDescriptor allocDescriptorForClass:[CmtyDeleteChannelGroup class]
                                     rootClass:[CmtyChannelGroupPbRoot class]
                                          file:CmtyChannelGroupPbRoot_FileDescriptor()
                                        fields:fields
                                    fieldCount:(uint32_t)(sizeof(fields) / sizeof(GPBMessageFieldDescription))
                                   storageSize:sizeof(CmtyDeleteChannelGroup__storage_)
                                         flags:(GPBDescriptorInitializationFlags)(GPBDescriptorInitializationFlag_UsesClassRefs | GPBDescriptorInitializationFlag_Proto3OptionalKnown)];
    #if defined(DEBUG) && DEBUG
      NSAssert(descriptor == nil, @"Startup recursed!");
    #endif  // DEBUG
    descriptor = localDescriptor;
  }
  return descriptor;
}

@end

#pragma mark - CmtyReorderChannelGroups

@implementation CmtyReorderChannelGroups

@dynamic communityId;
@dynamic groupIdsArray, groupIdsArray_Count;

typedef struct CmtyReorderChannelGroups__storage_ {
  uint32_t _has_storage_[1];
  NSString *communityId;
  NSMutableArray *groupIdsArray;
} CmtyReorderChannelGroups__storage_;

// This method is threadsafe because it is initially called
// in +initialize for each subclass.
+ (GPBDescriptor *)descriptor {
  static GPBDescriptor *descriptor = nil;
  if (!descriptor) {
    static GPBMessageFieldDescription fields[] = {
      {
        .name = "communityId",
        .dataTypeSpecific.clazz = Nil,
        .number = CmtyReorderChannelGroups_FieldNumber_CommunityId,
        .hasIndex = 0,
        .offset = (uint32_t)offsetof(CmtyReorderChannelGroups__storage_, communityId),
        .flags = (GPBFieldFlags)(GPBFieldOptional | GPBFieldClearHasIvarOnZero),
        .dataType = GPBDataTypeString,
      },
      {
        .name = "groupIdsArray",
        .dataTypeSpecific.clazz = Nil,
        .number = CmtyReorderChannelGroups_FieldNumber_GroupIdsArray,
        .hasIndex = GPBNoHasBit,
        .offset = (uint32_t)offsetof(CmtyReorderChannelGroups__storage_, groupIdsArray),
        .flags = GPBFieldRepeated,
        .dataType = GPBDataTypeString,
      },
    };
    GPBDescriptor *localDescriptor =
        [GPBDescriptor allocDescriptorForClass:[CmtyReorderChannelGroups class]
                                     rootClass:[CmtyChannelGroupPbRoot class]
                                          file:CmtyChannelGroupPbRoot_FileDescriptor()
                                        fields:fields
                                    fieldCount:(uint32_t)(sizeof(fields) / sizeof(GPBMessageFieldDescription))
                                   storageSize:sizeof(CmtyReorderChannelGroups__storage_)
                                         flags:(GPBDescriptorInitializationFlags)(GPBDescriptorInitializationFlag_UsesClassRefs | GPBDescriptorInitializationFlag_Proto3OptionalKnown)];
    #if defined(DEBUG) && DEBUG
      NSAssert(descriptor == nil, @"Startup recursed!");
    #endif  // DEBUG
    descriptor = localDescriptor;
  }
  return descriptor;
}

@end


#pragma clang diagnostic pop

// @@protoc_insertion_point(global_scope)
