// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: cmty/chat_pb.proto

// This CPP symbol can be defined to use imports that match up to the framework
// imports needed when using CocoaPods.
#if !defined(GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS)
 #define GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS 0
#endif

#if GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS
 #import <Protobuf/GPBProtocolBuffers.h>
#else
 #import "GPBProtocolBuffers.h"
#endif

#if GOOGLE_PROTOBUF_OBJC_VERSION < 30004
#error This file was generated by a newer version of protoc which is incompatible with your Protocol Buffer library sources.
#endif
#if 30004 < GOOGLE_PROTOBUF_OBJC_MIN_SUPPORTED_VERSION
#error This file was generated by an older version of protoc which is incompatible with your Protocol Buffer library sources.
#endif

// @@protoc_insertion_point(imports)

#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wdeprecated-declarations"

CF_EXTERN_C_BEGIN

@class AtMeMessage;
@class ContactSearchResult;
@class GroupBrief;
@class GroupMemberSearchResult;
@class ImMessage;
@class Notification;
@class Page;
GPB_ENUM_FWD_DECLARE(ConversationType);

NS_ASSUME_NONNULL_BEGIN

#pragma mark - Enum NotificationStatus

/** 通知状态枚举 */
typedef GPB_ENUM(NotificationStatus) {
  /**
   * Value used if any message's field encounters a value that is not defined
   * by this enum. The message will also have C functions to get/set the rawValue
   * of the field.
   **/
  NotificationStatus_GPBUnrecognizedEnumeratorValue = kGPBUnrecognizedEnumeratorValue,
  /** 未读（默认值） */
  NotificationStatus_NotificationUnread = 0,

  /** 已读 */
  NotificationStatus_NotificationRead = 1,

  /** 已删除 */
  NotificationStatus_NotificationDeleted = 2,
};

GPBEnumDescriptor *NotificationStatus_EnumDescriptor(void);

/**
 * Checks to see if the given value is defined by the enum or was not known at
 * the time this source was generated.
 **/
BOOL NotificationStatus_IsValidValue(int32_t value);

#pragma mark - ChatPbRoot

/**
 * Exposes the extension registry for this file.
 *
 * The base class provides:
 * @code
 *   + (GPBExtensionRegistry *)extensionRegistry;
 * @endcode
 * which is a @c GPBExtensionRegistry that includes all the extensions defined by
 * this file and all files that it depends on.
 **/
GPB_FINAL @interface ChatPbRoot : GPBRootObject
@end

#pragma mark - Search

typedef GPB_ENUM(Search_FieldNumber) {
  Search_FieldNumber_Keyword = 1,
  Search_FieldNumber_ConvType = 2,
  Search_FieldNumber_Page = 3,
  Search_FieldNumber_FromUserId = 4,
  Search_FieldNumber_StartTimeMs = 5,
  Search_FieldNumber_EndTimeMs = 6,
  Search_FieldNumber_ConvId = 7,
};

/**
 * 消息搜索 - 查询操作
 * 用于搜索单聊和群聊的聊天记录
 **/
GPB_FINAL @interface Search : GPBMessage

/** 搜索关键词（必填） */
@property(nonatomic, readwrite, copy, null_resettable) NSString *keyword;

/** 会话类型过滤（可选，单聊/群聊，使用枚举） */
@property(nonatomic, readwrite) enum ConversationType convType;

/** 按发送者用户ID过滤（可选） */
@property(nonatomic, readwrite, copy, null_resettable) NSString *fromUserId;

/** 开始时间（可选，毫秒时间戳） */
@property(nonatomic, readwrite) int64_t startTimeMs;

/** 结束时间（可选，毫秒时间戳） */
@property(nonatomic, readwrite) int64_t endTimeMs;

/** 分页参数（使用系统类型） */
@property(nonatomic, readwrite, strong, null_resettable) Page *page;
/** Test to see if @c page has been set. */
@property(nonatomic, readwrite) BOOL hasPage;

/** 会话ID过滤（可选，用于频道内搜索） */
@property(nonatomic, readwrite, copy, null_resettable) NSString *convId;

@end

/**
 * Fetches the raw value of a @c Search's @c convType property, even
 * if the value was not defined by the enum at the time the code was generated.
 **/
int32_t Search_ConvType_RawValue(Search *message);
/**
 * Sets the raw value of an @c Search's @c convType property, allowing
 * it to be set to a value that was not defined by the enum at the time the code
 * was generated.
 **/
void SetSearch_ConvType_RawValue(Search *message, int32_t value);

#pragma mark - CSearchResult

typedef GPB_ENUM(CSearchResult_FieldNumber) {
  CSearchResult_FieldNumber_MessagesArray = 1,
  CSearchResult_FieldNumber_Page = 2,
  CSearchResult_FieldNumber_ContactResultsArray = 3,
  CSearchResult_FieldNumber_GroupResultsArray = 4,
  CSearchResult_FieldNumber_MemberResultsArray = 5,
};

/**
 * 消息搜索结果 - 结果对象
 * 用于消息搜索的响应
 **/
GPB_FINAL @interface CSearchResult : GPBMessage

/** 消息列表（返回字段） */
@property(nonatomic, readwrite, strong, null_resettable) NSMutableArray<ImMessage*> *messagesArray;
/** The number of items in @c messagesArray without causing the array to be created. */
@property(nonatomic, readonly) NSUInteger messagesArray_Count;

/** 分页元数据（返回字段，使用系统类型） */
@property(nonatomic, readwrite, strong, null_resettable) Page *page;
/** Test to see if @c page has been set. */
@property(nonatomic, readwrite) BOOL hasPage;

/** 扩展搜索结果：分类结果（每个类型最多3条） */
@property(nonatomic, readwrite, strong, null_resettable) NSMutableArray<ContactSearchResult*> *contactResultsArray;
/** The number of items in @c contactResultsArray without causing the array to be created. */
@property(nonatomic, readonly) NSUInteger contactResultsArray_Count;

/** 群聊名称搜索结果（使用群组PB轻量对象） */
@property(nonatomic, readwrite, strong, null_resettable) NSMutableArray<GroupBrief*> *groupResultsArray;
/** The number of items in @c groupResultsArray without causing the array to be created. */
@property(nonatomic, readonly) NSUInteger groupResultsArray_Count;

/** 群成员昵称搜索结果 */
@property(nonatomic, readwrite, strong, null_resettable) NSMutableArray<GroupMemberSearchResult*> *memberResultsArray;
/** The number of items in @c memberResultsArray without causing the array to be created. */
@property(nonatomic, readonly) NSUInteger memberResultsArray_Count;

@end

#pragma mark - ContactSearchResult

typedef GPB_ENUM(ContactSearchResult_FieldNumber) {
  ContactSearchResult_FieldNumber_ContactUserId = 1,
  ContactSearchResult_FieldNumber_ContactNickname = 2,
  ContactSearchResult_FieldNumber_Remark = 3,
  ContactSearchResult_FieldNumber_Avatar = 4,
};

/**
 * 好友搜索结果
 **/
GPB_FINAL @interface ContactSearchResult : GPBMessage

/** 好友用户ID */
@property(nonatomic, readwrite, copy, null_resettable) NSString *contactUserId;

/** 好友昵称 */
@property(nonatomic, readwrite, copy, null_resettable) NSString *contactNickname;

/** 备注 */
@property(nonatomic, readwrite, copy, null_resettable) NSString *remark;

/** 头像 */
@property(nonatomic, readwrite, copy, null_resettable) NSString *avatar;

@end

#pragma mark - GroupMemberSearchResult

typedef GPB_ENUM(GroupMemberSearchResult_FieldNumber) {
  GroupMemberSearchResult_FieldNumber_GroupId = 1,
  GroupMemberSearchResult_FieldNumber_GroupName = 2,
  GroupMemberSearchResult_FieldNumber_MemberUserId = 3,
  GroupMemberSearchResult_FieldNumber_MemberNickname = 4,
  GroupMemberSearchResult_FieldNumber_MemberAlias = 5,
  GroupMemberSearchResult_FieldNumber_Avatar = 6,
};

/**
 * 群成员搜索结果
 **/
GPB_FINAL @interface GroupMemberSearchResult : GPBMessage

/** 群组ID */
@property(nonatomic, readwrite, copy, null_resettable) NSString *groupId;

/** 群组名称 */
@property(nonatomic, readwrite, copy, null_resettable) NSString *groupName;

/** 成员用户ID */
@property(nonatomic, readwrite, copy, null_resettable) NSString *memberUserId;

/** 成员昵称 */
@property(nonatomic, readwrite, copy, null_resettable) NSString *memberNickname;

/** 成员群内昵称 */
@property(nonatomic, readwrite, copy, null_resettable) NSString *memberAlias;

/** 成员头像 */
@property(nonatomic, readwrite, copy, null_resettable) NSString *avatar;

@end

#pragma mark - SearchAtMe

typedef GPB_ENUM(SearchAtMe_FieldNumber) {
  SearchAtMe_FieldNumber_Keyword = 1,
  SearchAtMe_FieldNumber_GroupId = 2,
  SearchAtMe_FieldNumber_StartTimeMs = 3,
  SearchAtMe_FieldNumber_EndTimeMs = 4,
  SearchAtMe_FieldNumber_UnreadOnly = 5,
  SearchAtMe_FieldNumber_Page = 6,
};

/**
 * 搜索\@我的消息 - 查询操作
 * 用于查询所有\@我的消息
 **/
GPB_FINAL @interface SearchAtMe : GPBMessage

/** 搜索关键词（可选，在\@消息内容中搜索） */
@property(nonatomic, readwrite, copy, null_resettable) NSString *keyword;

/** 群组ID过滤（可选） */
@property(nonatomic, readwrite, copy, null_resettable) NSString *groupId;

/** 开始时间（可选，毫秒时间戳） */
@property(nonatomic, readwrite) int64_t startTimeMs;

/** 结束时间（可选，毫秒时间戳） */
@property(nonatomic, readwrite) int64_t endTimeMs;

/** 仅未读消息（可选，默认false） */
@property(nonatomic, readwrite) BOOL unreadOnly;

/** 分页参数（使用系统类型） */
@property(nonatomic, readwrite, strong, null_resettable) Page *page;
/** Test to see if @c page has been set. */
@property(nonatomic, readwrite) BOOL hasPage;

@end

#pragma mark - SearchAtMeResult

typedef GPB_ENUM(SearchAtMeResult_FieldNumber) {
  SearchAtMeResult_FieldNumber_MessagesArray = 1,
  SearchAtMeResult_FieldNumber_Total = 2,
  SearchAtMeResult_FieldNumber_HasMore = 3,
  SearchAtMeResult_FieldNumber_Page = 4,
};

/**
 * \@我消息搜索结果 - 结果对象
 **/
GPB_FINAL @interface SearchAtMeResult : GPBMessage

/** \@我的消息列表 */
@property(nonatomic, readwrite, strong, null_resettable) NSMutableArray<AtMeMessage*> *messagesArray;
/** The number of items in @c messagesArray without causing the array to be created. */
@property(nonatomic, readonly) NSUInteger messagesArray_Count;

/** 总数 */
@property(nonatomic, readwrite) int32_t total;

/** 是否还有更多 */
@property(nonatomic, readwrite) BOOL hasMore;

/** 分页元数据 */
@property(nonatomic, readwrite, strong, null_resettable) Page *page;
/** Test to see if @c page has been set. */
@property(nonatomic, readwrite) BOOL hasPage;

@end

#pragma mark - AtMeMessage

typedef GPB_ENUM(AtMeMessage_FieldNumber) {
  AtMeMessage_FieldNumber_Message = 1,
  AtMeMessage_FieldNumber_GroupId = 2,
  AtMeMessage_FieldNumber_GroupName = 3,
  AtMeMessage_FieldNumber_FromUserId = 4,
  AtMeMessage_FieldNumber_FromUserName = 5,
  AtMeMessage_FieldNumber_SendTimeMs = 6,
  AtMeMessage_FieldNumber_IsRead = 7,
  AtMeMessage_FieldNumber_GroupSeq = 8,
};

/**
 * \@我消息详情 - 领域对象
 **/
GPB_FINAL @interface AtMeMessage : GPBMessage

/** 消息内容 */
@property(nonatomic, readwrite, strong, null_resettable) ImMessage *message;
/** Test to see if @c message has been set. */
@property(nonatomic, readwrite) BOOL hasMessage;

/** 群组ID（群聊消息时非空） */
@property(nonatomic, readwrite, copy, null_resettable) NSString *groupId;

/** 群组名称（可选） */
@property(nonatomic, readwrite, copy, null_resettable) NSString *groupName;

/** 发送者ID */
@property(nonatomic, readwrite, copy, null_resettable) NSString *fromUserId;

/** 发送者名称（可选） */
@property(nonatomic, readwrite, copy, null_resettable) NSString *fromUserName;

/** 发送时间（毫秒） */
@property(nonatomic, readwrite) int64_t sendTimeMs;

/** 是否已读 */
@property(nonatomic, readwrite) BOOL isRead;

/** 群组序列号（群聊消息时非空） */
@property(nonatomic, readwrite) int64_t groupSeq;

@end

#pragma mark - GetAtMeUnreadCount

/**
 * 获取\@我消息未读数量 - 查询操作
 * 用于获取\@我消息的未读数量
 **/
GPB_FINAL @interface GetAtMeUnreadCount : GPBMessage

@end

#pragma mark - AtMeUnreadCountResult

typedef GPB_ENUM(AtMeUnreadCountResult_FieldNumber) {
  AtMeUnreadCountResult_FieldNumber_TotalUnread = 1,
  AtMeUnreadCountResult_FieldNumber_GroupUnread = 2,
};

/**
 * \@我消息未读数量结果 - 结果对象
 **/
GPB_FINAL @interface AtMeUnreadCountResult : GPBMessage

/** 总未读数 */
@property(nonatomic, readwrite) int32_t totalUnread;

/** 各群组未读数（group_id -> count） */
@property(nonatomic, readwrite, strong, null_resettable) GPBStringInt32Dictionary *groupUnread;
/** The number of items in @c groupUnread without causing the array to be created. */
@property(nonatomic, readonly) NSUInteger groupUnread_Count;

@end

#pragma mark - MarkAtMeRead

typedef GPB_ENUM(MarkAtMeRead_FieldNumber) {
  MarkAtMeRead_FieldNumber_MessageIdsArray = 1,
  MarkAtMeRead_FieldNumber_GroupId = 2,
};

/**
 * 标记\@我消息为已读 - 操作
 **/
GPB_FINAL @interface MarkAtMeRead : GPBMessage

/** 消息ID列表（可选，为空则标记所有） */
@property(nonatomic, readwrite, strong, null_resettable) NSMutableArray<NSString*> *messageIdsArray;
/** The number of items in @c messageIdsArray without causing the array to be created. */
@property(nonatomic, readonly) NSUInteger messageIdsArray_Count;

/** 群组ID（可选，标记整个群组的\@消息为已读） */
@property(nonatomic, readwrite, copy, null_resettable) NSString *groupId;

@end

#pragma mark - MarkAtMeReadResult

typedef GPB_ENUM(MarkAtMeReadResult_FieldNumber) {
  MarkAtMeReadResult_FieldNumber_MarkedCount = 1,
  MarkAtMeReadResult_FieldNumber_FailedMessageIdsArray = 2,
};

/**
 * 标记\@我消息已读结果 - 结果对象
 **/
GPB_FINAL @interface MarkAtMeReadResult : GPBMessage

/** 标记数量 */
@property(nonatomic, readwrite) int32_t markedCount;

/** 失败的消息ID列表 */
@property(nonatomic, readwrite, strong, null_resettable) NSMutableArray<NSString*> *failedMessageIdsArray;
/** The number of items in @c failedMessageIdsArray without causing the array to be created. */
@property(nonatomic, readonly) NSUInteger failedMessageIdsArray_Count;

@end

#pragma mark - Notification

typedef GPB_ENUM(Notification_FieldNumber) {
  Notification_FieldNumber_Id_p = 1,
  Notification_FieldNumber_AppId = 2,
  Notification_FieldNumber_UserId = 3,
  Notification_FieldNumber_NotificationType = 4,
  Notification_FieldNumber_Title = 5,
  Notification_FieldNumber_Content = 6,
  Notification_FieldNumber_BusinessType = 7,
  Notification_FieldNumber_ServerMsgId = 8,
  Notification_FieldNumber_RelatedUserId = 9,
  Notification_FieldNumber_RelatedRequestId = 10,
  Notification_FieldNumber_Status = 11,
  Notification_FieldNumber_CreateTime = 12,
  Notification_FieldNumber_ReadTime = 13,
  Notification_FieldNumber_ExpireTime = 14,
};

/**
 * 通知消息对象（用于返回）
 **/
GPB_FINAL @interface Notification : GPBMessage

/** 通知ID（雪花ID） */
@property(nonatomic, readwrite) int64_t id_p;

/** 应用ID */
@property(nonatomic, readwrite, copy, null_resettable) NSString *appId;

/** 接收者用户ID */
@property(nonatomic, readwrite, copy, null_resettable) NSString *userId;

/** 通知类型（如 "FRIEND_REQUEST_ACCEPTED"） */
@property(nonatomic, readwrite, copy, null_resettable) NSString *notificationType;

/** 通知标题 */
@property(nonatomic, readwrite, copy, null_resettable) NSString *title;

/** 通知内容（JSON字符串） */
@property(nonatomic, readwrite, copy, null_resettable) NSString *content;

/** 业务类型（如 "CONTACT"） */
@property(nonatomic, readwrite, copy, null_resettable) NSString *businessType;

/** 全局唯一消息ID */
@property(nonatomic, readwrite, copy, null_resettable) NSString *serverMsgId;

/** 关联用户ID（可选） */
@property(nonatomic, readwrite, copy, null_resettable) NSString *relatedUserId;

/** 关联申请ID（可选） */
@property(nonatomic, readwrite) int64_t relatedRequestId;

/** 状态（UNREAD, READ, DELETED） */
@property(nonatomic, readwrite) NotificationStatus status;

/** 创建时间（毫秒时间戳） */
@property(nonatomic, readwrite) int64_t createTime;

/** 已读时间（毫秒时间戳，可选） */
@property(nonatomic, readwrite) int64_t readTime;

/** 过期时间（毫秒时间戳，可选） */
@property(nonatomic, readwrite) int64_t expireTime;

@end

/**
 * Fetches the raw value of a @c Notification's @c status property, even
 * if the value was not defined by the enum at the time the code was generated.
 **/
int32_t Notification_Status_RawValue(Notification *message);
/**
 * Sets the raw value of an @c Notification's @c status property, allowing
 * it to be set to a value that was not defined by the enum at the time the code
 * was generated.
 **/
void SetNotification_Status_RawValue(Notification *message, int32_t value);

#pragma mark - NotificationPull

typedef GPB_ENUM(NotificationPull_FieldNumber) {
  NotificationPull_FieldNumber_NotificationTypesArray = 1,
  NotificationPull_FieldNumber_Status = 2,
  NotificationPull_FieldNumber_StartTime = 3,
  NotificationPull_FieldNumber_EndTime = 4,
  NotificationPull_FieldNumber_Page = 5,
};

/**
 * 通知拉取 - 查询操作
 **/
GPB_FINAL @interface NotificationPull : GPBMessage

/** 通知类型过滤（可选，如 ["FRIEND_REQUEST_ACCEPTED", "FRIEND_ADD"]） */
@property(nonatomic, readwrite, strong, null_resettable) NSMutableArray<NSString*> *notificationTypesArray;
/** The number of items in @c notificationTypesArray without causing the array to be created. */
@property(nonatomic, readonly) NSUInteger notificationTypesArray_Count;

/** 状态过滤（可选，默认拉取所有状态） */
@property(nonatomic, readwrite) NotificationStatus status;

/** 开始时间（可选，毫秒时间戳） */
@property(nonatomic, readwrite) int64_t startTime;

/** 结束时间（可选，毫秒时间戳） */
@property(nonatomic, readwrite) int64_t endTime;

/** 分页参数（使用系统类型） */
@property(nonatomic, readwrite, strong, null_resettable) Page *page;
/** Test to see if @c page has been set. */
@property(nonatomic, readwrite) BOOL hasPage;

@end

/**
 * Fetches the raw value of a @c NotificationPull's @c status property, even
 * if the value was not defined by the enum at the time the code was generated.
 **/
int32_t NotificationPull_Status_RawValue(NotificationPull *message);
/**
 * Sets the raw value of an @c NotificationPull's @c status property, allowing
 * it to be set to a value that was not defined by the enum at the time the code
 * was generated.
 **/
void SetNotificationPull_Status_RawValue(NotificationPull *message, int32_t value);

#pragma mark - NotificationPullList

typedef GPB_ENUM(NotificationPullList_FieldNumber) {
  NotificationPullList_FieldNumber_NotificationsArray = 1,
  NotificationPullList_FieldNumber_Page = 2,
};

/**
 * 通知拉取结果 - 结果对象
 **/
GPB_FINAL @interface NotificationPullList : GPBMessage

/** 通知列表 */
@property(nonatomic, readwrite, strong, null_resettable) NSMutableArray<Notification*> *notificationsArray;
/** The number of items in @c notificationsArray without causing the array to be created. */
@property(nonatomic, readonly) NSUInteger notificationsArray_Count;

/** 分页元数据（使用系统类型） */
@property(nonatomic, readwrite, strong, null_resettable) Page *page;
/** Test to see if @c page has been set. */
@property(nonatomic, readwrite) BOOL hasPage;

@end

#pragma mark - NotificationMarkRead

typedef GPB_ENUM(NotificationMarkRead_FieldNumber) {
  NotificationMarkRead_FieldNumber_NotificationIdsArray = 1,
  NotificationMarkRead_FieldNumber_ReadTime = 2,
};

/**
 * 通知标记已读 - 操作对象
 **/
GPB_FINAL @interface NotificationMarkRead : GPBMessage

/** 要标记已读的通知ID列表（可选，为空则标记全部） */
@property(nonatomic, readwrite, strong, null_resettable) GPBInt64Array *notificationIdsArray;
/** The number of items in @c notificationIdsArray without causing the array to be created. */
@property(nonatomic, readonly) NSUInteger notificationIdsArray_Count;

/** 已读时间戳（可选，默认当前时间） */
@property(nonatomic, readwrite) int64_t readTime;

@end

#pragma mark - NotificationMarkReadResult

typedef GPB_ENUM(NotificationMarkReadResult_FieldNumber) {
  NotificationMarkReadResult_FieldNumber_SuccessCount = 1,
  NotificationMarkReadResult_FieldNumber_FailedIdsArray = 2,
};

/**
 * 通知标记已读结果 - 结果对象
 **/
GPB_FINAL @interface NotificationMarkReadResult : GPBMessage

/** 成功标记的通知数量 */
@property(nonatomic, readwrite) int32_t successCount;

/** 标记失败的通知ID列表 */
@property(nonatomic, readwrite, strong, null_resettable) GPBInt64Array *failedIdsArray;
/** The number of items in @c failedIdsArray without causing the array to be created. */
@property(nonatomic, readonly) NSUInteger failedIdsArray_Count;

@end

#pragma mark - NotificationDelete

typedef GPB_ENUM(NotificationDelete_FieldNumber) {
  NotificationDelete_FieldNumber_NotificationIdsArray = 1,
};

/**
 * 通知删除 - 操作对象
 **/
GPB_FINAL @interface NotificationDelete : GPBMessage

/** 要删除的通知ID列表（必填，至少一个） */
@property(nonatomic, readwrite, strong, null_resettable) GPBInt64Array *notificationIdsArray;
/** The number of items in @c notificationIdsArray without causing the array to be created. */
@property(nonatomic, readonly) NSUInteger notificationIdsArray_Count;

@end

#pragma mark - NotificationDeleteResult

typedef GPB_ENUM(NotificationDeleteResult_FieldNumber) {
  NotificationDeleteResult_FieldNumber_SuccessCount = 1,
  NotificationDeleteResult_FieldNumber_FailedIdsArray = 2,
};

/**
 * 通知删除结果 - 结果对象
 **/
GPB_FINAL @interface NotificationDeleteResult : GPBMessage

/** 成功删除的通知数量 */
@property(nonatomic, readwrite) int32_t successCount;

/** 删除失败的通知ID列表 */
@property(nonatomic, readwrite, strong, null_resettable) GPBInt64Array *failedIdsArray;
/** The number of items in @c failedIdsArray without causing the array to be created. */
@property(nonatomic, readonly) NSUInteger failedIdsArray_Count;

@end

#pragma mark - NotificationUnreadCount

typedef GPB_ENUM(NotificationUnreadCount_FieldNumber) {
  NotificationUnreadCount_FieldNumber_NotificationTypesArray = 1,
};

/**
 * 通知未读数查询 - 查询操作
 **/
GPB_FINAL @interface NotificationUnreadCount : GPBMessage

/** 通知类型过滤（可选，为空则统计所有类型） */
@property(nonatomic, readwrite, strong, null_resettable) NSMutableArray<NSString*> *notificationTypesArray;
/** The number of items in @c notificationTypesArray without causing the array to be created. */
@property(nonatomic, readonly) NSUInteger notificationTypesArray_Count;

@end

#pragma mark - NotificationUnreadCountResult

typedef GPB_ENUM(NotificationUnreadCountResult_FieldNumber) {
  NotificationUnreadCountResult_FieldNumber_TotalUnread = 1,
  NotificationUnreadCountResult_FieldNumber_TypeUnread = 2,
};

/**
 * 通知未读数统计 - 结果对象
 **/
GPB_FINAL @interface NotificationUnreadCountResult : GPBMessage

/** 总未读数量 */
@property(nonatomic, readwrite) int64_t totalUnread;

/** 各类型的未读数量（key为 notification_type） */
@property(nonatomic, readwrite, strong, null_resettable) GPBStringInt64Dictionary *typeUnread;
/** The number of items in @c typeUnread without causing the array to be created. */
@property(nonatomic, readonly) NSUInteger typeUnread_Count;

@end

NS_ASSUME_NONNULL_END

CF_EXTERN_C_END

#pragma clang diagnostic pop

// @@protoc_insertion_point(global_scope)
