// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: conv_pb.proto

// This CPP symbol can be defined to use imports that match up to the framework
// imports needed when using CocoaPods.
#if !defined(GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS)
 #define GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS 0
#endif

#if GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS
 #import <Protobuf/GPBProtocolBuffers_RuntimeSupport.h>
#else
 #import "GPBProtocolBuffers_RuntimeSupport.h"
#endif

#import "ConvPb.pbobjc.h"
#import "SystemPb.pbobjc.h"
#import "MessagePb.pbobjc.h"
// @@protoc_insertion_point(imports)

#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wdeprecated-declarations"
#pragma clang diagnostic ignored "-Wdollar-in-identifier-extension"

#pragma mark - Objective C Class declarations
// Forward declarations of Objective C classes that we can use as
// static values in struct initializers.
// We don't use [Foo class] because it is not a static value.
GPBObjCClassDeclaration(Conv);
GPBObjCClassDeclaration(ConvWithUnread);
GPBObjCClassDeclaration(ImMessage);
GPBObjCClassDeclaration(Page);

#pragma mark - ConvPbRoot

@implementation ConvPbRoot

// No extensions in the file and none of the imports (direct or indirect)
// defined extensions, so no need to generate +extensionRegistry.

@end

#pragma mark - ConvPbRoot_FileDescriptor

static GPBFileDescriptor *ConvPbRoot_FileDescriptor(void) {
  // This is called by +initialize so there is no need to worry
  // about thread safety of the singleton.
  static GPBFileDescriptor *descriptor = NULL;
  if (!descriptor) {
    GPB_DEBUG_CHECK_RUNTIME_VERSIONS();
    descriptor = [[GPBFileDescriptor alloc] initWithPackage:@"im.conv"
                                                     syntax:GPBFileSyntaxProto3];
  }
  return descriptor;
}

#pragma mark - Conv

@implementation Conv

@dynamic convId;
@dynamic parentId;
@dynamic convType;
@dynamic level;
@dynamic displayName;
@dynamic description_p;
@dynamic avatarURL;
@dynamic avatarBg;
@dynamic avatarInfo;
@dynamic targetId;
@dynamic status;
@dynamic isPrivate;
@dynamic createdAt;
@dynamic updatedAt;
@dynamic extraInfo;
@dynamic sysTagsArray, sysTagsArray_Count;
@dynamic userTagsArray, userTagsArray_Count;
@dynamic disturb;

typedef struct Conv__storage_ {
  uint32_t _has_storage_[1];
  ConversationType convType;
  int32_t level;
  int32_t status;
  NSString *convId;
  NSString *parentId;
  NSString *displayName;
  NSString *description_p;
  NSString *avatarURL;
  NSString *avatarInfo;
  NSString *targetId;
  NSString *extraInfo;
  NSString *avatarBg;
  NSMutableArray *sysTagsArray;
  NSMutableArray *userTagsArray;
  int64_t createdAt;
  int64_t updatedAt;
} Conv__storage_;

// This method is threadsafe because it is initially called
// in +initialize for each subclass.
+ (GPBDescriptor *)descriptor {
  static GPBDescriptor *descriptor = nil;
  if (!descriptor) {
    static GPBMessageFieldDescription fields[] = {
      {
        .name = "convId",
        .dataTypeSpecific.clazz = Nil,
        .number = Conv_FieldNumber_ConvId,
        .hasIndex = 0,
        .offset = (uint32_t)offsetof(Conv__storage_, convId),
        .flags = (GPBFieldFlags)(GPBFieldOptional | GPBFieldClearHasIvarOnZero),
        .dataType = GPBDataTypeString,
      },
      {
        .name = "parentId",
        .dataTypeSpecific.clazz = Nil,
        .number = Conv_FieldNumber_ParentId,
        .hasIndex = 1,
        .offset = (uint32_t)offsetof(Conv__storage_, parentId),
        .flags = (GPBFieldFlags)(GPBFieldOptional | GPBFieldClearHasIvarOnZero),
        .dataType = GPBDataTypeString,
      },
      {
        .name = "convType",
        .dataTypeSpecific.enumDescFunc = ConversationType_EnumDescriptor,
        .number = Conv_FieldNumber_ConvType,
        .hasIndex = 2,
        .offset = (uint32_t)offsetof(Conv__storage_, convType),
        .flags = (GPBFieldFlags)(GPBFieldOptional | GPBFieldHasEnumDescriptor | GPBFieldClearHasIvarOnZero),
        .dataType = GPBDataTypeEnum,
      },
      {
        .name = "level",
        .dataTypeSpecific.clazz = Nil,
        .number = Conv_FieldNumber_Level,
        .hasIndex = 3,
        .offset = (uint32_t)offsetof(Conv__storage_, level),
        .flags = (GPBFieldFlags)(GPBFieldOptional | GPBFieldClearHasIvarOnZero),
        .dataType = GPBDataTypeInt32,
      },
      {
        .name = "displayName",
        .dataTypeSpecific.clazz = Nil,
        .number = Conv_FieldNumber_DisplayName,
        .hasIndex = 4,
        .offset = (uint32_t)offsetof(Conv__storage_, displayName),
        .flags = (GPBFieldFlags)(GPBFieldOptional | GPBFieldClearHasIvarOnZero),
        .dataType = GPBDataTypeString,
      },
      {
        .name = "description_p",
        .dataTypeSpecific.clazz = Nil,
        .number = Conv_FieldNumber_Description_p,
        .hasIndex = 5,
        .offset = (uint32_t)offsetof(Conv__storage_, description_p),
        .flags = (GPBFieldFlags)(GPBFieldOptional | GPBFieldClearHasIvarOnZero),
        .dataType = GPBDataTypeString,
      },
      {
        .name = "avatarURL",
        .dataTypeSpecific.clazz = Nil,
        .number = Conv_FieldNumber_AvatarURL,
        .hasIndex = 6,
        .offset = (uint32_t)offsetof(Conv__storage_, avatarURL),
        .flags = (GPBFieldFlags)(GPBFieldOptional | GPBFieldTextFormatNameCustom | GPBFieldClearHasIvarOnZero),
        .dataType = GPBDataTypeString,
      },
      {
        .name = "avatarInfo",
        .dataTypeSpecific.clazz = Nil,
        .number = Conv_FieldNumber_AvatarInfo,
        .hasIndex = 8,
        .offset = (uint32_t)offsetof(Conv__storage_, avatarInfo),
        .flags = (GPBFieldFlags)(GPBFieldOptional | GPBFieldClearHasIvarOnZero),
        .dataType = GPBDataTypeString,
      },
      {
        .name = "targetId",
        .dataTypeSpecific.clazz = Nil,
        .number = Conv_FieldNumber_TargetId,
        .hasIndex = 9,
        .offset = (uint32_t)offsetof(Conv__storage_, targetId),
        .flags = (GPBFieldFlags)(GPBFieldOptional | GPBFieldClearHasIvarOnZero),
        .dataType = GPBDataTypeString,
      },
      {
        .name = "status",
        .dataTypeSpecific.clazz = Nil,
        .number = Conv_FieldNumber_Status,
        .hasIndex = 10,
        .offset = (uint32_t)offsetof(Conv__storage_, status),
        .flags = (GPBFieldFlags)(GPBFieldOptional | GPBFieldClearHasIvarOnZero),
        .dataType = GPBDataTypeInt32,
      },
      {
        .name = "isPrivate",
        .dataTypeSpecific.clazz = Nil,
        .number = Conv_FieldNumber_IsPrivate,
        .hasIndex = 11,
        .offset = 12,  // Stored in _has_storage_ to save space.
        .flags = (GPBFieldFlags)(GPBFieldOptional | GPBFieldClearHasIvarOnZero),
        .dataType = GPBDataTypeBool,
      },
      {
        .name = "createdAt",
        .dataTypeSpecific.clazz = Nil,
        .number = Conv_FieldNumber_CreatedAt,
        .hasIndex = 13,
        .offset = (uint32_t)offsetof(Conv__storage_, createdAt),
        .flags = (GPBFieldFlags)(GPBFieldOptional | GPBFieldClearHasIvarOnZero),
        .dataType = GPBDataTypeInt64,
      },
      {
        .name = "updatedAt",
        .dataTypeSpecific.clazz = Nil,
        .number = Conv_FieldNumber_UpdatedAt,
        .hasIndex = 14,
        .offset = (uint32_t)offsetof(Conv__storage_, updatedAt),
        .flags = (GPBFieldFlags)(GPBFieldOptional | GPBFieldClearHasIvarOnZero),
        .dataType = GPBDataTypeInt64,
      },
      {
        .name = "extraInfo",
        .dataTypeSpecific.clazz = Nil,
        .number = Conv_FieldNumber_ExtraInfo,
        .hasIndex = 15,
        .offset = (uint32_t)offsetof(Conv__storage_, extraInfo),
        .flags = (GPBFieldFlags)(GPBFieldOptional | GPBFieldClearHasIvarOnZero),
        .dataType = GPBDataTypeString,
      },
      {
        .name = "avatarBg",
        .dataTypeSpecific.clazz = Nil,
        .number = Conv_FieldNumber_AvatarBg,
        .hasIndex = 7,
        .offset = (uint32_t)offsetof(Conv__storage_, avatarBg),
        .flags = (GPBFieldFlags)(GPBFieldOptional | GPBFieldClearHasIvarOnZero),
        .dataType = GPBDataTypeString,
      },
      {
        .name = "sysTagsArray",
        .dataTypeSpecific.clazz = Nil,
        .number = Conv_FieldNumber_SysTagsArray,
        .hasIndex = GPBNoHasBit,
        .offset = (uint32_t)offsetof(Conv__storage_, sysTagsArray),
        .flags = GPBFieldRepeated,
        .dataType = GPBDataTypeString,
      },
      {
        .name = "userTagsArray",
        .dataTypeSpecific.clazz = Nil,
        .number = Conv_FieldNumber_UserTagsArray,
        .hasIndex = GPBNoHasBit,
        .offset = (uint32_t)offsetof(Conv__storage_, userTagsArray),
        .flags = GPBFieldRepeated,
        .dataType = GPBDataTypeString,
      },
      {
        .name = "disturb",
        .dataTypeSpecific.clazz = Nil,
        .number = Conv_FieldNumber_Disturb,
        .hasIndex = 16,
        .offset = 17,  // Stored in _has_storage_ to save space.
        .flags = (GPBFieldFlags)(GPBFieldOptional | GPBFieldClearHasIvarOnZero),
        .dataType = GPBDataTypeBool,
      },
    };
    GPBDescriptor *localDescriptor =
        [GPBDescriptor allocDescriptorForClass:[Conv class]
                                     rootClass:[ConvPbRoot class]
                                          file:ConvPbRoot_FileDescriptor()
                                        fields:fields
                                    fieldCount:(uint32_t)(sizeof(fields) / sizeof(GPBMessageFieldDescription))
                                   storageSize:sizeof(Conv__storage_)
                                         flags:(GPBDescriptorInitializationFlags)(GPBDescriptorInitializationFlag_UsesClassRefs | GPBDescriptorInitializationFlag_Proto3OptionalKnown)];
#if !GPBOBJC_SKIP_MESSAGE_TEXTFORMAT_EXTRAS
    static const char *extraTextFormatInfo =
        "\001\007\006\241!!\000";
    [localDescriptor setupExtraTextInfo:extraTextFormatInfo];
#endif  // !GPBOBJC_SKIP_MESSAGE_TEXTFORMAT_EXTRAS
    #if defined(DEBUG) && DEBUG
      NSAssert(descriptor == nil, @"Startup recursed!");
    #endif  // DEBUG
    descriptor = localDescriptor;
  }
  return descriptor;
}

@end

int32_t Conv_ConvType_RawValue(Conv *message) {
  GPBDescriptor *descriptor = [Conv descriptor];
  GPBFieldDescriptor *field = [descriptor fieldWithNumber:Conv_FieldNumber_ConvType];
  return GPBGetMessageRawEnumField(message, field);
}

void SetConv_ConvType_RawValue(Conv *message, int32_t value) {
  GPBDescriptor *descriptor = [Conv descriptor];
  GPBFieldDescriptor *field = [descriptor fieldWithNumber:Conv_FieldNumber_ConvType];
  GPBSetMessageRawEnumField(message, field, value);
}

#pragma mark - GetConv

@implementation GetConv

@dynamic convId;

typedef struct GetConv__storage_ {
  uint32_t _has_storage_[1];
  NSString *convId;
} GetConv__storage_;

// This method is threadsafe because it is initially called
// in +initialize for each subclass.
+ (GPBDescriptor *)descriptor {
  static GPBDescriptor *descriptor = nil;
  if (!descriptor) {
    static GPBMessageFieldDescription fields[] = {
      {
        .name = "convId",
        .dataTypeSpecific.clazz = Nil,
        .number = GetConv_FieldNumber_ConvId,
        .hasIndex = 0,
        .offset = (uint32_t)offsetof(GetConv__storage_, convId),
        .flags = (GPBFieldFlags)(GPBFieldOptional | GPBFieldClearHasIvarOnZero),
        .dataType = GPBDataTypeString,
      },
    };
    GPBDescriptor *localDescriptor =
        [GPBDescriptor allocDescriptorForClass:[GetConv class]
                                     rootClass:[ConvPbRoot class]
                                          file:ConvPbRoot_FileDescriptor()
                                        fields:fields
                                    fieldCount:(uint32_t)(sizeof(fields) / sizeof(GPBMessageFieldDescription))
                                   storageSize:sizeof(GetConv__storage_)
                                         flags:(GPBDescriptorInitializationFlags)(GPBDescriptorInitializationFlag_UsesClassRefs | GPBDescriptorInitializationFlag_Proto3OptionalKnown)];
    #if defined(DEBUG) && DEBUG
      NSAssert(descriptor == nil, @"Startup recursed!");
    #endif  // DEBUG
    descriptor = localDescriptor;
  }
  return descriptor;
}

@end

#pragma mark - DeleteConv

@implementation DeleteConv

@dynamic convId;

typedef struct DeleteConv__storage_ {
  uint32_t _has_storage_[1];
  NSString *convId;
} DeleteConv__storage_;

// This method is threadsafe because it is initially called
// in +initialize for each subclass.
+ (GPBDescriptor *)descriptor {
  static GPBDescriptor *descriptor = nil;
  if (!descriptor) {
    static GPBMessageFieldDescription fields[] = {
      {
        .name = "convId",
        .dataTypeSpecific.clazz = Nil,
        .number = DeleteConv_FieldNumber_ConvId,
        .hasIndex = 0,
        .offset = (uint32_t)offsetof(DeleteConv__storage_, convId),
        .flags = (GPBFieldFlags)(GPBFieldOptional | GPBFieldClearHasIvarOnZero),
        .dataType = GPBDataTypeString,
      },
    };
    GPBDescriptor *localDescriptor =
        [GPBDescriptor allocDescriptorForClass:[DeleteConv class]
                                     rootClass:[ConvPbRoot class]
                                          file:ConvPbRoot_FileDescriptor()
                                        fields:fields
                                    fieldCount:(uint32_t)(sizeof(fields) / sizeof(GPBMessageFieldDescription))
                                   storageSize:sizeof(DeleteConv__storage_)
                                         flags:(GPBDescriptorInitializationFlags)(GPBDescriptorInitializationFlag_UsesClassRefs | GPBDescriptorInitializationFlag_Proto3OptionalKnown)];
    #if defined(DEBUG) && DEBUG
      NSAssert(descriptor == nil, @"Startup recursed!");
    #endif  // DEBUG
    descriptor = localDescriptor;
  }
  return descriptor;
}

@end

#pragma mark - ConvListQuery

@implementation ConvListQuery

@dynamic convType;
@dynamic hasPage, page;
@dynamic withUnread;

typedef struct ConvListQuery__storage_ {
  uint32_t _has_storage_[1];
  ConversationType convType;
  Page *page;
} ConvListQuery__storage_;

// This method is threadsafe because it is initially called
// in +initialize for each subclass.
+ (GPBDescriptor *)descriptor {
  static GPBDescriptor *descriptor = nil;
  if (!descriptor) {
    static GPBMessageFieldDescription fields[] = {
      {
        .name = "convType",
        .dataTypeSpecific.enumDescFunc = ConversationType_EnumDescriptor,
        .number = ConvListQuery_FieldNumber_ConvType,
        .hasIndex = 0,
        .offset = (uint32_t)offsetof(ConvListQuery__storage_, convType),
        .flags = (GPBFieldFlags)(GPBFieldOptional | GPBFieldHasEnumDescriptor | GPBFieldClearHasIvarOnZero),
        .dataType = GPBDataTypeEnum,
      },
      {
        .name = "page",
        .dataTypeSpecific.clazz = GPBObjCClass(Page),
        .number = ConvListQuery_FieldNumber_Page,
        .hasIndex = 1,
        .offset = (uint32_t)offsetof(ConvListQuery__storage_, page),
        .flags = GPBFieldOptional,
        .dataType = GPBDataTypeMessage,
      },
      {
        .name = "withUnread",
        .dataTypeSpecific.clazz = Nil,
        .number = ConvListQuery_FieldNumber_WithUnread,
        .hasIndex = 2,
        .offset = 3,  // Stored in _has_storage_ to save space.
        .flags = (GPBFieldFlags)(GPBFieldOptional | GPBFieldClearHasIvarOnZero),
        .dataType = GPBDataTypeBool,
      },
    };
    GPBDescriptor *localDescriptor =
        [GPBDescriptor allocDescriptorForClass:[ConvListQuery class]
                                     rootClass:[ConvPbRoot class]
                                          file:ConvPbRoot_FileDescriptor()
                                        fields:fields
                                    fieldCount:(uint32_t)(sizeof(fields) / sizeof(GPBMessageFieldDescription))
                                   storageSize:sizeof(ConvListQuery__storage_)
                                         flags:(GPBDescriptorInitializationFlags)(GPBDescriptorInitializationFlag_UsesClassRefs | GPBDescriptorInitializationFlag_Proto3OptionalKnown)];
    #if defined(DEBUG) && DEBUG
      NSAssert(descriptor == nil, @"Startup recursed!");
    #endif  // DEBUG
    descriptor = localDescriptor;
  }
  return descriptor;
}

@end

int32_t ConvListQuery_ConvType_RawValue(ConvListQuery *message) {
  GPBDescriptor *descriptor = [ConvListQuery descriptor];
  GPBFieldDescriptor *field = [descriptor fieldWithNumber:ConvListQuery_FieldNumber_ConvType];
  return GPBGetMessageRawEnumField(message, field);
}

void SetConvListQuery_ConvType_RawValue(ConvListQuery *message, int32_t value) {
  GPBDescriptor *descriptor = [ConvListQuery descriptor];
  GPBFieldDescriptor *field = [descriptor fieldWithNumber:ConvListQuery_FieldNumber_ConvType];
  GPBSetMessageRawEnumField(message, field, value);
}

#pragma mark - ConvList

@implementation ConvList

@dynamic convsArray, convsArray_Count;
@dynamic totalCount;
@dynamic page;
@dynamic size;

typedef struct ConvList__storage_ {
  uint32_t _has_storage_[1];
  int32_t page;
  int32_t size;
  NSMutableArray *convsArray;
  int64_t totalCount;
} ConvList__storage_;

// This method is threadsafe because it is initially called
// in +initialize for each subclass.
+ (GPBDescriptor *)descriptor {
  static GPBDescriptor *descriptor = nil;
  if (!descriptor) {
    static GPBMessageFieldDescription fields[] = {
      {
        .name = "convsArray",
        .dataTypeSpecific.clazz = GPBObjCClass(Conv),
        .number = ConvList_FieldNumber_ConvsArray,
        .hasIndex = GPBNoHasBit,
        .offset = (uint32_t)offsetof(ConvList__storage_, convsArray),
        .flags = GPBFieldRepeated,
        .dataType = GPBDataTypeMessage,
      },
      {
        .name = "totalCount",
        .dataTypeSpecific.clazz = Nil,
        .number = ConvList_FieldNumber_TotalCount,
        .hasIndex = 0,
        .offset = (uint32_t)offsetof(ConvList__storage_, totalCount),
        .flags = (GPBFieldFlags)(GPBFieldOptional | GPBFieldClearHasIvarOnZero),
        .dataType = GPBDataTypeInt64,
      },
      {
        .name = "page",
        .dataTypeSpecific.clazz = Nil,
        .number = ConvList_FieldNumber_Page,
        .hasIndex = 1,
        .offset = (uint32_t)offsetof(ConvList__storage_, page),
        .flags = (GPBFieldFlags)(GPBFieldOptional | GPBFieldClearHasIvarOnZero),
        .dataType = GPBDataTypeInt32,
      },
      {
        .name = "size",
        .dataTypeSpecific.clazz = Nil,
        .number = ConvList_FieldNumber_Size,
        .hasIndex = 2,
        .offset = (uint32_t)offsetof(ConvList__storage_, size),
        .flags = (GPBFieldFlags)(GPBFieldOptional | GPBFieldClearHasIvarOnZero),
        .dataType = GPBDataTypeInt32,
      },
    };
    GPBDescriptor *localDescriptor =
        [GPBDescriptor allocDescriptorForClass:[ConvList class]
                                     rootClass:[ConvPbRoot class]
                                          file:ConvPbRoot_FileDescriptor()
                                        fields:fields
                                    fieldCount:(uint32_t)(sizeof(fields) / sizeof(GPBMessageFieldDescription))
                                   storageSize:sizeof(ConvList__storage_)
                                         flags:(GPBDescriptorInitializationFlags)(GPBDescriptorInitializationFlag_UsesClassRefs | GPBDescriptorInitializationFlag_Proto3OptionalKnown)];
    #if defined(DEBUG) && DEBUG
      NSAssert(descriptor == nil, @"Startup recursed!");
    #endif  // DEBUG
    descriptor = localDescriptor;
  }
  return descriptor;
}

@end

#pragma mark - ConvWithUnread

@implementation ConvWithUnread

@dynamic hasConv, conv;
@dynamic unreadCount;
@dynamic lastReadSeq;
@dynamic convMaxSeq;
@dynamic hasLastMessage, lastMessage;
@dynamic hasLastAtMessage, lastAtMessage;

typedef struct ConvWithUnread__storage_ {
  uint32_t _has_storage_[1];
  int32_t unreadCount;
  Conv *conv;
  ImMessage *lastMessage;
  ImMessage *lastAtMessage;
  int64_t lastReadSeq;
  int64_t convMaxSeq;
} ConvWithUnread__storage_;

// This method is threadsafe because it is initially called
// in +initialize for each subclass.
+ (GPBDescriptor *)descriptor {
  static GPBDescriptor *descriptor = nil;
  if (!descriptor) {
    static GPBMessageFieldDescription fields[] = {
      {
        .name = "conv",
        .dataTypeSpecific.clazz = GPBObjCClass(Conv),
        .number = ConvWithUnread_FieldNumber_Conv,
        .hasIndex = 0,
        .offset = (uint32_t)offsetof(ConvWithUnread__storage_, conv),
        .flags = GPBFieldOptional,
        .dataType = GPBDataTypeMessage,
      },
      {
        .name = "unreadCount",
        .dataTypeSpecific.clazz = Nil,
        .number = ConvWithUnread_FieldNumber_UnreadCount,
        .hasIndex = 1,
        .offset = (uint32_t)offsetof(ConvWithUnread__storage_, unreadCount),
        .flags = (GPBFieldFlags)(GPBFieldOptional | GPBFieldClearHasIvarOnZero),
        .dataType = GPBDataTypeInt32,
      },
      {
        .name = "lastReadSeq",
        .dataTypeSpecific.clazz = Nil,
        .number = ConvWithUnread_FieldNumber_LastReadSeq,
        .hasIndex = 2,
        .offset = (uint32_t)offsetof(ConvWithUnread__storage_, lastReadSeq),
        .flags = (GPBFieldFlags)(GPBFieldOptional | GPBFieldClearHasIvarOnZero),
        .dataType = GPBDataTypeInt64,
      },
      {
        .name = "convMaxSeq",
        .dataTypeSpecific.clazz = Nil,
        .number = ConvWithUnread_FieldNumber_ConvMaxSeq,
        .hasIndex = 3,
        .offset = (uint32_t)offsetof(ConvWithUnread__storage_, convMaxSeq),
        .flags = (GPBFieldFlags)(GPBFieldOptional | GPBFieldClearHasIvarOnZero),
        .dataType = GPBDataTypeInt64,
      },
      {
        .name = "lastMessage",
        .dataTypeSpecific.clazz = GPBObjCClass(ImMessage),
        .number = ConvWithUnread_FieldNumber_LastMessage,
        .hasIndex = 4,
        .offset = (uint32_t)offsetof(ConvWithUnread__storage_, lastMessage),
        .flags = GPBFieldOptional,
        .dataType = GPBDataTypeMessage,
      },
      {
        .name = "lastAtMessage",
        .dataTypeSpecific.clazz = GPBObjCClass(ImMessage),
        .number = ConvWithUnread_FieldNumber_LastAtMessage,
        .hasIndex = 5,
        .offset = (uint32_t)offsetof(ConvWithUnread__storage_, lastAtMessage),
        .flags = GPBFieldOptional,
        .dataType = GPBDataTypeMessage,
      },
    };
    GPBDescriptor *localDescriptor =
        [GPBDescriptor allocDescriptorForClass:[ConvWithUnread class]
                                     rootClass:[ConvPbRoot class]
                                          file:ConvPbRoot_FileDescriptor()
                                        fields:fields
                                    fieldCount:(uint32_t)(sizeof(fields) / sizeof(GPBMessageFieldDescription))
                                   storageSize:sizeof(ConvWithUnread__storage_)
                                         flags:(GPBDescriptorInitializationFlags)(GPBDescriptorInitializationFlag_UsesClassRefs | GPBDescriptorInitializationFlag_Proto3OptionalKnown)];
    #if defined(DEBUG) && DEBUG
      NSAssert(descriptor == nil, @"Startup recursed!");
    #endif  // DEBUG
    descriptor = localDescriptor;
  }
  return descriptor;
}

@end

#pragma mark - ListWithUnread

@implementation ListWithUnread

@dynamic convsArray, convsArray_Count;
@dynamic totalUnread;
@dynamic hasMore;
@dynamic page;
@dynamic size;
@dynamic version;

typedef struct ListWithUnread__storage_ {
  uint32_t _has_storage_[1];
  int32_t page;
  int32_t size;
  NSMutableArray *convsArray;
  int64_t totalUnread;
  int64_t version;
} ListWithUnread__storage_;

// This method is threadsafe because it is initially called
// in +initialize for each subclass.
+ (GPBDescriptor *)descriptor {
  static GPBDescriptor *descriptor = nil;
  if (!descriptor) {
    static GPBMessageFieldDescription fields[] = {
      {
        .name = "convsArray",
        .dataTypeSpecific.clazz = GPBObjCClass(ConvWithUnread),
        .number = ListWithUnread_FieldNumber_ConvsArray,
        .hasIndex = GPBNoHasBit,
        .offset = (uint32_t)offsetof(ListWithUnread__storage_, convsArray),
        .flags = GPBFieldRepeated,
        .dataType = GPBDataTypeMessage,
      },
      {
        .name = "totalUnread",
        .dataTypeSpecific.clazz = Nil,
        .number = ListWithUnread_FieldNumber_TotalUnread,
        .hasIndex = 0,
        .offset = (uint32_t)offsetof(ListWithUnread__storage_, totalUnread),
        .flags = (GPBFieldFlags)(GPBFieldOptional | GPBFieldClearHasIvarOnZero),
        .dataType = GPBDataTypeInt64,
      },
      {
        .name = "hasMore",
        .dataTypeSpecific.clazz = Nil,
        .number = ListWithUnread_FieldNumber_HasMore,
        .hasIndex = 1,
        .offset = 2,  // Stored in _has_storage_ to save space.
        .flags = (GPBFieldFlags)(GPBFieldOptional | GPBFieldClearHasIvarOnZero),
        .dataType = GPBDataTypeBool,
      },
      {
        .name = "page",
        .dataTypeSpecific.clazz = Nil,
        .number = ListWithUnread_FieldNumber_Page,
        .hasIndex = 3,
        .offset = (uint32_t)offsetof(ListWithUnread__storage_, page),
        .flags = (GPBFieldFlags)(GPBFieldOptional | GPBFieldClearHasIvarOnZero),
        .dataType = GPBDataTypeInt32,
      },
      {
        .name = "size",
        .dataTypeSpecific.clazz = Nil,
        .number = ListWithUnread_FieldNumber_Size,
        .hasIndex = 4,
        .offset = (uint32_t)offsetof(ListWithUnread__storage_, size),
        .flags = (GPBFieldFlags)(GPBFieldOptional | GPBFieldClearHasIvarOnZero),
        .dataType = GPBDataTypeInt32,
      },
      {
        .name = "version",
        .dataTypeSpecific.clazz = Nil,
        .number = ListWithUnread_FieldNumber_Version,
        .hasIndex = 5,
        .offset = (uint32_t)offsetof(ListWithUnread__storage_, version),
        .flags = (GPBFieldFlags)(GPBFieldOptional | GPBFieldClearHasIvarOnZero),
        .dataType = GPBDataTypeInt64,
      },
    };
    GPBDescriptor *localDescriptor =
        [GPBDescriptor allocDescriptorForClass:[ListWithUnread class]
                                     rootClass:[ConvPbRoot class]
                                          file:ConvPbRoot_FileDescriptor()
                                        fields:fields
                                    fieldCount:(uint32_t)(sizeof(fields) / sizeof(GPBMessageFieldDescription))
                                   storageSize:sizeof(ListWithUnread__storage_)
                                         flags:(GPBDescriptorInitializationFlags)(GPBDescriptorInitializationFlag_UsesClassRefs | GPBDescriptorInitializationFlag_Proto3OptionalKnown)];
    #if defined(DEBUG) && DEBUG
      NSAssert(descriptor == nil, @"Startup recursed!");
    #endif  // DEBUG
    descriptor = localDescriptor;
  }
  return descriptor;
}

@end

#pragma mark - UpdateStats

@implementation UpdateStats

@dynamic convId;
@dynamic messageId;
@dynamic messageTime;
@dynamic senderId;
@dynamic messagePreview;

typedef struct UpdateStats__storage_ {
  uint32_t _has_storage_[1];
  NSString *convId;
  NSString *messageId;
  NSString *senderId;
  NSString *messagePreview;
  int64_t messageTime;
} UpdateStats__storage_;

// This method is threadsafe because it is initially called
// in +initialize for each subclass.
+ (GPBDescriptor *)descriptor {
  static GPBDescriptor *descriptor = nil;
  if (!descriptor) {
    static GPBMessageFieldDescription fields[] = {
      {
        .name = "convId",
        .dataTypeSpecific.clazz = Nil,
        .number = UpdateStats_FieldNumber_ConvId,
        .hasIndex = 0,
        .offset = (uint32_t)offsetof(UpdateStats__storage_, convId),
        .flags = (GPBFieldFlags)(GPBFieldOptional | GPBFieldClearHasIvarOnZero),
        .dataType = GPBDataTypeString,
      },
      {
        .name = "messageId",
        .dataTypeSpecific.clazz = Nil,
        .number = UpdateStats_FieldNumber_MessageId,
        .hasIndex = 1,
        .offset = (uint32_t)offsetof(UpdateStats__storage_, messageId),
        .flags = (GPBFieldFlags)(GPBFieldOptional | GPBFieldClearHasIvarOnZero),
        .dataType = GPBDataTypeString,
      },
      {
        .name = "messageTime",
        .dataTypeSpecific.clazz = Nil,
        .number = UpdateStats_FieldNumber_MessageTime,
        .hasIndex = 2,
        .offset = (uint32_t)offsetof(UpdateStats__storage_, messageTime),
        .flags = (GPBFieldFlags)(GPBFieldOptional | GPBFieldClearHasIvarOnZero),
        .dataType = GPBDataTypeInt64,
      },
      {
        .name = "senderId",
        .dataTypeSpecific.clazz = Nil,
        .number = UpdateStats_FieldNumber_SenderId,
        .hasIndex = 3,
        .offset = (uint32_t)offsetof(UpdateStats__storage_, senderId),
        .flags = (GPBFieldFlags)(GPBFieldOptional | GPBFieldClearHasIvarOnZero),
        .dataType = GPBDataTypeString,
      },
      {
        .name = "messagePreview",
        .dataTypeSpecific.clazz = Nil,
        .number = UpdateStats_FieldNumber_MessagePreview,
        .hasIndex = 4,
        .offset = (uint32_t)offsetof(UpdateStats__storage_, messagePreview),
        .flags = (GPBFieldFlags)(GPBFieldOptional | GPBFieldClearHasIvarOnZero),
        .dataType = GPBDataTypeString,
      },
    };
    GPBDescriptor *localDescriptor =
        [GPBDescriptor allocDescriptorForClass:[UpdateStats class]
                                     rootClass:[ConvPbRoot class]
                                          file:ConvPbRoot_FileDescriptor()
                                        fields:fields
                                    fieldCount:(uint32_t)(sizeof(fields) / sizeof(GPBMessageFieldDescription))
                                   storageSize:sizeof(UpdateStats__storage_)
                                         flags:(GPBDescriptorInitializationFlags)(GPBDescriptorInitializationFlag_UsesClassRefs | GPBDescriptorInitializationFlag_Proto3OptionalKnown)];
    #if defined(DEBUG) && DEBUG
      NSAssert(descriptor == nil, @"Startup recursed!");
    #endif  // DEBUG
    descriptor = localDescriptor;
  }
  return descriptor;
}

@end

#pragma mark - UpdatePullTime

@implementation UpdatePullTime

@dynamic convId;
@dynamic userId;
@dynamic pullTime;

typedef struct UpdatePullTime__storage_ {
  uint32_t _has_storage_[1];
  NSString *convId;
  NSString *userId;
  int64_t pullTime;
} UpdatePullTime__storage_;

// This method is threadsafe because it is initially called
// in +initialize for each subclass.
+ (GPBDescriptor *)descriptor {
  static GPBDescriptor *descriptor = nil;
  if (!descriptor) {
    static GPBMessageFieldDescription fields[] = {
      {
        .name = "convId",
        .dataTypeSpecific.clazz = Nil,
        .number = UpdatePullTime_FieldNumber_ConvId,
        .hasIndex = 0,
        .offset = (uint32_t)offsetof(UpdatePullTime__storage_, convId),
        .flags = (GPBFieldFlags)(GPBFieldOptional | GPBFieldClearHasIvarOnZero),
        .dataType = GPBDataTypeString,
      },
      {
        .name = "userId",
        .dataTypeSpecific.clazz = Nil,
        .number = UpdatePullTime_FieldNumber_UserId,
        .hasIndex = 1,
        .offset = (uint32_t)offsetof(UpdatePullTime__storage_, userId),
        .flags = (GPBFieldFlags)(GPBFieldOptional | GPBFieldClearHasIvarOnZero),
        .dataType = GPBDataTypeString,
      },
      {
        .name = "pullTime",
        .dataTypeSpecific.clazz = Nil,
        .number = UpdatePullTime_FieldNumber_PullTime,
        .hasIndex = 2,
        .offset = (uint32_t)offsetof(UpdatePullTime__storage_, pullTime),
        .flags = (GPBFieldFlags)(GPBFieldOptional | GPBFieldClearHasIvarOnZero),
        .dataType = GPBDataTypeInt64,
      },
    };
    GPBDescriptor *localDescriptor =
        [GPBDescriptor allocDescriptorForClass:[UpdatePullTime class]
                                     rootClass:[ConvPbRoot class]
                                          file:ConvPbRoot_FileDescriptor()
                                        fields:fields
                                    fieldCount:(uint32_t)(sizeof(fields) / sizeof(GPBMessageFieldDescription))
                                   storageSize:sizeof(UpdatePullTime__storage_)
                                         flags:(GPBDescriptorInitializationFlags)(GPBDescriptorInitializationFlag_UsesClassRefs | GPBDescriptorInitializationFlag_Proto3OptionalKnown)];
    #if defined(DEBUG) && DEBUG
      NSAssert(descriptor == nil, @"Startup recursed!");
    #endif  // DEBUG
    descriptor = localDescriptor;
  }
  return descriptor;
}

@end

#pragma mark - BatchCreateUserStates

@implementation BatchCreateUserStates

@dynamic convId;
@dynamic convType;
@dynamic sourceId;
@dynamic displayName;

typedef struct BatchCreateUserStates__storage_ {
  uint32_t _has_storage_[1];
  ConversationType convType;
  NSString *convId;
  NSString *sourceId;
  NSString *displayName;
} BatchCreateUserStates__storage_;

// This method is threadsafe because it is initially called
// in +initialize for each subclass.
+ (GPBDescriptor *)descriptor {
  static GPBDescriptor *descriptor = nil;
  if (!descriptor) {
    static GPBMessageFieldDescription fields[] = {
      {
        .name = "convId",
        .dataTypeSpecific.clazz = Nil,
        .number = BatchCreateUserStates_FieldNumber_ConvId,
        .hasIndex = 0,
        .offset = (uint32_t)offsetof(BatchCreateUserStates__storage_, convId),
        .flags = (GPBFieldFlags)(GPBFieldOptional | GPBFieldClearHasIvarOnZero),
        .dataType = GPBDataTypeString,
      },
      {
        .name = "convType",
        .dataTypeSpecific.enumDescFunc = ConversationType_EnumDescriptor,
        .number = BatchCreateUserStates_FieldNumber_ConvType,
        .hasIndex = 1,
        .offset = (uint32_t)offsetof(BatchCreateUserStates__storage_, convType),
        .flags = (GPBFieldFlags)(GPBFieldOptional | GPBFieldHasEnumDescriptor | GPBFieldClearHasIvarOnZero),
        .dataType = GPBDataTypeEnum,
      },
      {
        .name = "sourceId",
        .dataTypeSpecific.clazz = Nil,
        .number = BatchCreateUserStates_FieldNumber_SourceId,
        .hasIndex = 2,
        .offset = (uint32_t)offsetof(BatchCreateUserStates__storage_, sourceId),
        .flags = (GPBFieldFlags)(GPBFieldOptional | GPBFieldClearHasIvarOnZero),
        .dataType = GPBDataTypeString,
      },
      {
        .name = "displayName",
        .dataTypeSpecific.clazz = Nil,
        .number = BatchCreateUserStates_FieldNumber_DisplayName,
        .hasIndex = 3,
        .offset = (uint32_t)offsetof(BatchCreateUserStates__storage_, displayName),
        .flags = (GPBFieldFlags)(GPBFieldOptional | GPBFieldClearHasIvarOnZero),
        .dataType = GPBDataTypeString,
      },
    };
    GPBDescriptor *localDescriptor =
        [GPBDescriptor allocDescriptorForClass:[BatchCreateUserStates class]
                                     rootClass:[ConvPbRoot class]
                                          file:ConvPbRoot_FileDescriptor()
                                        fields:fields
                                    fieldCount:(uint32_t)(sizeof(fields) / sizeof(GPBMessageFieldDescription))
                                   storageSize:sizeof(BatchCreateUserStates__storage_)
                                         flags:(GPBDescriptorInitializationFlags)(GPBDescriptorInitializationFlag_UsesClassRefs | GPBDescriptorInitializationFlag_Proto3OptionalKnown)];
    #if defined(DEBUG) && DEBUG
      NSAssert(descriptor == nil, @"Startup recursed!");
    #endif  // DEBUG
    descriptor = localDescriptor;
  }
  return descriptor;
}

@end

int32_t BatchCreateUserStates_ConvType_RawValue(BatchCreateUserStates *message) {
  GPBDescriptor *descriptor = [BatchCreateUserStates descriptor];
  GPBFieldDescriptor *field = [descriptor fieldWithNumber:BatchCreateUserStates_FieldNumber_ConvType];
  return GPBGetMessageRawEnumField(message, field);
}

void SetBatchCreateUserStates_ConvType_RawValue(BatchCreateUserStates *message, int32_t value) {
  GPBDescriptor *descriptor = [BatchCreateUserStates descriptor];
  GPBFieldDescriptor *field = [descriptor fieldWithNumber:BatchCreateUserStates_FieldNumber_ConvType];
  GPBSetMessageRawEnumField(message, field, value);
}

#pragma mark - BatchCreateUserStatesResult

@implementation BatchCreateUserStatesResult

@dynamic success;
@dynamic createdCount;
@dynamic skippedCount;
@dynamic failedCount;

typedef struct BatchCreateUserStatesResult__storage_ {
  uint32_t _has_storage_[1];
  int32_t createdCount;
  int32_t skippedCount;
  int32_t failedCount;
} BatchCreateUserStatesResult__storage_;

// This method is threadsafe because it is initially called
// in +initialize for each subclass.
+ (GPBDescriptor *)descriptor {
  static GPBDescriptor *descriptor = nil;
  if (!descriptor) {
    static GPBMessageFieldDescription fields[] = {
      {
        .name = "success",
        .dataTypeSpecific.clazz = Nil,
        .number = BatchCreateUserStatesResult_FieldNumber_Success,
        .hasIndex = 0,
        .offset = 1,  // Stored in _has_storage_ to save space.
        .flags = (GPBFieldFlags)(GPBFieldOptional | GPBFieldClearHasIvarOnZero),
        .dataType = GPBDataTypeBool,
      },
      {
        .name = "createdCount",
        .dataTypeSpecific.clazz = Nil,
        .number = BatchCreateUserStatesResult_FieldNumber_CreatedCount,
        .hasIndex = 2,
        .offset = (uint32_t)offsetof(BatchCreateUserStatesResult__storage_, createdCount),
        .flags = (GPBFieldFlags)(GPBFieldOptional | GPBFieldClearHasIvarOnZero),
        .dataType = GPBDataTypeInt32,
      },
      {
        .name = "skippedCount",
        .dataTypeSpecific.clazz = Nil,
        .number = BatchCreateUserStatesResult_FieldNumber_SkippedCount,
        .hasIndex = 3,
        .offset = (uint32_t)offsetof(BatchCreateUserStatesResult__storage_, skippedCount),
        .flags = (GPBFieldFlags)(GPBFieldOptional | GPBFieldClearHasIvarOnZero),
        .dataType = GPBDataTypeInt32,
      },
      {
        .name = "failedCount",
        .dataTypeSpecific.clazz = Nil,
        .number = BatchCreateUserStatesResult_FieldNumber_FailedCount,
        .hasIndex = 4,
        .offset = (uint32_t)offsetof(BatchCreateUserStatesResult__storage_, failedCount),
        .flags = (GPBFieldFlags)(GPBFieldOptional | GPBFieldClearHasIvarOnZero),
        .dataType = GPBDataTypeInt32,
      },
    };
    GPBDescriptor *localDescriptor =
        [GPBDescriptor allocDescriptorForClass:[BatchCreateUserStatesResult class]
                                     rootClass:[ConvPbRoot class]
                                          file:ConvPbRoot_FileDescriptor()
                                        fields:fields
                                    fieldCount:(uint32_t)(sizeof(fields) / sizeof(GPBMessageFieldDescription))
                                   storageSize:sizeof(BatchCreateUserStatesResult__storage_)
                                         flags:(GPBDescriptorInitializationFlags)(GPBDescriptorInitializationFlag_UsesClassRefs | GPBDescriptorInitializationFlag_Proto3OptionalKnown)];
    #if defined(DEBUG) && DEBUG
      NSAssert(descriptor == nil, @"Startup recursed!");
    #endif  // DEBUG
    descriptor = localDescriptor;
  }
  return descriptor;
}

@end

#pragma mark - BatchCreateConv

@implementation BatchCreateConv

@dynamic convsArray, convsArray_Count;
@dynamic userIdsArray, userIdsArray_Count;

typedef struct BatchCreateConv__storage_ {
  uint32_t _has_storage_[1];
  NSMutableArray *convsArray;
  NSMutableArray *userIdsArray;
} BatchCreateConv__storage_;

// This method is threadsafe because it is initially called
// in +initialize for each subclass.
+ (GPBDescriptor *)descriptor {
  static GPBDescriptor *descriptor = nil;
  if (!descriptor) {
    static GPBMessageFieldDescription fields[] = {
      {
        .name = "convsArray",
        .dataTypeSpecific.clazz = GPBObjCClass(Conv),
        .number = BatchCreateConv_FieldNumber_ConvsArray,
        .hasIndex = GPBNoHasBit,
        .offset = (uint32_t)offsetof(BatchCreateConv__storage_, convsArray),
        .flags = GPBFieldRepeated,
        .dataType = GPBDataTypeMessage,
      },
      {
        .name = "userIdsArray",
        .dataTypeSpecific.clazz = Nil,
        .number = BatchCreateConv_FieldNumber_UserIdsArray,
        .hasIndex = GPBNoHasBit,
        .offset = (uint32_t)offsetof(BatchCreateConv__storage_, userIdsArray),
        .flags = GPBFieldRepeated,
        .dataType = GPBDataTypeString,
      },
    };
    GPBDescriptor *localDescriptor =
        [GPBDescriptor allocDescriptorForClass:[BatchCreateConv class]
                                     rootClass:[ConvPbRoot class]
                                          file:ConvPbRoot_FileDescriptor()
                                        fields:fields
                                    fieldCount:(uint32_t)(sizeof(fields) / sizeof(GPBMessageFieldDescription))
                                   storageSize:sizeof(BatchCreateConv__storage_)
                                         flags:(GPBDescriptorInitializationFlags)(GPBDescriptorInitializationFlag_UsesClassRefs | GPBDescriptorInitializationFlag_Proto3OptionalKnown)];
    #if defined(DEBUG) && DEBUG
      NSAssert(descriptor == nil, @"Startup recursed!");
    #endif  // DEBUG
    descriptor = localDescriptor;
  }
  return descriptor;
}

@end

#pragma mark - Disturb

@implementation Disturb

@dynamic convId;
@dynamic disturb;

typedef struct Disturb__storage_ {
  uint32_t _has_storage_[1];
  NSString *convId;
} Disturb__storage_;

// This method is threadsafe because it is initially called
// in +initialize for each subclass.
+ (GPBDescriptor *)descriptor {
  static GPBDescriptor *descriptor = nil;
  if (!descriptor) {
    static GPBMessageFieldDescription fields[] = {
      {
        .name = "convId",
        .dataTypeSpecific.clazz = Nil,
        .number = Disturb_FieldNumber_ConvId,
        .hasIndex = 0,
        .offset = (uint32_t)offsetof(Disturb__storage_, convId),
        .flags = (GPBFieldFlags)(GPBFieldOptional | GPBFieldClearHasIvarOnZero),
        .dataType = GPBDataTypeString,
      },
      {
        .name = "disturb",
        .dataTypeSpecific.clazz = Nil,
        .number = Disturb_FieldNumber_Disturb,
        .hasIndex = 1,
        .offset = 2,  // Stored in _has_storage_ to save space.
        .flags = (GPBFieldFlags)(GPBFieldOptional | GPBFieldClearHasIvarOnZero),
        .dataType = GPBDataTypeBool,
      },
    };
    GPBDescriptor *localDescriptor =
        [GPBDescriptor allocDescriptorForClass:[Disturb class]
                                     rootClass:[ConvPbRoot class]
                                          file:ConvPbRoot_FileDescriptor()
                                        fields:fields
                                    fieldCount:(uint32_t)(sizeof(fields) / sizeof(GPBMessageFieldDescription))
                                   storageSize:sizeof(Disturb__storage_)
                                         flags:(GPBDescriptorInitializationFlags)(GPBDescriptorInitializationFlag_UsesClassRefs | GPBDescriptorInitializationFlag_Proto3OptionalKnown)];
    #if defined(DEBUG) && DEBUG
      NSAssert(descriptor == nil, @"Startup recursed!");
    #endif  // DEBUG
    descriptor = localDescriptor;
  }
  return descriptor;
}

@end

#pragma mark - DisturbState

@implementation DisturbState

@dynamic success;
@dynamic disturb;

typedef struct DisturbState__storage_ {
  uint32_t _has_storage_[1];
} DisturbState__storage_;

// This method is threadsafe because it is initially called
// in +initialize for each subclass.
+ (GPBDescriptor *)descriptor {
  static GPBDescriptor *descriptor = nil;
  if (!descriptor) {
    static GPBMessageFieldDescription fields[] = {
      {
        .name = "success",
        .dataTypeSpecific.clazz = Nil,
        .number = DisturbState_FieldNumber_Success,
        .hasIndex = 0,
        .offset = 1,  // Stored in _has_storage_ to save space.
        .flags = (GPBFieldFlags)(GPBFieldOptional | GPBFieldClearHasIvarOnZero),
        .dataType = GPBDataTypeBool,
      },
      {
        .name = "disturb",
        .dataTypeSpecific.clazz = Nil,
        .number = DisturbState_FieldNumber_Disturb,
        .hasIndex = 2,
        .offset = 3,  // Stored in _has_storage_ to save space.
        .flags = (GPBFieldFlags)(GPBFieldOptional | GPBFieldClearHasIvarOnZero),
        .dataType = GPBDataTypeBool,
      },
    };
    GPBDescriptor *localDescriptor =
        [GPBDescriptor allocDescriptorForClass:[DisturbState class]
                                     rootClass:[ConvPbRoot class]
                                          file:ConvPbRoot_FileDescriptor()
                                        fields:fields
                                    fieldCount:(uint32_t)(sizeof(fields) / sizeof(GPBMessageFieldDescription))
                                   storageSize:sizeof(DisturbState__storage_)
                                         flags:(GPBDescriptorInitializationFlags)(GPBDescriptorInitializationFlag_UsesClassRefs | GPBDescriptorInitializationFlag_Proto3OptionalKnown)];
    #if defined(DEBUG) && DEBUG
      NSAssert(descriptor == nil, @"Startup recursed!");
    #endif  // DEBUG
    descriptor = localDescriptor;
  }
  return descriptor;
}

@end


#pragma clang diagnostic pop

// @@protoc_insertion_point(global_scope)
