// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: conv_pb.proto

// This CPP symbol can be defined to use imports that match up to the framework
// imports needed when using CocoaPods.
#if !defined(GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS)
 #define GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS 0
#endif

#if GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS
 #import <Protobuf/GPBProtocolBuffers.h>
#else
 #import "GPBProtocolBuffers.h"
#endif

#if GOOGLE_PROTOBUF_OBJC_VERSION < 30004
#error This file was generated by a newer version of protoc which is incompatible with your Protocol Buffer library sources.
#endif
#if 30004 < GOOGLE_PROTOBUF_OBJC_MIN_SUPPORTED_VERSION
#error This file was generated by an older version of protoc which is incompatible with your Protocol Buffer library sources.
#endif

// @@protoc_insertion_point(imports)

#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wdeprecated-declarations"

CF_EXTERN_C_BEGIN

@class Conv;
@class ConvWithUnread;
@class ImMessage;
@class Page;
GPB_ENUM_FWD_DECLARE(ConversationType);

NS_ASSUME_NONNULL_BEGIN

#pragma mark - ConvPbRoot

/**
 * Exposes the extension registry for this file.
 *
 * The base class provides:
 * @code
 *   + (GPBExtensionRegistry *)extensionRegistry;
 * @endcode
 * which is a @c GPBExtensionRegistry that includes all the extensions defined by
 * this file and all files that it depends on.
 **/
GPB_FINAL @interface ConvPbRoot : GPBRootObject
@end

#pragma mark - Conv

typedef GPB_ENUM(Conv_FieldNumber) {
  Conv_FieldNumber_ConvId = 1,
  Conv_FieldNumber_ParentId = 2,
  Conv_FieldNumber_ConvType = 3,
  Conv_FieldNumber_Level = 4,
  Conv_FieldNumber_DisplayName = 5,
  Conv_FieldNumber_Description_p = 6,
  Conv_FieldNumber_AvatarURL = 7,
  Conv_FieldNumber_AvatarInfo = 8,
  Conv_FieldNumber_TargetId = 9,
  Conv_FieldNumber_Status = 10,
  Conv_FieldNumber_IsPrivate = 11,
  Conv_FieldNumber_CreatedAt = 12,
  Conv_FieldNumber_UpdatedAt = 13,
  Conv_FieldNumber_ExtraInfo = 14,
  Conv_FieldNumber_AvatarBg = 15,
  Conv_FieldNumber_SysTagsArray = 22,
  Conv_FieldNumber_UserTagsArray = 23,
  Conv_FieldNumber_Disturb = 50,
};

/**
 * 会话信息 - 核心领域对象
 * 创建时必要参数：conv_type, display_name
 * 更新时必要参数：conv_id + 要更新的字段
 **/
GPB_FINAL @interface Conv : GPBMessage

/** 会话ID（创建时自动生成） */
@property(nonatomic, readwrite, copy, null_resettable) NSString *convId;

/** 父会话ID */
@property(nonatomic, readwrite, copy, null_resettable) NSString *parentId;

/** 会话类型（创建时必需） */
@property(nonatomic, readwrite) enum ConversationType convType;

/** 层级深度 */
@property(nonatomic, readwrite) int32_t level;

/** 显示名称（创建时必需） */
@property(nonatomic, readwrite, copy, null_resettable) NSString *displayName;

/** 描述 */
@property(nonatomic, readwrite, copy, null_resettable) NSString *description_p;

/** 头像URL */
@property(nonatomic, readwrite, copy, null_resettable) NSString *avatarURL;

/** 头像背景色（可选，当avatar_url为空时使用，格式：#色值1 或 #色值1&#色值2） */
@property(nonatomic, readwrite, copy, null_resettable) NSString *avatarBg;

/** 头像详细信息(JSON) */
@property(nonatomic, readwrite, copy, null_resettable) NSString *avatarInfo;

/** 目标对象ID（单聊=对方用户ID，群聊=群ID等） */
@property(nonatomic, readwrite, copy, null_resettable) NSString *targetId;

/** 状态 */
@property(nonatomic, readwrite) int32_t status;

/** 是否私有 */
@property(nonatomic, readwrite) BOOL isPrivate;

/** 创建时间 */
@property(nonatomic, readwrite) int64_t createdAt;

/** 更新时间 */
@property(nonatomic, readwrite) int64_t updatedAt;

/** 扩展信息(JSON) */
@property(nonatomic, readwrite, copy, null_resettable) NSString *extraInfo;

/** 标签：系统级与用户自定义（用户自定义为"当前请求用户"的个性化标签） */
@property(nonatomic, readwrite, strong, null_resettable) NSMutableArray<NSString*> *sysTagsArray;
/** The number of items in @c sysTagsArray without causing the array to be created. */
@property(nonatomic, readonly) NSUInteger sysTagsArray_Count;

/** 用户个性化标签（随请求用户变化） */
@property(nonatomic, readwrite, strong, null_resettable) NSMutableArray<NSString*> *userTagsArray;
/** The number of items in @c userTagsArray without causing the array to be created. */
@property(nonatomic, readonly) NSUInteger userTagsArray_Count;

/** 用户个性化设置 */
@property(nonatomic, readwrite) BOOL disturb;

@end

/**
 * Fetches the raw value of a @c Conv's @c convType property, even
 * if the value was not defined by the enum at the time the code was generated.
 **/
int32_t Conv_ConvType_RawValue(Conv *message);
/**
 * Sets the raw value of an @c Conv's @c convType property, allowing
 * it to be set to a value that was not defined by the enum at the time the code
 * was generated.
 **/
void SetConv_ConvType_RawValue(Conv *message, int32_t value);

#pragma mark - GetConv

typedef GPB_ENUM(GetConv_FieldNumber) {
  GetConv_FieldNumber_ConvId = 1,
};

/**
 * 获取会话请求 - 必要参数：conv_id
 **/
GPB_FINAL @interface GetConv : GPBMessage

/** 会话ID（必需） */
@property(nonatomic, readwrite, copy, null_resettable) NSString *convId;

@end

#pragma mark - DeleteConv

typedef GPB_ENUM(DeleteConv_FieldNumber) {
  DeleteConv_FieldNumber_ConvId = 1,
};

/**
 * 删除会话请求 - 必要参数：conv_id
 **/
GPB_FINAL @interface DeleteConv : GPBMessage

/** 会话ID（必需） */
@property(nonatomic, readwrite, copy, null_resettable) NSString *convId;

@end

#pragma mark - ConvListQuery

typedef GPB_ENUM(ConvListQuery_FieldNumber) {
  ConvListQuery_FieldNumber_ConvType = 1,
  ConvListQuery_FieldNumber_Page = 2,
  ConvListQuery_FieldNumber_WithUnread = 3,
};

/**
 * 会话列表查询请求 - 用于 list 方法
 **/
GPB_FINAL @interface ConvListQuery : GPBMessage

/** 会话类型过滤（可选：SINGLE/GROUP/ALL，默认ALL） */
@property(nonatomic, readwrite) enum ConversationType convType;

/** 分页参数（可选，使用系统类型） */
@property(nonatomic, readwrite, strong, null_resettable) Page *page;
/** Test to see if @c page has been set. */
@property(nonatomic, readwrite) BOOL hasPage;

/** 返回结果是否带未读数（可选：true=带未读数，false=不带未读数，默认false） */
@property(nonatomic, readwrite) BOOL withUnread;

@end

/**
 * Fetches the raw value of a @c ConvListQuery's @c convType property, even
 * if the value was not defined by the enum at the time the code was generated.
 **/
int32_t ConvListQuery_ConvType_RawValue(ConvListQuery *message);
/**
 * Sets the raw value of an @c ConvListQuery's @c convType property, allowing
 * it to be set to a value that was not defined by the enum at the time the code
 * was generated.
 **/
void SetConvListQuery_ConvType_RawValue(ConvListQuery *message, int32_t value);

#pragma mark - ConvList

typedef GPB_ENUM(ConvList_FieldNumber) {
  ConvList_FieldNumber_ConvsArray = 1,
  ConvList_FieldNumber_TotalCount = 2,
  ConvList_FieldNumber_Page = 3,
  ConvList_FieldNumber_Size = 4,
};

/**
 * 会话列表响应
 **/
GPB_FINAL @interface ConvList : GPBMessage

/** 会话列表 */
@property(nonatomic, readwrite, strong, null_resettable) NSMutableArray<Conv*> *convsArray;
/** The number of items in @c convsArray without causing the array to be created. */
@property(nonatomic, readonly) NSUInteger convsArray_Count;

/** 总数 */
@property(nonatomic, readwrite) int64_t totalCount;

/** 当前页 */
@property(nonatomic, readwrite) int32_t page;

/** 页面大小 */
@property(nonatomic, readwrite) int32_t size;

@end

#pragma mark - ConvWithUnread

typedef GPB_ENUM(ConvWithUnread_FieldNumber) {
  ConvWithUnread_FieldNumber_Conv = 1,
  ConvWithUnread_FieldNumber_UnreadCount = 2,
  ConvWithUnread_FieldNumber_LastReadSeq = 3,
  ConvWithUnread_FieldNumber_ConvMaxSeq = 4,
  ConvWithUnread_FieldNumber_LastMessage = 5,
  ConvWithUnread_FieldNumber_LastAtMessage = 6,
};

/**
 * 带未读数的会话信息
 **/
GPB_FINAL @interface ConvWithUnread : GPBMessage

/** 会话信息 */
@property(nonatomic, readwrite, strong, null_resettable) Conv *conv;
/** Test to see if @c conv has been set. */
@property(nonatomic, readwrite) BOOL hasConv;

/** 未读数量 */
@property(nonatomic, readwrite) int32_t unreadCount;

/** 最后阅读位置 */
@property(nonatomic, readwrite) int64_t lastReadSeq;

/** 会话最大序号 */
@property(nonatomic, readwrite) int64_t convMaxSeq;

/** 最后一条消息（可选） */
@property(nonatomic, readwrite, strong, null_resettable) ImMessage *lastMessage;
/** Test to see if @c lastMessage has been set. */
@property(nonatomic, readwrite) BOOL hasLastMessage;

/** 最后一条\@消息（可选，仅群聊） */
@property(nonatomic, readwrite, strong, null_resettable) ImMessage *lastAtMessage;
/** Test to see if @c lastAtMessage has been set. */
@property(nonatomic, readwrite) BOOL hasLastAtMessage;

@end

#pragma mark - ListWithUnread

typedef GPB_ENUM(ListWithUnread_FieldNumber) {
  ListWithUnread_FieldNumber_ConvsArray = 1,
  ListWithUnread_FieldNumber_TotalUnread = 2,
  ListWithUnread_FieldNumber_HasMore = 3,
  ListWithUnread_FieldNumber_Page = 4,
  ListWithUnread_FieldNumber_Size = 5,
  ListWithUnread_FieldNumber_Version = 6,
};

/**
 * 带未读数的会话列表响应
 **/
GPB_FINAL @interface ListWithUnread : GPBMessage

/** 会话列表 */
@property(nonatomic, readwrite, strong, null_resettable) NSMutableArray<ConvWithUnread*> *convsArray;
/** The number of items in @c convsArray without causing the array to be created. */
@property(nonatomic, readonly) NSUInteger convsArray_Count;

/** 用户总未读数 */
@property(nonatomic, readwrite) int64_t totalUnread;

/** 是否还有更多 */
@property(nonatomic, readwrite) BOOL hasMore;

/** 当前页 */
@property(nonatomic, readwrite) int32_t page;

/** 页面大小 */
@property(nonatomic, readwrite) int32_t size;

/** 版本号 */
@property(nonatomic, readwrite) int64_t version;

@end

#pragma mark - UpdateStats

typedef GPB_ENUM(UpdateStats_FieldNumber) {
  UpdateStats_FieldNumber_ConvId = 1,
  UpdateStats_FieldNumber_MessageId = 2,
  UpdateStats_FieldNumber_MessageTime = 3,
  UpdateStats_FieldNumber_SenderId = 4,
  UpdateStats_FieldNumber_MessagePreview = 5,
};

/**
 * 更新会话统计信息请求 - 必要参数：conv_id, message_info
 **/
GPB_FINAL @interface UpdateStats : GPBMessage

/** 会话ID（必需） */
@property(nonatomic, readwrite, copy, null_resettable) NSString *convId;

/** 消息ID */
@property(nonatomic, readwrite, copy, null_resettable) NSString *messageId;

/** 消息时间（毫秒时间戳） */
@property(nonatomic, readwrite) int64_t messageTime;

/** 发送者ID */
@property(nonatomic, readwrite, copy, null_resettable) NSString *senderId;

/** 消息预览（可选） */
@property(nonatomic, readwrite, copy, null_resettable) NSString *messagePreview;

@end

#pragma mark - UpdatePullTime

typedef GPB_ENUM(UpdatePullTime_FieldNumber) {
  UpdatePullTime_FieldNumber_ConvId = 1,
  UpdatePullTime_FieldNumber_UserId = 2,
  UpdatePullTime_FieldNumber_PullTime = 3,
};

/**
 * 更新拉取时间请求 - 必要参数：conv_id, user_id
 **/
GPB_FINAL @interface UpdatePullTime : GPBMessage

/** 会话ID（必需） */
@property(nonatomic, readwrite, copy, null_resettable) NSString *convId;

/** 用户ID（必需） */
@property(nonatomic, readwrite, copy, null_resettable) NSString *userId;

/** 拉取时间（毫秒时间戳） */
@property(nonatomic, readwrite) int64_t pullTime;

@end

#pragma mark - BatchCreateUserStates

typedef GPB_ENUM(BatchCreateUserStates_FieldNumber) {
  BatchCreateUserStates_FieldNumber_ConvId = 1,
  BatchCreateUserStates_FieldNumber_ConvType = 2,
  BatchCreateUserStates_FieldNumber_SourceId = 3,
  BatchCreateUserStates_FieldNumber_DisplayName = 4,
};

/**
 * 批量建立用户会话关系请求
 * 用于群消息分发时批量创建群成员的 user_state 记录
 * 注意：通过 InnerBatchMessage 的 toUsers() 传递目标用户列表
 **/
GPB_FINAL @interface BatchCreateUserStates : GPBMessage

/** 会话ID（必需） */
@property(nonatomic, readwrite, copy, null_resettable) NSString *convId;

/** 会话类型（必需，群聊=GROUP） */
@property(nonatomic, readwrite) enum ConversationType convType;

/** 会话发起方ID（群聊=创建者ID） */
@property(nonatomic, readwrite, copy, null_resettable) NSString *sourceId;

/** 显示名称（可选，群聊=群名称） */
@property(nonatomic, readwrite, copy, null_resettable) NSString *displayName;

@end

/**
 * Fetches the raw value of a @c BatchCreateUserStates's @c convType property, even
 * if the value was not defined by the enum at the time the code was generated.
 **/
int32_t BatchCreateUserStates_ConvType_RawValue(BatchCreateUserStates *message);
/**
 * Sets the raw value of an @c BatchCreateUserStates's @c convType property, allowing
 * it to be set to a value that was not defined by the enum at the time the code
 * was generated.
 **/
void SetBatchCreateUserStates_ConvType_RawValue(BatchCreateUserStates *message, int32_t value);

#pragma mark - BatchCreateUserStatesResult

typedef GPB_ENUM(BatchCreateUserStatesResult_FieldNumber) {
  BatchCreateUserStatesResult_FieldNumber_Success = 1,
  BatchCreateUserStatesResult_FieldNumber_CreatedCount = 2,
  BatchCreateUserStatesResult_FieldNumber_SkippedCount = 3,
  BatchCreateUserStatesResult_FieldNumber_FailedCount = 4,
};

/**
 * 批量建立用户会话关系结果
 **/
GPB_FINAL @interface BatchCreateUserStatesResult : GPBMessage

/** 是否成功 */
@property(nonatomic, readwrite) BOOL success;

/** 成功创建的用户数 */
@property(nonatomic, readwrite) int32_t createdCount;

/** 跳过数（已存在） */
@property(nonatomic, readwrite) int32_t skippedCount;

/** 失败数 */
@property(nonatomic, readwrite) int32_t failedCount;

@end

#pragma mark - Disturb

typedef GPB_ENUM(Disturb_FieldNumber) {
  Disturb_FieldNumber_ConvId = 1,
  Disturb_FieldNumber_Disturb = 2,
};

/**
 * 设置免打扰请求
 **/
GPB_FINAL @interface Disturb : GPBMessage

/** 会话ID（必需） */
@property(nonatomic, readwrite, copy, null_resettable) NSString *convId;

/** 是否免打扰（必需，true=免打扰，false=取消免打扰） */
@property(nonatomic, readwrite) BOOL disturb;

@end

#pragma mark - DisturbState

typedef GPB_ENUM(DisturbState_FieldNumber) {
  DisturbState_FieldNumber_Success = 1,
  DisturbState_FieldNumber_Disturb = 2,
};

/**
 * 设置免打扰响应
 **/
GPB_FINAL @interface DisturbState : GPBMessage

/** 是否成功 */
@property(nonatomic, readwrite) BOOL success;

/** 当前免打扰状态 */
@property(nonatomic, readwrite) BOOL disturb;

@end

NS_ASSUME_NONNULL_END

CF_EXTERN_C_END

#pragma clang diagnostic pop

// @@protoc_insertion_point(global_scope)
