// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: device_pb.proto

// This CPP symbol can be defined to use imports that match up to the framework
// imports needed when using CocoaPods.
#if !defined(GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS)
 #define GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS 0
#endif

#if GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS
 #import <Protobuf/GPBProtocolBuffers_RuntimeSupport.h>
#else
 #import "GPBProtocolBuffers_RuntimeSupport.h"
#endif

#import <stdatomic.h>

#import "DevicePb.pbobjc.h"
#import "SystemPb.pbobjc.h"
// @@protoc_insertion_point(imports)

#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wdeprecated-declarations"
#pragma clang diagnostic ignored "-Wdollar-in-identifier-extension"

#pragma mark - Objective C Class declarations
// Forward declarations of Objective C classes that we can use as
// static values in struct initializers.
// We don't use [Foo class] because it is not a static value.
GPBObjCClassDeclaration(Device);
GPBObjCClassDeclaration(Page);

#pragma mark - DevicePbRoot

@implementation DevicePbRoot

// No extensions in the file and none of the imports (direct or indirect)
// defined extensions, so no need to generate +extensionRegistry.

@end

#pragma mark - DevicePbRoot_FileDescriptor

static GPBFileDescriptor *DevicePbRoot_FileDescriptor(void) {
  // This is called by +initialize so there is no need to worry
  // about thread safety of the singleton.
  static GPBFileDescriptor *descriptor = NULL;
  if (!descriptor) {
    GPB_DEBUG_CHECK_RUNTIME_VERSIONS();
    descriptor = [[GPBFileDescriptor alloc] initWithPackage:@"im.device"
                                                     syntax:GPBFileSyntaxProto3];
  }
  return descriptor;
}

#pragma mark - Enum DeviceType

GPBEnumDescriptor *DeviceType_EnumDescriptor(void) {
  static _Atomic(GPBEnumDescriptor*) descriptor = nil;
  if (!descriptor) {
    static const char *valueNames =
        "Android\000Ios\000Pc\000Web\000";
    static const int32_t values[] = {
        DeviceType_Android,
        DeviceType_Ios,
        DeviceType_Pc,
        DeviceType_Web,
    };
    GPBEnumDescriptor *worker =
        [GPBEnumDescriptor allocDescriptorForName:GPBNSStringifySymbol(DeviceType)
                                       valueNames:valueNames
                                           values:values
                                            count:(uint32_t)(sizeof(values) / sizeof(int32_t))
                                     enumVerifier:DeviceType_IsValidValue];
    GPBEnumDescriptor *expected = nil;
    if (!atomic_compare_exchange_strong(&descriptor, &expected, worker)) {
//   //   [worker release];
    }
  }
  return descriptor;
}

BOOL DeviceType_IsValidValue(int32_t value__) {
  switch (value__) {
    case DeviceType_Android:
    case DeviceType_Ios:
    case DeviceType_Pc:
    case DeviceType_Web:
      return YES;
    default:
      return NO;
  }
}

#pragma mark - Enum DeviceStatus

GPBEnumDescriptor *DeviceStatus_EnumDescriptor(void) {
  static _Atomic(GPBEnumDescriptor*) descriptor = nil;
  if (!descriptor) {
    static const char *valueNames =
        "Active\000Inactive\000Banned\000Archived\000";
    static const int32_t values[] = {
        DeviceStatus_Active,
        DeviceStatus_Inactive,
        DeviceStatus_Banned,
        DeviceStatus_Archived,
    };
    GPBEnumDescriptor *worker =
        [GPBEnumDescriptor allocDescriptorForName:GPBNSStringifySymbol(DeviceStatus)
                                       valueNames:valueNames
                                           values:values
                                            count:(uint32_t)(sizeof(values) / sizeof(int32_t))
                                     enumVerifier:DeviceStatus_IsValidValue];
    GPBEnumDescriptor *expected = nil;
    if (!atomic_compare_exchange_strong(&descriptor, &expected, worker)) {
//   //   [worker release];
    }
  }
  return descriptor;
}

BOOL DeviceStatus_IsValidValue(int32_t value__) {
  switch (value__) {
    case DeviceStatus_Active:
    case DeviceStatus_Inactive:
    case DeviceStatus_Banned:
    case DeviceStatus_Archived:
      return YES;
    default:
      return NO;
  }
}

#pragma mark - Device

@implementation Device

@dynamic deviceId;
@dynamic deviceName;
@dynamic deviceType;
@dynamic status;
@dynamic appVersion;
@dynamic clientIp;
@dynamic lastActiveTime;
@dynamic createdAt;
@dynamic updatedAt;
@dynamic systemName;
@dynamic systemVersion;
@dynamic kernelVersion;
@dynamic apiLevel;
@dynamic brand;
@dynamic model;
@dynamic hardware;
@dynamic board;
@dynamic product;
@dynamic serial;
@dynamic screenResolution;
@dynamic screenDensity;
@dynamic screenSize;
@dynamic cpuInfo;
@dynamic memoryInfo;
@dynamic storageInfo;
@dynamic gpuInfo;
@dynamic networkType;
@dynamic carrier;
@dynamic wifiSsid;
@dynamic macAddress;
@dynamic batteryStatus;
@dynamic batteryLevel;
@dynamic timezone;
@dynamic language;
@dynamic region;
@dynamic extra, extra_Count;

typedef struct Device__storage_ {
  uint32_t _has_storage_[2];
  DeviceType deviceType;
  DeviceStatus status;
  int32_t batteryLevel;
  NSString *deviceId;
  NSString *deviceName;
  NSString *appVersion;
  NSString *clientIp;
  NSString *systemName;
  NSString *systemVersion;
  NSString *kernelVersion;
  NSString *apiLevel;
  NSString *brand;
  NSString *model;
  NSString *hardware;
  NSString *board;
  NSString *product;
  NSString *serial;
  NSString *screenResolution;
  NSString *screenDensity;
  NSString *screenSize;
  NSString *cpuInfo;
  NSString *memoryInfo;
  NSString *storageInfo;
  NSString *gpuInfo;
  NSString *networkType;
  NSString *carrier;
  NSString *wifiSsid;
  NSString *macAddress;
  NSString *batteryStatus;
  NSString *timezone;
  NSString *language;
  NSString *region;
  NSMutableDictionary *extra;
  int64_t lastActiveTime;
  int64_t createdAt;
  int64_t updatedAt;
} Device__storage_;

// This method is threadsafe because it is initially called
// in +initialize for each subclass.
+ (GPBDescriptor *)descriptor {
  static GPBDescriptor *descriptor = nil;
  if (!descriptor) {
    static GPBMessageFieldDescription fields[] = {
      {
        .name = "deviceId",
        .dataTypeSpecific.clazz = Nil,
        .number = Device_FieldNumber_DeviceId,
        .hasIndex = 0,
        .offset = (uint32_t)offsetof(Device__storage_, deviceId),
        .flags = (GPBFieldFlags)(GPBFieldOptional | GPBFieldClearHasIvarOnZero),
        .dataType = GPBDataTypeString,
      },
      {
        .name = "deviceName",
        .dataTypeSpecific.clazz = Nil,
        .number = Device_FieldNumber_DeviceName,
        .hasIndex = 1,
        .offset = (uint32_t)offsetof(Device__storage_, deviceName),
        .flags = (GPBFieldFlags)(GPBFieldOptional | GPBFieldClearHasIvarOnZero),
        .dataType = GPBDataTypeString,
      },
      {
        .name = "deviceType",
        .dataTypeSpecific.enumDescFunc = DeviceType_EnumDescriptor,
        .number = Device_FieldNumber_DeviceType,
        .hasIndex = 2,
        .offset = (uint32_t)offsetof(Device__storage_, deviceType),
        .flags = (GPBFieldFlags)(GPBFieldOptional | GPBFieldHasEnumDescriptor | GPBFieldClearHasIvarOnZero),
        .dataType = GPBDataTypeEnum,
      },
      {
        .name = "status",
        .dataTypeSpecific.enumDescFunc = DeviceStatus_EnumDescriptor,
        .number = Device_FieldNumber_Status,
        .hasIndex = 3,
        .offset = (uint32_t)offsetof(Device__storage_, status),
        .flags = (GPBFieldFlags)(GPBFieldOptional | GPBFieldHasEnumDescriptor | GPBFieldClearHasIvarOnZero),
        .dataType = GPBDataTypeEnum,
      },
      {
        .name = "appVersion",
        .dataTypeSpecific.clazz = Nil,
        .number = Device_FieldNumber_AppVersion,
        .hasIndex = 4,
        .offset = (uint32_t)offsetof(Device__storage_, appVersion),
        .flags = (GPBFieldFlags)(GPBFieldOptional | GPBFieldClearHasIvarOnZero),
        .dataType = GPBDataTypeString,
      },
      {
        .name = "clientIp",
        .dataTypeSpecific.clazz = Nil,
        .number = Device_FieldNumber_ClientIp,
        .hasIndex = 5,
        .offset = (uint32_t)offsetof(Device__storage_, clientIp),
        .flags = (GPBFieldFlags)(GPBFieldOptional | GPBFieldClearHasIvarOnZero),
        .dataType = GPBDataTypeString,
      },
      {
        .name = "lastActiveTime",
        .dataTypeSpecific.clazz = Nil,
        .number = Device_FieldNumber_LastActiveTime,
        .hasIndex = 6,
        .offset = (uint32_t)offsetof(Device__storage_, lastActiveTime),
        .flags = (GPBFieldFlags)(GPBFieldOptional | GPBFieldClearHasIvarOnZero),
        .dataType = GPBDataTypeInt64,
      },
      {
        .name = "createdAt",
        .dataTypeSpecific.clazz = Nil,
        .number = Device_FieldNumber_CreatedAt,
        .hasIndex = 7,
        .offset = (uint32_t)offsetof(Device__storage_, createdAt),
        .flags = (GPBFieldFlags)(GPBFieldOptional | GPBFieldClearHasIvarOnZero),
        .dataType = GPBDataTypeInt64,
      },
      {
        .name = "updatedAt",
        .dataTypeSpecific.clazz = Nil,
        .number = Device_FieldNumber_UpdatedAt,
        .hasIndex = 8,
        .offset = (uint32_t)offsetof(Device__storage_, updatedAt),
        .flags = (GPBFieldFlags)(GPBFieldOptional | GPBFieldClearHasIvarOnZero),
        .dataType = GPBDataTypeInt64,
      },
      {
        .name = "systemName",
        .dataTypeSpecific.clazz = Nil,
        .number = Device_FieldNumber_SystemName,
        .hasIndex = 9,
        .offset = (uint32_t)offsetof(Device__storage_, systemName),
        .flags = (GPBFieldFlags)(GPBFieldOptional | GPBFieldClearHasIvarOnZero),
        .dataType = GPBDataTypeString,
      },
      {
        .name = "systemVersion",
        .dataTypeSpecific.clazz = Nil,
        .number = Device_FieldNumber_SystemVersion,
        .hasIndex = 10,
        .offset = (uint32_t)offsetof(Device__storage_, systemVersion),
        .flags = (GPBFieldFlags)(GPBFieldOptional | GPBFieldClearHasIvarOnZero),
        .dataType = GPBDataTypeString,
      },
      {
        .name = "kernelVersion",
        .dataTypeSpecific.clazz = Nil,
        .number = Device_FieldNumber_KernelVersion,
        .hasIndex = 11,
        .offset = (uint32_t)offsetof(Device__storage_, kernelVersion),
        .flags = (GPBFieldFlags)(GPBFieldOptional | GPBFieldClearHasIvarOnZero),
        .dataType = GPBDataTypeString,
      },
      {
        .name = "apiLevel",
        .dataTypeSpecific.clazz = Nil,
        .number = Device_FieldNumber_ApiLevel,
        .hasIndex = 12,
        .offset = (uint32_t)offsetof(Device__storage_, apiLevel),
        .flags = (GPBFieldFlags)(GPBFieldOptional | GPBFieldClearHasIvarOnZero),
        .dataType = GPBDataTypeString,
      },
      {
        .name = "brand",
        .dataTypeSpecific.clazz = Nil,
        .number = Device_FieldNumber_Brand,
        .hasIndex = 13,
        .offset = (uint32_t)offsetof(Device__storage_, brand),
        .flags = (GPBFieldFlags)(GPBFieldOptional | GPBFieldClearHasIvarOnZero),
        .dataType = GPBDataTypeString,
      },
      {
        .name = "model",
        .dataTypeSpecific.clazz = Nil,
        .number = Device_FieldNumber_Model,
        .hasIndex = 14,
        .offset = (uint32_t)offsetof(Device__storage_, model),
        .flags = (GPBFieldFlags)(GPBFieldOptional | GPBFieldClearHasIvarOnZero),
        .dataType = GPBDataTypeString,
      },
      {
        .name = "hardware",
        .dataTypeSpecific.clazz = Nil,
        .number = Device_FieldNumber_Hardware,
        .hasIndex = 15,
        .offset = (uint32_t)offsetof(Device__storage_, hardware),
        .flags = (GPBFieldFlags)(GPBFieldOptional | GPBFieldClearHasIvarOnZero),
        .dataType = GPBDataTypeString,
      },
      {
        .name = "board",
        .dataTypeSpecific.clazz = Nil,
        .number = Device_FieldNumber_Board,
        .hasIndex = 16,
        .offset = (uint32_t)offsetof(Device__storage_, board),
        .flags = (GPBFieldFlags)(GPBFieldOptional | GPBFieldClearHasIvarOnZero),
        .dataType = GPBDataTypeString,
      },
      {
        .name = "product",
        .dataTypeSpecific.clazz = Nil,
        .number = Device_FieldNumber_Product,
        .hasIndex = 17,
        .offset = (uint32_t)offsetof(Device__storage_, product),
        .flags = (GPBFieldFlags)(GPBFieldOptional | GPBFieldClearHasIvarOnZero),
        .dataType = GPBDataTypeString,
      },
      {
        .name = "serial",
        .dataTypeSpecific.clazz = Nil,
        .number = Device_FieldNumber_Serial,
        .hasIndex = 18,
        .offset = (uint32_t)offsetof(Device__storage_, serial),
        .flags = (GPBFieldFlags)(GPBFieldOptional | GPBFieldClearHasIvarOnZero),
        .dataType = GPBDataTypeString,
      },
      {
        .name = "screenResolution",
        .dataTypeSpecific.clazz = Nil,
        .number = Device_FieldNumber_ScreenResolution,
        .hasIndex = 19,
        .offset = (uint32_t)offsetof(Device__storage_, screenResolution),
        .flags = (GPBFieldFlags)(GPBFieldOptional | GPBFieldClearHasIvarOnZero),
        .dataType = GPBDataTypeString,
      },
      {
        .name = "screenDensity",
        .dataTypeSpecific.clazz = Nil,
        .number = Device_FieldNumber_ScreenDensity,
        .hasIndex = 20,
        .offset = (uint32_t)offsetof(Device__storage_, screenDensity),
        .flags = (GPBFieldFlags)(GPBFieldOptional | GPBFieldClearHasIvarOnZero),
        .dataType = GPBDataTypeString,
      },
      {
        .name = "screenSize",
        .dataTypeSpecific.clazz = Nil,
        .number = Device_FieldNumber_ScreenSize,
        .hasIndex = 21,
        .offset = (uint32_t)offsetof(Device__storage_, screenSize),
        .flags = (GPBFieldFlags)(GPBFieldOptional | GPBFieldClearHasIvarOnZero),
        .dataType = GPBDataTypeString,
      },
      {
        .name = "cpuInfo",
        .dataTypeSpecific.clazz = Nil,
        .number = Device_FieldNumber_CpuInfo,
        .hasIndex = 22,
        .offset = (uint32_t)offsetof(Device__storage_, cpuInfo),
        .flags = (GPBFieldFlags)(GPBFieldOptional | GPBFieldClearHasIvarOnZero),
        .dataType = GPBDataTypeString,
      },
      {
        .name = "memoryInfo",
        .dataTypeSpecific.clazz = Nil,
        .number = Device_FieldNumber_MemoryInfo,
        .hasIndex = 23,
        .offset = (uint32_t)offsetof(Device__storage_, memoryInfo),
        .flags = (GPBFieldFlags)(GPBFieldOptional | GPBFieldClearHasIvarOnZero),
        .dataType = GPBDataTypeString,
      },
      {
        .name = "storageInfo",
        .dataTypeSpecific.clazz = Nil,
        .number = Device_FieldNumber_StorageInfo,
        .hasIndex = 24,
        .offset = (uint32_t)offsetof(Device__storage_, storageInfo),
        .flags = (GPBFieldFlags)(GPBFieldOptional | GPBFieldClearHasIvarOnZero),
        .dataType = GPBDataTypeString,
      },
      {
        .name = "gpuInfo",
        .dataTypeSpecific.clazz = Nil,
        .number = Device_FieldNumber_GpuInfo,
        .hasIndex = 25,
        .offset = (uint32_t)offsetof(Device__storage_, gpuInfo),
        .flags = (GPBFieldFlags)(GPBFieldOptional | GPBFieldClearHasIvarOnZero),
        .dataType = GPBDataTypeString,
      },
      {
        .name = "networkType",
        .dataTypeSpecific.clazz = Nil,
        .number = Device_FieldNumber_NetworkType,
        .hasIndex = 26,
        .offset = (uint32_t)offsetof(Device__storage_, networkType),
        .flags = (GPBFieldFlags)(GPBFieldOptional | GPBFieldClearHasIvarOnZero),
        .dataType = GPBDataTypeString,
      },
      {
        .name = "carrier",
        .dataTypeSpecific.clazz = Nil,
        .number = Device_FieldNumber_Carrier,
        .hasIndex = 27,
        .offset = (uint32_t)offsetof(Device__storage_, carrier),
        .flags = (GPBFieldFlags)(GPBFieldOptional | GPBFieldClearHasIvarOnZero),
        .dataType = GPBDataTypeString,
      },
      {
        .name = "wifiSsid",
        .dataTypeSpecific.clazz = Nil,
        .number = Device_FieldNumber_WifiSsid,
        .hasIndex = 28,
        .offset = (uint32_t)offsetof(Device__storage_, wifiSsid),
        .flags = (GPBFieldFlags)(GPBFieldOptional | GPBFieldClearHasIvarOnZero),
        .dataType = GPBDataTypeString,
      },
      {
        .name = "macAddress",
        .dataTypeSpecific.clazz = Nil,
        .number = Device_FieldNumber_MacAddress,
        .hasIndex = 29,
        .offset = (uint32_t)offsetof(Device__storage_, macAddress),
        .flags = (GPBFieldFlags)(GPBFieldOptional | GPBFieldClearHasIvarOnZero),
        .dataType = GPBDataTypeString,
      },
      {
        .name = "batteryStatus",
        .dataTypeSpecific.clazz = Nil,
        .number = Device_FieldNumber_BatteryStatus,
        .hasIndex = 30,
        .offset = (uint32_t)offsetof(Device__storage_, batteryStatus),
        .flags = (GPBFieldFlags)(GPBFieldOptional | GPBFieldClearHasIvarOnZero),
        .dataType = GPBDataTypeString,
      },
      {
        .name = "batteryLevel",
        .dataTypeSpecific.clazz = Nil,
        .number = Device_FieldNumber_BatteryLevel,
        .hasIndex = 31,
        .offset = (uint32_t)offsetof(Device__storage_, batteryLevel),
        .flags = (GPBFieldFlags)(GPBFieldOptional | GPBFieldClearHasIvarOnZero),
        .dataType = GPBDataTypeInt32,
      },
      {
        .name = "timezone",
        .dataTypeSpecific.clazz = Nil,
        .number = Device_FieldNumber_Timezone,
        .hasIndex = 32,
        .offset = (uint32_t)offsetof(Device__storage_, timezone),
        .flags = (GPBFieldFlags)(GPBFieldOptional | GPBFieldClearHasIvarOnZero),
        .dataType = GPBDataTypeString,
      },
      {
        .name = "language",
        .dataTypeSpecific.clazz = Nil,
        .number = Device_FieldNumber_Language,
        .hasIndex = 33,
        .offset = (uint32_t)offsetof(Device__storage_, language),
        .flags = (GPBFieldFlags)(GPBFieldOptional | GPBFieldClearHasIvarOnZero),
        .dataType = GPBDataTypeString,
      },
      {
        .name = "region",
        .dataTypeSpecific.clazz = Nil,
        .number = Device_FieldNumber_Region,
        .hasIndex = 34,
        .offset = (uint32_t)offsetof(Device__storage_, region),
        .flags = (GPBFieldFlags)(GPBFieldOptional | GPBFieldClearHasIvarOnZero),
        .dataType = GPBDataTypeString,
      },
      {
        .name = "extra",
        .dataTypeSpecific.clazz = Nil,
        .number = Device_FieldNumber_Extra,
        .hasIndex = GPBNoHasBit,
        .offset = (uint32_t)offsetof(Device__storage_, extra),
        .flags = GPBFieldMapKeyString,
        .dataType = GPBDataTypeString,
      },
    };
    GPBDescriptor *localDescriptor =
        [GPBDescriptor allocDescriptorForClass:[Device class]
                                     rootClass:[DevicePbRoot class]
                                          file:DevicePbRoot_FileDescriptor()
                                        fields:fields
                                    fieldCount:(uint32_t)(sizeof(fields) / sizeof(GPBMessageFieldDescription))
                                   storageSize:sizeof(Device__storage_)
                                         flags:(GPBDescriptorInitializationFlags)(GPBDescriptorInitializationFlag_UsesClassRefs | GPBDescriptorInitializationFlag_Proto3OptionalKnown)];
    #if defined(DEBUG) && DEBUG
      NSAssert(descriptor == nil, @"Startup recursed!");
    #endif  // DEBUG
    descriptor = localDescriptor;
  }
  return descriptor;
}

@end

int32_t Device_DeviceType_RawValue(Device *message) {
  GPBDescriptor *descriptor = [Device descriptor];
  GPBFieldDescriptor *field = [descriptor fieldWithNumber:Device_FieldNumber_DeviceType];
  return GPBGetMessageRawEnumField(message, field);
}

void SetDevice_DeviceType_RawValue(Device *message, int32_t value) {
  GPBDescriptor *descriptor = [Device descriptor];
  GPBFieldDescriptor *field = [descriptor fieldWithNumber:Device_FieldNumber_DeviceType];
  GPBSetMessageRawEnumField(message, field, value);
}

int32_t Device_Status_RawValue(Device *message) {
  GPBDescriptor *descriptor = [Device descriptor];
  GPBFieldDescriptor *field = [descriptor fieldWithNumber:Device_FieldNumber_Status];
  return GPBGetMessageRawEnumField(message, field);
}

void SetDevice_Status_RawValue(Device *message, int32_t value) {
  GPBDescriptor *descriptor = [Device descriptor];
  GPBFieldDescriptor *field = [descriptor fieldWithNumber:Device_FieldNumber_Status];
  GPBSetMessageRawEnumField(message, field, value);
}

#pragma mark - Check

@implementation Check

@dynamic userId;
@dynamic deviceId;
@dynamic hasDevice, device;

typedef struct Check__storage_ {
  uint32_t _has_storage_[1];
  NSString *userId;
  NSString *deviceId;
  Device *device;
} Check__storage_;

// This method is threadsafe because it is initially called
// in +initialize for each subclass.
+ (GPBDescriptor *)descriptor {
  static GPBDescriptor *descriptor = nil;
  if (!descriptor) {
    static GPBMessageFieldDescription fields[] = {
      {
        .name = "userId",
        .dataTypeSpecific.clazz = Nil,
        .number = Check_FieldNumber_UserId,
        .hasIndex = 0,
        .offset = (uint32_t)offsetof(Check__storage_, userId),
        .flags = (GPBFieldFlags)(GPBFieldOptional | GPBFieldClearHasIvarOnZero),
        .dataType = GPBDataTypeString,
      },
      {
        .name = "deviceId",
        .dataTypeSpecific.clazz = Nil,
        .number = Check_FieldNumber_DeviceId,
        .hasIndex = 1,
        .offset = (uint32_t)offsetof(Check__storage_, deviceId),
        .flags = (GPBFieldFlags)(GPBFieldOptional | GPBFieldClearHasIvarOnZero),
        .dataType = GPBDataTypeString,
      },
      {
        .name = "device",
        .dataTypeSpecific.clazz = GPBObjCClass(Device),
        .number = Check_FieldNumber_Device,
        .hasIndex = 2,
        .offset = (uint32_t)offsetof(Check__storage_, device),
        .flags = GPBFieldOptional,
        .dataType = GPBDataTypeMessage,
      },
    };
    GPBDescriptor *localDescriptor =
        [GPBDescriptor allocDescriptorForClass:[Check class]
                                     rootClass:[DevicePbRoot class]
                                          file:DevicePbRoot_FileDescriptor()
                                        fields:fields
                                    fieldCount:(uint32_t)(sizeof(fields) / sizeof(GPBMessageFieldDescription))
                                   storageSize:sizeof(Check__storage_)
                                         flags:(GPBDescriptorInitializationFlags)(GPBDescriptorInitializationFlag_UsesClassRefs | GPBDescriptorInitializationFlag_Proto3OptionalKnown)];
    #if defined(DEBUG) && DEBUG
      NSAssert(descriptor == nil, @"Startup recursed!");
    #endif  // DEBUG
    descriptor = localDescriptor;
  }
  return descriptor;
}

@end

#pragma mark - Get

@implementation Get

@dynamic userId;
@dynamic deviceId;

typedef struct Get__storage_ {
  uint32_t _has_storage_[1];
  NSString *userId;
  NSString *deviceId;
} Get__storage_;

// This method is threadsafe because it is initially called
// in +initialize for each subclass.
+ (GPBDescriptor *)descriptor {
  static GPBDescriptor *descriptor = nil;
  if (!descriptor) {
    static GPBMessageFieldDescription fields[] = {
      {
        .name = "userId",
        .dataTypeSpecific.clazz = Nil,
        .number = Get_FieldNumber_UserId,
        .hasIndex = 0,
        .offset = (uint32_t)offsetof(Get__storage_, userId),
        .flags = (GPBFieldFlags)(GPBFieldOptional | GPBFieldClearHasIvarOnZero),
        .dataType = GPBDataTypeString,
      },
      {
        .name = "deviceId",
        .dataTypeSpecific.clazz = Nil,
        .number = Get_FieldNumber_DeviceId,
        .hasIndex = 1,
        .offset = (uint32_t)offsetof(Get__storage_, deviceId),
        .flags = (GPBFieldFlags)(GPBFieldOptional | GPBFieldClearHasIvarOnZero),
        .dataType = GPBDataTypeString,
      },
    };
    GPBDescriptor *localDescriptor =
        [GPBDescriptor allocDescriptorForClass:[Get class]
                                     rootClass:[DevicePbRoot class]
                                          file:DevicePbRoot_FileDescriptor()
                                        fields:fields
                                    fieldCount:(uint32_t)(sizeof(fields) / sizeof(GPBMessageFieldDescription))
                                   storageSize:sizeof(Get__storage_)
                                         flags:(GPBDescriptorInitializationFlags)(GPBDescriptorInitializationFlag_UsesClassRefs | GPBDescriptorInitializationFlag_Proto3OptionalKnown)];
    #if defined(DEBUG) && DEBUG
      NSAssert(descriptor == nil, @"Startup recursed!");
    #endif  // DEBUG
    descriptor = localDescriptor;
  }
  return descriptor;
}

@end

#pragma mark - ListQuery

@implementation ListQuery

@dynamic userId;
@dynamic deviceType;
@dynamic status;
@dynamic hasPage, page;

typedef struct ListQuery__storage_ {
  uint32_t _has_storage_[1];
  DeviceType deviceType;
  DeviceStatus status;
  NSString *userId;
  Page *page;
} ListQuery__storage_;

// This method is threadsafe because it is initially called
// in +initialize for each subclass.
+ (GPBDescriptor *)descriptor {
  static GPBDescriptor *descriptor = nil;
  if (!descriptor) {
    static GPBMessageFieldDescription fields[] = {
      {
        .name = "userId",
        .dataTypeSpecific.clazz = Nil,
        .number = ListQuery_FieldNumber_UserId,
        .hasIndex = 0,
        .offset = (uint32_t)offsetof(ListQuery__storage_, userId),
        .flags = (GPBFieldFlags)(GPBFieldOptional | GPBFieldClearHasIvarOnZero),
        .dataType = GPBDataTypeString,
      },
      {
        .name = "deviceType",
        .dataTypeSpecific.enumDescFunc = DeviceType_EnumDescriptor,
        .number = ListQuery_FieldNumber_DeviceType,
        .hasIndex = 1,
        .offset = (uint32_t)offsetof(ListQuery__storage_, deviceType),
        .flags = (GPBFieldFlags)(GPBFieldOptional | GPBFieldHasEnumDescriptor | GPBFieldClearHasIvarOnZero),
        .dataType = GPBDataTypeEnum,
      },
      {
        .name = "status",
        .dataTypeSpecific.enumDescFunc = DeviceStatus_EnumDescriptor,
        .number = ListQuery_FieldNumber_Status,
        .hasIndex = 2,
        .offset = (uint32_t)offsetof(ListQuery__storage_, status),
        .flags = (GPBFieldFlags)(GPBFieldOptional | GPBFieldHasEnumDescriptor | GPBFieldClearHasIvarOnZero),
        .dataType = GPBDataTypeEnum,
      },
      {
        .name = "page",
        .dataTypeSpecific.clazz = GPBObjCClass(Page),
        .number = ListQuery_FieldNumber_Page,
        .hasIndex = 3,
        .offset = (uint32_t)offsetof(ListQuery__storage_, page),
        .flags = GPBFieldOptional,
        .dataType = GPBDataTypeMessage,
      },
    };
    GPBDescriptor *localDescriptor =
        [GPBDescriptor allocDescriptorForClass:[ListQuery class]
                                     rootClass:[DevicePbRoot class]
                                          file:DevicePbRoot_FileDescriptor()
                                        fields:fields
                                    fieldCount:(uint32_t)(sizeof(fields) / sizeof(GPBMessageFieldDescription))
                                   storageSize:sizeof(ListQuery__storage_)
                                         flags:(GPBDescriptorInitializationFlags)(GPBDescriptorInitializationFlag_UsesClassRefs | GPBDescriptorInitializationFlag_Proto3OptionalKnown)];
    #if defined(DEBUG) && DEBUG
      NSAssert(descriptor == nil, @"Startup recursed!");
    #endif  // DEBUG
    descriptor = localDescriptor;
  }
  return descriptor;
}

@end

int32_t ListQuery_DeviceType_RawValue(ListQuery *message) {
  GPBDescriptor *descriptor = [ListQuery descriptor];
  GPBFieldDescriptor *field = [descriptor fieldWithNumber:ListQuery_FieldNumber_DeviceType];
  return GPBGetMessageRawEnumField(message, field);
}

void SetListQuery_DeviceType_RawValue(ListQuery *message, int32_t value) {
  GPBDescriptor *descriptor = [ListQuery descriptor];
  GPBFieldDescriptor *field = [descriptor fieldWithNumber:ListQuery_FieldNumber_DeviceType];
  GPBSetMessageRawEnumField(message, field, value);
}

int32_t ListQuery_Status_RawValue(ListQuery *message) {
  GPBDescriptor *descriptor = [ListQuery descriptor];
  GPBFieldDescriptor *field = [descriptor fieldWithNumber:ListQuery_FieldNumber_Status];
  return GPBGetMessageRawEnumField(message, field);
}

void SetListQuery_Status_RawValue(ListQuery *message, int32_t value) {
  GPBDescriptor *descriptor = [ListQuery descriptor];
  GPBFieldDescriptor *field = [descriptor fieldWithNumber:ListQuery_FieldNumber_Status];
  GPBSetMessageRawEnumField(message, field, value);
}

#pragma mark - GetUserByDevice

@implementation GetUserByDevice

@dynamic deviceId;

typedef struct GetUserByDevice__storage_ {
  uint32_t _has_storage_[1];
  NSString *deviceId;
} GetUserByDevice__storage_;

// This method is threadsafe because it is initially called
// in +initialize for each subclass.
+ (GPBDescriptor *)descriptor {
  static GPBDescriptor *descriptor = nil;
  if (!descriptor) {
    static GPBMessageFieldDescription fields[] = {
      {
        .name = "deviceId",
        .dataTypeSpecific.clazz = Nil,
        .number = GetUserByDevice_FieldNumber_DeviceId,
        .hasIndex = 0,
        .offset = (uint32_t)offsetof(GetUserByDevice__storage_, deviceId),
        .flags = (GPBFieldFlags)(GPBFieldOptional | GPBFieldClearHasIvarOnZero),
        .dataType = GPBDataTypeString,
      },
    };
    GPBDescriptor *localDescriptor =
        [GPBDescriptor allocDescriptorForClass:[GetUserByDevice class]
                                     rootClass:[DevicePbRoot class]
                                          file:DevicePbRoot_FileDescriptor()
                                        fields:fields
                                    fieldCount:(uint32_t)(sizeof(fields) / sizeof(GPBMessageFieldDescription))
                                   storageSize:sizeof(GetUserByDevice__storage_)
                                         flags:(GPBDescriptorInitializationFlags)(GPBDescriptorInitializationFlag_UsesClassRefs | GPBDescriptorInitializationFlag_Proto3OptionalKnown)];
    #if defined(DEBUG) && DEBUG
      NSAssert(descriptor == nil, @"Startup recursed!");
    #endif  // DEBUG
    descriptor = localDescriptor;
  }
  return descriptor;
}

@end

#pragma mark - UpdateActivity

@implementation UpdateActivity

@dynamic userId;
@dynamic deviceId;
@dynamic clientIp;
@dynamic activeTime;

typedef struct UpdateActivity__storage_ {
  uint32_t _has_storage_[1];
  NSString *userId;
  NSString *deviceId;
  NSString *clientIp;
  int64_t activeTime;
} UpdateActivity__storage_;

// This method is threadsafe because it is initially called
// in +initialize for each subclass.
+ (GPBDescriptor *)descriptor {
  static GPBDescriptor *descriptor = nil;
  if (!descriptor) {
    static GPBMessageFieldDescription fields[] = {
      {
        .name = "userId",
        .dataTypeSpecific.clazz = Nil,
        .number = UpdateActivity_FieldNumber_UserId,
        .hasIndex = 0,
        .offset = (uint32_t)offsetof(UpdateActivity__storage_, userId),
        .flags = (GPBFieldFlags)(GPBFieldOptional | GPBFieldClearHasIvarOnZero),
        .dataType = GPBDataTypeString,
      },
      {
        .name = "deviceId",
        .dataTypeSpecific.clazz = Nil,
        .number = UpdateActivity_FieldNumber_DeviceId,
        .hasIndex = 1,
        .offset = (uint32_t)offsetof(UpdateActivity__storage_, deviceId),
        .flags = (GPBFieldFlags)(GPBFieldOptional | GPBFieldClearHasIvarOnZero),
        .dataType = GPBDataTypeString,
      },
      {
        .name = "clientIp",
        .dataTypeSpecific.clazz = Nil,
        .number = UpdateActivity_FieldNumber_ClientIp,
        .hasIndex = 2,
        .offset = (uint32_t)offsetof(UpdateActivity__storage_, clientIp),
        .flags = (GPBFieldFlags)(GPBFieldOptional | GPBFieldClearHasIvarOnZero),
        .dataType = GPBDataTypeString,
      },
      {
        .name = "activeTime",
        .dataTypeSpecific.clazz = Nil,
        .number = UpdateActivity_FieldNumber_ActiveTime,
        .hasIndex = 3,
        .offset = (uint32_t)offsetof(UpdateActivity__storage_, activeTime),
        .flags = (GPBFieldFlags)(GPBFieldOptional | GPBFieldClearHasIvarOnZero),
        .dataType = GPBDataTypeInt64,
      },
    };
    GPBDescriptor *localDescriptor =
        [GPBDescriptor allocDescriptorForClass:[UpdateActivity class]
                                     rootClass:[DevicePbRoot class]
                                          file:DevicePbRoot_FileDescriptor()
                                        fields:fields
                                    fieldCount:(uint32_t)(sizeof(fields) / sizeof(GPBMessageFieldDescription))
                                   storageSize:sizeof(UpdateActivity__storage_)
                                         flags:(GPBDescriptorInitializationFlags)(GPBDescriptorInitializationFlag_UsesClassRefs | GPBDescriptorInitializationFlag_Proto3OptionalKnown)];
    #if defined(DEBUG) && DEBUG
      NSAssert(descriptor == nil, @"Startup recursed!");
    #endif  // DEBUG
    descriptor = localDescriptor;
  }
  return descriptor;
}

@end

#pragma mark - RenameDevice

@implementation RenameDevice

@dynamic userId;
@dynamic deviceId;
@dynamic newName;

typedef struct RenameDevice__storage_ {
  uint32_t _has_storage_[1];
  NSString *userId;
  NSString *deviceId;
  NSString *newName;
} RenameDevice__storage_;

// This method is threadsafe because it is initially called
// in +initialize for each subclass.
+ (GPBDescriptor *)descriptor {
  static GPBDescriptor *descriptor = nil;
  if (!descriptor) {
    static GPBMessageFieldDescription fields[] = {
      {
        .name = "userId",
        .dataTypeSpecific.clazz = Nil,
        .number = RenameDevice_FieldNumber_UserId,
        .hasIndex = 0,
        .offset = (uint32_t)offsetof(RenameDevice__storage_, userId),
        .flags = (GPBFieldFlags)(GPBFieldOptional | GPBFieldClearHasIvarOnZero),
        .dataType = GPBDataTypeString,
      },
      {
        .name = "deviceId",
        .dataTypeSpecific.clazz = Nil,
        .number = RenameDevice_FieldNumber_DeviceId,
        .hasIndex = 1,
        .offset = (uint32_t)offsetof(RenameDevice__storage_, deviceId),
        .flags = (GPBFieldFlags)(GPBFieldOptional | GPBFieldClearHasIvarOnZero),
        .dataType = GPBDataTypeString,
      },
      {
        .name = "newName",
        .dataTypeSpecific.clazz = Nil,
        .number = RenameDevice_FieldNumber_NewName,
        .hasIndex = 2,
        .offset = (uint32_t)offsetof(RenameDevice__storage_, newName),
        .flags = (GPBFieldFlags)(GPBFieldOptional | GPBFieldClearHasIvarOnZero),
        .dataType = GPBDataTypeString,
      },
    };
    GPBDescriptor *localDescriptor =
        [GPBDescriptor allocDescriptorForClass:[RenameDevice class]
                                     rootClass:[DevicePbRoot class]
                                          file:DevicePbRoot_FileDescriptor()
                                        fields:fields
                                    fieldCount:(uint32_t)(sizeof(fields) / sizeof(GPBMessageFieldDescription))
                                   storageSize:sizeof(RenameDevice__storage_)
                                         flags:(GPBDescriptorInitializationFlags)(GPBDescriptorInitializationFlag_UsesClassRefs | GPBDescriptorInitializationFlag_Proto3OptionalKnown)];
    #if defined(DEBUG) && DEBUG
      NSAssert(descriptor == nil, @"Startup recursed!");
    #endif  // DEBUG
    descriptor = localDescriptor;
  }
  return descriptor;
}

@end

#pragma mark - DeviceAuthSuccess

@implementation DeviceAuthSuccess

@dynamic userId;
@dynamic deviceId;
@dynamic hasDevice, device;
@dynamic captchaId;

typedef struct DeviceAuthSuccess__storage_ {
  uint32_t _has_storage_[1];
  NSString *userId;
  NSString *deviceId;
  Device *device;
  NSString *captchaId;
} DeviceAuthSuccess__storage_;

// This method is threadsafe because it is initially called
// in +initialize for each subclass.
+ (GPBDescriptor *)descriptor {
  static GPBDescriptor *descriptor = nil;
  if (!descriptor) {
    static GPBMessageFieldDescription fields[] = {
      {
        .name = "userId",
        .dataTypeSpecific.clazz = Nil,
        .number = DeviceAuthSuccess_FieldNumber_UserId,
        .hasIndex = 0,
        .offset = (uint32_t)offsetof(DeviceAuthSuccess__storage_, userId),
        .flags = (GPBFieldFlags)(GPBFieldOptional | GPBFieldClearHasIvarOnZero),
        .dataType = GPBDataTypeString,
      },
      {
        .name = "deviceId",
        .dataTypeSpecific.clazz = Nil,
        .number = DeviceAuthSuccess_FieldNumber_DeviceId,
        .hasIndex = 1,
        .offset = (uint32_t)offsetof(DeviceAuthSuccess__storage_, deviceId),
        .flags = (GPBFieldFlags)(GPBFieldOptional | GPBFieldClearHasIvarOnZero),
        .dataType = GPBDataTypeString,
      },
      {
        .name = "device",
        .dataTypeSpecific.clazz = GPBObjCClass(Device),
        .number = DeviceAuthSuccess_FieldNumber_Device,
        .hasIndex = 2,
        .offset = (uint32_t)offsetof(DeviceAuthSuccess__storage_, device),
        .flags = GPBFieldOptional,
        .dataType = GPBDataTypeMessage,
      },
      {
        .name = "captchaId",
        .dataTypeSpecific.clazz = Nil,
        .number = DeviceAuthSuccess_FieldNumber_CaptchaId,
        .hasIndex = 3,
        .offset = (uint32_t)offsetof(DeviceAuthSuccess__storage_, captchaId),
        .flags = (GPBFieldFlags)(GPBFieldOptional | GPBFieldClearHasIvarOnZero),
        .dataType = GPBDataTypeString,
      },
    };
    GPBDescriptor *localDescriptor =
        [GPBDescriptor allocDescriptorForClass:[DeviceAuthSuccess class]
                                     rootClass:[DevicePbRoot class]
                                          file:DevicePbRoot_FileDescriptor()
                                        fields:fields
                                    fieldCount:(uint32_t)(sizeof(fields) / sizeof(GPBMessageFieldDescription))
                                   storageSize:sizeof(DeviceAuthSuccess__storage_)
                                         flags:(GPBDescriptorInitializationFlags)(GPBDescriptorInitializationFlag_UsesClassRefs | GPBDescriptorInitializationFlag_Proto3OptionalKnown)];
    #if defined(DEBUG) && DEBUG
      NSAssert(descriptor == nil, @"Startup recursed!");
    #endif  // DEBUG
    descriptor = localDescriptor;
  }
  return descriptor;
}

@end

#pragma mark - DCheckResult

@implementation DCheckResult

@dynamic deviceExists;
@dynamic authRequired;
@dynamic limitExceeded;
@dynamic currentCount;
@dynamic maxCount;
@dynamic authTokenJwt;

typedef struct DCheckResult__storage_ {
  uint32_t _has_storage_[1];
  int32_t currentCount;
  int32_t maxCount;
  NSString *authTokenJwt;
} DCheckResult__storage_;

// This method is threadsafe because it is initially called
// in +initialize for each subclass.
+ (GPBDescriptor *)descriptor {
  static GPBDescriptor *descriptor = nil;
  if (!descriptor) {
    static GPBMessageFieldDescription fields[] = {
      {
        .name = "deviceExists",
        .dataTypeSpecific.clazz = Nil,
        .number = DCheckResult_FieldNumber_DeviceExists,
        .hasIndex = 0,
        .offset = 1,  // Stored in _has_storage_ to save space.
        .flags = (GPBFieldFlags)(GPBFieldOptional | GPBFieldClearHasIvarOnZero),
        .dataType = GPBDataTypeBool,
      },
      {
        .name = "authRequired",
        .dataTypeSpecific.clazz = Nil,
        .number = DCheckResult_FieldNumber_AuthRequired,
        .hasIndex = 2,
        .offset = 3,  // Stored in _has_storage_ to save space.
        .flags = (GPBFieldFlags)(GPBFieldOptional | GPBFieldClearHasIvarOnZero),
        .dataType = GPBDataTypeBool,
      },
      {
        .name = "limitExceeded",
        .dataTypeSpecific.clazz = Nil,
        .number = DCheckResult_FieldNumber_LimitExceeded,
        .hasIndex = 4,
        .offset = 5,  // Stored in _has_storage_ to save space.
        .flags = (GPBFieldFlags)(GPBFieldOptional | GPBFieldClearHasIvarOnZero),
        .dataType = GPBDataTypeBool,
      },
      {
        .name = "currentCount",
        .dataTypeSpecific.clazz = Nil,
        .number = DCheckResult_FieldNumber_CurrentCount,
        .hasIndex = 6,
        .offset = (uint32_t)offsetof(DCheckResult__storage_, currentCount),
        .flags = (GPBFieldFlags)(GPBFieldOptional | GPBFieldClearHasIvarOnZero),
        .dataType = GPBDataTypeInt32,
      },
      {
        .name = "maxCount",
        .dataTypeSpecific.clazz = Nil,
        .number = DCheckResult_FieldNumber_MaxCount,
        .hasIndex = 7,
        .offset = (uint32_t)offsetof(DCheckResult__storage_, maxCount),
        .flags = (GPBFieldFlags)(GPBFieldOptional | GPBFieldClearHasIvarOnZero),
        .dataType = GPBDataTypeInt32,
      },
      {
        .name = "authTokenJwt",
        .dataTypeSpecific.clazz = Nil,
        .number = DCheckResult_FieldNumber_AuthTokenJwt,
        .hasIndex = 8,
        .offset = (uint32_t)offsetof(DCheckResult__storage_, authTokenJwt),
        .flags = (GPBFieldFlags)(GPBFieldOptional | GPBFieldClearHasIvarOnZero),
        .dataType = GPBDataTypeString,
      },
    };
    GPBDescriptor *localDescriptor =
        [GPBDescriptor allocDescriptorForClass:[DCheckResult class]
                                     rootClass:[DevicePbRoot class]
                                          file:DevicePbRoot_FileDescriptor()
                                        fields:fields
                                    fieldCount:(uint32_t)(sizeof(fields) / sizeof(GPBMessageFieldDescription))
                                   storageSize:sizeof(DCheckResult__storage_)
                                         flags:(GPBDescriptorInitializationFlags)(GPBDescriptorInitializationFlag_UsesClassRefs | GPBDescriptorInitializationFlag_Proto3OptionalKnown)];
    #if defined(DEBUG) && DEBUG
      NSAssert(descriptor == nil, @"Startup recursed!");
    #endif  // DEBUG
    descriptor = localDescriptor;
  }
  return descriptor;
}

@end

#pragma mark - DeviceList

@implementation DeviceList

@dynamic devicesArray, devicesArray_Count;
@dynamic hasPage, page;

typedef struct DeviceList__storage_ {
  uint32_t _has_storage_[1];
  NSMutableArray *devicesArray;
  Page *page;
} DeviceList__storage_;

// This method is threadsafe because it is initially called
// in +initialize for each subclass.
+ (GPBDescriptor *)descriptor {
  static GPBDescriptor *descriptor = nil;
  if (!descriptor) {
    static GPBMessageFieldDescription fields[] = {
      {
        .name = "devicesArray",
        .dataTypeSpecific.clazz = GPBObjCClass(Device),
        .number = DeviceList_FieldNumber_DevicesArray,
        .hasIndex = GPBNoHasBit,
        .offset = (uint32_t)offsetof(DeviceList__storage_, devicesArray),
        .flags = GPBFieldRepeated,
        .dataType = GPBDataTypeMessage,
      },
      {
        .name = "page",
        .dataTypeSpecific.clazz = GPBObjCClass(Page),
        .number = DeviceList_FieldNumber_Page,
        .hasIndex = 0,
        .offset = (uint32_t)offsetof(DeviceList__storage_, page),
        .flags = GPBFieldOptional,
        .dataType = GPBDataTypeMessage,
      },
    };
    GPBDescriptor *localDescriptor =
        [GPBDescriptor allocDescriptorForClass:[DeviceList class]
                                     rootClass:[DevicePbRoot class]
                                          file:DevicePbRoot_FileDescriptor()
                                        fields:fields
                                    fieldCount:(uint32_t)(sizeof(fields) / sizeof(GPBMessageFieldDescription))
                                   storageSize:sizeof(DeviceList__storage_)
                                         flags:(GPBDescriptorInitializationFlags)(GPBDescriptorInitializationFlag_UsesClassRefs | GPBDescriptorInitializationFlag_Proto3OptionalKnown)];
    #if defined(DEBUG) && DEBUG
      NSAssert(descriptor == nil, @"Startup recursed!");
    #endif  // DEBUG
    descriptor = localDescriptor;
  }
  return descriptor;
}

@end

#pragma mark - UserInfo

@implementation UserInfo

@dynamic userId;
@dynamic hasDevice, device;

typedef struct UserInfo__storage_ {
  uint32_t _has_storage_[1];
  NSString *userId;
  Device *device;
} UserInfo__storage_;

// This method is threadsafe because it is initially called
// in +initialize for each subclass.
+ (GPBDescriptor *)descriptor {
  static GPBDescriptor *descriptor = nil;
  if (!descriptor) {
    static GPBMessageFieldDescription fields[] = {
      {
        .name = "userId",
        .dataTypeSpecific.clazz = Nil,
        .number = UserInfo_FieldNumber_UserId,
        .hasIndex = 0,
        .offset = (uint32_t)offsetof(UserInfo__storage_, userId),
        .flags = (GPBFieldFlags)(GPBFieldOptional | GPBFieldClearHasIvarOnZero),
        .dataType = GPBDataTypeString,
      },
      {
        .name = "device",
        .dataTypeSpecific.clazz = GPBObjCClass(Device),
        .number = UserInfo_FieldNumber_Device,
        .hasIndex = 1,
        .offset = (uint32_t)offsetof(UserInfo__storage_, device),
        .flags = GPBFieldOptional,
        .dataType = GPBDataTypeMessage,
      },
    };
    GPBDescriptor *localDescriptor =
        [GPBDescriptor allocDescriptorForClass:[UserInfo class]
                                     rootClass:[DevicePbRoot class]
                                          file:DevicePbRoot_FileDescriptor()
                                        fields:fields
                                    fieldCount:(uint32_t)(sizeof(fields) / sizeof(GPBMessageFieldDescription))
                                   storageSize:sizeof(UserInfo__storage_)
                                         flags:(GPBDescriptorInitializationFlags)(GPBDescriptorInitializationFlag_UsesClassRefs | GPBDescriptorInitializationFlag_Proto3OptionalKnown)];
    #if defined(DEBUG) && DEBUG
      NSAssert(descriptor == nil, @"Startup recursed!");
    #endif  // DEBUG
    descriptor = localDescriptor;
  }
  return descriptor;
}

@end

#pragma mark - GenerateQR

@implementation GenerateQR

@dynamic authTokenJwt;

typedef struct GenerateQR__storage_ {
  uint32_t _has_storage_[1];
  NSString *authTokenJwt;
} GenerateQR__storage_;

// This method is threadsafe because it is initially called
// in +initialize for each subclass.
+ (GPBDescriptor *)descriptor {
  static GPBDescriptor *descriptor = nil;
  if (!descriptor) {
    static GPBMessageFieldDescription fields[] = {
      {
        .name = "authTokenJwt",
        .dataTypeSpecific.clazz = Nil,
        .number = GenerateQR_FieldNumber_AuthTokenJwt,
        .hasIndex = 0,
        .offset = (uint32_t)offsetof(GenerateQR__storage_, authTokenJwt),
        .flags = (GPBFieldFlags)(GPBFieldOptional | GPBFieldClearHasIvarOnZero),
        .dataType = GPBDataTypeString,
      },
    };
    GPBDescriptor *localDescriptor =
        [GPBDescriptor allocDescriptorForClass:[GenerateQR class]
                                     rootClass:[DevicePbRoot class]
                                          file:DevicePbRoot_FileDescriptor()
                                        fields:fields
                                    fieldCount:(uint32_t)(sizeof(fields) / sizeof(GPBMessageFieldDescription))
                                   storageSize:sizeof(GenerateQR__storage_)
                                         flags:(GPBDescriptorInitializationFlags)(GPBDescriptorInitializationFlag_UsesClassRefs | GPBDescriptorInitializationFlag_Proto3OptionalKnown)];
    #if defined(DEBUG) && DEBUG
      NSAssert(descriptor == nil, @"Startup recursed!");
    #endif  // DEBUG
    descriptor = localDescriptor;
  }
  return descriptor;
}

@end

#pragma mark - QrCode

@implementation QrCode

@dynamic qrCodeJwt;
@dynamic expireSeconds;
@dynamic qrURL;

typedef struct QrCode__storage_ {
  uint32_t _has_storage_[1];
  int32_t expireSeconds;
  NSString *qrCodeJwt;
  NSString *qrURL;
} QrCode__storage_;

// This method is threadsafe because it is initially called
// in +initialize for each subclass.
+ (GPBDescriptor *)descriptor {
  static GPBDescriptor *descriptor = nil;
  if (!descriptor) {
    static GPBMessageFieldDescription fields[] = {
      {
        .name = "qrCodeJwt",
        .dataTypeSpecific.clazz = Nil,
        .number = QrCode_FieldNumber_QrCodeJwt,
        .hasIndex = 0,
        .offset = (uint32_t)offsetof(QrCode__storage_, qrCodeJwt),
        .flags = (GPBFieldFlags)(GPBFieldOptional | GPBFieldClearHasIvarOnZero),
        .dataType = GPBDataTypeString,
      },
      {
        .name = "expireSeconds",
        .dataTypeSpecific.clazz = Nil,
        .number = QrCode_FieldNumber_ExpireSeconds,
        .hasIndex = 1,
        .offset = (uint32_t)offsetof(QrCode__storage_, expireSeconds),
        .flags = (GPBFieldFlags)(GPBFieldOptional | GPBFieldClearHasIvarOnZero),
        .dataType = GPBDataTypeInt32,
      },
      {
        .name = "qrURL",
        .dataTypeSpecific.clazz = Nil,
        .number = QrCode_FieldNumber_QrURL,
        .hasIndex = 2,
        .offset = (uint32_t)offsetof(QrCode__storage_, qrURL),
        .flags = (GPBFieldFlags)(GPBFieldOptional | GPBFieldTextFormatNameCustom | GPBFieldClearHasIvarOnZero),
        .dataType = GPBDataTypeString,
      },
    };
    GPBDescriptor *localDescriptor =
        [GPBDescriptor allocDescriptorForClass:[QrCode class]
                                     rootClass:[DevicePbRoot class]
                                          file:DevicePbRoot_FileDescriptor()
                                        fields:fields
                                    fieldCount:(uint32_t)(sizeof(fields) / sizeof(GPBMessageFieldDescription))
                                   storageSize:sizeof(QrCode__storage_)
                                         flags:(GPBDescriptorInitializationFlags)(GPBDescriptorInitializationFlag_UsesClassRefs | GPBDescriptorInitializationFlag_Proto3OptionalKnown)];
#if !GPBOBJC_SKIP_MESSAGE_TEXTFORMAT_EXTRAS
    static const char *extraTextFormatInfo =
        "\001\003\002\241!!\000";
    [localDescriptor setupExtraTextInfo:extraTextFormatInfo];
#endif  // !GPBOBJC_SKIP_MESSAGE_TEXTFORMAT_EXTRAS
    #if defined(DEBUG) && DEBUG
      NSAssert(descriptor == nil, @"Startup recursed!");
    #endif  // DEBUG
    descriptor = localDescriptor;
  }
  return descriptor;
}

@end

#pragma mark - ScanQR

@implementation ScanQR

@dynamic qrCodeJwt;

typedef struct ScanQR__storage_ {
  uint32_t _has_storage_[1];
  NSString *qrCodeJwt;
} ScanQR__storage_;

// This method is threadsafe because it is initially called
// in +initialize for each subclass.
+ (GPBDescriptor *)descriptor {
  static GPBDescriptor *descriptor = nil;
  if (!descriptor) {
    static GPBMessageFieldDescription fields[] = {
      {
        .name = "qrCodeJwt",
        .dataTypeSpecific.clazz = Nil,
        .number = ScanQR_FieldNumber_QrCodeJwt,
        .hasIndex = 0,
        .offset = (uint32_t)offsetof(ScanQR__storage_, qrCodeJwt),
        .flags = (GPBFieldFlags)(GPBFieldOptional | GPBFieldClearHasIvarOnZero),
        .dataType = GPBDataTypeString,
      },
    };
    GPBDescriptor *localDescriptor =
        [GPBDescriptor allocDescriptorForClass:[ScanQR class]
                                     rootClass:[DevicePbRoot class]
                                          file:DevicePbRoot_FileDescriptor()
                                        fields:fields
                                    fieldCount:(uint32_t)(sizeof(fields) / sizeof(GPBMessageFieldDescription))
                                   storageSize:sizeof(ScanQR__storage_)
                                         flags:(GPBDescriptorInitializationFlags)(GPBDescriptorInitializationFlag_UsesClassRefs | GPBDescriptorInitializationFlag_Proto3OptionalKnown)];
    #if defined(DEBUG) && DEBUG
      NSAssert(descriptor == nil, @"Startup recursed!");
    #endif  // DEBUG
    descriptor = localDescriptor;
  }
  return descriptor;
}

@end

#pragma mark - SubmitCode

@implementation SubmitCode

@dynamic authTokenJwt;
@dynamic code;

typedef struct SubmitCode__storage_ {
  uint32_t _has_storage_[1];
  NSString *authTokenJwt;
  NSString *code;
} SubmitCode__storage_;

// This method is threadsafe because it is initially called
// in +initialize for each subclass.
+ (GPBDescriptor *)descriptor {
  static GPBDescriptor *descriptor = nil;
  if (!descriptor) {
    static GPBMessageFieldDescription fields[] = {
      {
        .name = "authTokenJwt",
        .dataTypeSpecific.clazz = Nil,
        .number = SubmitCode_FieldNumber_AuthTokenJwt,
        .hasIndex = 0,
        .offset = (uint32_t)offsetof(SubmitCode__storage_, authTokenJwt),
        .flags = (GPBFieldFlags)(GPBFieldOptional | GPBFieldClearHasIvarOnZero),
        .dataType = GPBDataTypeString,
      },
      {
        .name = "code",
        .dataTypeSpecific.clazz = Nil,
        .number = SubmitCode_FieldNumber_Code,
        .hasIndex = 1,
        .offset = (uint32_t)offsetof(SubmitCode__storage_, code),
        .flags = (GPBFieldFlags)(GPBFieldOptional | GPBFieldClearHasIvarOnZero),
        .dataType = GPBDataTypeString,
      },
    };
    GPBDescriptor *localDescriptor =
        [GPBDescriptor allocDescriptorForClass:[SubmitCode class]
                                     rootClass:[DevicePbRoot class]
                                          file:DevicePbRoot_FileDescriptor()
                                        fields:fields
                                    fieldCount:(uint32_t)(sizeof(fields) / sizeof(GPBMessageFieldDescription))
                                   storageSize:sizeof(SubmitCode__storage_)
                                         flags:(GPBDescriptorInitializationFlags)(GPBDescriptorInitializationFlag_UsesClassRefs | GPBDescriptorInitializationFlag_Proto3OptionalKnown)];
    #if defined(DEBUG) && DEBUG
      NSAssert(descriptor == nil, @"Startup recursed!");
    #endif  // DEBUG
    descriptor = localDescriptor;
  }
  return descriptor;
}

@end

#pragma mark - GetCode

@implementation GetCode

@dynamic authTokenJwt;

typedef struct GetCode__storage_ {
  uint32_t _has_storage_[1];
  NSString *authTokenJwt;
} GetCode__storage_;

// This method is threadsafe because it is initially called
// in +initialize for each subclass.
+ (GPBDescriptor *)descriptor {
  static GPBDescriptor *descriptor = nil;
  if (!descriptor) {
    static GPBMessageFieldDescription fields[] = {
      {
        .name = "authTokenJwt",
        .dataTypeSpecific.clazz = Nil,
        .number = GetCode_FieldNumber_AuthTokenJwt,
        .hasIndex = 0,
        .offset = (uint32_t)offsetof(GetCode__storage_, authTokenJwt),
        .flags = (GPBFieldFlags)(GPBFieldOptional | GPBFieldClearHasIvarOnZero),
        .dataType = GPBDataTypeString,
      },
    };
    GPBDescriptor *localDescriptor =
        [GPBDescriptor allocDescriptorForClass:[GetCode class]
                                     rootClass:[DevicePbRoot class]
                                          file:DevicePbRoot_FileDescriptor()
                                        fields:fields
                                    fieldCount:(uint32_t)(sizeof(fields) / sizeof(GPBMessageFieldDescription))
                                   storageSize:sizeof(GetCode__storage_)
                                         flags:(GPBDescriptorInitializationFlags)(GPBDescriptorInitializationFlag_UsesClassRefs | GPBDescriptorInitializationFlag_Proto3OptionalKnown)];
    #if defined(DEBUG) && DEBUG
      NSAssert(descriptor == nil, @"Startup recursed!");
    #endif  // DEBUG
    descriptor = localDescriptor;
  }
  return descriptor;
}

@end

#pragma mark - ConfirmCode

@implementation ConfirmCode

@dynamic authTokenJwt;
@dynamic confirmed;

typedef struct ConfirmCode__storage_ {
  uint32_t _has_storage_[1];
  NSString *authTokenJwt;
} ConfirmCode__storage_;

// This method is threadsafe because it is initially called
// in +initialize for each subclass.
+ (GPBDescriptor *)descriptor {
  static GPBDescriptor *descriptor = nil;
  if (!descriptor) {
    static GPBMessageFieldDescription fields[] = {
      {
        .name = "authTokenJwt",
        .dataTypeSpecific.clazz = Nil,
        .number = ConfirmCode_FieldNumber_AuthTokenJwt,
        .hasIndex = 0,
        .offset = (uint32_t)offsetof(ConfirmCode__storage_, authTokenJwt),
        .flags = (GPBFieldFlags)(GPBFieldOptional | GPBFieldClearHasIvarOnZero),
        .dataType = GPBDataTypeString,
      },
      {
        .name = "confirmed",
        .dataTypeSpecific.clazz = Nil,
        .number = ConfirmCode_FieldNumber_Confirmed,
        .hasIndex = 1,
        .offset = 2,  // Stored in _has_storage_ to save space.
        .flags = (GPBFieldFlags)(GPBFieldOptional | GPBFieldClearHasIvarOnZero),
        .dataType = GPBDataTypeBool,
      },
    };
    GPBDescriptor *localDescriptor =
        [GPBDescriptor allocDescriptorForClass:[ConfirmCode class]
                                     rootClass:[DevicePbRoot class]
                                          file:DevicePbRoot_FileDescriptor()
                                        fields:fields
                                    fieldCount:(uint32_t)(sizeof(fields) / sizeof(GPBMessageFieldDescription))
                                   storageSize:sizeof(ConfirmCode__storage_)
                                         flags:(GPBDescriptorInitializationFlags)(GPBDescriptorInitializationFlag_UsesClassRefs | GPBDescriptorInitializationFlag_Proto3OptionalKnown)];
    #if defined(DEBUG) && DEBUG
      NSAssert(descriptor == nil, @"Startup recursed!");
    #endif  // DEBUG
    descriptor = localDescriptor;
  }
  return descriptor;
}

@end

#pragma mark - AuthRequired

@implementation AuthRequired

@dynamic authTokenJwt;
@dynamic authMethod;
@dynamic expireMinutes;
@dynamic description_p;

typedef struct AuthRequired__storage_ {
  uint32_t _has_storage_[1];
  int32_t expireMinutes;
  NSString *authTokenJwt;
  NSString *authMethod;
  NSString *description_p;
} AuthRequired__storage_;

// This method is threadsafe because it is initially called
// in +initialize for each subclass.
+ (GPBDescriptor *)descriptor {
  static GPBDescriptor *descriptor = nil;
  if (!descriptor) {
    static GPBMessageFieldDescription fields[] = {
      {
        .name = "authTokenJwt",
        .dataTypeSpecific.clazz = Nil,
        .number = AuthRequired_FieldNumber_AuthTokenJwt,
        .hasIndex = 0,
        .offset = (uint32_t)offsetof(AuthRequired__storage_, authTokenJwt),
        .flags = (GPBFieldFlags)(GPBFieldOptional | GPBFieldClearHasIvarOnZero),
        .dataType = GPBDataTypeString,
      },
      {
        .name = "authMethod",
        .dataTypeSpecific.clazz = Nil,
        .number = AuthRequired_FieldNumber_AuthMethod,
        .hasIndex = 1,
        .offset = (uint32_t)offsetof(AuthRequired__storage_, authMethod),
        .flags = (GPBFieldFlags)(GPBFieldOptional | GPBFieldClearHasIvarOnZero),
        .dataType = GPBDataTypeString,
      },
      {
        .name = "expireMinutes",
        .dataTypeSpecific.clazz = Nil,
        .number = AuthRequired_FieldNumber_ExpireMinutes,
        .hasIndex = 2,
        .offset = (uint32_t)offsetof(AuthRequired__storage_, expireMinutes),
        .flags = (GPBFieldFlags)(GPBFieldOptional | GPBFieldClearHasIvarOnZero),
        .dataType = GPBDataTypeInt32,
      },
      {
        .name = "description_p",
        .dataTypeSpecific.clazz = Nil,
        .number = AuthRequired_FieldNumber_Description_p,
        .hasIndex = 3,
        .offset = (uint32_t)offsetof(AuthRequired__storage_, description_p),
        .flags = (GPBFieldFlags)(GPBFieldOptional | GPBFieldClearHasIvarOnZero),
        .dataType = GPBDataTypeString,
      },
    };
    GPBDescriptor *localDescriptor =
        [GPBDescriptor allocDescriptorForClass:[AuthRequired class]
                                     rootClass:[DevicePbRoot class]
                                          file:DevicePbRoot_FileDescriptor()
                                        fields:fields
                                    fieldCount:(uint32_t)(sizeof(fields) / sizeof(GPBMessageFieldDescription))
                                   storageSize:sizeof(AuthRequired__storage_)
                                         flags:(GPBDescriptorInitializationFlags)(GPBDescriptorInitializationFlag_UsesClassRefs | GPBDescriptorInitializationFlag_Proto3OptionalKnown)];
    #if defined(DEBUG) && DEBUG
      NSAssert(descriptor == nil, @"Startup recursed!");
    #endif  // DEBUG
    descriptor = localDescriptor;
  }
  return descriptor;
}

@end


#pragma clang diagnostic pop

// @@protoc_insertion_point(global_scope)
