// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: file_pb.proto

// This CPP symbol can be defined to use imports that match up to the framework
// imports needed when using CocoaPods.
#if !defined(GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS)
 #define GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS 0
#endif

#if GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS
 #import <Protobuf/GPBProtocolBuffers.h>
#else
 #import "GPBProtocolBuffers.h"
#endif

#if GOOGLE_PROTOBUF_OBJC_VERSION < 30004
#error This file was generated by a newer version of protoc which is incompatible with your Protocol Buffer library sources.
#endif
#if 30004 < GOOGLE_PROTOBUF_OBJC_MIN_SUPPORTED_VERSION
#error This file was generated by an older version of protoc which is incompatible with your Protocol Buffer library sources.
#endif

// @@protoc_insertion_point(imports)

#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wdeprecated-declarations"

CF_EXTERN_C_BEGIN

@class FChannel;
@class FChannelField;
@class Validation;

NS_ASSUME_NONNULL_BEGIN

#pragma mark - Enum BusinessModule

/**
 * ========== 枚举定义 ==========
 * 要存储的业务方向，和系统的业务模块没啥关系。主要是要明确相关的文件存储的规则
 **/
typedef GPB_ENUM(BusinessModule) {
  /**
   * Value used if any message's field encounters a value that is not defined
   * by this enum. The message will also have C functions to get/set the rawValue
   * of the field.
   **/
  BusinessModule_GPBUnrecognizedEnumeratorValue = kGPBUnrecognizedEnumeratorValue,
  /** 用户头像 */
  BusinessModule_Avatar = 0,

  /** 群头像 */
  BusinessModule_GroupAvatar = 1,

  /** 群图片 */
  BusinessModule_GroupImg = 2,

  /** 群视频 */
  BusinessModule_GroupVideo = 3,

  /** 群音频 */
  BusinessModule_GroupAudio = 4,

  /** 群文件 */
  BusinessModule_GroupFile = 5,

  /** 聊天图片 */
  BusinessModule_ChatImg = 6,

  /** 聊天视频 */
  BusinessModule_ChatVideo = 7,

  /** 聊天音频 */
  BusinessModule_ChatAudio = 8,

  /** 聊天文件 */
  BusinessModule_ChatFile = 9,

  /** 消息附件（通用） */
  BusinessModule_Message = 10,
};

GPBEnumDescriptor *BusinessModule_EnumDescriptor(void);

/**
 * Checks to see if the given value is defined by the enum or was not known at
 * the time this source was generated.
 **/
BOOL BusinessModule_IsValidValue(int32_t value);

#pragma mark - Enum OssProviderType

/** OSS提供商类型 */
typedef GPB_ENUM(OssProviderType) {
  /**
   * Value used if any message's field encounters a value that is not defined
   * by this enum. The message will also have C functions to get/set the rawValue
   * of the field.
   **/
  OssProviderType_GPBUnrecognizedEnumeratorValue = kGPBUnrecognizedEnumeratorValue,
  /** 阿里云OSS */
  OssProviderType_Aliyun = 0,

  /** 腾讯云COS */
  OssProviderType_Tencent = 1,

  /** AWS S3 */
  OssProviderType_Aws = 2,

  /** MinIO */
  OssProviderType_Minio = 3,

  /** 华为云OBS */
  OssProviderType_Huawei = 4,
};

GPBEnumDescriptor *OssProviderType_EnumDescriptor(void);

/**
 * Checks to see if the given value is defined by the enum or was not known at
 * the time this source was generated.
 **/
BOOL OssProviderType_IsValidValue(int32_t value);

#pragma mark - Enum HttpMethod

/** HTTP方法 */
typedef GPB_ENUM(HttpMethod) {
  /**
   * Value used if any message's field encounters a value that is not defined
   * by this enum. The message will also have C functions to get/set the rawValue
   * of the field.
   **/
  HttpMethod_GPBUnrecognizedEnumeratorValue = kGPBUnrecognizedEnumeratorValue,
  HttpMethod_Get = 0,
  HttpMethod_Post = 1,
  HttpMethod_Put = 2,
  HttpMethod_Delete = 3,
  HttpMethod_Patch = 4,
};

GPBEnumDescriptor *HttpMethod_EnumDescriptor(void);

/**
 * Checks to see if the given value is defined by the enum or was not known at
 * the time this source was generated.
 **/
BOOL HttpMethod_IsValidValue(int32_t value);

#pragma mark - Enum UploadMode

/** 上传模式 */
typedef GPB_ENUM(UploadMode) {
  /**
   * Value used if any message's field encounters a value that is not defined
   * by this enum. The message will also have C functions to get/set the rawValue
   * of the field.
   **/
  UploadMode_GPBUnrecognizedEnumeratorValue = kGPBUnrecognizedEnumeratorValue,
  /** 表单上传（兼容模式） */
  UploadMode_PostObject = 0,

  /** STS临时凭证通过SDK上传（推荐模式） */
  UploadMode_StsSdk = 1,

  /** Presigned URL上传 */
  UploadMode_PresignedURL = 2,
};

GPBEnumDescriptor *UploadMode_EnumDescriptor(void);

/**
 * Checks to see if the given value is defined by the enum or was not known at
 * the time this source was generated.
 **/
BOOL UploadMode_IsValidValue(int32_t value);

#pragma mark - Enum FieldType

/** 字段类型 */
typedef GPB_ENUM(FieldType) {
  /**
   * Value used if any message's field encounters a value that is not defined
   * by this enum. The message will also have C functions to get/set the rawValue
   * of the field.
   **/
  FieldType_GPBUnrecognizedEnumeratorValue = kGPBUnrecognizedEnumeratorValue,
  /** 字符串类型 */
  FieldType_String = 0,

  /** 整数类型 */
  FieldType_Integer = 1,

  /** 布尔类型 */
  FieldType_Boolean = 2,

  /** 密码类型（敏感字段） */
  FieldType_Password = 3,

  /** 文本类型（多行） */
  FieldType_Text = 4,
};

GPBEnumDescriptor *FieldType_EnumDescriptor(void);

/**
 * Checks to see if the given value is defined by the enum or was not known at
 * the time this source was generated.
 **/
BOOL FieldType_IsValidValue(int32_t value);

#pragma mark - FilePbRoot

/**
 * Exposes the extension registry for this file.
 *
 * The base class provides:
 * @code
 *   + (GPBExtensionRegistry *)extensionRegistry;
 * @endcode
 * which is a @c GPBExtensionRegistry that includes all the extensions defined by
 * this file and all files that it depends on.
 **/
GPB_FINAL @interface FilePbRoot : GPBRootObject
@end

#pragma mark - GetFChannels

typedef GPB_ENUM(GetFChannels_FieldNumber) {
  GetFChannels_FieldNumber_IncludeFields = 1,
};

/**
 * 获取渠道列表 - 查询操作
 **/
GPB_FINAL @interface GetFChannels : GPBMessage

/** 是否包含字段定义（可选，默认false） */
@property(nonatomic, readwrite) BOOL includeFields;

@end

#pragma mark - Prepare

typedef GPB_ENUM(Prepare_FieldNumber) {
  Prepare_FieldNumber_BusinessModule = 1,
  Prepare_FieldNumber_FileName = 2,
  Prepare_FieldNumber_FileSize = 3,
  Prepare_FieldNumber_ContentType = 4,
};

/**
 * 准备上传 - 操作对象
 **/
GPB_FINAL @interface Prepare : GPBMessage

/** 业务模块（必填） */
@property(nonatomic, readwrite) BusinessModule businessModule;

/** 文件名（必填） */
@property(nonatomic, readwrite, copy, null_resettable) NSString *fileName;

/** 文件大小（可选，字节） */
@property(nonatomic, readwrite) int64_t fileSize;

/** 文件MIME类型（可选） */
@property(nonatomic, readwrite, copy, null_resettable) NSString *contentType;

@end

/**
 * Fetches the raw value of a @c Prepare's @c businessModule property, even
 * if the value was not defined by the enum at the time the code was generated.
 **/
int32_t Prepare_BusinessModule_RawValue(Prepare *message);
/**
 * Sets the raw value of an @c Prepare's @c businessModule property, allowing
 * it to be set to a value that was not defined by the enum at the time the code
 * was generated.
 **/
void SetPrepare_BusinessModule_RawValue(Prepare *message, int32_t value);

#pragma mark - SwitchFChannel

typedef GPB_ENUM(SwitchFChannel_FieldNumber) {
  SwitchFChannel_FieldNumber_ChannelType = 1,
  SwitchFChannel_FieldNumber_OssConfig = 2,
};

/**
 * 切换渠道 - 操作对象
 **/
GPB_FINAL @interface SwitchFChannel : GPBMessage

/** 渠道类型（必填） */
@property(nonatomic, readwrite) OssProviderType channelType;

/** OSS配置JSON（必填，根据渠道fields定义） */
@property(nonatomic, readwrite, copy, null_resettable) NSString *ossConfig;

@end

/**
 * Fetches the raw value of a @c SwitchFChannel's @c channelType property, even
 * if the value was not defined by the enum at the time the code was generated.
 **/
int32_t SwitchFChannel_ChannelType_RawValue(SwitchFChannel *message);
/**
 * Sets the raw value of an @c SwitchFChannel's @c channelType property, allowing
 * it to be set to a value that was not defined by the enum at the time the code
 * was generated.
 **/
void SetSwitchFChannel_ChannelType_RawValue(SwitchFChannel *message, int32_t value);

#pragma mark - Token

typedef GPB_ENUM(Token_FieldNumber) {
  Token_FieldNumber_ProviderCode = 1,
  Token_FieldNumber_UploadURL = 2,
  Token_FieldNumber_Method = 3,
  Token_FieldNumber_Headers = 4,
  Token_FieldNumber_FormData = 5,
  Token_FieldNumber_FilePath = 6,
  Token_FieldNumber_FileURL = 7,
  Token_FieldNumber_ExpiresAt = 8,
  Token_FieldNumber_ExpiresIn = 9,
  Token_FieldNumber_UploadMode = 10,
  Token_FieldNumber_StsAccessKeyId = 11,
  Token_FieldNumber_StsAccessKeySecret = 12,
  Token_FieldNumber_StsSecurityToken = 13,
  Token_FieldNumber_StsExpiration = 14,
  Token_FieldNumber_BucketName = 15,
  Token_FieldNumber_Region = 16,
};

/**
 * 上传凭证
 **/
GPB_FINAL @interface Token : GPBMessage

/** 提供商类型 */
@property(nonatomic, readwrite) OssProviderType providerCode;

/** 上传URL */
@property(nonatomic, readwrite, copy, null_resettable) NSString *uploadURL;

/** HTTP方法 */
@property(nonatomic, readwrite) HttpMethod method;

/** HTTP头 */
@property(nonatomic, readwrite, strong, null_resettable) NSMutableDictionary<NSString*, NSString*> *headers;
/** The number of items in @c headers without causing the array to be created. */
@property(nonatomic, readonly) NSUInteger headers_Count;

/** 表单字段 */
@property(nonatomic, readwrite, strong, null_resettable) NSMutableDictionary<NSString*, NSString*> *formData;
/** The number of items in @c formData without causing the array to be created. */
@property(nonatomic, readonly) NSUInteger formData_Count;

/** 文件路径 */
@property(nonatomic, readwrite, copy, null_resettable) NSString *filePath;

/** 文件访问URL */
@property(nonatomic, readwrite, copy, null_resettable) NSString *fileURL;

/** 过期时间戳（Unix时间戳，秒） */
@property(nonatomic, readwrite) int64_t expiresAt;

/** 有效期（秒） */
@property(nonatomic, readwrite) int32_t expiresIn;

/** STS临时凭证相关字段（当upload_mode=STS_SDK时使用） */
@property(nonatomic, readwrite) UploadMode uploadMode;

/** STS临时访问密钥ID */
@property(nonatomic, readwrite, copy, null_resettable) NSString *stsAccessKeyId;

/** STS临时访问密钥Secret */
@property(nonatomic, readwrite, copy, null_resettable) NSString *stsAccessKeySecret;

/** STS安全令牌（Session Token） */
@property(nonatomic, readwrite, copy, null_resettable) NSString *stsSecurityToken;

/** STS过期时间（ISO 8601格式） */
@property(nonatomic, readwrite, copy, null_resettable) NSString *stsExpiration;

/** 存储桶名称 */
@property(nonatomic, readwrite, copy, null_resettable) NSString *bucketName;

/** 区域ID */
@property(nonatomic, readwrite, copy, null_resettable) NSString *region;

@end

/**
 * Fetches the raw value of a @c Token's @c providerCode property, even
 * if the value was not defined by the enum at the time the code was generated.
 **/
int32_t Token_ProviderCode_RawValue(Token *message);
/**
 * Sets the raw value of an @c Token's @c providerCode property, allowing
 * it to be set to a value that was not defined by the enum at the time the code
 * was generated.
 **/
void SetToken_ProviderCode_RawValue(Token *message, int32_t value);

/**
 * Fetches the raw value of a @c Token's @c method property, even
 * if the value was not defined by the enum at the time the code was generated.
 **/
int32_t Token_Method_RawValue(Token *message);
/**
 * Sets the raw value of an @c Token's @c method property, allowing
 * it to be set to a value that was not defined by the enum at the time the code
 * was generated.
 **/
void SetToken_Method_RawValue(Token *message, int32_t value);

/**
 * Fetches the raw value of a @c Token's @c uploadMode property, even
 * if the value was not defined by the enum at the time the code was generated.
 **/
int32_t Token_UploadMode_RawValue(Token *message);
/**
 * Sets the raw value of an @c Token's @c uploadMode property, allowing
 * it to be set to a value that was not defined by the enum at the time the code
 * was generated.
 **/
void SetToken_UploadMode_RawValue(Token *message, int32_t value);

#pragma mark - FChannelList

typedef GPB_ENUM(FChannelList_FieldNumber) {
  FChannelList_FieldNumber_ChannelsArray = 1,
  FChannelList_FieldNumber_DefaultChannelType = 2,
};

/**
 * 渠道列表
 **/
GPB_FINAL @interface FChannelList : GPBMessage

/** 渠道列表 */
@property(nonatomic, readwrite, strong, null_resettable) NSMutableArray<FChannel*> *channelsArray;
/** The number of items in @c channelsArray without causing the array to be created. */
@property(nonatomic, readonly) NSUInteger channelsArray_Count;

/** 默认渠道类型 */
@property(nonatomic, readwrite) OssProviderType defaultChannelType;

@end

/**
 * Fetches the raw value of a @c FChannelList's @c defaultChannelType property, even
 * if the value was not defined by the enum at the time the code was generated.
 **/
int32_t FChannelList_DefaultChannelType_RawValue(FChannelList *message);
/**
 * Sets the raw value of an @c FChannelList's @c defaultChannelType property, allowing
 * it to be set to a value that was not defined by the enum at the time the code
 * was generated.
 **/
void SetFChannelList_DefaultChannelType_RawValue(FChannelList *message, int32_t value);

#pragma mark - FChannel

typedef GPB_ENUM(FChannel_FieldNumber) {
  FChannel_FieldNumber_ChannelType = 1,
  FChannel_FieldNumber_ChannelName = 2,
  FChannel_FieldNumber_ChannelDescription = 3,
  FChannel_FieldNumber_ServiceClassName = 4,
  FChannel_FieldNumber_FieldsArray = 5,
  FChannel_FieldNumber_DefaultConfigJson = 6,
  FChannel_FieldNumber_IsSystem = 7,
  FChannel_FieldNumber_DisplayOrder = 8,
  FChannel_FieldNumber_IconURL = 9,
  FChannel_FieldNumber_DocumentationURL = 10,
};

/**
 * 渠道信息
 **/
GPB_FINAL @interface FChannel : GPBMessage

/** 渠道类型 */
@property(nonatomic, readwrite) OssProviderType channelType;

/** 渠道显示名称 */
@property(nonatomic, readwrite, copy, null_resettable) NSString *channelName;

/** 渠道描述 */
@property(nonatomic, readwrite, copy, null_resettable) NSString *channelDescription;

/** 服务实现类名 */
@property(nonatomic, readwrite, copy, null_resettable) NSString *serviceClassName;

/** 配置字段定义列表（可选） */
@property(nonatomic, readwrite, strong, null_resettable) NSMutableArray<FChannelField*> *fieldsArray;
/** The number of items in @c fieldsArray without causing the array to be created. */
@property(nonatomic, readonly) NSUInteger fieldsArray_Count;

/** 默认配置JSON字符串（可选） */
@property(nonatomic, readwrite, copy, null_resettable) NSString *defaultConfigJson;

/** 是否系统内置渠道 */
@property(nonatomic, readwrite) BOOL isSystem;

/** 显示顺序 */
@property(nonatomic, readwrite) int32_t displayOrder;

/** 图标URL（可选） */
@property(nonatomic, readwrite, copy, null_resettable) NSString *iconURL;

/** 文档链接（可选） */
@property(nonatomic, readwrite, copy, null_resettable) NSString *documentationURL;

@end

/**
 * Fetches the raw value of a @c FChannel's @c channelType property, even
 * if the value was not defined by the enum at the time the code was generated.
 **/
int32_t FChannel_ChannelType_RawValue(FChannel *message);
/**
 * Sets the raw value of an @c FChannel's @c channelType property, allowing
 * it to be set to a value that was not defined by the enum at the time the code
 * was generated.
 **/
void SetFChannel_ChannelType_RawValue(FChannel *message, int32_t value);

#pragma mark - FChannelField

typedef GPB_ENUM(FChannelField_FieldNumber) {
  FChannelField_FieldNumber_FieldName = 1,
  FChannelField_FieldNumber_FieldLabel = 2,
  FChannelField_FieldNumber_FieldType = 3,
  FChannelField_FieldNumber_FieldDescription = 4,
  FChannelField_FieldNumber_IsRequired = 5,
  FChannelField_FieldNumber_IsSensitive = 6,
  FChannelField_FieldNumber_DefaultValue = 7,
  FChannelField_FieldNumber_Placeholder = 8,
  FChannelField_FieldNumber_HelpText = 9,
  FChannelField_FieldNumber_DisplayOrder = 10,
  FChannelField_FieldNumber_Validation = 11,
};

/**
 * 渠道字段定义
 **/
GPB_FINAL @interface FChannelField : GPBMessage

/** 字段名 */
@property(nonatomic, readwrite, copy, null_resettable) NSString *fieldName;

/** 字段显示标签 */
@property(nonatomic, readwrite, copy, null_resettable) NSString *fieldLabel;

/** 字段类型 */
@property(nonatomic, readwrite) FieldType fieldType;

/** 字段描述 */
@property(nonatomic, readwrite, copy, null_resettable) NSString *fieldDescription;

/** 是否必填 */
@property(nonatomic, readwrite) BOOL isRequired;

/** 是否敏感字段 */
@property(nonatomic, readwrite) BOOL isSensitive;

/** 默认值（可选） */
@property(nonatomic, readwrite, copy, null_resettable) NSString *defaultValue;

/** 输入框占位符 */
@property(nonatomic, readwrite, copy, null_resettable) NSString *placeholder;

/** 帮助文本 */
@property(nonatomic, readwrite, copy, null_resettable) NSString *helpText;

/** 显示顺序 */
@property(nonatomic, readwrite) int32_t displayOrder;

/** 验证规则对象（可选） */
@property(nonatomic, readwrite, strong, null_resettable) Validation *validation;
/** Test to see if @c validation has been set. */
@property(nonatomic, readwrite) BOOL hasValidation;

@end

/**
 * Fetches the raw value of a @c FChannelField's @c fieldType property, even
 * if the value was not defined by the enum at the time the code was generated.
 **/
int32_t FChannelField_FieldType_RawValue(FChannelField *message);
/**
 * Sets the raw value of an @c FChannelField's @c fieldType property, allowing
 * it to be set to a value that was not defined by the enum at the time the code
 * was generated.
 **/
void SetFChannelField_FieldType_RawValue(FChannelField *message, int32_t value);

#pragma mark - Validation

typedef GPB_ENUM(Validation_FieldNumber) {
  Validation_FieldNumber_Regex = 1,
  Validation_FieldNumber_MinLength = 2,
  Validation_FieldNumber_MaxLength = 3,
  Validation_FieldNumber_MinValue = 4,
  Validation_FieldNumber_MaxValue = 5,
  Validation_FieldNumber_IsValid = 6,
  Validation_FieldNumber_ErrorMessage = 7,
};

/**
 * 字段验证规则
 **/
GPB_FINAL @interface Validation : GPBMessage

/** 验证正则表达式 */
@property(nonatomic, readwrite, copy, null_resettable) NSString *regex;

/** 最小长度 */
@property(nonatomic, readwrite) int32_t minLength;

/** 最大长度 */
@property(nonatomic, readwrite) int32_t maxLength;

/** 最小值（数值类型） */
@property(nonatomic, readwrite) double minValue;

/** 最大值（数值类型） */
@property(nonatomic, readwrite) double maxValue;

/** 验证是否通过（用于返回验证结果） */
@property(nonatomic, readwrite) BOOL isValid;

/** 错误消息（用于返回验证结果） */
@property(nonatomic, readwrite, copy, null_resettable) NSString *errorMessage;

@end

NS_ASSUME_NONNULL_END

CF_EXTERN_C_END

#pragma clang diagnostic pop

// @@protoc_insertion_point(global_scope)
