// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: cmty/group_pb.proto

// This CPP symbol can be defined to use imports that match up to the framework
// imports needed when using CocoaPods.
#if !defined(GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS)
 #define GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS 0
#endif

#if GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS
 #import <Protobuf/GPBProtocolBuffers.h>
#else
 #import "GPBProtocolBuffers.h"
#endif

#if GOOGLE_PROTOBUF_OBJC_VERSION < 30004
#error This file was generated by a newer version of protoc which is incompatible with your Protocol Buffer library sources.
#endif
#if 30004 < GOOGLE_PROTOBUF_OBJC_MIN_SUPPORTED_VERSION
#error This file was generated by an older version of protoc which is incompatible with your Protocol Buffer library sources.
#endif

// @@protoc_insertion_point(imports)

#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wdeprecated-declarations"

CF_EXTERN_C_BEGIN

@class Group;
@class GroupMember;
@class GroupPolicy;
@class ImMessage;
@class JoinRequest;
@class Page;

NS_ASSUME_NONNULL_BEGIN

#pragma mark - Enum GroupType

/** 群组类型枚举 - 定义群组的类型 */
typedef GPB_ENUM(GroupType) {
  /**
   * Value used if any message's field encounters a value that is not defined
   * by this enum. The message will also have C functions to get/set the rawValue
   * of the field.
   **/
  GroupType_GPBUnrecognizedEnumeratorValue = kGPBUnrecognizedEnumeratorValue,
  /** 普通群（默认值） */
  GroupType_Normal = 0,

  /** 超级群 */
  GroupType_Super = 1,
};

GPBEnumDescriptor *GroupType_EnumDescriptor(void);

/**
 * Checks to see if the given value is defined by the enum or was not known at
 * the time this source was generated.
 **/
BOOL GroupType_IsValidValue(int32_t value);

#pragma mark - Enum GroupStatus

/** 群组状态枚举 - 定义群组的状态 */
typedef GPB_ENUM(GroupStatus) {
  /**
   * Value used if any message's field encounters a value that is not defined
   * by this enum. The message will also have C functions to get/set the rawValue
   * of the field.
   **/
  GroupStatus_GPBUnrecognizedEnumeratorValue = kGPBUnrecognizedEnumeratorValue,
  /** 正常（默认值） */
  GroupStatus_Active = 0,

  /** 封禁 */
  GroupStatus_Ban = 1,

  /** 解散 */
  GroupStatus_Dissolved = 2,
};

GPBEnumDescriptor *GroupStatus_EnumDescriptor(void);

/**
 * Checks to see if the given value is defined by the enum or was not known at
 * the time this source was generated.
 **/
BOOL GroupStatus_IsValidValue(int32_t value);

#pragma mark - Enum JoinType

/** 加入方式枚举 - 定义加入群组的方式 */
typedef GPB_ENUM(JoinType) {
  /**
   * Value used if any message's field encounters a value that is not defined
   * by this enum. The message will also have C functions to get/set the rawValue
   * of the field.
   **/
  JoinType_GPBUnrecognizedEnumeratorValue = kGPBUnrecognizedEnumeratorValue,
  /** 邀请（默认值） */
  JoinType_Invite = 0,

  /** 申请 */
  JoinType_Apply = 1,

  /** 扫码 */
  JoinType_Scan = 2,
};

GPBEnumDescriptor *JoinType_EnumDescriptor(void);

/**
 * Checks to see if the given value is defined by the enum or was not known at
 * the time this source was generated.
 **/
BOOL JoinType_IsValidValue(int32_t value);

#pragma mark - Enum MemberStatus

/** 成员状态枚举 - 定义群组成员的状态 */
typedef GPB_ENUM(MemberStatus) {
  /**
   * Value used if any message's field encounters a value that is not defined
   * by this enum. The message will also have C functions to get/set the rawValue
   * of the field.
   **/
  MemberStatus_GPBUnrecognizedEnumeratorValue = kGPBUnrecognizedEnumeratorValue,
  /** 正常（默认值） */
  MemberStatus_MemberActive = 0,

  /** 被踢 */
  MemberStatus_Kicked = 1,

  /** 主动退出 */
  MemberStatus_Left = 2,
};

GPBEnumDescriptor *MemberStatus_EnumDescriptor(void);

/**
 * Checks to see if the given value is defined by the enum or was not known at
 * the time this source was generated.
 **/
BOOL MemberStatus_IsValidValue(int32_t value);

#pragma mark - Enum JoinRequestStatus

/** 加入申请状态枚举 - 定义加入申请的状态 */
typedef GPB_ENUM(JoinRequestStatus) {
  /**
   * Value used if any message's field encounters a value that is not defined
   * by this enum. The message will also have C functions to get/set the rawValue
   * of the field.
   **/
  JoinRequestStatus_GPBUnrecognizedEnumeratorValue = kGPBUnrecognizedEnumeratorValue,
  /** 待审批（默认值） */
  JoinRequestStatus_Pending = 0,

  /** 已通过 */
  JoinRequestStatus_Approved = 1,

  /** 已拒绝 */
  JoinRequestStatus_Rejected = 2,

  /** 已过期 */
  JoinRequestStatus_Expired = 3,

  /** 已取消 */
  JoinRequestStatus_Cancelled = 4,
};

GPBEnumDescriptor *JoinRequestStatus_EnumDescriptor(void);

/**
 * Checks to see if the given value is defined by the enum or was not known at
 * the time this source was generated.
 **/
BOOL JoinRequestStatus_IsValidValue(int32_t value);

#pragma mark - GroupPbRoot

/**
 * Exposes the extension registry for this file.
 *
 * The base class provides:
 * @code
 *   + (GPBExtensionRegistry *)extensionRegistry;
 * @endcode
 * which is a @c GPBExtensionRegistry that includes all the extensions defined by
 * this file and all files that it depends on.
 **/
GPB_FINAL @interface GroupPbRoot : GPBRootObject
@end

#pragma mark - Group

typedef GPB_ENUM(Group_FieldNumber) {
  Group_FieldNumber_GroupId = 1,
  Group_FieldNumber_GroupName = 2,
  Group_FieldNumber_GroupAvatar = 3,
  Group_FieldNumber_GroupAnnouncement = 4,
  Group_FieldNumber_GroupDescription = 5,
  Group_FieldNumber_GroupType = 6,
  Group_FieldNumber_MaxMemberCount = 7,
  Group_FieldNumber_CreatorUserId = 8,
  Group_FieldNumber_Status = 9,
  Group_FieldNumber_Policy = 11,
  Group_FieldNumber_CreatedAt = 12,
  Group_FieldNumber_UpdatedAt = 13,
  Group_FieldNumber_IsMember = 15,
  Group_FieldNumber_AvatarBg = 16,
};

/**
 * 群组信息 - 核心领域对象
 * 用于群组的基本信息存储和传输
 **/
GPB_FINAL @interface Group : GPBMessage

/** 群组ID（必填） */
@property(nonatomic, readwrite, copy, null_resettable) NSString *groupId;

/** 群组名称（必填） */
@property(nonatomic, readwrite, copy, null_resettable) NSString *groupName;

/** 群组头像URL（可选） */
@property(nonatomic, readwrite, copy, null_resettable) NSString *groupAvatar;

/** 群组头像背景色（可选，当group_avatar为空时使用，格式：#色值1 或 #色值1&#色值2） */
@property(nonatomic, readwrite, copy, null_resettable) NSString *avatarBg;

/** 群组公告（可选） */
@property(nonatomic, readwrite, copy, null_resettable) NSString *groupAnnouncement;

/** 群组描述（可选） */
@property(nonatomic, readwrite, copy, null_resettable) NSString *groupDescription;

/** 群组类型（必填） */
@property(nonatomic, readwrite) GroupType groupType;

/** 最大成员数（可选） */
@property(nonatomic, readwrite) int32_t maxMemberCount;

/** 创建者ID（必填） */
@property(nonatomic, readwrite, copy, null_resettable) NSString *creatorUserId;

/** 群组状态（必填） */
@property(nonatomic, readwrite) GroupStatus status;

/** 群组策略（可选） */
@property(nonatomic, readwrite, strong, null_resettable) GroupPolicy *policy;
/** Test to see if @c policy has been set. */
@property(nonatomic, readwrite) BOOL hasPolicy;

/** 创建时间（系统自动生成） */
@property(nonatomic, readwrite) int64_t createdAt;

/** 更新时间（系统自动更新） */
@property(nonatomic, readwrite) int64_t updatedAt;

/** 是否在群组中（可选） */
@property(nonatomic, readwrite) BOOL isMember;

@end

/**
 * Fetches the raw value of a @c Group's @c groupType property, even
 * if the value was not defined by the enum at the time the code was generated.
 **/
int32_t Group_GroupType_RawValue(Group *message);
/**
 * Sets the raw value of an @c Group's @c groupType property, allowing
 * it to be set to a value that was not defined by the enum at the time the code
 * was generated.
 **/
void SetGroup_GroupType_RawValue(Group *message, int32_t value);

/**
 * Fetches the raw value of a @c Group's @c status property, even
 * if the value was not defined by the enum at the time the code was generated.
 **/
int32_t Group_Status_RawValue(Group *message);
/**
 * Sets the raw value of an @c Group's @c status property, allowing
 * it to be set to a value that was not defined by the enum at the time the code
 * was generated.
 **/
void SetGroup_Status_RawValue(Group *message, int32_t value);

#pragma mark - GroupBrief

typedef GPB_ENUM(GroupBrief_FieldNumber) {
  GroupBrief_FieldNumber_GroupId = 1,
  GroupBrief_FieldNumber_GroupName = 2,
  GroupBrief_FieldNumber_GroupAvatar = 3,
  GroupBrief_FieldNumber_MemberCount = 4,
};

/**
 * 群组简要信息 - 结果对象
 * 用于消息搜索、会话列表等轻量展示场景（避免直接复用 Group 全量对象）
 **/
GPB_FINAL @interface GroupBrief : GPBMessage

/** 群组ID（必填） */
@property(nonatomic, readwrite, copy, null_resettable) NSString *groupId;

/** 群组名称（必填） */
@property(nonatomic, readwrite, copy, null_resettable) NSString *groupName;

/** 群组头像URL（可选） */
@property(nonatomic, readwrite, copy, null_resettable) NSString *groupAvatar;

/** 成员数量（可选） */
@property(nonatomic, readwrite) int32_t memberCount;

@end

#pragma mark - GroupPolicy

typedef GPB_ENUM(GroupPolicy_FieldNumber) {
  GroupPolicy_FieldNumber_NeedVerify = 1,
  GroupPolicy_FieldNumber_AllowInvite = 2,
  GroupPolicy_FieldNumber_AllowAddFriend = 3,
  GroupPolicy_FieldNumber_ShowMemberList = 4,
  GroupPolicy_FieldNumber_AllowPrivateChat = 5,
  GroupPolicy_FieldNumber_EnableAudioVideoCall = 6,
  GroupPolicy_FieldNumber_ShowHistoryMessage = 7,
  GroupPolicy_FieldNumber_ShowQrCode = 8,
  GroupPolicy_FieldNumber_MessageNotification = 9,
  GroupPolicy_FieldNumber_AllowSearchMember = 10,
  GroupPolicy_FieldNumber_SpeakIntervalSec = 11,
  GroupPolicy_FieldNumber_DisturbRolesArray = 12,
  GroupPolicy_FieldNumber_NotifyMemberThreshold = 13,
};

/**
 * 群组策略配置 - 群组策略对象
 * 用于群组的各种策略配置
 **/
GPB_FINAL @interface GroupPolicy : GPBMessage

/** 加群是否需要验证（可选） */
@property(nonatomic, readwrite) BOOL needVerify;

/** 是否允许邀请（可选） */
@property(nonatomic, readwrite) BOOL allowInvite;

/** 是否允许添加群内成员为好友（可选） */
@property(nonatomic, readwrite) BOOL allowAddFriend;

/** 群成员是否展示（可选） */
@property(nonatomic, readwrite) BOOL showMemberList;

/** 是否允许和群成员私聊（可选） */
@property(nonatomic, readwrite) BOOL allowPrivateChat;

/** 群内是否能够开启音视频通话功能（可选） */
@property(nonatomic, readwrite) BOOL enableAudioVideoCall;

/** 是否展示历史消息（可选） */
@property(nonatomic, readwrite) BOOL showHistoryMessage;

/** 是否展示二维码（可选） */
@property(nonatomic, readwrite) BOOL showQrCode;

/** 新消息通知开关（可选） */
@property(nonatomic, readwrite) BOOL messageNotification;

/** 是否允许搜索群成员（可选） */
@property(nonatomic, readwrite) BOOL allowSearchMember;

/** 发言间隔（秒）（可选） */
@property(nonatomic, readwrite) int32_t speakIntervalSec;

/** 被免打扰的角色列表（可选） */
@property(nonatomic, readwrite, strong, null_resettable) NSMutableArray<NSString*> *disturbRolesArray;
/** The number of items in @c disturbRolesArray without causing the array to be created. */
@property(nonatomic, readonly) NSUInteger disturbRolesArray_Count;

/** 推拉模式阈值（成员数 >= 阈值时使用NOTIFY模式，否则使用PUSH模式，默认0表示始终使用PUSH模式）（可选） */
@property(nonatomic, readwrite) int32_t notifyMemberThreshold;

@end

#pragma mark - GroupMember

typedef GPB_ENUM(GroupMember_FieldNumber) {
  GroupMember_FieldNumber_GroupId = 1,
  GroupMember_FieldNumber_UserId = 2,
  GroupMember_FieldNumber_MemberAlias = 3,
  GroupMember_FieldNumber_JoinType = 4,
  GroupMember_FieldNumber_JoinTime = 5,
  GroupMember_FieldNumber_InviterUserId = 6,
  GroupMember_FieldNumber_Status = 7,
  GroupMember_FieldNumber_DisturbUntil = 8,
  GroupMember_FieldNumber_IsAdmin = 9,
  GroupMember_FieldNumber_LastReadTime = 10,
  GroupMember_FieldNumber_RolesArray = 11,
};

/**
 * 群组成员信息 - 群组成员对象
 * 用于群组成员的基本信息存储和传输
 **/
GPB_FINAL @interface GroupMember : GPBMessage

/** 群组ID（必填） */
@property(nonatomic, readwrite, copy, null_resettable) NSString *groupId;

/** 用户ID（必填） */
@property(nonatomic, readwrite, copy, null_resettable) NSString *userId;

/** 群内昵称（可选） */
@property(nonatomic, readwrite, copy, null_resettable) NSString *memberAlias;

/** 加入方式（必填） */
@property(nonatomic, readwrite) JoinType joinType;

/** 加入时间（必填） */
@property(nonatomic, readwrite) int64_t joinTime;

/** 邀请人ID（可选） */
@property(nonatomic, readwrite, copy, null_resettable) NSString *inviterUserId;

/** 成员状态（必填） */
@property(nonatomic, readwrite) MemberStatus status;

/** 免打扰到期时间（可选） */
@property(nonatomic, readwrite) int64_t disturbUntil;

/** 是否管理员（可选） */
@property(nonatomic, readwrite) BOOL isAdmin;

/** 最后阅读时间（可选） */
@property(nonatomic, readwrite) int64_t lastReadTime;

/** 成员角色列表（可选） */
@property(nonatomic, readwrite, strong, null_resettable) NSMutableArray<NSString*> *rolesArray;
/** The number of items in @c rolesArray without causing the array to be created. */
@property(nonatomic, readonly) NSUInteger rolesArray_Count;

@end

/**
 * Fetches the raw value of a @c GroupMember's @c joinType property, even
 * if the value was not defined by the enum at the time the code was generated.
 **/
int32_t GroupMember_JoinType_RawValue(GroupMember *message);
/**
 * Sets the raw value of an @c GroupMember's @c joinType property, allowing
 * it to be set to a value that was not defined by the enum at the time the code
 * was generated.
 **/
void SetGroupMember_JoinType_RawValue(GroupMember *message, int32_t value);

/**
 * Fetches the raw value of a @c GroupMember's @c status property, even
 * if the value was not defined by the enum at the time the code was generated.
 **/
int32_t GroupMember_Status_RawValue(GroupMember *message);
/**
 * Sets the raw value of an @c GroupMember's @c status property, allowing
 * it to be set to a value that was not defined by the enum at the time the code
 * was generated.
 **/
void SetGroupMember_Status_RawValue(GroupMember *message, int32_t value);

#pragma mark - JoinRequest

typedef GPB_ENUM(JoinRequest_FieldNumber) {
  JoinRequest_FieldNumber_RequestId = 1,
  JoinRequest_FieldNumber_GroupId = 2,
  JoinRequest_FieldNumber_ApplicantId = 3,
  JoinRequest_FieldNumber_RequestMessage = 4,
  JoinRequest_FieldNumber_RequestTime = 5,
  JoinRequest_FieldNumber_ExpireTime = 6,
  JoinRequest_FieldNumber_Status = 7,
  JoinRequest_FieldNumber_ReviewerId = 8,
  JoinRequest_FieldNumber_ReviewTime = 9,
  JoinRequest_FieldNumber_ReviewMessage = 10,
};

/**
 * 加入申请记录 - 核心领域对象
 * 用于群组加入申请记录的存储和传输
 **/
GPB_FINAL @interface JoinRequest : GPBMessage

/** 申请ID（必填） */
@property(nonatomic, readwrite, copy, null_resettable) NSString *requestId;

/** 群组ID（必填） */
@property(nonatomic, readwrite, copy, null_resettable) NSString *groupId;

/** 申请人ID（必填） */
@property(nonatomic, readwrite, copy, null_resettable) NSString *applicantId;

/** 申请理由（可选） */
@property(nonatomic, readwrite, copy, null_resettable) NSString *requestMessage;

/** 申请时间戳（必填） */
@property(nonatomic, readwrite) int64_t requestTime;

/** 过期时间戳（可选） */
@property(nonatomic, readwrite) int64_t expireTime;

/** 申请状态（必填） */
@property(nonatomic, readwrite) JoinRequestStatus status;

/** 审批人ID（可选） */
@property(nonatomic, readwrite, copy, null_resettable) NSString *reviewerId;

/** 审批时间戳（可选） */
@property(nonatomic, readwrite) int64_t reviewTime;

/** 审批意见（可选） */
@property(nonatomic, readwrite, copy, null_resettable) NSString *reviewMessage;

@end

/**
 * Fetches the raw value of a @c JoinRequest's @c status property, even
 * if the value was not defined by the enum at the time the code was generated.
 **/
int32_t JoinRequest_Status_RawValue(JoinRequest *message);
/**
 * Sets the raw value of an @c JoinRequest's @c status property, allowing
 * it to be set to a value that was not defined by the enum at the time the code
 * was generated.
 **/
void SetJoinRequest_Status_RawValue(JoinRequest *message, int32_t value);

#pragma mark - getGroup

typedef GPB_ENUM(getGroup_FieldNumber) {
  getGroup_FieldNumber_GroupId = 1,
};

/**
 * 获取群组信息 - 查询操作
 * 用于获取指定群组的详细信息
 **/
GPB_FINAL @interface getGroup : GPBMessage

/** 群组ID（必填） */
@property(nonatomic, readwrite, copy, null_resettable) NSString *groupId;

@end

#pragma mark - listQuery

typedef GPB_ENUM(listQuery_FieldNumber) {
  listQuery_FieldNumber_GroupType = 1,
  listQuery_FieldNumber_Status = 2,
  listQuery_FieldNumber_Keyword = 3,
  listQuery_FieldNumber_Page = 4,
  listQuery_FieldNumber_GroupName = 5,
  listQuery_FieldNumber_StartTime = 6,
  listQuery_FieldNumber_EndTime = 7,
  listQuery_FieldNumber_GroupOwner = 8,
};

/**
 * 群组列表查询 - 查询操作
 * 用于分页查询群组列表
 **/
GPB_FINAL @interface listQuery : GPBMessage

/** 群组类型过滤（可选） */
@property(nonatomic, readwrite) GroupType groupType;

/** 群组状态过滤（可选） */
@property(nonatomic, readwrite) GroupStatus status;

@property(nonatomic, readwrite) BOOL hasStatus;
/** 搜索关键词（可选） */
@property(nonatomic, readwrite, copy, null_resettable) NSString *keyword;

/** 分页参数（使用系统类型） */
@property(nonatomic, readwrite, strong, null_resettable) Page *page;
/** Test to see if @c page has been set. */
@property(nonatomic, readwrite) BOOL hasPage;

/** 群组名称（可选） */
@property(nonatomic, readwrite, copy, null_resettable) NSString *groupName;
/** Test to see if @c groupName has been set. */
@property(nonatomic, readwrite) BOOL hasGroupName;

/** 查询时间起（可选） */
@property(nonatomic, readwrite) int64_t startTime;

@property(nonatomic, readwrite) BOOL hasStartTime;
/** 查询时间止（可选） */
@property(nonatomic, readwrite) int64_t endTime;

@property(nonatomic, readwrite) BOOL hasEndTime;
/** 群主名称（可选） */
@property(nonatomic, readwrite, copy, null_resettable) NSString *groupOwner;
/** Test to see if @c groupOwner has been set. */
@property(nonatomic, readwrite) BOOL hasGroupOwner;

@end

/**
 * Fetches the raw value of a @c listQuery's @c groupType property, even
 * if the value was not defined by the enum at the time the code was generated.
 **/
int32_t listQuery_GroupType_RawValue(listQuery *message);
/**
 * Sets the raw value of an @c listQuery's @c groupType property, allowing
 * it to be set to a value that was not defined by the enum at the time the code
 * was generated.
 **/
void SetlistQuery_GroupType_RawValue(listQuery *message, int32_t value);

/**
 * Fetches the raw value of a @c listQuery's @c status property, even
 * if the value was not defined by the enum at the time the code was generated.
 **/
int32_t listQuery_Status_RawValue(listQuery *message);
/**
 * Sets the raw value of an @c listQuery's @c status property, allowing
 * it to be set to a value that was not defined by the enum at the time the code
 * was generated.
 **/
void SetlistQuery_Status_RawValue(listQuery *message, int32_t value);

#pragma mark - membersQuery

typedef GPB_ENUM(membersQuery_FieldNumber) {
  membersQuery_FieldNumber_GroupId = 1,
  membersQuery_FieldNumber_Status = 2,
  membersQuery_FieldNumber_Page = 3,
};

/**
 * 群组成员查询 - 查询操作
 * 用于分页查询群组成员列表
 **/
GPB_FINAL @interface membersQuery : GPBMessage

/** 群组ID（必填） */
@property(nonatomic, readwrite, copy, null_resettable) NSString *groupId;

/** 成员状态过滤（可选） */
@property(nonatomic, readwrite) MemberStatus status;

/** 分页参数（使用系统类型） */
@property(nonatomic, readwrite, strong, null_resettable) Page *page;
/** Test to see if @c page has been set. */
@property(nonatomic, readwrite) BOOL hasPage;

@end

/**
 * Fetches the raw value of a @c membersQuery's @c status property, even
 * if the value was not defined by the enum at the time the code was generated.
 **/
int32_t membersQuery_Status_RawValue(membersQuery *message);
/**
 * Sets the raw value of an @c membersQuery's @c status property, allowing
 * it to be set to a value that was not defined by the enum at the time the code
 * was generated.
 **/
void SetmembersQuery_Status_RawValue(membersQuery *message, int32_t value);

#pragma mark - getGroupPolicy

typedef GPB_ENUM(getGroupPolicy_FieldNumber) {
  getGroupPolicy_FieldNumber_GroupId = 1,
};

/**
 * 群组策略查询 - 查询操作
 * 用于获取群组策略配置
 **/
GPB_FINAL @interface getGroupPolicy : GPBMessage

/** 群组ID（必填） */
@property(nonatomic, readwrite, copy, null_resettable) NSString *groupId;

@end

#pragma mark - checkPermission

typedef GPB_ENUM(checkPermission_FieldNumber) {
  checkPermission_FieldNumber_GroupId = 1,
  checkPermission_FieldNumber_UserId = 2,
  checkPermission_FieldNumber_Permission = 3,
};

/**
 * 权限检查 - 查询操作
 * 用于检查用户在群组中的权限
 **/
GPB_FINAL @interface checkPermission : GPBMessage

/** 群组ID（必填） */
@property(nonatomic, readwrite, copy, null_resettable) NSString *groupId;

/** 用户ID（必填） */
@property(nonatomic, readwrite, copy, null_resettable) NSString *userId;

/** 权限类型（必填，如: "speak", "invite", "kick"） */
@property(nonatomic, readwrite, copy, null_resettable) NSString *permission;

@end

#pragma mark - messageHistoryQuery

typedef GPB_ENUM(messageHistoryQuery_FieldNumber) {
  messageHistoryQuery_FieldNumber_GroupId = 1,
  messageHistoryQuery_FieldNumber_BeforeTime = 2,
  messageHistoryQuery_FieldNumber_AfterTime = 3,
  messageHistoryQuery_FieldNumber_Cursor = 4,
  messageHistoryQuery_FieldNumber_Page = 5,
};

/**
 * 群消息历史查询 - 查询操作
 * 用于分页查询群消息历史
 **/
GPB_FINAL @interface messageHistoryQuery : GPBMessage

/** 群组ID（必填） */
@property(nonatomic, readwrite, copy, null_resettable) NSString *groupId;

/** 查询此时间之前的消息（可选） */
@property(nonatomic, readwrite) int64_t beforeTime;

/** 查询此时间之后的消息（可选） */
@property(nonatomic, readwrite) int64_t afterTime;

/** 游标（可选） */
@property(nonatomic, readwrite, copy, null_resettable) NSString *cursor;

/** 分页参数（使用系统类型） */
@property(nonatomic, readwrite, strong, null_resettable) Page *page;
/** Test to see if @c page has been set. */
@property(nonatomic, readwrite) BOOL hasPage;

@end

#pragma mark - joinRequestQuery

typedef GPB_ENUM(joinRequestQuery_FieldNumber) {
  joinRequestQuery_FieldNumber_GroupId = 1,
  joinRequestQuery_FieldNumber_Status = 2,
  joinRequestQuery_FieldNumber_Page = 3,
};

/**
 * 加入申请列表查询 - 查询操作
 * 用于分页查询群组的加入申请列表
 **/
GPB_FINAL @interface joinRequestQuery : GPBMessage

/** 群组ID（必填） */
@property(nonatomic, readwrite, copy, null_resettable) NSString *groupId;

/** 申请状态（可选，默认PENDING） */
@property(nonatomic, readwrite) JoinRequestStatus status;

/** 分页参数（必填） */
@property(nonatomic, readwrite, strong, null_resettable) Page *page;
/** Test to see if @c page has been set. */
@property(nonatomic, readwrite) BOOL hasPage;

@end

/**
 * Fetches the raw value of a @c joinRequestQuery's @c status property, even
 * if the value was not defined by the enum at the time the code was generated.
 **/
int32_t joinRequestQuery_Status_RawValue(joinRequestQuery *message);
/**
 * Sets the raw value of an @c joinRequestQuery's @c status property, allowing
 * it to be set to a value that was not defined by the enum at the time the code
 * was generated.
 **/
void SetjoinRequestQuery_Status_RawValue(joinRequestQuery *message, int32_t value);

#pragma mark - disturbStatusQuery

typedef GPB_ENUM(disturbStatusQuery_FieldNumber) {
  disturbStatusQuery_FieldNumber_GroupId = 1,
  disturbStatusQuery_FieldNumber_UserId = 2,
};

/**
 * 免打扰状态查询 - 查询操作
 * 用于查询群组或成员的免打扰状态
 **/
GPB_FINAL @interface disturbStatusQuery : GPBMessage

/** 群组ID（必填） */
@property(nonatomic, readwrite, copy, null_resettable) NSString *groupId;

/** 用户ID（可选，不填则查询群组状态） */
@property(nonatomic, readwrite, copy, null_resettable) NSString *userId;

@end

#pragma mark - OnlineCount

typedef GPB_ENUM(OnlineCount_FieldNumber) {
  OnlineCount_FieldNumber_GroupId = 1,
  OnlineCount_FieldNumber_OnlineCount = 2,
  OnlineCount_FieldNumber_UpdatedAt = 3,
};

/**
 * 在线人数响应 - 结果对象
 * 用于返回群组在线人数
 **/
GPB_FINAL @interface OnlineCount : GPBMessage

/** 群组ID（返回字段） */
@property(nonatomic, readwrite, copy, null_resettable) NSString *groupId;

/** 在线人数（返回字段） */
@property(nonatomic, readwrite) int32_t onlineCount;

/** 更新时间（返回字段，时间戳毫秒） */
@property(nonatomic, readwrite) int64_t updatedAt;

@end

#pragma mark - CreateGroup

typedef GPB_ENUM(CreateGroup_FieldNumber) {
  CreateGroup_FieldNumber_GroupName = 1,
  CreateGroup_FieldNumber_GroupAvatar = 2,
  CreateGroup_FieldNumber_GroupDescription = 3,
  CreateGroup_FieldNumber_GroupType = 4,
  CreateGroup_FieldNumber_MaxMemberCount = 5,
  CreateGroup_FieldNumber_Policy = 6,
  CreateGroup_FieldNumber_InitialMembersArray = 7,
};

/**
 * 创建群组 - 操作对象
 * 用于创建新的群组
 **/
GPB_FINAL @interface CreateGroup : GPBMessage

/** 群组名称（必填） */
@property(nonatomic, readwrite, copy, null_resettable) NSString *groupName;

/** 群组头像URL（可选） */
@property(nonatomic, readwrite, copy, null_resettable) NSString *groupAvatar;

/** 群组描述（可选） */
@property(nonatomic, readwrite, copy, null_resettable) NSString *groupDescription;

/** 群组类型（必填） */
@property(nonatomic, readwrite) GroupType groupType;

/** 最大成员数（可选，默认500） */
@property(nonatomic, readwrite) int32_t maxMemberCount;

/** 群组策略（可选） */
@property(nonatomic, readwrite, strong, null_resettable) GroupPolicy *policy;
/** Test to see if @c policy has been set. */
@property(nonatomic, readwrite) BOOL hasPolicy;

/** 初始成员列表（可选） */
@property(nonatomic, readwrite, strong, null_resettable) NSMutableArray<NSString*> *initialMembersArray;
/** The number of items in @c initialMembersArray without causing the array to be created. */
@property(nonatomic, readonly) NSUInteger initialMembersArray_Count;

@end

/**
 * Fetches the raw value of a @c CreateGroup's @c groupType property, even
 * if the value was not defined by the enum at the time the code was generated.
 **/
int32_t CreateGroup_GroupType_RawValue(CreateGroup *message);
/**
 * Sets the raw value of an @c CreateGroup's @c groupType property, allowing
 * it to be set to a value that was not defined by the enum at the time the code
 * was generated.
 **/
void SetCreateGroup_GroupType_RawValue(CreateGroup *message, int32_t value);

#pragma mark - UpdateGroup

typedef GPB_ENUM(UpdateGroup_FieldNumber) {
  UpdateGroup_FieldNumber_GroupId = 1,
  UpdateGroup_FieldNumber_GroupName = 2,
  UpdateGroup_FieldNumber_GroupAvatar = 3,
  UpdateGroup_FieldNumber_GroupAnnouncement = 4,
  UpdateGroup_FieldNumber_GroupDescription = 5,
  UpdateGroup_FieldNumber_Policy = 6,
  UpdateGroup_FieldNumber_Version = 7,
};

/**
 * 更新群组信息 - 操作对象
 * 用于更新群组的基本信息
 **/
GPB_FINAL @interface UpdateGroup : GPBMessage

/** 群组ID（必填） */
@property(nonatomic, readwrite, copy, null_resettable) NSString *groupId;

/** 群组名称（可选） */
@property(nonatomic, readwrite, copy, null_resettable) NSString *groupName;

/** 群组头像URL（可选） */
@property(nonatomic, readwrite, copy, null_resettable) NSString *groupAvatar;

/** 群组公告（可选） */
@property(nonatomic, readwrite, copy, null_resettable) NSString *groupAnnouncement;

/** 群组描述（可选） */
@property(nonatomic, readwrite, copy, null_resettable) NSString *groupDescription;

/** 群组策略（可选） */
@property(nonatomic, readwrite, strong, null_resettable) GroupPolicy *policy;
/** Test to see if @c policy has been set. */
@property(nonatomic, readwrite) BOOL hasPolicy;

/** 乐观锁版本号（必填） */
@property(nonatomic, readwrite) int32_t version;

@end

#pragma mark - DissolveGroup

typedef GPB_ENUM(DissolveGroup_FieldNumber) {
  DissolveGroup_FieldNumber_GroupId = 1,
  DissolveGroup_FieldNumber_Reason = 2,
};

/**
 * 解散群组 - 操作对象
 * 用于解散群组
 **/
GPB_FINAL @interface DissolveGroup : GPBMessage

/** 群组ID（必填） */
@property(nonatomic, readwrite, copy, null_resettable) NSString *groupId;

/** 解散原因（可选） */
@property(nonatomic, readwrite, copy, null_resettable) NSString *reason;

@end

#pragma mark - AddMember

typedef GPB_ENUM(AddMember_FieldNumber) {
  AddMember_FieldNumber_GroupId = 1,
  AddMember_FieldNumber_UserIdsArray = 2,
  AddMember_FieldNumber_Reason = 3,
};

/**
 * 添加群成员 - 操作对象
 * 用于向群组添加成员
 **/
GPB_FINAL @interface AddMember : GPBMessage

/** 群组ID（必填） */
@property(nonatomic, readwrite, copy, null_resettable) NSString *groupId;

/** 用户ID列表（必填） */
@property(nonatomic, readwrite, strong, null_resettable) NSMutableArray<NSString*> *userIdsArray;
/** The number of items in @c userIdsArray without causing the array to be created. */
@property(nonatomic, readonly) NSUInteger userIdsArray_Count;

/** 邀请理由（可选） */
@property(nonatomic, readwrite, copy, null_resettable) NSString *reason;

@end

#pragma mark - RemoveMember

typedef GPB_ENUM(RemoveMember_FieldNumber) {
  RemoveMember_FieldNumber_GroupId = 1,
  RemoveMember_FieldNumber_UserIdsArray = 2,
  RemoveMember_FieldNumber_Reason = 3,
};

/**
 * 移除群成员 - 操作对象
 * 用于从群组移除成员
 **/
GPB_FINAL @interface RemoveMember : GPBMessage

/** 群组ID（必填） */
@property(nonatomic, readwrite, copy, null_resettable) NSString *groupId;

/** 用户ID列表（必填） */
@property(nonatomic, readwrite, strong, null_resettable) NSMutableArray<NSString*> *userIdsArray;
/** The number of items in @c userIdsArray without causing the array to be created. */
@property(nonatomic, readonly) NSUInteger userIdsArray_Count;

/** 移除理由（可选） */
@property(nonatomic, readwrite, copy, null_resettable) NSString *reason;

@end

#pragma mark - SetAlias

typedef GPB_ENUM(SetAlias_FieldNumber) {
  SetAlias_FieldNumber_GroupId = 1,
  SetAlias_FieldNumber_MemberAlias = 2,
};

/**
 * 设置群内昵称 - 操作对象
 * 用于用户修改自己在群内的昵称
 **/
GPB_FINAL @interface SetAlias : GPBMessage

/** 群组ID（必填） */
@property(nonatomic, readwrite, copy, null_resettable) NSString *groupId;

/** 群内昵称（必填，字符范围【2，50】） */
@property(nonatomic, readwrite, copy, null_resettable) NSString *memberAlias;

@end

#pragma mark - AssignRole

typedef GPB_ENUM(AssignRole_FieldNumber) {
  AssignRole_FieldNumber_GroupId = 1,
  AssignRole_FieldNumber_UserId = 2,
  AssignRole_FieldNumber_RolesArray = 3,
};

/**
 * 分配角色 - 操作对象
 * 用于为群成员分配角色
 **/
GPB_FINAL @interface AssignRole : GPBMessage

/** 群组ID（必填） */
@property(nonatomic, readwrite, copy, null_resettable) NSString *groupId;

/** 用户ID（必填） */
@property(nonatomic, readwrite, copy, null_resettable) NSString *userId;

/** 角色列表（必填） */
@property(nonatomic, readwrite, strong, null_resettable) NSMutableArray<NSString*> *rolesArray;
/** The number of items in @c rolesArray without causing the array to be created. */
@property(nonatomic, readonly) NSUInteger rolesArray_Count;

@end

#pragma mark - RevokeRole

typedef GPB_ENUM(RevokeRole_FieldNumber) {
  RevokeRole_FieldNumber_GroupId = 1,
  RevokeRole_FieldNumber_UserId = 2,
  RevokeRole_FieldNumber_RolesArray = 3,
};

/**
 * 撤销角色 - 操作对象
 * 用于撤销群成员的角色
 **/
GPB_FINAL @interface RevokeRole : GPBMessage

/** 群组ID（必填） */
@property(nonatomic, readwrite, copy, null_resettable) NSString *groupId;

/** 用户ID（必填） */
@property(nonatomic, readwrite, copy, null_resettable) NSString *userId;

/** 要撤销的角色列表（必填） */
@property(nonatomic, readwrite, strong, null_resettable) NSMutableArray<NSString*> *rolesArray;
/** The number of items in @c rolesArray without causing the array to be created. */
@property(nonatomic, readonly) NSUInteger rolesArray_Count;

@end

#pragma mark - SetGroupPolicy

typedef GPB_ENUM(SetGroupPolicy_FieldNumber) {
  SetGroupPolicy_FieldNumber_GroupId = 1,
  SetGroupPolicy_FieldNumber_Policy = 2,
};

/**
 * 设置群组策略 - 操作对象
 * 用于更新群组策略配置
 **/
GPB_FINAL @interface SetGroupPolicy : GPBMessage

/** 群组ID（必填） */
@property(nonatomic, readwrite, copy, null_resettable) NSString *groupId;

/** 群组策略（必填） */
@property(nonatomic, readwrite, strong, null_resettable) GroupPolicy *policy;
/** Test to see if @c policy has been set. */
@property(nonatomic, readwrite) BOOL hasPolicy;

@end

#pragma mark - Apply

typedef GPB_ENUM(Apply_FieldNumber) {
  Apply_FieldNumber_GroupId = 1,
  Apply_FieldNumber_RequestMessage = 2,
};

/**
 * 申请加入群组 - 操作对象
 * 用于申请加入群组
 **/
GPB_FINAL @interface Apply : GPBMessage

/** 群组ID（必填） */
@property(nonatomic, readwrite, copy, null_resettable) NSString *groupId;

/** 申请理由（可选） */
@property(nonatomic, readwrite, copy, null_resettable) NSString *requestMessage;

@end

#pragma mark - Approve

typedef GPB_ENUM(Approve_FieldNumber) {
  Approve_FieldNumber_GroupId = 1,
  Approve_FieldNumber_ApplicantId = 2,
  Approve_FieldNumber_ReviewMessage = 3,
};

/**
 * 审批加入申请 - 操作对象
 * 用于审批通过加入申请
 **/
GPB_FINAL @interface Approve : GPBMessage

/** 群组ID（必填） */
@property(nonatomic, readwrite, copy, null_resettable) NSString *groupId;

/** 申请人ID（必填） */
@property(nonatomic, readwrite, copy, null_resettable) NSString *applicantId;

/** 审批意见（可选） */
@property(nonatomic, readwrite, copy, null_resettable) NSString *reviewMessage;

@end

#pragma mark - Reject

typedef GPB_ENUM(Reject_FieldNumber) {
  Reject_FieldNumber_GroupId = 1,
  Reject_FieldNumber_ApplicantId = 2,
  Reject_FieldNumber_ReviewMessage = 3,
};

/**
 * 拒绝加入申请 - 操作对象
 * 用于拒绝加入申请
 **/
GPB_FINAL @interface Reject : GPBMessage

/** 群组ID（必填） */
@property(nonatomic, readwrite, copy, null_resettable) NSString *groupId;

/** 申请人ID（必填） */
@property(nonatomic, readwrite, copy, null_resettable) NSString *applicantId;

/** 拒绝理由（可选） */
@property(nonatomic, readwrite, copy, null_resettable) NSString *reviewMessage;

@end

#pragma mark - BanMember

typedef GPB_ENUM(BanMember_FieldNumber) {
  BanMember_FieldNumber_UserId = 1,
  BanMember_FieldNumber_BanUntil = 2,
  BanMember_FieldNumber_Reason = 3,
};

/**
 * 禁言成员 - 操作对象
 * 用于禁言/解禁群成员
 **/
GPB_FINAL @interface BanMember : GPBMessage

/** 用户ID（必填） */
@property(nonatomic, readwrite, copy, null_resettable) NSString *userId;

/** 禁言到期时间戳（可选，0或未设置表示解禁，>0表示临时禁言） */
@property(nonatomic, readwrite) int64_t banUntil;

/** 禁言理由（可选） */
@property(nonatomic, readwrite, copy, null_resettable) NSString *reason;

@end

#pragma mark - BatchBanMember

typedef GPB_ENUM(BatchBanMember_FieldNumber) {
  BatchBanMember_FieldNumber_UserIdsArray = 1,
  BatchBanMember_FieldNumber_BanUntil = 2,
  BatchBanMember_FieldNumber_Reason = 3,
};

/**
 * 批量禁言成员 - 操作对象
 * 用于批量禁言/解禁群成员
 **/
GPB_FINAL @interface BatchBanMember : GPBMessage

/** 用户ID列表（必填） */
@property(nonatomic, readwrite, strong, null_resettable) NSMutableArray<NSString*> *userIdsArray;
/** The number of items in @c userIdsArray without causing the array to be created. */
@property(nonatomic, readonly) NSUInteger userIdsArray_Count;

/** 禁言到期时间戳（可选，0或未设置表示解禁，>0表示临时禁言） */
@property(nonatomic, readwrite) int64_t banUntil;

/** 禁言理由（可选） */
@property(nonatomic, readwrite, copy, null_resettable) NSString *reason;

@end

#pragma mark - GroupMessageNotify

typedef GPB_ENUM(GroupMessageNotify_FieldNumber) {
  GroupMessageNotify_FieldNumber_Gid = 1,
  GroupMessageNotify_FieldNumber_Seq = 2,
  GroupMessageNotify_FieldNumber_Ts = 3,
};

/**
 * 群消息通知 - 领域对象
 * 用于NOTIFY模式的群消息通知（极简版，节省流量）
 **/
GPB_FINAL @interface GroupMessageNotify : GPBMessage

/** 群组ID（压缩字段名） */
@property(nonatomic, readwrite, copy, null_resettable) NSString *gid;

/** 消息序号 */
@property(nonatomic, readwrite) int64_t seq;

/** 时间戳（毫秒） */
@property(nonatomic, readwrite) int64_t ts;

@end

#pragma mark - MarkGroupMessageRead

typedef GPB_ENUM(MarkGroupMessageRead_FieldNumber) {
  MarkGroupMessageRead_FieldNumber_GroupId = 1,
  MarkGroupMessageRead_FieldNumber_MessageIdsArray = 2,
  MarkGroupMessageRead_FieldNumber_ReadTime = 3,
};

/**
 * 标记群消息已读 - 操作对象
 * 用于标记群消息为已读
 **/
GPB_FINAL @interface MarkGroupMessageRead : GPBMessage

/** 群组ID（必填） */
@property(nonatomic, readwrite, copy, null_resettable) NSString *groupId;

/** 消息ID列表（必填） */
@property(nonatomic, readwrite, strong, null_resettable) NSMutableArray<NSString*> *messageIdsArray;
/** The number of items in @c messageIdsArray without causing the array to be created. */
@property(nonatomic, readonly) NSUInteger messageIdsArray_Count;

/** 阅读时间（必填） */
@property(nonatomic, readwrite) int64_t readTime;

@end

#pragma mark - RecallGroupMessage

typedef GPB_ENUM(RecallGroupMessage_FieldNumber) {
  RecallGroupMessage_FieldNumber_GroupId = 1,
  RecallGroupMessage_FieldNumber_MessageId = 2,
  RecallGroupMessage_FieldNumber_Reason = 3,
};

/**
 * 撤回群消息 - 操作对象
 * 用于撤回群消息
 **/
GPB_FINAL @interface RecallGroupMessage : GPBMessage

/** 群组ID（必填） */
@property(nonatomic, readwrite, copy, null_resettable) NSString *groupId;

/** 消息ID（必填） */
@property(nonatomic, readwrite, copy, null_resettable) NSString *messageId;

/** 撤回原因（可选） */
@property(nonatomic, readwrite, copy, null_resettable) NSString *reason;

@end

#pragma mark - DeleteGroupMessage

typedef GPB_ENUM(DeleteGroupMessage_FieldNumber) {
  DeleteGroupMessage_FieldNumber_GroupId = 1,
  DeleteGroupMessage_FieldNumber_MessageId = 2,
  DeleteGroupMessage_FieldNumber_ForAll = 3,
};

/**
 * 删除群消息 - 操作对象
 * 用于删除群消息
 **/
GPB_FINAL @interface DeleteGroupMessage : GPBMessage

/** 群组ID（必填） */
@property(nonatomic, readwrite, copy, null_resettable) NSString *groupId;

/** 消息ID（必填） */
@property(nonatomic, readwrite, copy, null_resettable) NSString *messageId;

/** 是否为所有人删除（可选） */
@property(nonatomic, readwrite) BOOL forAll;

@end

#pragma mark - TransferOwner

typedef GPB_ENUM(TransferOwner_FieldNumber) {
  TransferOwner_FieldNumber_GroupId = 1,
  TransferOwner_FieldNumber_NewOwnerId = 2,
  TransferOwner_FieldNumber_KeepAsAdmin = 3,
  TransferOwner_FieldNumber_Reason = 4,
};

/**
 * 转让群主 - 操作对象
 * 用于转让群主身份
 **/
GPB_FINAL @interface TransferOwner : GPBMessage

/** 群组ID（必填） */
@property(nonatomic, readwrite, copy, null_resettable) NSString *groupId;

/** 新群主ID（必填） */
@property(nonatomic, readwrite, copy, null_resettable) NSString *newOwnerId NS_RETURNS_NOT_RETAINED;

/** 原群主是否保持管理员身份（可选，默认true） */
@property(nonatomic, readwrite) BOOL keepAsAdmin;

/** 转让理由（可选） */
@property(nonatomic, readwrite, copy, null_resettable) NSString *reason;

@end

#pragma mark - GPull

typedef GPB_ENUM(GPull_FieldNumber) {
  GPull_FieldNumber_LastSeq = 1,
  GPull_FieldNumber_Limit = 2,
};

/**
 * 单群组消息拉取 - 查询操作
 * 用于拉取指定群组的热数据消息
 **/
GPB_FINAL @interface GPull : GPBMessage

/** 最后序号（必填） */
@property(nonatomic, readwrite) int64_t lastSeq;

/** 拉取数量限制（可选，默认100，最大500） */
@property(nonatomic, readwrite) int32_t limit;

@end

#pragma mark - GPullList

typedef GPB_ENUM(GPullList_FieldNumber) {
  GPullList_FieldNumber_MessagesArray = 1,
  GPullList_FieldNumber_MaxSeq = 2,
  GPullList_FieldNumber_HasMore = 3,
  GPullList_FieldNumber_TotalCount = 4,
};

/**
 * 单群组消息拉取结果 - 结果对象
 * 用于返回单群组拉取的消息列表
 **/
GPB_FINAL @interface GPullList : GPBMessage

/** 消息列表 */
@property(nonatomic, readwrite, strong, null_resettable) NSMutableArray<ImMessage*> *messagesArray;
/** The number of items in @c messagesArray without causing the array to be created. */
@property(nonatomic, readonly) NSUInteger messagesArray_Count;

/** 最大序号 */
@property(nonatomic, readwrite) int64_t maxSeq;

/** 是否还有更多 */
@property(nonatomic, readwrite) BOOL hasMore;

/** 本次拉取的消息数量 */
@property(nonatomic, readwrite) int32_t totalCount;

@end

#pragma mark - GListPull

typedef GPB_ENUM(GListPull_FieldNumber) {
  GListPull_FieldNumber_Groups = 1,
  GListPull_FieldNumber_Limit = 2,
};

/**
 * 批量群组消息拉取 - 查询操作
 * 用于批量拉取多个群组的热数据消息
 **/
GPB_FINAL @interface GListPull : GPBMessage

/** groupId -> last_seq（必填） */
@property(nonatomic, readwrite, strong, null_resettable) GPBStringInt64Dictionary *groups;
/** The number of items in @c groups without causing the array to be created. */
@property(nonatomic, readonly) NSUInteger groups_Count;

/** 每个群组的拉取数量限制（可选，默认100，最大500） */
@property(nonatomic, readwrite) int32_t limit;

@end

#pragma mark - GListPullList

typedef GPB_ENUM(GListPullList_FieldNumber) {
  GListPullList_FieldNumber_MessagesArray = 1,
  GListPullList_FieldNumber_MaxSeqs = 2,
  GListPullList_FieldNumber_HasMore = 3,
  GListPullList_FieldNumber_TotalCount = 4,
  GListPullList_FieldNumber_ServerTime = 5,
};

/**
 * 批量群组消息拉取结果 - 结果对象
 * 用于返回批量拉取的消息列表
 **/
GPB_FINAL @interface GListPullList : GPBMessage

/** 扁平的消息列表（所有群组混合） */
@property(nonatomic, readwrite, strong, null_resettable) NSMutableArray<ImMessage*> *messagesArray;
/** The number of items in @c messagesArray without causing the array to be created. */
@property(nonatomic, readonly) NSUInteger messagesArray_Count;

/** groupId -> max_seq */
@property(nonatomic, readwrite, strong, null_resettable) GPBStringInt64Dictionary *maxSeqs;
/** The number of items in @c maxSeqs without causing the array to be created. */
@property(nonatomic, readonly) NSUInteger maxSeqs_Count;

/** groupId -> has_more */
@property(nonatomic, readwrite, strong, null_resettable) GPBStringBoolDictionary *hasMore;
/** The number of items in @c hasMore without causing the array to be created. */
@property(nonatomic, readonly) NSUInteger hasMore_Count;

/** 总消息数 */
@property(nonatomic, readwrite) int32_t totalCount;

/** 服务器时间戳 */
@property(nonatomic, readwrite) int64_t serverTime;

@end

#pragma mark - GList

typedef GPB_ENUM(GList_FieldNumber) {
  GList_FieldNumber_GroupsArray = 1,
  GList_FieldNumber_Page = 2,
};

/**
 * 群组列表 - 结果对象
 * 用于群组列表查询的响应
 **/
GPB_FINAL @interface GList : GPBMessage

/** 群组列表 */
@property(nonatomic, readwrite, strong, null_resettable) NSMutableArray<Group*> *groupsArray;
/** The number of items in @c groupsArray without causing the array to be created. */
@property(nonatomic, readonly) NSUInteger groupsArray_Count;

/** 分页元数据（使用系统类型） */
@property(nonatomic, readwrite, strong, null_resettable) Page *page;
/** Test to see if @c page has been set. */
@property(nonatomic, readwrite) BOOL hasPage;

@end

#pragma mark - members

typedef GPB_ENUM(members_FieldNumber) {
  members_FieldNumber_MembersArray = 1,
  members_FieldNumber_Page = 2,
};

/**
 * 群组成员列表 - 结果对象
 * 用于群组成员列表查询的响应
 **/
GPB_FINAL @interface members : GPBMessage

/** 成员列表（按加群时间排序，最先加群的在前面） */
@property(nonatomic, readwrite, strong, null_resettable) NSMutableArray<GroupMember*> *membersArray;
/** The number of items in @c membersArray without causing the array to be created. */
@property(nonatomic, readonly) NSUInteger membersArray_Count;

/** 分页元数据（使用系统类型） */
@property(nonatomic, readwrite, strong, null_resettable) Page *page;
/** Test to see if @c page has been set. */
@property(nonatomic, readwrite) BOOL hasPage;

@end

#pragma mark - GCheckResult

typedef GPB_ENUM(GCheckResult_FieldNumber) {
  GCheckResult_FieldNumber_Allowed = 1,
  GCheckResult_FieldNumber_Reason = 2,
};

/**
 * 权限检查结果 - 结果对象
 * 用于权限检查的响应
 **/
GPB_FINAL @interface GCheckResult : GPBMessage

/** 是否允许 */
@property(nonatomic, readwrite) BOOL allowed;

/** 不允许的原因（可选） */
@property(nonatomic, readwrite, copy, null_resettable) NSString *reason;

@end

#pragma mark - messageHistory

typedef GPB_ENUM(messageHistory_FieldNumber) {
  messageHistory_FieldNumber_MessagesArray = 1,
  messageHistory_FieldNumber_Page = 2,
};

/**
 * 群消息历史 - 结果对象
 * 用于群消息历史查询的响应
 **/
GPB_FINAL @interface messageHistory : GPBMessage

/** 消息列表（使用统一的 ImMessage） */
@property(nonatomic, readwrite, strong, null_resettable) NSMutableArray<ImMessage*> *messagesArray;
/** The number of items in @c messagesArray without causing the array to be created. */
@property(nonatomic, readonly) NSUInteger messagesArray_Count;

/** 分页元数据（使用系统类型） */
@property(nonatomic, readwrite, strong, null_resettable) Page *page;
/** Test to see if @c page has been set. */
@property(nonatomic, readwrite) BOOL hasPage;

@end

#pragma mark - joinRequestList

typedef GPB_ENUM(joinRequestList_FieldNumber) {
  joinRequestList_FieldNumber_RequestsArray = 1,
  joinRequestList_FieldNumber_Page = 2,
};

/**
 * 加入申请列表 - 结果对象
 * 用于加入申请列表查询的响应
 **/
GPB_FINAL @interface joinRequestList : GPBMessage

/** 申请列表 */
@property(nonatomic, readwrite, strong, null_resettable) NSMutableArray<JoinRequest*> *requestsArray;
/** The number of items in @c requestsArray without causing the array to be created. */
@property(nonatomic, readonly) NSUInteger requestsArray_Count;

/** 分页元数据（使用系统类型） */
@property(nonatomic, readwrite, strong, null_resettable) Page *page;
/** Test to see if @c page has been set. */
@property(nonatomic, readwrite) BOOL hasPage;

@end

#pragma mark - DisturbStatus

typedef GPB_ENUM(DisturbStatus_FieldNumber) {
  DisturbStatus_FieldNumber_IsGroupDisturbed = 1,
  DisturbStatus_FieldNumber_IsMemberDisturbed = 2,
  DisturbStatus_FieldNumber_DisturbUntil = 3,
  DisturbStatus_FieldNumber_DisturbReason = 4,
  DisturbStatus_FieldNumber_CanSpeak = 5,
};

/**
 * 免打扰状态信息 - 领域对象
 * 用于免打扰状态查询的响应
 **/
GPB_FINAL @interface DisturbStatus : GPBMessage

/** 群组是否全员免打扰（必填） */
@property(nonatomic, readwrite) BOOL isGroupDisturbed;

/** 成员是否被免打扰（必填） */
@property(nonatomic, readwrite) BOOL isMemberDisturbed;

/** 免打扰到期时间戳（可选，0表示未免打扰或已过期） */
@property(nonatomic, readwrite) int64_t disturbUntil;

/** 免打扰原因（可选） */
@property(nonatomic, readwrite, copy, null_resettable) NSString *disturbReason;

/** 是否可以发言（必填，综合判断结果） */
@property(nonatomic, readwrite) BOOL canSpeak;

@end

#pragma mark - GroupSearchResult

typedef GPB_ENUM(GroupSearchResult_FieldNumber) {
  GroupSearchResult_FieldNumber_GroupsArray = 1,
  GroupSearchResult_FieldNumber_MatchedMembersArray = 2,
  GroupSearchResult_FieldNumber_Page = 3,
};

/**
 * 群组搜索结果 - 结果对象
 * 用于群组搜索的响应
 **/
GPB_FINAL @interface GroupSearchResult : GPBMessage

/** 群组列表（返回字段） */
@property(nonatomic, readwrite, strong, null_resettable) NSMutableArray<Group*> *groupsArray;
/** The number of items in @c groupsArray without causing the array to be created. */
@property(nonatomic, readonly) NSUInteger groupsArray_Count;

/** 匹配的成员信息（返回字段，用于显示"包含: 王大锤"） */
@property(nonatomic, readwrite, strong, null_resettable) NSMutableArray<GroupMember*> *matchedMembersArray;
/** The number of items in @c matchedMembersArray without causing the array to be created. */
@property(nonatomic, readonly) NSUInteger matchedMembersArray_Count;

/** 分页元数据（返回字段，使用系统类型） */
@property(nonatomic, readwrite, strong, null_resettable) Page *page;
/** Test to see if @c page has been set. */
@property(nonatomic, readwrite) BOOL hasPage;

@end

#pragma mark - GroupPreview

typedef GPB_ENUM(GroupPreview_FieldNumber) {
  GroupPreview_FieldNumber_GroupId = 1,
  GroupPreview_FieldNumber_GroupName = 2,
  GroupPreview_FieldNumber_GroupAvatar = 3,
  GroupPreview_FieldNumber_Status = 4,
  GroupPreview_FieldNumber_IsCreater = 5,
  GroupPreview_FieldNumber_MemberAlias = 6,
  GroupPreview_FieldNumber_IsMember = 7,
  GroupPreview_FieldNumber_IsDisturbed = 8,
  GroupPreview_FieldNumber_IsBanned = 9,
  GroupPreview_FieldNumber_AvatarBg = 10,
};

/**
 * 群组预览 - 结果对象
 * 用于群组预览查询的响应
 * 如果成员不在群，只返回群组ID、群组名称、群组头像和状态
 * 如果成员在群，返回完整的预览信息
 **/
GPB_FINAL @interface GroupPreview : GPBMessage

/** 群组ID（必填） */
@property(nonatomic, readwrite, copy, null_resettable) NSString *groupId;

/** 群组名称（可选） */
@property(nonatomic, readwrite, copy, null_resettable) NSString *groupName;

/** 群组头像URL（可选） */
@property(nonatomic, readwrite, copy, null_resettable) NSString *groupAvatar;

/** 群组头像背景色（可选，当group_avatar为空时使用，格式：#色值1 或 #色值1&#色值2） */
@property(nonatomic, readwrite, copy, null_resettable) NSString *avatarBg;

/** 群组状态（必填） */
@property(nonatomic, readwrite) GroupStatus status;

/** 是否是群主（可选，仅成员在群时返回） */
@property(nonatomic, readwrite) BOOL isCreater;

/** 查询人在群的昵称（可选，仅成员在群时返回） */
@property(nonatomic, readwrite, copy, null_resettable) NSString *memberAlias;

/** 查询人是否在群（必填） */
@property(nonatomic, readwrite) BOOL isMember;

/** 查询人是否开启免打扰（可选，仅成员在群时返回） */
@property(nonatomic, readwrite) BOOL isDisturbed;

/** 查询人是否被禁言（可选，仅成员在群时返回） */
@property(nonatomic, readwrite) BOOL isBanned;

@end

/**
 * Fetches the raw value of a @c GroupPreview's @c status property, even
 * if the value was not defined by the enum at the time the code was generated.
 **/
int32_t GroupPreview_Status_RawValue(GroupPreview *message);
/**
 * Sets the raw value of an @c GroupPreview's @c status property, allowing
 * it to be set to a value that was not defined by the enum at the time the code
 * was generated.
 **/
void SetGroupPreview_Status_RawValue(GroupPreview *message, int32_t value);

#pragma mark - MarkGroupMessageStateRead

typedef GPB_ENUM(MarkGroupMessageStateRead_FieldNumber) {
  MarkGroupMessageStateRead_FieldNumber_GroupId = 1,
  MarkGroupMessageStateRead_FieldNumber_MemberId = 2,
  MarkGroupMessageStateRead_FieldNumber_ReadSeq = 3,
};

/**
 * 标记消息状态已读请求（用于群组消息状态管理）
 **/
GPB_FINAL @interface MarkGroupMessageStateRead : GPBMessage

/** 群组ID */
@property(nonatomic, readwrite, copy, null_resettable) NSString *groupId;

/** 群成员ID（自己） */
@property(nonatomic, readwrite, copy, null_resettable) NSString *memberId;

/** 已读序号 */
@property(nonatomic, readwrite) int64_t readSeq;

@end

NS_ASSUME_NONNULL_END

CF_EXTERN_C_END

#pragma clang diagnostic pop

// @@protoc_insertion_point(global_scope)
