// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: system_pb.proto

// This CPP symbol can be defined to use imports that match up to the framework
// imports needed when using CocoaPods.
#if !defined(GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS)
 #define GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS 0
#endif

#if GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS
 #import <Protobuf/GPBProtocolBuffers.h>
#else
 #import "GPBProtocolBuffers.h"
#endif

#if GOOGLE_PROTOBUF_OBJC_VERSION < 30004
#error This file was generated by a newer version of protoc which is incompatible with your Protocol Buffer library sources.
#endif
#if 30004 < GOOGLE_PROTOBUF_OBJC_MIN_SUPPORTED_VERSION
#error This file was generated by an older version of protoc which is incompatible with your Protocol Buffer library sources.
#endif

// @@protoc_insertion_point(imports)

#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wdeprecated-declarations"

CF_EXTERN_C_BEGIN

@class AreaCode;

NS_ASSUME_NONNULL_BEGIN

#pragma mark - Enum ConversationType

/** 会话类型（单聊/群聊/系统/社区） */
typedef GPB_ENUM(ConversationType) {
  /**
   * Value used if any message's field encounters a value that is not defined
   * by this enum. The message will also have C functions to get/set the rawValue
   * of the field.
   **/
  ConversationType_GPBUnrecognizedEnumeratorValue = kGPBUnrecognizedEnumeratorValue,
  /** 查询所有类型（protobuf 要求第一个值必须是 0） */
  ConversationType_All = 0,

  /** 单聊 */
  ConversationType_Single = 1,

  /** 群聊 */
  ConversationType_Group = 2,

  /** 系统 */
  ConversationType_System = 3,

  /** 社区 */
  ConversationType_Community = 4,
};

GPBEnumDescriptor *ConversationType_EnumDescriptor(void);

/**
 * Checks to see if the given value is defined by the enum or was not known at
 * the time this source was generated.
 **/
BOOL ConversationType_IsValidValue(int32_t value);

#pragma mark - SystemPbRoot

/**
 * Exposes the extension registry for this file.
 *
 * The base class provides:
 * @code
 *   + (GPBExtensionRegistry *)extensionRegistry;
 * @endcode
 * which is a @c GPBExtensionRegistry that includes all the extensions defined by
 * this file and all files that it depends on.
 **/
GPB_FINAL @interface SystemPbRoot : GPBRootObject
@end

#pragma mark - ConfigResp

typedef GPB_ENUM(ConfigResp_FieldNumber) {
  ConfigResp_FieldNumber_Data_p = 1,
};

/**
 * 配置响应对象
 **/
GPB_FINAL @interface ConfigResp : GPBMessage

@property(nonatomic, readwrite, strong, null_resettable) NSMutableDictionary<NSString*, NSString*> *data_p;
/** The number of items in @c data_p without causing the array to be created. */
@property(nonatomic, readonly) NSUInteger data_p_Count;

@end

#pragma mark - Error

typedef GPB_ENUM(Error_FieldNumber) {
  Error_FieldNumber_Code = 1,
  Error_FieldNumber_Message = 2,
  Error_FieldNumber_PlaceholdersArray = 3,
};

/**
 * 错误响应对象
 **/
GPB_FINAL @interface Error : GPBMessage

/** 错误码，例如 400、500 等 */
@property(nonatomic, readwrite) int32_t code;

/** 错误描述模板 */
@property(nonatomic, readwrite, copy, null_resettable) NSString *message;

/** 占位符列表，用于在客户端做动态替换 */
@property(nonatomic, readwrite, strong, null_resettable) NSMutableArray<NSString*> *placeholdersArray;
/** The number of items in @c placeholdersArray without causing the array to be created. */
@property(nonatomic, readonly) NSUInteger placeholdersArray_Count;

@end

#pragma mark - EmptyResponse

/**
 * 通用空响应 - 用于所有业务模块的成功响应
 **/
GPB_FINAL @interface EmptyResponse : GPBMessage

@end

#pragma mark - Page

typedef GPB_ENUM(Page_FieldNumber) {
  Page_FieldNumber_Page = 1,
  Page_FieldNumber_Size = 2,
  Page_FieldNumber_SortField = 3,
  Page_FieldNumber_SortOrder = 4,
  Page_FieldNumber_TotalCount = 5,
  Page_FieldNumber_TotalPages = 6,
  Page_FieldNumber_HasPrevious = 7,
  Page_FieldNumber_HasNext = 8,
};

/**
 * 通用分页对象
 **/
GPB_FINAL @interface Page : GPBMessage

/** 页码（从1开始） */
@property(nonatomic, readwrite) int32_t page;

/** 每页大小 */
@property(nonatomic, readwrite) int32_t size;

/** 排序字段（可选） */
@property(nonatomic, readwrite, copy, null_resettable) NSString *sortField;

/** 排序方向：ASC/DESC（可选，默认ASC） */
@property(nonatomic, readwrite, copy, null_resettable) NSString *sortOrder;

/** 总记录数 */
@property(nonatomic, readwrite) int32_t totalCount;

/** 总页数 */
@property(nonatomic, readwrite) int32_t totalPages;

/** 是否有上一页 */
@property(nonatomic, readwrite) BOOL hasPrevious;

/** 是否有下一页 */
@property(nonatomic, readwrite) BOOL hasNext;

@end

#pragma mark - QueryErrorCode

typedef GPB_ENUM(QueryErrorCode_FieldNumber) {
  QueryErrorCode_FieldNumber_Code = 1,
};

/**
 * 错误码查询 - 查询操作
 **/
GPB_FINAL @interface QueryErrorCode : GPBMessage

/** 完整错误码 */
@property(nonatomic, readwrite) int32_t code;

@end

#pragma mark - ErrorCodeDetail

typedef GPB_ENUM(ErrorCodeDetail_FieldNumber) {
  ErrorCodeDetail_FieldNumber_Code = 1,
  ErrorCodeDetail_FieldNumber_BizModelCode = 2,
  ErrorCodeDetail_FieldNumber_BizModelDesc = 3,
  ErrorCodeDetail_FieldNumber_ModuleCode = 4,
  ErrorCodeDetail_FieldNumber_ModuleDesc = 5,
  ErrorCodeDetail_FieldNumber_DetailCode = 6,
  ErrorCodeDetail_FieldNumber_DetailDesc = 7,
  ErrorCodeDetail_FieldNumber_FullMessage = 8,
  ErrorCodeDetail_FieldNumber_Found = 9,
};

/**
 * 错误码详情 - 查询结果
 **/
GPB_FINAL @interface ErrorCodeDetail : GPBMessage

/** 完整错误码 */
@property(nonatomic, readwrite) int32_t code;

/** 业务模型码（MMM，3位，第三位占位） */
@property(nonatomic, readwrite) int32_t bizModelCode;

/** 业务模型描述 */
@property(nonatomic, readwrite, copy, null_resettable) NSString *bizModelDesc;

/** 模块码（PP，2位） */
@property(nonatomic, readwrite) int32_t moduleCode;

/** 模块描述 */
@property(nonatomic, readwrite, copy, null_resettable) NSString *moduleDesc;

/** 详细错误码（SSS，3位） */
@property(nonatomic, readwrite) int32_t detailCode;

/** 详细错误描述 */
@property(nonatomic, readwrite, copy, null_resettable) NSString *detailDesc;

/** 完整错误消息（格式：业务模型-模块-详细错误） */
@property(nonatomic, readwrite, copy, null_resettable) NSString *fullMessage;

/** 是否找到错误码 */
@property(nonatomic, readwrite) BOOL found;

@end

#pragma mark - Param

typedef GPB_ENUM(Param_FieldNumber) {
  Param_FieldNumber_Param = 1,
};

/**
 * 通用参数请求 - 用于所有只需要一个字符串参数的请求（可以是各种ID）
 **/
GPB_FINAL @interface Param : GPBMessage

/** 参数值（必填，具体含义由方法上下文决定，如community_id、channel_id等） */
@property(nonatomic, readwrite, copy, null_resettable) NSString *param;

@end

#pragma mark - BParam

typedef GPB_ENUM(BParam_FieldNumber) {
  BParam_FieldNumber_Param = 1,
};

/**
 * 通用参数请求 - 用于所有只需要一个字符串参数的请求（布尔类型）
 **/
GPB_FINAL @interface BParam : GPBMessage

/** 参数值（必填，switch、Exist 等） */
@property(nonatomic, readwrite) BOOL param;

@end

#pragma mark - AreaCode

typedef GPB_ENUM(AreaCode_FieldNumber) {
  AreaCode_FieldNumber_Code = 1,
  AreaCode_FieldNumber_CountryCode = 2,
  AreaCode_FieldNumber_CountryName = 3,
  AreaCode_FieldNumber_CountryNameEn = 4,
  AreaCode_FieldNumber_Flag = 5,
  AreaCode_FieldNumber_PhoneLength = 6,
  AreaCode_FieldNumber_PhonePattern = 7,
};

/**
 * 区号信息
 **/
GPB_FINAL @interface AreaCode : GPBMessage

/** 区号，如 +86 */
@property(nonatomic, readwrite, copy, null_resettable) NSString *code;

/** 国家代码，如 CN */
@property(nonatomic, readwrite, copy, null_resettable) NSString *countryCode;

/** 国家名称，如 中国 */
@property(nonatomic, readwrite, copy, null_resettable) NSString *countryName;

/** 国家名称（英文） */
@property(nonatomic, readwrite, copy, null_resettable) NSString *countryNameEn;

/** 国旗emoji，如 🇨🇳 */
@property(nonatomic, readwrite, copy, null_resettable) NSString *flag;

/** 手机号长度（可选） */
@property(nonatomic, readwrite) int32_t phoneLength;

/** 手机号格式正则表达式（可选） */
@property(nonatomic, readwrite, copy, null_resettable) NSString *phonePattern;

@end

#pragma mark - AreaCodeList

typedef GPB_ENUM(AreaCodeList_FieldNumber) {
  AreaCodeList_FieldNumber_AreaCodesArray = 1,
};

/**
 * 区号列表响应
 **/
GPB_FINAL @interface AreaCodeList : GPBMessage

/** 区号列表 */
@property(nonatomic, readwrite, strong, null_resettable) NSMutableArray<AreaCode*> *areaCodesArray;
/** The number of items in @c areaCodesArray without causing the array to be created. */
@property(nonatomic, readonly) NSUInteger areaCodesArray_Count;

@end

#pragma mark - IpLocationRequest

typedef GPB_ENUM(IpLocationRequest_FieldNumber) {
  IpLocationRequest_FieldNumber_Ip = 1,
};

/**
 * IP定位请求
 **/
GPB_FINAL @interface IpLocationRequest : GPBMessage

/** IP地址（可选，如果不提供则从连接上下文获取） */
@property(nonatomic, readwrite, copy, null_resettable) NSString *ip;

@end

#pragma mark - IpLocationResponse

typedef GPB_ENUM(IpLocationResponse_FieldNumber) {
  IpLocationResponse_FieldNumber_Ip = 1,
  IpLocationResponse_FieldNumber_AreaCode = 2,
  IpLocationResponse_FieldNumber_CountryCode = 3,
  IpLocationResponse_FieldNumber_CountryName = 4,
  IpLocationResponse_FieldNumber_CountryNameEn = 5,
  IpLocationResponse_FieldNumber_Flag = 6,
  IpLocationResponse_FieldNumber_Region = 7,
  IpLocationResponse_FieldNumber_City = 8,
  IpLocationResponse_FieldNumber_Found = 9,
};

/**
 * IP定位响应
 **/
GPB_FINAL @interface IpLocationResponse : GPBMessage

/** IP地址 */
@property(nonatomic, readwrite, copy, null_resettable) NSString *ip;

/** 区号，如 +86 */
@property(nonatomic, readwrite, copy, null_resettable) NSString *areaCode;

/** 国家代码，如 CN */
@property(nonatomic, readwrite, copy, null_resettable) NSString *countryCode;

/** 国家名称，如 中国 */
@property(nonatomic, readwrite, copy, null_resettable) NSString *countryName;

/** 国家名称（英文） */
@property(nonatomic, readwrite, copy, null_resettable) NSString *countryNameEn;

/** 国旗emoji，如 🇨🇳 */
@property(nonatomic, readwrite, copy, null_resettable) NSString *flag;

/** 地区信息（可选） */
@property(nonatomic, readwrite, copy, null_resettable) NSString *region;

/** 城市信息（可选） */
@property(nonatomic, readwrite, copy, null_resettable) NSString *city;

/** 是否找到定位信息 */
@property(nonatomic, readwrite) BOOL found;

@end

NS_ASSUME_NONNULL_END

CF_EXTERN_C_END

#pragma clang diagnostic pop

// @@protoc_insertion_point(global_scope)
