// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: chat_pb.proto

// This CPP symbol can be defined to use imports that match up to the framework
// imports needed when using CocoaPods.
#if !defined(GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS)
 #define GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS 0
#endif

#if GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS
 #import <Protobuf/GPBProtocolBuffers_RuntimeSupport.h>
#else
 #import "GPBProtocolBuffers_RuntimeSupport.h"
#endif

#import "ChatPb.pbobjc.h"
#import "MessagePb.pbobjc.h"
#import "ConvPb.pbobjc.h"
#import "SystemPb.pbobjc.h"
// @@protoc_insertion_point(imports)

#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wdeprecated-declarations"
#pragma clang diagnostic ignored "-Wdollar-in-identifier-extension"

#pragma mark - Objective C Class declarations
// Forward declarations of Objective C classes that we can use as
// static values in struct initializers.
// We don't use [Foo class] because it is not a static value.
GPBObjCClassDeclaration(AtMeMessage);
GPBObjCClassDeclaration(AtMeUnreadCountResult);
GPBObjCClassDeclaration(ContactSearchResult);
GPBObjCClassDeclaration(GroupMemberSearchResult);
GPBObjCClassDeclaration(GroupSearchResult);
GPBObjCClassDeclaration(ImMessage);
GPBObjCClassDeclaration(Page);

#pragma mark - ChatPbRoot

@implementation ChatPbRoot

// No extensions in the file and none of the imports (direct or indirect)
// defined extensions, so no need to generate +extensionRegistry.

@end

#pragma mark - ChatPbRoot_FileDescriptor

static GPBFileDescriptor *ChatPbRoot_FileDescriptor(void) {
  // This is called by +initialize so there is no need to worry
  // about thread safety of the singleton.
  static GPBFileDescriptor *descriptor = NULL;
  if (!descriptor) {
    GPB_DEBUG_CHECK_RUNTIME_VERSIONS();
    descriptor = [[GPBFileDescriptor alloc] initWithPackage:@"im.chat"
                                                     syntax:GPBFileSyntaxProto3];
  }
  return descriptor;
}

#pragma mark - Search

@implementation Search

@dynamic keyword;
@dynamic convType;
@dynamic fromUserId;
@dynamic startTimeMs;
@dynamic endTimeMs;
@dynamic hasPage, page;
@dynamic convId;

typedef struct Search__storage_ {
  uint32_t _has_storage_[1];
  ConversationType convType;
  NSString *keyword;
  Page *page;
  NSString *fromUserId;
  NSString *convId;
  int64_t startTimeMs;
  int64_t endTimeMs;
} Search__storage_;

// This method is threadsafe because it is initially called
// in +initialize for each subclass.
+ (GPBDescriptor *)descriptor {
  static GPBDescriptor *descriptor = nil;
  if (!descriptor) {
    static GPBMessageFieldDescription fields[] = {
      {
        .name = "keyword",
        .dataTypeSpecific.clazz = Nil,
        .number = Search_FieldNumber_Keyword,
        .hasIndex = 0,
        .offset = (uint32_t)offsetof(Search__storage_, keyword),
        .flags = (GPBFieldFlags)(GPBFieldOptional | GPBFieldClearHasIvarOnZero),
        .dataType = GPBDataTypeString,
      },
      {
        .name = "convType",
        .dataTypeSpecific.enumDescFunc = ConversationType_EnumDescriptor,
        .number = Search_FieldNumber_ConvType,
        .hasIndex = 1,
        .offset = (uint32_t)offsetof(Search__storage_, convType),
        .flags = (GPBFieldFlags)(GPBFieldOptional | GPBFieldHasEnumDescriptor | GPBFieldClearHasIvarOnZero),
        .dataType = GPBDataTypeEnum,
      },
      {
        .name = "page",
        .dataTypeSpecific.clazz = GPBObjCClass(Page),
        .number = Search_FieldNumber_Page,
        .hasIndex = 5,
        .offset = (uint32_t)offsetof(Search__storage_, page),
        .flags = GPBFieldOptional,
        .dataType = GPBDataTypeMessage,
      },
      {
        .name = "fromUserId",
        .dataTypeSpecific.clazz = Nil,
        .number = Search_FieldNumber_FromUserId,
        .hasIndex = 2,
        .offset = (uint32_t)offsetof(Search__storage_, fromUserId),
        .flags = (GPBFieldFlags)(GPBFieldOptional | GPBFieldClearHasIvarOnZero),
        .dataType = GPBDataTypeString,
      },
      {
        .name = "startTimeMs",
        .dataTypeSpecific.clazz = Nil,
        .number = Search_FieldNumber_StartTimeMs,
        .hasIndex = 3,
        .offset = (uint32_t)offsetof(Search__storage_, startTimeMs),
        .flags = (GPBFieldFlags)(GPBFieldOptional | GPBFieldClearHasIvarOnZero),
        .dataType = GPBDataTypeInt64,
      },
      {
        .name = "endTimeMs",
        .dataTypeSpecific.clazz = Nil,
        .number = Search_FieldNumber_EndTimeMs,
        .hasIndex = 4,
        .offset = (uint32_t)offsetof(Search__storage_, endTimeMs),
        .flags = (GPBFieldFlags)(GPBFieldOptional | GPBFieldClearHasIvarOnZero),
        .dataType = GPBDataTypeInt64,
      },
      {
        .name = "convId",
        .dataTypeSpecific.clazz = Nil,
        .number = Search_FieldNumber_ConvId,
        .hasIndex = 6,
        .offset = (uint32_t)offsetof(Search__storage_, convId),
        .flags = (GPBFieldFlags)(GPBFieldOptional | GPBFieldClearHasIvarOnZero),
        .dataType = GPBDataTypeString,
      },
    };
    GPBDescriptor *localDescriptor =
        [GPBDescriptor allocDescriptorForClass:[Search class]
                                     rootClass:[ChatPbRoot class]
                                          file:ChatPbRoot_FileDescriptor()
                                        fields:fields
                                    fieldCount:(uint32_t)(sizeof(fields) / sizeof(GPBMessageFieldDescription))
                                   storageSize:sizeof(Search__storage_)
                                         flags:(GPBDescriptorInitializationFlags)(GPBDescriptorInitializationFlag_UsesClassRefs | GPBDescriptorInitializationFlag_Proto3OptionalKnown)];
    #if defined(DEBUG) && DEBUG
      NSAssert(descriptor == nil, @"Startup recursed!");
    #endif  // DEBUG
    descriptor = localDescriptor;
  }
  return descriptor;
}

@end

int32_t Search_ConvType_RawValue(Search *message) {
  GPBDescriptor *descriptor = [Search descriptor];
  GPBFieldDescriptor *field = [descriptor fieldWithNumber:Search_FieldNumber_ConvType];
  return GPBGetMessageRawEnumField(message, field);
}

void SetSearch_ConvType_RawValue(Search *message, int32_t value) {
  GPBDescriptor *descriptor = [Search descriptor];
  GPBFieldDescriptor *field = [descriptor fieldWithNumber:Search_FieldNumber_ConvType];
  GPBSetMessageRawEnumField(message, field, value);
}

#pragma mark - SearchResult

@implementation SearchResult

@dynamic messagesArray, messagesArray_Count;
@dynamic hasPage, page;
@dynamic contactResultsArray, contactResultsArray_Count;
@dynamic groupResultsArray, groupResultsArray_Count;
@dynamic memberResultsArray, memberResultsArray_Count;

typedef struct SearchResult__storage_ {
  uint32_t _has_storage_[1];
  NSMutableArray *messagesArray;
  Page *page;
  NSMutableArray *contactResultsArray;
  NSMutableArray *groupResultsArray;
  NSMutableArray *memberResultsArray;
} SearchResult__storage_;

// This method is threadsafe because it is initially called
// in +initialize for each subclass.
+ (GPBDescriptor *)descriptor {
  static GPBDescriptor *descriptor = nil;
  if (!descriptor) {
    static GPBMessageFieldDescription fields[] = {
      {
        .name = "messagesArray",
        .dataTypeSpecific.clazz = GPBObjCClass(ImMessage),
        .number = SearchResult_FieldNumber_MessagesArray,
        .hasIndex = GPBNoHasBit,
        .offset = (uint32_t)offsetof(SearchResult__storage_, messagesArray),
        .flags = GPBFieldRepeated,
        .dataType = GPBDataTypeMessage,
      },
      {
        .name = "page",
        .dataTypeSpecific.clazz = GPBObjCClass(Page),
        .number = SearchResult_FieldNumber_Page,
        .hasIndex = 0,
        .offset = (uint32_t)offsetof(SearchResult__storage_, page),
        .flags = GPBFieldOptional,
        .dataType = GPBDataTypeMessage,
      },
      {
        .name = "contactResultsArray",
        .dataTypeSpecific.clazz = GPBObjCClass(ContactSearchResult),
        .number = SearchResult_FieldNumber_ContactResultsArray,
        .hasIndex = GPBNoHasBit,
        .offset = (uint32_t)offsetof(SearchResult__storage_, contactResultsArray),
        .flags = GPBFieldRepeated,
        .dataType = GPBDataTypeMessage,
      },
      {
        .name = "groupResultsArray",
        .dataTypeSpecific.clazz = GPBObjCClass(GroupSearchResult),
        .number = SearchResult_FieldNumber_GroupResultsArray,
        .hasIndex = GPBNoHasBit,
        .offset = (uint32_t)offsetof(SearchResult__storage_, groupResultsArray),
        .flags = GPBFieldRepeated,
        .dataType = GPBDataTypeMessage,
      },
      {
        .name = "memberResultsArray",
        .dataTypeSpecific.clazz = GPBObjCClass(GroupMemberSearchResult),
        .number = SearchResult_FieldNumber_MemberResultsArray,
        .hasIndex = GPBNoHasBit,
        .offset = (uint32_t)offsetof(SearchResult__storage_, memberResultsArray),
        .flags = GPBFieldRepeated,
        .dataType = GPBDataTypeMessage,
      },
    };
    GPBDescriptor *localDescriptor =
        [GPBDescriptor allocDescriptorForClass:[SearchResult class]
                                     rootClass:[ChatPbRoot class]
                                          file:ChatPbRoot_FileDescriptor()
                                        fields:fields
                                    fieldCount:(uint32_t)(sizeof(fields) / sizeof(GPBMessageFieldDescription))
                                   storageSize:sizeof(SearchResult__storage_)
                                         flags:(GPBDescriptorInitializationFlags)(GPBDescriptorInitializationFlag_UsesClassRefs | GPBDescriptorInitializationFlag_Proto3OptionalKnown)];
    #if defined(DEBUG) && DEBUG
      NSAssert(descriptor == nil, @"Startup recursed!");
    #endif  // DEBUG
    descriptor = localDescriptor;
  }
  return descriptor;
}

@end

#pragma mark - ContactSearchResult

@implementation ContactSearchResult

@dynamic contactUserId;
@dynamic contactNickname;
@dynamic remark;
@dynamic avatar;

typedef struct ContactSearchResult__storage_ {
  uint32_t _has_storage_[1];
  NSString *contactUserId;
  NSString *contactNickname;
  NSString *remark;
  NSString *avatar;
} ContactSearchResult__storage_;

// This method is threadsafe because it is initially called
// in +initialize for each subclass.
+ (GPBDescriptor *)descriptor {
  static GPBDescriptor *descriptor = nil;
  if (!descriptor) {
    static GPBMessageFieldDescription fields[] = {
      {
        .name = "contactUserId",
        .dataTypeSpecific.clazz = Nil,
        .number = ContactSearchResult_FieldNumber_ContactUserId,
        .hasIndex = 0,
        .offset = (uint32_t)offsetof(ContactSearchResult__storage_, contactUserId),
        .flags = (GPBFieldFlags)(GPBFieldOptional | GPBFieldClearHasIvarOnZero),
        .dataType = GPBDataTypeString,
      },
      {
        .name = "contactNickname",
        .dataTypeSpecific.clazz = Nil,
        .number = ContactSearchResult_FieldNumber_ContactNickname,
        .hasIndex = 1,
        .offset = (uint32_t)offsetof(ContactSearchResult__storage_, contactNickname),
        .flags = (GPBFieldFlags)(GPBFieldOptional | GPBFieldClearHasIvarOnZero),
        .dataType = GPBDataTypeString,
      },
      {
        .name = "remark",
        .dataTypeSpecific.clazz = Nil,
        .number = ContactSearchResult_FieldNumber_Remark,
        .hasIndex = 2,
        .offset = (uint32_t)offsetof(ContactSearchResult__storage_, remark),
        .flags = (GPBFieldFlags)(GPBFieldOptional | GPBFieldClearHasIvarOnZero),
        .dataType = GPBDataTypeString,
      },
      {
        .name = "avatar",
        .dataTypeSpecific.clazz = Nil,
        .number = ContactSearchResult_FieldNumber_Avatar,
        .hasIndex = 3,
        .offset = (uint32_t)offsetof(ContactSearchResult__storage_, avatar),
        .flags = (GPBFieldFlags)(GPBFieldOptional | GPBFieldClearHasIvarOnZero),
        .dataType = GPBDataTypeString,
      },
    };
    GPBDescriptor *localDescriptor =
        [GPBDescriptor allocDescriptorForClass:[ContactSearchResult class]
                                     rootClass:[ChatPbRoot class]
                                          file:ChatPbRoot_FileDescriptor()
                                        fields:fields
                                    fieldCount:(uint32_t)(sizeof(fields) / sizeof(GPBMessageFieldDescription))
                                   storageSize:sizeof(ContactSearchResult__storage_)
                                         flags:(GPBDescriptorInitializationFlags)(GPBDescriptorInitializationFlag_UsesClassRefs | GPBDescriptorInitializationFlag_Proto3OptionalKnown)];
    #if defined(DEBUG) && DEBUG
      NSAssert(descriptor == nil, @"Startup recursed!");
    #endif  // DEBUG
    descriptor = localDescriptor;
  }
  return descriptor;
}

@end

#pragma mark - GroupSearchResult

@implementation GroupSearchResult

@dynamic groupId;
@dynamic groupName;
@dynamic avatar;
@dynamic memberCount;

typedef struct GroupSearchResult__storage_ {
  uint32_t _has_storage_[1];
  int32_t memberCount;
  NSString *groupId;
  NSString *groupName;
  NSString *avatar;
} GroupSearchResult__storage_;

// This method is threadsafe because it is initially called
// in +initialize for each subclass.
+ (GPBDescriptor *)descriptor {
  static GPBDescriptor *descriptor = nil;
  if (!descriptor) {
    static GPBMessageFieldDescription fields[] = {
      {
        .name = "groupId",
        .dataTypeSpecific.clazz = Nil,
        .number = GroupSearchResult_FieldNumber_GroupId,
        .hasIndex = 0,
        .offset = (uint32_t)offsetof(GroupSearchResult__storage_, groupId),
        .flags = (GPBFieldFlags)(GPBFieldOptional | GPBFieldClearHasIvarOnZero),
        .dataType = GPBDataTypeString,
      },
      {
        .name = "groupName",
        .dataTypeSpecific.clazz = Nil,
        .number = GroupSearchResult_FieldNumber_GroupName,
        .hasIndex = 1,
        .offset = (uint32_t)offsetof(GroupSearchResult__storage_, groupName),
        .flags = (GPBFieldFlags)(GPBFieldOptional | GPBFieldClearHasIvarOnZero),
        .dataType = GPBDataTypeString,
      },
      {
        .name = "avatar",
        .dataTypeSpecific.clazz = Nil,
        .number = GroupSearchResult_FieldNumber_Avatar,
        .hasIndex = 2,
        .offset = (uint32_t)offsetof(GroupSearchResult__storage_, avatar),
        .flags = (GPBFieldFlags)(GPBFieldOptional | GPBFieldClearHasIvarOnZero),
        .dataType = GPBDataTypeString,
      },
      {
        .name = "memberCount",
        .dataTypeSpecific.clazz = Nil,
        .number = GroupSearchResult_FieldNumber_MemberCount,
        .hasIndex = 3,
        .offset = (uint32_t)offsetof(GroupSearchResult__storage_, memberCount),
        .flags = (GPBFieldFlags)(GPBFieldOptional | GPBFieldClearHasIvarOnZero),
        .dataType = GPBDataTypeInt32,
      },
    };
    GPBDescriptor *localDescriptor =
        [GPBDescriptor allocDescriptorForClass:[GroupSearchResult class]
                                     rootClass:[ChatPbRoot class]
                                          file:ChatPbRoot_FileDescriptor()
                                        fields:fields
                                    fieldCount:(uint32_t)(sizeof(fields) / sizeof(GPBMessageFieldDescription))
                                   storageSize:sizeof(GroupSearchResult__storage_)
                                         flags:(GPBDescriptorInitializationFlags)(GPBDescriptorInitializationFlag_UsesClassRefs | GPBDescriptorInitializationFlag_Proto3OptionalKnown)];
    #if defined(DEBUG) && DEBUG
      NSAssert(descriptor == nil, @"Startup recursed!");
    #endif  // DEBUG
    descriptor = localDescriptor;
  }
  return descriptor;
}

@end

#pragma mark - GroupMemberSearchResult

@implementation GroupMemberSearchResult

@dynamic groupId;
@dynamic groupName;
@dynamic memberUserId;
@dynamic memberNickname;
@dynamic memberAlias;
@dynamic avatar;

typedef struct GroupMemberSearchResult__storage_ {
  uint32_t _has_storage_[1];
  NSString *groupId;
  NSString *groupName;
  NSString *memberUserId;
  NSString *memberNickname;
  NSString *memberAlias;
  NSString *avatar;
} GroupMemberSearchResult__storage_;

// This method is threadsafe because it is initially called
// in +initialize for each subclass.
+ (GPBDescriptor *)descriptor {
  static GPBDescriptor *descriptor = nil;
  if (!descriptor) {
    static GPBMessageFieldDescription fields[] = {
      {
        .name = "groupId",
        .dataTypeSpecific.clazz = Nil,
        .number = GroupMemberSearchResult_FieldNumber_GroupId,
        .hasIndex = 0,
        .offset = (uint32_t)offsetof(GroupMemberSearchResult__storage_, groupId),
        .flags = (GPBFieldFlags)(GPBFieldOptional | GPBFieldClearHasIvarOnZero),
        .dataType = GPBDataTypeString,
      },
      {
        .name = "groupName",
        .dataTypeSpecific.clazz = Nil,
        .number = GroupMemberSearchResult_FieldNumber_GroupName,
        .hasIndex = 1,
        .offset = (uint32_t)offsetof(GroupMemberSearchResult__storage_, groupName),
        .flags = (GPBFieldFlags)(GPBFieldOptional | GPBFieldClearHasIvarOnZero),
        .dataType = GPBDataTypeString,
      },
      {
        .name = "memberUserId",
        .dataTypeSpecific.clazz = Nil,
        .number = GroupMemberSearchResult_FieldNumber_MemberUserId,
        .hasIndex = 2,
        .offset = (uint32_t)offsetof(GroupMemberSearchResult__storage_, memberUserId),
        .flags = (GPBFieldFlags)(GPBFieldOptional | GPBFieldClearHasIvarOnZero),
        .dataType = GPBDataTypeString,
      },
      {
        .name = "memberNickname",
        .dataTypeSpecific.clazz = Nil,
        .number = GroupMemberSearchResult_FieldNumber_MemberNickname,
        .hasIndex = 3,
        .offset = (uint32_t)offsetof(GroupMemberSearchResult__storage_, memberNickname),
        .flags = (GPBFieldFlags)(GPBFieldOptional | GPBFieldClearHasIvarOnZero),
        .dataType = GPBDataTypeString,
      },
      {
        .name = "memberAlias",
        .dataTypeSpecific.clazz = Nil,
        .number = GroupMemberSearchResult_FieldNumber_MemberAlias,
        .hasIndex = 4,
        .offset = (uint32_t)offsetof(GroupMemberSearchResult__storage_, memberAlias),
        .flags = (GPBFieldFlags)(GPBFieldOptional | GPBFieldClearHasIvarOnZero),
        .dataType = GPBDataTypeString,
      },
      {
        .name = "avatar",
        .dataTypeSpecific.clazz = Nil,
        .number = GroupMemberSearchResult_FieldNumber_Avatar,
        .hasIndex = 5,
        .offset = (uint32_t)offsetof(GroupMemberSearchResult__storage_, avatar),
        .flags = (GPBFieldFlags)(GPBFieldOptional | GPBFieldClearHasIvarOnZero),
        .dataType = GPBDataTypeString,
      },
    };
    GPBDescriptor *localDescriptor =
        [GPBDescriptor allocDescriptorForClass:[GroupMemberSearchResult class]
                                     rootClass:[ChatPbRoot class]
                                          file:ChatPbRoot_FileDescriptor()
                                        fields:fields
                                    fieldCount:(uint32_t)(sizeof(fields) / sizeof(GPBMessageFieldDescription))
                                   storageSize:sizeof(GroupMemberSearchResult__storage_)
                                         flags:(GPBDescriptorInitializationFlags)(GPBDescriptorInitializationFlag_UsesClassRefs | GPBDescriptorInitializationFlag_Proto3OptionalKnown)];
    #if defined(DEBUG) && DEBUG
      NSAssert(descriptor == nil, @"Startup recursed!");
    #endif  // DEBUG
    descriptor = localDescriptor;
  }
  return descriptor;
}

@end

#pragma mark - SearchAtMe

@implementation SearchAtMe

@dynamic keyword;
@dynamic groupId;
@dynamic startTimeMs;
@dynamic endTimeMs;
@dynamic unreadOnly;
@dynamic hasPage, page;

typedef struct SearchAtMe__storage_ {
  uint32_t _has_storage_[1];
  NSString *keyword;
  NSString *groupId;
  Page *page;
  int64_t startTimeMs;
  int64_t endTimeMs;
} SearchAtMe__storage_;

// This method is threadsafe because it is initially called
// in +initialize for each subclass.
+ (GPBDescriptor *)descriptor {
  static GPBDescriptor *descriptor = nil;
  if (!descriptor) {
    static GPBMessageFieldDescription fields[] = {
      {
        .name = "keyword",
        .dataTypeSpecific.clazz = Nil,
        .number = SearchAtMe_FieldNumber_Keyword,
        .hasIndex = 0,
        .offset = (uint32_t)offsetof(SearchAtMe__storage_, keyword),
        .flags = (GPBFieldFlags)(GPBFieldOptional | GPBFieldClearHasIvarOnZero),
        .dataType = GPBDataTypeString,
      },
      {
        .name = "groupId",
        .dataTypeSpecific.clazz = Nil,
        .number = SearchAtMe_FieldNumber_GroupId,
        .hasIndex = 1,
        .offset = (uint32_t)offsetof(SearchAtMe__storage_, groupId),
        .flags = (GPBFieldFlags)(GPBFieldOptional | GPBFieldClearHasIvarOnZero),
        .dataType = GPBDataTypeString,
      },
      {
        .name = "startTimeMs",
        .dataTypeSpecific.clazz = Nil,
        .number = SearchAtMe_FieldNumber_StartTimeMs,
        .hasIndex = 2,
        .offset = (uint32_t)offsetof(SearchAtMe__storage_, startTimeMs),
        .flags = (GPBFieldFlags)(GPBFieldOptional | GPBFieldClearHasIvarOnZero),
        .dataType = GPBDataTypeInt64,
      },
      {
        .name = "endTimeMs",
        .dataTypeSpecific.clazz = Nil,
        .number = SearchAtMe_FieldNumber_EndTimeMs,
        .hasIndex = 3,
        .offset = (uint32_t)offsetof(SearchAtMe__storage_, endTimeMs),
        .flags = (GPBFieldFlags)(GPBFieldOptional | GPBFieldClearHasIvarOnZero),
        .dataType = GPBDataTypeInt64,
      },
      {
        .name = "unreadOnly",
        .dataTypeSpecific.clazz = Nil,
        .number = SearchAtMe_FieldNumber_UnreadOnly,
        .hasIndex = 4,
        .offset = 5,  // Stored in _has_storage_ to save space.
        .flags = (GPBFieldFlags)(GPBFieldOptional | GPBFieldClearHasIvarOnZero),
        .dataType = GPBDataTypeBool,
      },
      {
        .name = "page",
        .dataTypeSpecific.clazz = GPBObjCClass(Page),
        .number = SearchAtMe_FieldNumber_Page,
        .hasIndex = 6,
        .offset = (uint32_t)offsetof(SearchAtMe__storage_, page),
        .flags = GPBFieldOptional,
        .dataType = GPBDataTypeMessage,
      },
    };
    GPBDescriptor *localDescriptor =
        [GPBDescriptor allocDescriptorForClass:[SearchAtMe class]
                                     rootClass:[ChatPbRoot class]
                                          file:ChatPbRoot_FileDescriptor()
                                        fields:fields
                                    fieldCount:(uint32_t)(sizeof(fields) / sizeof(GPBMessageFieldDescription))
                                   storageSize:sizeof(SearchAtMe__storage_)
                                         flags:(GPBDescriptorInitializationFlags)(GPBDescriptorInitializationFlag_UsesClassRefs | GPBDescriptorInitializationFlag_Proto3OptionalKnown)];
    #if defined(DEBUG) && DEBUG
      NSAssert(descriptor == nil, @"Startup recursed!");
    #endif  // DEBUG
    descriptor = localDescriptor;
  }
  return descriptor;
}

@end

#pragma mark - SearchAtMeResult

@implementation SearchAtMeResult

@dynamic messagesArray, messagesArray_Count;
@dynamic total;
@dynamic hasMore;
@dynamic hasPage, page;

typedef struct SearchAtMeResult__storage_ {
  uint32_t _has_storage_[1];
  int32_t total;
  NSMutableArray *messagesArray;
  Page *page;
} SearchAtMeResult__storage_;

// This method is threadsafe because it is initially called
// in +initialize for each subclass.
+ (GPBDescriptor *)descriptor {
  static GPBDescriptor *descriptor = nil;
  if (!descriptor) {
    static GPBMessageFieldDescription fields[] = {
      {
        .name = "messagesArray",
        .dataTypeSpecific.clazz = GPBObjCClass(AtMeMessage),
        .number = SearchAtMeResult_FieldNumber_MessagesArray,
        .hasIndex = GPBNoHasBit,
        .offset = (uint32_t)offsetof(SearchAtMeResult__storage_, messagesArray),
        .flags = GPBFieldRepeated,
        .dataType = GPBDataTypeMessage,
      },
      {
        .name = "total",
        .dataTypeSpecific.clazz = Nil,
        .number = SearchAtMeResult_FieldNumber_Total,
        .hasIndex = 0,
        .offset = (uint32_t)offsetof(SearchAtMeResult__storage_, total),
        .flags = (GPBFieldFlags)(GPBFieldOptional | GPBFieldClearHasIvarOnZero),
        .dataType = GPBDataTypeInt32,
      },
      {
        .name = "hasMore",
        .dataTypeSpecific.clazz = Nil,
        .number = SearchAtMeResult_FieldNumber_HasMore,
        .hasIndex = 1,
        .offset = 2,  // Stored in _has_storage_ to save space.
        .flags = (GPBFieldFlags)(GPBFieldOptional | GPBFieldClearHasIvarOnZero),
        .dataType = GPBDataTypeBool,
      },
      {
        .name = "page",
        .dataTypeSpecific.clazz = GPBObjCClass(Page),
        .number = SearchAtMeResult_FieldNumber_Page,
        .hasIndex = 3,
        .offset = (uint32_t)offsetof(SearchAtMeResult__storage_, page),
        .flags = GPBFieldOptional,
        .dataType = GPBDataTypeMessage,
      },
    };
    GPBDescriptor *localDescriptor =
        [GPBDescriptor allocDescriptorForClass:[SearchAtMeResult class]
                                     rootClass:[ChatPbRoot class]
                                          file:ChatPbRoot_FileDescriptor()
                                        fields:fields
                                    fieldCount:(uint32_t)(sizeof(fields) / sizeof(GPBMessageFieldDescription))
                                   storageSize:sizeof(SearchAtMeResult__storage_)
                                         flags:(GPBDescriptorInitializationFlags)(GPBDescriptorInitializationFlag_UsesClassRefs | GPBDescriptorInitializationFlag_Proto3OptionalKnown)];
    #if defined(DEBUG) && DEBUG
      NSAssert(descriptor == nil, @"Startup recursed!");
    #endif  // DEBUG
    descriptor = localDescriptor;
  }
  return descriptor;
}

@end

#pragma mark - AtMeMessage

@implementation AtMeMessage

@dynamic hasMessage, message;
@dynamic groupId;
@dynamic groupName;
@dynamic fromUserId;
@dynamic fromUserName;
@dynamic sendTimeMs;
@dynamic isRead;
@dynamic groupSeq;

typedef struct AtMeMessage__storage_ {
  uint32_t _has_storage_[1];
  ImMessage *message;
  NSString *groupId;
  NSString *groupName;
  NSString *fromUserId;
  NSString *fromUserName;
  int64_t sendTimeMs;
  int64_t groupSeq;
} AtMeMessage__storage_;

// This method is threadsafe because it is initially called
// in +initialize for each subclass.
+ (GPBDescriptor *)descriptor {
  static GPBDescriptor *descriptor = nil;
  if (!descriptor) {
    static GPBMessageFieldDescription fields[] = {
      {
        .name = "message",
        .dataTypeSpecific.clazz = GPBObjCClass(ImMessage),
        .number = AtMeMessage_FieldNumber_Message,
        .hasIndex = 0,
        .offset = (uint32_t)offsetof(AtMeMessage__storage_, message),
        .flags = GPBFieldOptional,
        .dataType = GPBDataTypeMessage,
      },
      {
        .name = "groupId",
        .dataTypeSpecific.clazz = Nil,
        .number = AtMeMessage_FieldNumber_GroupId,
        .hasIndex = 1,
        .offset = (uint32_t)offsetof(AtMeMessage__storage_, groupId),
        .flags = (GPBFieldFlags)(GPBFieldOptional | GPBFieldClearHasIvarOnZero),
        .dataType = GPBDataTypeString,
      },
      {
        .name = "groupName",
        .dataTypeSpecific.clazz = Nil,
        .number = AtMeMessage_FieldNumber_GroupName,
        .hasIndex = 2,
        .offset = (uint32_t)offsetof(AtMeMessage__storage_, groupName),
        .flags = (GPBFieldFlags)(GPBFieldOptional | GPBFieldClearHasIvarOnZero),
        .dataType = GPBDataTypeString,
      },
      {
        .name = "fromUserId",
        .dataTypeSpecific.clazz = Nil,
        .number = AtMeMessage_FieldNumber_FromUserId,
        .hasIndex = 3,
        .offset = (uint32_t)offsetof(AtMeMessage__storage_, fromUserId),
        .flags = (GPBFieldFlags)(GPBFieldOptional | GPBFieldClearHasIvarOnZero),
        .dataType = GPBDataTypeString,
      },
      {
        .name = "fromUserName",
        .dataTypeSpecific.clazz = Nil,
        .number = AtMeMessage_FieldNumber_FromUserName,
        .hasIndex = 4,
        .offset = (uint32_t)offsetof(AtMeMessage__storage_, fromUserName),
        .flags = (GPBFieldFlags)(GPBFieldOptional | GPBFieldClearHasIvarOnZero),
        .dataType = GPBDataTypeString,
      },
      {
        .name = "sendTimeMs",
        .dataTypeSpecific.clazz = Nil,
        .number = AtMeMessage_FieldNumber_SendTimeMs,
        .hasIndex = 5,
        .offset = (uint32_t)offsetof(AtMeMessage__storage_, sendTimeMs),
        .flags = (GPBFieldFlags)(GPBFieldOptional | GPBFieldClearHasIvarOnZero),
        .dataType = GPBDataTypeInt64,
      },
      {
        .name = "isRead",
        .dataTypeSpecific.clazz = Nil,
        .number = AtMeMessage_FieldNumber_IsRead,
        .hasIndex = 6,
        .offset = 7,  // Stored in _has_storage_ to save space.
        .flags = (GPBFieldFlags)(GPBFieldOptional | GPBFieldClearHasIvarOnZero),
        .dataType = GPBDataTypeBool,
      },
      {
        .name = "groupSeq",
        .dataTypeSpecific.clazz = Nil,
        .number = AtMeMessage_FieldNumber_GroupSeq,
        .hasIndex = 8,
        .offset = (uint32_t)offsetof(AtMeMessage__storage_, groupSeq),
        .flags = (GPBFieldFlags)(GPBFieldOptional | GPBFieldClearHasIvarOnZero),
        .dataType = GPBDataTypeInt64,
      },
    };
    GPBDescriptor *localDescriptor =
        [GPBDescriptor allocDescriptorForClass:[AtMeMessage class]
                                     rootClass:[ChatPbRoot class]
                                          file:ChatPbRoot_FileDescriptor()
                                        fields:fields
                                    fieldCount:(uint32_t)(sizeof(fields) / sizeof(GPBMessageFieldDescription))
                                   storageSize:sizeof(AtMeMessage__storage_)
                                         flags:(GPBDescriptorInitializationFlags)(GPBDescriptorInitializationFlag_UsesClassRefs | GPBDescriptorInitializationFlag_Proto3OptionalKnown)];
    #if defined(DEBUG) && DEBUG
      NSAssert(descriptor == nil, @"Startup recursed!");
    #endif  // DEBUG
    descriptor = localDescriptor;
  }
  return descriptor;
}

@end

#pragma mark - GetAtMeUnreadCount

@implementation GetAtMeUnreadCount


typedef struct GetAtMeUnreadCount__storage_ {
  uint32_t _has_storage_[1];
} GetAtMeUnreadCount__storage_;

// This method is threadsafe because it is initially called
// in +initialize for each subclass.
+ (GPBDescriptor *)descriptor {
  static GPBDescriptor *descriptor = nil;
  if (!descriptor) {
    GPBDescriptor *localDescriptor =
        [GPBDescriptor allocDescriptorForClass:[GetAtMeUnreadCount class]
                                     rootClass:[ChatPbRoot class]
                                          file:ChatPbRoot_FileDescriptor()
                                        fields:NULL
                                    fieldCount:0
                                   storageSize:sizeof(GetAtMeUnreadCount__storage_)
                                         flags:(GPBDescriptorInitializationFlags)(GPBDescriptorInitializationFlag_UsesClassRefs | GPBDescriptorInitializationFlag_Proto3OptionalKnown)];
    #if defined(DEBUG) && DEBUG
      NSAssert(descriptor == nil, @"Startup recursed!");
    #endif  // DEBUG
    descriptor = localDescriptor;
  }
  return descriptor;
}

@end

#pragma mark - AtMeUnreadCountResult

@implementation AtMeUnreadCountResult

@dynamic totalUnread;
@dynamic groupUnread, groupUnread_Count;

typedef struct AtMeUnreadCountResult__storage_ {
  uint32_t _has_storage_[1];
  int32_t totalUnread;
  GPBStringInt32Dictionary *groupUnread;
} AtMeUnreadCountResult__storage_;

// This method is threadsafe because it is initially called
// in +initialize for each subclass.
+ (GPBDescriptor *)descriptor {
  static GPBDescriptor *descriptor = nil;
  if (!descriptor) {
    static GPBMessageFieldDescription fields[] = {
      {
        .name = "totalUnread",
        .dataTypeSpecific.clazz = Nil,
        .number = AtMeUnreadCountResult_FieldNumber_TotalUnread,
        .hasIndex = 0,
        .offset = (uint32_t)offsetof(AtMeUnreadCountResult__storage_, totalUnread),
        .flags = (GPBFieldFlags)(GPBFieldOptional | GPBFieldClearHasIvarOnZero),
        .dataType = GPBDataTypeInt32,
      },
      {
        .name = "groupUnread",
        .dataTypeSpecific.clazz = Nil,
        .number = AtMeUnreadCountResult_FieldNumber_GroupUnread,
        .hasIndex = GPBNoHasBit,
        .offset = (uint32_t)offsetof(AtMeUnreadCountResult__storage_, groupUnread),
        .flags = GPBFieldMapKeyString,
        .dataType = GPBDataTypeInt32,
      },
    };
    GPBDescriptor *localDescriptor =
        [GPBDescriptor allocDescriptorForClass:[AtMeUnreadCountResult class]
                                     rootClass:[ChatPbRoot class]
                                          file:ChatPbRoot_FileDescriptor()
                                        fields:fields
                                    fieldCount:(uint32_t)(sizeof(fields) / sizeof(GPBMessageFieldDescription))
                                   storageSize:sizeof(AtMeUnreadCountResult__storage_)
                                         flags:(GPBDescriptorInitializationFlags)(GPBDescriptorInitializationFlag_UsesClassRefs | GPBDescriptorInitializationFlag_Proto3OptionalKnown)];
    #if defined(DEBUG) && DEBUG
      NSAssert(descriptor == nil, @"Startup recursed!");
    #endif  // DEBUG
    descriptor = localDescriptor;
  }
  return descriptor;
}

@end

#pragma mark - MarkAtMeRead

@implementation MarkAtMeRead

@dynamic messageIdsArray, messageIdsArray_Count;
@dynamic groupId;

typedef struct MarkAtMeRead__storage_ {
  uint32_t _has_storage_[1];
  NSMutableArray *messageIdsArray;
  NSString *groupId;
} MarkAtMeRead__storage_;

// This method is threadsafe because it is initially called
// in +initialize for each subclass.
+ (GPBDescriptor *)descriptor {
  static GPBDescriptor *descriptor = nil;
  if (!descriptor) {
    static GPBMessageFieldDescription fields[] = {
      {
        .name = "messageIdsArray",
        .dataTypeSpecific.clazz = Nil,
        .number = MarkAtMeRead_FieldNumber_MessageIdsArray,
        .hasIndex = GPBNoHasBit,
        .offset = (uint32_t)offsetof(MarkAtMeRead__storage_, messageIdsArray),
        .flags = GPBFieldRepeated,
        .dataType = GPBDataTypeString,
      },
      {
        .name = "groupId",
        .dataTypeSpecific.clazz = Nil,
        .number = MarkAtMeRead_FieldNumber_GroupId,
        .hasIndex = 0,
        .offset = (uint32_t)offsetof(MarkAtMeRead__storage_, groupId),
        .flags = (GPBFieldFlags)(GPBFieldOptional | GPBFieldClearHasIvarOnZero),
        .dataType = GPBDataTypeString,
      },
    };
    GPBDescriptor *localDescriptor =
        [GPBDescriptor allocDescriptorForClass:[MarkAtMeRead class]
                                     rootClass:[ChatPbRoot class]
                                          file:ChatPbRoot_FileDescriptor()
                                        fields:fields
                                    fieldCount:(uint32_t)(sizeof(fields) / sizeof(GPBMessageFieldDescription))
                                   storageSize:sizeof(MarkAtMeRead__storage_)
                                         flags:(GPBDescriptorInitializationFlags)(GPBDescriptorInitializationFlag_UsesClassRefs | GPBDescriptorInitializationFlag_Proto3OptionalKnown)];
    #if defined(DEBUG) && DEBUG
      NSAssert(descriptor == nil, @"Startup recursed!");
    #endif  // DEBUG
    descriptor = localDescriptor;
  }
  return descriptor;
}

@end

#pragma mark - MarkAtMeReadResult

@implementation MarkAtMeReadResult

@dynamic markedCount;
@dynamic failedMessageIdsArray, failedMessageIdsArray_Count;

typedef struct MarkAtMeReadResult__storage_ {
  uint32_t _has_storage_[1];
  int32_t markedCount;
  NSMutableArray *failedMessageIdsArray;
} MarkAtMeReadResult__storage_;

// This method is threadsafe because it is initially called
// in +initialize for each subclass.
+ (GPBDescriptor *)descriptor {
  static GPBDescriptor *descriptor = nil;
  if (!descriptor) {
    static GPBMessageFieldDescription fields[] = {
      {
        .name = "markedCount",
        .dataTypeSpecific.clazz = Nil,
        .number = MarkAtMeReadResult_FieldNumber_MarkedCount,
        .hasIndex = 0,
        .offset = (uint32_t)offsetof(MarkAtMeReadResult__storage_, markedCount),
        .flags = (GPBFieldFlags)(GPBFieldOptional | GPBFieldClearHasIvarOnZero),
        .dataType = GPBDataTypeInt32,
      },
      {
        .name = "failedMessageIdsArray",
        .dataTypeSpecific.clazz = Nil,
        .number = MarkAtMeReadResult_FieldNumber_FailedMessageIdsArray,
        .hasIndex = GPBNoHasBit,
        .offset = (uint32_t)offsetof(MarkAtMeReadResult__storage_, failedMessageIdsArray),
        .flags = GPBFieldRepeated,
        .dataType = GPBDataTypeString,
      },
    };
    GPBDescriptor *localDescriptor =
        [GPBDescriptor allocDescriptorForClass:[MarkAtMeReadResult class]
                                     rootClass:[ChatPbRoot class]
                                          file:ChatPbRoot_FileDescriptor()
                                        fields:fields
                                    fieldCount:(uint32_t)(sizeof(fields) / sizeof(GPBMessageFieldDescription))
                                   storageSize:sizeof(MarkAtMeReadResult__storage_)
                                         flags:(GPBDescriptorInitializationFlags)(GPBDescriptorInitializationFlag_UsesClassRefs | GPBDescriptorInitializationFlag_Proto3OptionalKnown)];
    #if defined(DEBUG) && DEBUG
      NSAssert(descriptor == nil, @"Startup recursed!");
    #endif  // DEBUG
    descriptor = localDescriptor;
  }
  return descriptor;
}

@end


#pragma clang diagnostic pop

// @@protoc_insertion_point(global_scope)
