// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// clang-format off
// source: system_pb.proto

// This CPP symbol can be defined to use imports that match up to the framework
// imports needed when using CocoaPods.
#if !defined(GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS)
 #define GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS 0
#endif

#if GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS
 #import <Protobuf/GPBProtocolBuffers_RuntimeSupport.h>
#else
 #import <Protobuf/GPBProtocolBuffers_RuntimeSupport.h>
#endif

#if GOOGLE_PROTOBUF_OBJC_VERSION < 30007
#error This file was generated by a newer version of protoc which is incompatible with your Protocol Buffer library sources.
#endif
#if 30007 < GOOGLE_PROTOBUF_OBJC_MIN_SUPPORTED_VERSION
#error This file was generated by an older version of protoc which is incompatible with your Protocol Buffer library sources.
#endif

#import "SystemPb.pbobjc.h"
// @@protoc_insertion_point(imports)

#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wdeprecated-declarations"
#pragma clang diagnostic ignored "-Wdollar-in-identifier-extension"

#pragma mark - Objective-C Class declarations
// Forward declarations of Objective-C classes that we can use as
// static values in struct initializers.
// We don't use [Foo class] because it is not a static value.
GPBObjCClassDeclaration(ConfigResp);
GPBObjCClassDeclaration(EmptyResponse);
GPBObjCClassDeclaration(Error);
GPBObjCClassDeclaration(ErrorCodeDetail);
GPBObjCClassDeclaration(Page);
GPBObjCClassDeclaration(Param);
GPBObjCClassDeclaration(QueryErrorCode);

#pragma mark - SystemPbRoot

@implementation SystemPbRoot

// No extensions in the file and no imports or none of the imports (direct or
// indirect) defined extensions, so no need to generate +extensionRegistry.

@end

static GPBFileDescription SystemPbRoot_FileDescription = {
  .package = "com.cloud.im.common.core.system",
  .prefix = NULL,
  .syntax = GPBFileSyntaxProto3
};

#pragma mark - ConfigResp

@implementation ConfigResp

@dynamic data_p, data_p_Count;

typedef struct ConfigResp__storage_ {
  uint32_t _has_storage_[1];
  NSMutableDictionary *data_p;
} ConfigResp__storage_;

// This method is threadsafe because it is initially called
// in +initialize for each subclass.
+ (GPBDescriptor *)descriptor {
  static GPBDescriptor *descriptor = nil;
  if (!descriptor) {
    GPB_DEBUG_CHECK_RUNTIME_VERSIONS();
    static GPBMessageFieldDescription fields[] = {
      {
        .name = "data_p",
        .dataTypeSpecific.clazz = Nil,
        .number = ConfigResp_FieldNumber_Data_p,
        .hasIndex = GPBNoHasBit,
        .offset = (uint32_t)offsetof(ConfigResp__storage_, data_p),
        .flags = GPBFieldMapKeyString,
        .dataType = GPBDataTypeString,
      },
    };
    GPBDescriptor *localDescriptor =
        [GPBDescriptor allocDescriptorForClass:GPBObjCClass(ConfigResp)
                                   messageName:@"ConfigResp"
                               fileDescription:&SystemPbRoot_FileDescription
                                        fields:fields
                                    fieldCount:(uint32_t)(sizeof(fields) / sizeof(GPBMessageFieldDescription))
                                   storageSize:sizeof(ConfigResp__storage_)
                                         flags:(GPBDescriptorInitializationFlags)(GPBDescriptorInitializationFlag_UsesClassRefs | GPBDescriptorInitializationFlag_Proto3OptionalKnown | GPBDescriptorInitializationFlag_ClosedEnumSupportKnown)];
    #if defined(DEBUG) && DEBUG
      NSAssert(descriptor == nil, @"Startup recursed!");
    #endif  // DEBUG
    descriptor = localDescriptor;
  }
  return descriptor;
}

@end

#pragma mark - Error

@implementation Error

@dynamic code;
@dynamic message;
@dynamic placeholdersArray, placeholdersArray_Count;

typedef struct Error__storage_ {
  uint32_t _has_storage_[1];
  int32_t code;
  NSString *message;
  NSMutableArray *placeholdersArray;
} Error__storage_;

// This method is threadsafe because it is initially called
// in +initialize for each subclass.
+ (GPBDescriptor *)descriptor {
  static GPBDescriptor *descriptor = nil;
  if (!descriptor) {
    GPB_DEBUG_CHECK_RUNTIME_VERSIONS();
    static GPBMessageFieldDescription fields[] = {
      {
        .name = "code",
        .dataTypeSpecific.clazz = Nil,
        .number = Error_FieldNumber_Code,
        .hasIndex = 0,
        .offset = (uint32_t)offsetof(Error__storage_, code),
        .flags = (GPBFieldFlags)(GPBFieldOptional | GPBFieldClearHasIvarOnZero),
        .dataType = GPBDataTypeInt32,
      },
      {
        .name = "message",
        .dataTypeSpecific.clazz = Nil,
        .number = Error_FieldNumber_Message,
        .hasIndex = 1,
        .offset = (uint32_t)offsetof(Error__storage_, message),
        .flags = (GPBFieldFlags)(GPBFieldOptional | GPBFieldClearHasIvarOnZero),
        .dataType = GPBDataTypeString,
      },
      {
        .name = "placeholdersArray",
        .dataTypeSpecific.clazz = Nil,
        .number = Error_FieldNumber_PlaceholdersArray,
        .hasIndex = GPBNoHasBit,
        .offset = (uint32_t)offsetof(Error__storage_, placeholdersArray),
        .flags = GPBFieldRepeated,
        .dataType = GPBDataTypeString,
      },
    };
    GPBDescriptor *localDescriptor =
        [GPBDescriptor allocDescriptorForClass:GPBObjCClass(Error)
                                   messageName:@"Error"
                               fileDescription:&SystemPbRoot_FileDescription
                                        fields:fields
                                    fieldCount:(uint32_t)(sizeof(fields) / sizeof(GPBMessageFieldDescription))
                                   storageSize:sizeof(Error__storage_)
                                         flags:(GPBDescriptorInitializationFlags)(GPBDescriptorInitializationFlag_UsesClassRefs | GPBDescriptorInitializationFlag_Proto3OptionalKnown | GPBDescriptorInitializationFlag_ClosedEnumSupportKnown)];
    #if defined(DEBUG) && DEBUG
      NSAssert(descriptor == nil, @"Startup recursed!");
    #endif  // DEBUG
    descriptor = localDescriptor;
  }
  return descriptor;
}

@end

#pragma mark - EmptyResponse

@implementation EmptyResponse


typedef struct EmptyResponse__storage_ {
  uint32_t _has_storage_[1];
} EmptyResponse__storage_;

// This method is threadsafe because it is initially called
// in +initialize for each subclass.
+ (GPBDescriptor *)descriptor {
  static GPBDescriptor *descriptor = nil;
  if (!descriptor) {
    GPB_DEBUG_CHECK_RUNTIME_VERSIONS();
    GPBDescriptor *localDescriptor =
        [GPBDescriptor allocDescriptorForClass:GPBObjCClass(EmptyResponse)
                                   messageName:@"EmptyResponse"
                               fileDescription:&SystemPbRoot_FileDescription
                                        fields:NULL
                                    fieldCount:0
                                   storageSize:sizeof(EmptyResponse__storage_)
                                         flags:(GPBDescriptorInitializationFlags)(GPBDescriptorInitializationFlag_UsesClassRefs | GPBDescriptorInitializationFlag_Proto3OptionalKnown | GPBDescriptorInitializationFlag_ClosedEnumSupportKnown)];
    #if defined(DEBUG) && DEBUG
      NSAssert(descriptor == nil, @"Startup recursed!");
    #endif  // DEBUG
    descriptor = localDescriptor;
  }
  return descriptor;
}

@end

#pragma mark - Page

@implementation Page

@dynamic page;
@dynamic size;
@dynamic sortField;
@dynamic sortOrder;
@dynamic totalCount;
@dynamic totalPages;
@dynamic hasPrevious;
@dynamic hasNext;

typedef struct Page__storage_ {
  uint32_t _has_storage_[1];
  int32_t page;
  int32_t size;
  int32_t totalCount;
  int32_t totalPages;
  NSString *sortField;
  NSString *sortOrder;
} Page__storage_;

// This method is threadsafe because it is initially called
// in +initialize for each subclass.
+ (GPBDescriptor *)descriptor {
  static GPBDescriptor *descriptor = nil;
  if (!descriptor) {
    GPB_DEBUG_CHECK_RUNTIME_VERSIONS();
    static GPBMessageFieldDescription fields[] = {
      {
        .name = "page",
        .dataTypeSpecific.clazz = Nil,
        .number = Page_FieldNumber_Page,
        .hasIndex = 0,
        .offset = (uint32_t)offsetof(Page__storage_, page),
        .flags = (GPBFieldFlags)(GPBFieldOptional | GPBFieldClearHasIvarOnZero),
        .dataType = GPBDataTypeInt32,
      },
      {
        .name = "size",
        .dataTypeSpecific.clazz = Nil,
        .number = Page_FieldNumber_Size,
        .hasIndex = 1,
        .offset = (uint32_t)offsetof(Page__storage_, size),
        .flags = (GPBFieldFlags)(GPBFieldOptional | GPBFieldClearHasIvarOnZero),
        .dataType = GPBDataTypeInt32,
      },
      {
        .name = "sortField",
        .dataTypeSpecific.clazz = Nil,
        .number = Page_FieldNumber_SortField,
        .hasIndex = 2,
        .offset = (uint32_t)offsetof(Page__storage_, sortField),
        .flags = (GPBFieldFlags)(GPBFieldOptional | GPBFieldClearHasIvarOnZero),
        .dataType = GPBDataTypeString,
      },
      {
        .name = "sortOrder",
        .dataTypeSpecific.clazz = Nil,
        .number = Page_FieldNumber_SortOrder,
        .hasIndex = 3,
        .offset = (uint32_t)offsetof(Page__storage_, sortOrder),
        .flags = (GPBFieldFlags)(GPBFieldOptional | GPBFieldClearHasIvarOnZero),
        .dataType = GPBDataTypeString,
      },
      {
        .name = "totalCount",
        .dataTypeSpecific.clazz = Nil,
        .number = Page_FieldNumber_TotalCount,
        .hasIndex = 4,
        .offset = (uint32_t)offsetof(Page__storage_, totalCount),
        .flags = (GPBFieldFlags)(GPBFieldOptional | GPBFieldClearHasIvarOnZero),
        .dataType = GPBDataTypeInt32,
      },
      {
        .name = "totalPages",
        .dataTypeSpecific.clazz = Nil,
        .number = Page_FieldNumber_TotalPages,
        .hasIndex = 5,
        .offset = (uint32_t)offsetof(Page__storage_, totalPages),
        .flags = (GPBFieldFlags)(GPBFieldOptional | GPBFieldClearHasIvarOnZero),
        .dataType = GPBDataTypeInt32,
      },
      {
        .name = "hasPrevious",
        .dataTypeSpecific.clazz = Nil,
        .number = Page_FieldNumber_HasPrevious,
        .hasIndex = 6,
        .offset = 7,  // Stored in _has_storage_ to save space.
        .flags = (GPBFieldFlags)(GPBFieldOptional | GPBFieldClearHasIvarOnZero),
        .dataType = GPBDataTypeBool,
      },
      {
        .name = "hasNext",
        .dataTypeSpecific.clazz = Nil,
        .number = Page_FieldNumber_HasNext,
        .hasIndex = 8,
        .offset = 9,  // Stored in _has_storage_ to save space.
        .flags = (GPBFieldFlags)(GPBFieldOptional | GPBFieldClearHasIvarOnZero),
        .dataType = GPBDataTypeBool,
      },
    };
    GPBDescriptor *localDescriptor =
        [GPBDescriptor allocDescriptorForClass:GPBObjCClass(Page)
                                   messageName:@"Page"
                               fileDescription:&SystemPbRoot_FileDescription
                                        fields:fields
                                    fieldCount:(uint32_t)(sizeof(fields) / sizeof(GPBMessageFieldDescription))
                                   storageSize:sizeof(Page__storage_)
                                         flags:(GPBDescriptorInitializationFlags)(GPBDescriptorInitializationFlag_UsesClassRefs | GPBDescriptorInitializationFlag_Proto3OptionalKnown | GPBDescriptorInitializationFlag_ClosedEnumSupportKnown)];
    #if defined(DEBUG) && DEBUG
      NSAssert(descriptor == nil, @"Startup recursed!");
    #endif  // DEBUG
    descriptor = localDescriptor;
  }
  return descriptor;
}

@end

#pragma mark - QueryErrorCode

@implementation QueryErrorCode

@dynamic code;

typedef struct QueryErrorCode__storage_ {
  uint32_t _has_storage_[1];
  int32_t code;
} QueryErrorCode__storage_;

// This method is threadsafe because it is initially called
// in +initialize for each subclass.
+ (GPBDescriptor *)descriptor {
  static GPBDescriptor *descriptor = nil;
  if (!descriptor) {
    GPB_DEBUG_CHECK_RUNTIME_VERSIONS();
    static GPBMessageFieldDescription fields[] = {
      {
        .name = "code",
        .dataTypeSpecific.clazz = Nil,
        .number = QueryErrorCode_FieldNumber_Code,
        .hasIndex = 0,
        .offset = (uint32_t)offsetof(QueryErrorCode__storage_, code),
        .flags = (GPBFieldFlags)(GPBFieldOptional | GPBFieldClearHasIvarOnZero),
        .dataType = GPBDataTypeInt32,
      },
    };
    GPBDescriptor *localDescriptor =
        [GPBDescriptor allocDescriptorForClass:GPBObjCClass(QueryErrorCode)
                                   messageName:@"QueryErrorCode"
                               fileDescription:&SystemPbRoot_FileDescription
                                        fields:fields
                                    fieldCount:(uint32_t)(sizeof(fields) / sizeof(GPBMessageFieldDescription))
                                   storageSize:sizeof(QueryErrorCode__storage_)
                                         flags:(GPBDescriptorInitializationFlags)(GPBDescriptorInitializationFlag_UsesClassRefs | GPBDescriptorInitializationFlag_Proto3OptionalKnown | GPBDescriptorInitializationFlag_ClosedEnumSupportKnown)];
    #if defined(DEBUG) && DEBUG
      NSAssert(descriptor == nil, @"Startup recursed!");
    #endif  // DEBUG
    descriptor = localDescriptor;
  }
  return descriptor;
}

@end

#pragma mark - ErrorCodeDetail

@implementation ErrorCodeDetail

@dynamic code;
@dynamic bizModelCode;
@dynamic bizModelDesc;
@dynamic moduleCode;
@dynamic moduleDesc;
@dynamic detailCode;
@dynamic detailDesc;
@dynamic fullMessage;
@dynamic found;

typedef struct ErrorCodeDetail__storage_ {
  uint32_t _has_storage_[1];
  int32_t code;
  int32_t bizModelCode;
  int32_t moduleCode;
  int32_t detailCode;
  NSString *bizModelDesc;
  NSString *moduleDesc;
  NSString *detailDesc;
  NSString *fullMessage;
} ErrorCodeDetail__storage_;

// This method is threadsafe because it is initially called
// in +initialize for each subclass.
+ (GPBDescriptor *)descriptor {
  static GPBDescriptor *descriptor = nil;
  if (!descriptor) {
    GPB_DEBUG_CHECK_RUNTIME_VERSIONS();
    static GPBMessageFieldDescription fields[] = {
      {
        .name = "code",
        .dataTypeSpecific.clazz = Nil,
        .number = ErrorCodeDetail_FieldNumber_Code,
        .hasIndex = 0,
        .offset = (uint32_t)offsetof(ErrorCodeDetail__storage_, code),
        .flags = (GPBFieldFlags)(GPBFieldOptional | GPBFieldClearHasIvarOnZero),
        .dataType = GPBDataTypeInt32,
      },
      {
        .name = "bizModelCode",
        .dataTypeSpecific.clazz = Nil,
        .number = ErrorCodeDetail_FieldNumber_BizModelCode,
        .hasIndex = 1,
        .offset = (uint32_t)offsetof(ErrorCodeDetail__storage_, bizModelCode),
        .flags = (GPBFieldFlags)(GPBFieldOptional | GPBFieldClearHasIvarOnZero),
        .dataType = GPBDataTypeInt32,
      },
      {
        .name = "bizModelDesc",
        .dataTypeSpecific.clazz = Nil,
        .number = ErrorCodeDetail_FieldNumber_BizModelDesc,
        .hasIndex = 2,
        .offset = (uint32_t)offsetof(ErrorCodeDetail__storage_, bizModelDesc),
        .flags = (GPBFieldFlags)(GPBFieldOptional | GPBFieldClearHasIvarOnZero),
        .dataType = GPBDataTypeString,
      },
      {
        .name = "moduleCode",
        .dataTypeSpecific.clazz = Nil,
        .number = ErrorCodeDetail_FieldNumber_ModuleCode,
        .hasIndex = 3,
        .offset = (uint32_t)offsetof(ErrorCodeDetail__storage_, moduleCode),
        .flags = (GPBFieldFlags)(GPBFieldOptional | GPBFieldClearHasIvarOnZero),
        .dataType = GPBDataTypeInt32,
      },
      {
        .name = "moduleDesc",
        .dataTypeSpecific.clazz = Nil,
        .number = ErrorCodeDetail_FieldNumber_ModuleDesc,
        .hasIndex = 4,
        .offset = (uint32_t)offsetof(ErrorCodeDetail__storage_, moduleDesc),
        .flags = (GPBFieldFlags)(GPBFieldOptional | GPBFieldClearHasIvarOnZero),
        .dataType = GPBDataTypeString,
      },
      {
        .name = "detailCode",
        .dataTypeSpecific.clazz = Nil,
        .number = ErrorCodeDetail_FieldNumber_DetailCode,
        .hasIndex = 5,
        .offset = (uint32_t)offsetof(ErrorCodeDetail__storage_, detailCode),
        .flags = (GPBFieldFlags)(GPBFieldOptional | GPBFieldClearHasIvarOnZero),
        .dataType = GPBDataTypeInt32,
      },
      {
        .name = "detailDesc",
        .dataTypeSpecific.clazz = Nil,
        .number = ErrorCodeDetail_FieldNumber_DetailDesc,
        .hasIndex = 6,
        .offset = (uint32_t)offsetof(ErrorCodeDetail__storage_, detailDesc),
        .flags = (GPBFieldFlags)(GPBFieldOptional | GPBFieldClearHasIvarOnZero),
        .dataType = GPBDataTypeString,
      },
      {
        .name = "fullMessage",
        .dataTypeSpecific.clazz = Nil,
        .number = ErrorCodeDetail_FieldNumber_FullMessage,
        .hasIndex = 7,
        .offset = (uint32_t)offsetof(ErrorCodeDetail__storage_, fullMessage),
        .flags = (GPBFieldFlags)(GPBFieldOptional | GPBFieldClearHasIvarOnZero),
        .dataType = GPBDataTypeString,
      },
      {
        .name = "found",
        .dataTypeSpecific.clazz = Nil,
        .number = ErrorCodeDetail_FieldNumber_Found,
        .hasIndex = 8,
        .offset = 9,  // Stored in _has_storage_ to save space.
        .flags = (GPBFieldFlags)(GPBFieldOptional | GPBFieldClearHasIvarOnZero),
        .dataType = GPBDataTypeBool,
      },
    };
    GPBDescriptor *localDescriptor =
        [GPBDescriptor allocDescriptorForClass:GPBObjCClass(ErrorCodeDetail)
                                   messageName:@"ErrorCodeDetail"
                               fileDescription:&SystemPbRoot_FileDescription
                                        fields:fields
                                    fieldCount:(uint32_t)(sizeof(fields) / sizeof(GPBMessageFieldDescription))
                                   storageSize:sizeof(ErrorCodeDetail__storage_)
                                         flags:(GPBDescriptorInitializationFlags)(GPBDescriptorInitializationFlag_UsesClassRefs | GPBDescriptorInitializationFlag_Proto3OptionalKnown | GPBDescriptorInitializationFlag_ClosedEnumSupportKnown)];
    #if defined(DEBUG) && DEBUG
      NSAssert(descriptor == nil, @"Startup recursed!");
    #endif  // DEBUG
    descriptor = localDescriptor;
  }
  return descriptor;
}

@end

#pragma mark - Param

@implementation Param

@dynamic param;

typedef struct Param__storage_ {
  uint32_t _has_storage_[1];
  NSString *param;
} Param__storage_;

// This method is threadsafe because it is initially called
// in +initialize for each subclass.
+ (GPBDescriptor *)descriptor {
  static GPBDescriptor *descriptor = nil;
  if (!descriptor) {
    GPB_DEBUG_CHECK_RUNTIME_VERSIONS();
    static GPBMessageFieldDescription fields[] = {
      {
        .name = "param",
        .dataTypeSpecific.clazz = Nil,
        .number = Param_FieldNumber_Param,
        .hasIndex = 0,
        .offset = (uint32_t)offsetof(Param__storage_, param),
        .flags = (GPBFieldFlags)(GPBFieldOptional | GPBFieldClearHasIvarOnZero),
        .dataType = GPBDataTypeString,
      },
    };
    GPBDescriptor *localDescriptor =
        [GPBDescriptor allocDescriptorForClass:GPBObjCClass(Param)
                                   messageName:@"Param"
                               fileDescription:&SystemPbRoot_FileDescription
                                        fields:fields
                                    fieldCount:(uint32_t)(sizeof(fields) / sizeof(GPBMessageFieldDescription))
                                   storageSize:sizeof(Param__storage_)
                                         flags:(GPBDescriptorInitializationFlags)(GPBDescriptorInitializationFlag_UsesClassRefs | GPBDescriptorInitializationFlag_Proto3OptionalKnown | GPBDescriptorInitializationFlag_ClosedEnumSupportKnown)];
    #if defined(DEBUG) && DEBUG
      NSAssert(descriptor == nil, @"Startup recursed!");
    #endif  // DEBUG
    descriptor = localDescriptor;
  }
  return descriptor;
}

@end


#pragma clang diagnostic pop

// @@protoc_insertion_point(global_scope)

// clang-format on
